### ISSUE TITLE
Can't use Java app, null pointer exceptions on attempt

### ISSUE THREAD

**Issue by ubergeek77** [alexa/alexa-avs-sample-app#1000]
I can't use the Java app. Whenever I try to invoke Alexa, a number of NullPointerExceptions are thrown.

I can authenticate with the companion service just fine, and I can see my access token in the Java app. I can also use my Conexant AVS board's microphone using gpio (sensory appears to be broken at the moment). However, Alexa cannot be used.

I am using this guide: https://github.com/alexa/alexa-avs-sample-app/wiki/Conexant2Mic-Raspberry-Pi

### Device Information:
**Hardware:** Raspberry Pi 3 Model B+/Conexant AudioSmart 2-mic Development Kit
**Operating System:** Raspbian Jessie
**Java Version:** 1.8.0 Update 151 (Installed by automatic setup script)
**Locale:** en-US
**Java App Error Log:** [Pastebin](https://pastebin.com/raw/sZgstFuD)

Has anyone else encountered this?

**Comment by frozenberg** [comment]
Hi @ubergeek77,

Can you run `cat ~/.asoundrc`? 

Thanks

**Comment by ubergeek77** [comment]
@frozenberg Ah, you caught me just in time. I was actually about to close this. It turns out the MicroUSB port on my Conexant board is a little finicky, and my MicroUSB cable was improperly seated. Those exceptions occur when the Pi can't communicate with the Conexant board. Re-seating the MicroUSB cable fixes those problems.
