### ISSUE TITLE
400 Bad Request The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

### ISSUE THREAD

**Issue by VinnieSims** [alexa/alexa-avs-sample-app#1001]
I'm having trouble with it activating through the local host web page. I've tried re-configering it with allowed origins and allowed return origins, but nothing seems to work. Please help!
<img width="1168" alt="screen shot 2017-11-03 at 9 27 55 pm" src="https://user-images.githubusercontent.com/29235817/32400993-e5e02b04-c0dd-11e7-8f58-d485e27a30d7.png">

<img width="711" alt="screen shot 2017-11-03 at 9 21 25 pm" src="https://user-images.githubusercontent.com/29235817/32400919-0d07c6a2-c0dd-11e7-81c4-949d1eddff58.png">

**Comment by monkut** [comment]
Similar issue here... it seems that the AlexaPi doesn't serve on https, and the amazon console doesn't allow IPs on http....So it's not possible (?) to activate via an external pc. (Connecting to the raspberrypi3 in my case)

I wonder how difficult it would be to add https

**Comment by VinnieSims** [comment]
Hopefully we can get better support to fix this issue!

**Comment by StuartBeacon** [comment]
Having the same issue as well!

**Comment by kjkh** [comment]
Hi @VinnieSims,

Could you describe your set up a little bit as well as what you have tried so far to resolve the issue?

Additionally, if you weren't aware, we have guides for configuring the security profile with the Java Sample App. This is an example for the [Pi](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#lets-get-started).

Some comments based on the information you've currently provided: 
I see in your screenshot that you have http://localhost:3000/authresponse as an Allowed Return URL. However, with the Java Sample App, you should be using https://localhost:3000/authresponse. If you wish to use another port (I see you tried 5000), you need to modify the following files:

- alexa-avs-sample-app/samples/javaclient/config.json
- alexa-avs-sample-app/samples/companionService/config.json
- alexa-avs-sample-app/samples/companionService/bin/www

and replace the port number with the one you wish to use. Hope this helps.

**Comment by VinnieSims** [comment]
Hello.

My current setup is simply the Raspberry Pi, connect with a microphone and speaker, as well as a power source with HDMI being displayed to the moniter.

I do have the localhost:3000 response. If you could kindly provide the steeps to fix the issue and how to do it, I will give it another shot.

Thank you, and Merry Christmas!

**Comment by mradulan** [comment]
does it still give 400 Bad request even after you changed it to https than http?

**Comment by VinnieSims** [comment]
I'll have to try it when I get some free time.

**Comment by codemonkeybr** [comment]
Anyone Fixed this issue? Im having the same problem i add the http://10.1.1.1.11:5050/code to the whitelist of return urls and stilll gives me the following error:

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
scope=alexa%3Aall
redirect_uri=http%3A%2F%2F10.1.1.111%3A5050%2Fcode
response_type=code

**Comment by codemonkeybr** [comment]
Just an update, just found the issue, lose de port... just use the ip/code
http://10.1.1.111/code works fine... (into response url)

**Comment by VinnieSims** [comment]
Does that response URL make the Alexa to work?

**Comment by codemonkeybr** [comment]
@VinnieSims in my case, using the latest pi and alexa, yes. it made it work.

**Comment by VinnieSims** [comment]
Do you think if I try the same response URL, it will work for me as well?

**Comment by bandkenamazoncom** [comment]
@VinnieSims Did you try it?

**Comment by VinnieSims** [comment]
@bandkenamazoncom • I have not, as I’ve been busy. I will try this weekend.

**Comment by mradulan** [comment]
closing the issue as response not received.

**Comment by VinnieSims** [comment]
@bandkenamazoncom • Tried the new link, works like a charm!

**Comment by korre79** [comment]
http://10.1.1.1.11/code  The code is? cuz i can´t put in just "http://10.1.1.1.11/code"  
Can somebody show me an example please? 

Thx
