### ISSUE TITLE
Support en-IN locale

### ISSUE THREAD

**Issue by cybersa** [alexa/alexa-avs-sample-app#1002]
I want to test my Skill set which was developed for Indian user. I can't test my skill set using this service.
Could you please support for en-IN locale?

Thanks.

**Comment by jjamazon** [comment]
Hi cybersa, can you check with the Alexa skills team

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs

Thanks

**Comment by jjamazon** [comment]
is it possible you can use the C++ SampleApp instead?

First you will have to delete your database file ‘rm –f <path-to-settings-database-file>’
Then set the locale in AlexaClientSDKConfig.json to en-IN

**Comment by kjkh** [comment]
Hi @cybersa,

We have recently added support for en-IN in our newest release.
