### ISSUE TITLE
Ability to use alexa.amazon.co.uk and Alexa ios app?

### ISSUE THREAD

**Issue by Pukington** [alexa/alexa-avs-sample-app#1003]
Hi Guys

I previously had my pi running alexa quite happily, with extra skills added via alexa.amazon.co.uk, and i used the app.  I had it controlling my HASS install quite happily.  Since moving, and setting things up again (an absence of about six months) i see Amazon's alexa site has changed, and you have to register a device to be able to use it, same as the app.

Am i missing something, i can't get past a device registration page, Is there anyway round this so we can add extra skills and use the ios app?  I can't seem to change the time on my device either.

Cheers for any input!

**Comment by jjamazon** [comment]
Hi Pukington,

Are you using the java sample app or the C++ sdk, also which version? Are you able to talk to Alexa at all ? get the time, play music, etc. 
can we get some more information, on the problem you are facing.

**Comment by Pukington** [comment]
Sorry if I was a little vague, i may just being stupid but i don't have the greatest memory.  I appreciate your help for a silly fool.  I think i'm being stupid and asking more for the Alexa sample app than is do'able.

I'm running the java sample app on a Pi3 which i use as a homeassistant server, it runs quite happily, and was installed fresh two days ago.

I can talk to Alexa, I can ask the time, although it's 11hours fast, but think from memory there's a config file somewhere for that.  It doesn't play music, just get "spotify isn't supported", it operates my IFTTT triggers and smart home devices alright.

I couldn't access my alexa-sample-app install via alexa.amazon.co.uk as all i got was a setup page for device registration, be it a new echo, a dot, plus, tap.  But somehow i've ended up on alexa.amazon.co.uk/spa/index.html#player where i can access the skills and my smart home devices.  I can't access the skills from the alexa app, but guessing the sample-app is the limitation again.

Now i've reached the skills page i can sort myself, my IFTTT triggers and my smart home devices are all good, so sorry for the hassal @jjamazon, think we can consider this closed.
