### ISSUE TITLE
Error (0x10001) after command ./generate.sh

### ISSUE THREAD

**Issue by gratianj** [alexa/alexa-avs-sample-app#1004]
Hi, I'm having some problems:

after I start the ./generate.sh command in the terminal it gives me this error:

Generating RSA private key, 4096 bit long modulus
..........................................++
..............................++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736094008200:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
Generating RSA private key, 2048 bit long modulus
........................+++
........................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736094008200:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
certs/client/client.csr: No such file or directory
Error opening input file certs/client/client.crt
certs/client/client.crt: No such file or directory
Generating RSA private key, 2048 bit long modulus
.......................................................+++
.......................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736094008200:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
certs/server/node.csr: No such file or directory
Generating RSA private key, 2048 bit long modulus
.............................................+++
............................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736094008200:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
error on line 14 of config file 'ssl.cnf'
Error opening input file certs/server/jetty.crt
certs/server/jetty.crt: No such file or directory
cp: certs/ca/ca.crt: No such file or directory
Error opening Certificate certs/ca/ca.crt
140736094008200:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:255:fopen('certs/ca/ca.crt', 'r')
140736094008200:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:257:
unable to load certificate
cp: certs/ca/ca.der: No such file or directory

**Comment by gratianj** [comment]
My ssl.cnf file is configured like this:

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = IT		                        # C=
stateOrProvinceName     = FVG             					# ST=
localityName            = Codroipo                          # L=
organizationName        = none                              # O=
organizationalUnitName  = none                              # OU=

The line 14 mentioned in the error would be the commonName one, but I don't understand what the error is.

**Comment by jjamazon** [comment]
Hi gratianj,

This seems similar to what is described here.
https://github.com/alexa/alexa-avs-sample-app/issues/108

**Comment by bilalmuhammad-ips** [comment]
I'm also having this issue but #108 doesn't seem to be of any help

**Comment by bilalmuhammad-ips** [comment]
I decided to run each line of the script manually and change 

`commonName              = $ENV::COMMON_NAME`

along the way and now it works fine. I'm suspecting the OpenSSL syntax has changed or is different on the Mac.

**Comment by MMikkilineni** [comment]
I also have the same issue.
"error on line 14"!!
Please Help!!

**Comment by MMikkilineni** [comment]
I fixed the issue by editing the ssl.cnf with the right spacing, as it was when we opened it.
Good luck!!

**Comment by jjamazon** [comment]
Hi gratianj,
Did any of the comments above help ? Are you able to move forward ?

Janak

**Comment by gratianj** [comment]
Kind of. I did manage to solve the problem though, it was because of macOS High Sierra. I managed to fix the issue adding openSSL to the path using this method
![schermata 2017-11-10 alle 09 45 52](https://user-images.githubusercontent.com/33481606/32649939-3f1192ee-c5fc-11e7-8efb-84d8d4fe66c4.png)

**Comment by gimox** [comment]
the problem is the openssl version bundled with OSX. the only working solution is to install openssl with brew.  If you don't want to add it as default this is the scrip:

```
#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $SCRIPT_DIR

echo -n "Product ID: "
read productId

echo -n "Serial Number: "
read dsn

echo -n "Password for Keystores (won't echo): "
read -s password

mkdir -p certs/ca/
mkdir -p certs/server/
mkdir -p certs/client/
mkdir -p ../iOSCompanionApp/Resources/App/
mkdir -p ../androidCompanionApp/app/src/main/res/raw/

/usr/local/opt/openssl/bin/openssl genrsa -out certs/ca/ca.key 4096
COMMON_NAME="My CA" /usr/local/opt/openssl/bin/openssl req -new -x509 -days 365 -key certs/ca/ca.key -out certs/ca/ca.crt -config ssl.cnf -sha256

# Create the Client KeyPair for the Device Code
/usr/local/opt/openssl/bin/openssl genrsa -out certs/client/client.key 2048
COMMON_NAME="$productId:$dsn" /usr/local/opt/openssl/bin/openssl req -new -key certs/client/client.key -out certs/client/client.csr -config ssl.cnf -sha256
/usr/local/opt/openssl/bin/openssl x509 -req -days 365 -in certs/client/client.csr -CA certs/ca/ca.crt -CAkey certs/ca/ca.key -set_serial 01 -out certs/client/client.crt -sha256
/usr/local/opt/openssl/bin/openssl pkcs12 -inkey certs/client/client.key -in certs/client/client.crt -export -out certs/client/client.pkcs12 -password pass:$password

# Create the KeyPair for the Node.js Companion Service
/usr/local/opt/openssl/bin/openssl genrsa -out certs/server/node.key 2048
COMMON_NAME="localhost" /usr/local/opt/openssl/bin/openssl/openssl req -new -key certs/server/node.key -out certs/server/node.csr -config ssl.cnf -sha256
/usr/local/opt/openssl/bin/openssl x509 -req -days 365 -in certs/server/node.csr -CA certs/ca/ca.crt -CAkey certs/ca/ca.key -set_serial 02 -out certs/server/node.crt -sha256

# Create the KeyPair for the Jetty server running on the Device Code in companionApp mode
/usr/local/opt/openssl/bin/openssl genrsa -out certs/server/jetty.key 2048
COMMON_NAME="localhost" /usr/local/opt/openssl/bin/openssl req -new -key certs/server/jetty.key -out certs/server/jetty.csr -config ssl.cnf -sha256
COMMON_NAME="localhost" /usr/local/opt/openssl/bin/openssl x509 -req -days 365 -in certs/server/jetty.csr -CA certs/ca/ca.crt -CAkey certs/ca/ca.key -set_serial 03 -out certs/server/jetty.crt -extensions v3_req -extfile ssl.cnf -sha256
/usr/local/opt/openssl/bin/openssl pkcs12 -inkey certs/server/jetty.key -in certs/server/jetty.crt -export -out certs/server/jetty.pkcs12 -password pass:$password

# Copy the CA certificate to Android
cp certs/ca/ca.crt ../androidCompanionApp/app/src/main/res/raw/

# Copy the CA certificate in the correct format to iOS
/usr/local/opt/openssl/bin/openssl x509 -outform der -in certs/ca/ca.crt -out certs/ca/ca.der
cp certs/ca/ca.der ../iOSCompanionApp/Resources/App/

```
