### ISSUE TITLE
Change time/zone and location?

### ISSUE THREAD

**Issue by Pukington** [alexa/alexa-avs-sample-app#1005]
Hi guys.

I've got the java sample app running on a pi3 with stretch.  It's running fine, i can talk and it responds, i've got it to work with IFTTT and found my local devices i set up with lambda.  All nice like i had on a previous install.

But how do i change it's time and location?  I ran the automated install script and updated the details to my location, but it hasn't changed, it still thinks it's in Seattle.

How can i change the timezone/location for it?  I thought i could do it in alexa.amazon.co.uk but all i get is a screen asking me to begin a setup of a device like [this](https://cdn.pbrd.co/images/GSIMgNX.png) and [this](https://cdn.pbrd.co/images/GSIMWCT.png).

Am i not able to use the sample app with amazon's alexa site so change it's settings?  Same goes with the app.  I can add skills by by getting past the setup page like [this](https://cdn.pbrd.co/images/GSIPRtu.png) and see my [smart home devices.](https://cdn.pbrd.co/images/GSIPozy.png)

**Comment by jjamazon** [comment]
Hi Pukington,

You will need to register your device and link it with the correct account. After this it should show up under alexa.amazon.com and change it under "settings->devices"

See. https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

**Comment by Pukington** [comment]
@jjamazon Thanks for your input.

I've double checked all my settings, and as far as i can see they're correct.  I've followed the instructions again, setup a new security profile for the sake of it, checked all the details are correct. I re-run automated_install script, it prompts me to login to the new security profile on the pi, logs in okay, i can run alexa fine, still not showing up in the alexa app nor on alexa.amazon.

Really odd, i can't see anything incorrect anywhere.  Do i have to generate an ios api key as part of the security profile?

If i goto the settings->devices i can't change, just setup new device.  Does anything need to be refreshed?  I've logged in/out of alexa.amazon, but on login just get the setup new device page again.

**Comment by Pukington** [comment]
@jjamazon Thanks for your help mate, i'll close this.  Mysteriously i left my device after my last msg last night, woke up this morning and boom, it's showing in my alexa.amazon page.  Perhaps it just took a while to register through the system.  Thanks again.
