### ISSUE TITLE
 Alexa Voice Service Sample App (Java)

### ISSUE THREAD

**Issue by kamalnathponnusamy** [alexa/alexa-avs-sample-app#1007]
Hi everyone,
Using Alexa Voice Service Sample App (Java) is it possible to give request in voice command(eg. **input voice : Alexa A is 5 and B is 5**) to hit local webserice url and to get the reponse in voice (eg. **Response voice: SUM of A and B is 10**) . Is it possible to obtain .If yes kindly reply to my question I am very confused.

Regards,
Kamal

**Comment by priyagsenthil** [comment]
Hi kamalnathponnusamy,

Could you provide more details. Its not clear what you mean by  "hit local webserice url".
With the JAVA SampleApp  you can request "Alexa, add 5 + 5" and Alexa should be able to respond with the right answer. Please advise.

Thanks
Priya

**Comment by kamalnathponnusamy** [comment]
Thanks for reply Priya,

In my local machine I have written a **JAVA RESTFUL WEB-SERVICE**  to add two numbers the rest_url is         **http://localhost:5113/restservices/default/addition/**  .If I pass two input fields to this rest_url it may hit the rest_url and give the response in json format .

Is this operation call is possible in ALEXA ??

Regards,
Kamal

**Comment by priyagsenthil** [comment]
Hi Kamalnathponusamy,

This is not possible with Alexa.

Thanks
Priya

**Comment by kamalnathponnusamy** [comment]
Thanks for reply Priya 👍 ,

Is there any alternate.. if yes please share which will be more useful for me to proceed.

Regards,
Kamal :)

**Comment by kencecka** [comment]
Hi @kamalnathponnusamy,

From your description above, it really sounds like you should be looking at the Alexa Skills Kit.  This is what allows you to create a new skill in the cloud.  In a skill, you are able to receive the interpreted voice commands from the user, process them, and send text back to the user, which will be spoken in Alexa's voice.  Once you create a skill, any device can access it, whether it's an Amazon Echo Show, or your custom-built raspberry pi AVS box.

I can't give a lot of detailed guidance on skills, but you can learn more about them here:
https://developer.amazon.com/docs/ask-overviews/build-skills-with-the-alexa-skills-kit.html

Ken

**Comment by kamalnathponnusamy** [comment]
Hi kencecka,
                  Thanks for the reply , it is very useful for me to proceed.I will refer it. :) 👍 

Regards,
Kamal
