### ISSUE TITLE
Bluetooth audio clipping

### ISSUE THREAD

**Issue by gb160** [alexa/alexa-avs-sample-app#1008]
Hi , just discovered this and frankly im very impressed, only one slight issue that im hoping someone can help me out with.

Im running it on a Pi using a wireless bluetooth speaker (via pulse audio), as the built in audio quality on raspberry pi isn't great and thats being polite!
The problem is the first second (roughly) of every response is getting clipped off, probably due to the bluetooth going idle between responses.

Ive had a quick look at the code and not being an expert in java im not sure if there could be an adjustment made anywhere or making an offset to just delay the response by a second to wakeup the bluetooth  before the Alexa response starts.

I used an old unofficial version a while back and there was a 1 second silent mp3 played before every response, almost like padding, which fixed this problem for me and many others.

Ive tried changing hundreds of different settings in pulse audio but to no avail...So if any java experts out there could give any tips on how this could be achieved I would be very grateful.

Many Thanks.

**Comment by priyagsenthil** [comment]
hi gb160,

Which version of SDK are you using. We have seen the issue of audio getting cut in version 1.1 and before. With version 1.2 and migration to Jessie we have not seen this issue anymore. Also we recommend using an analog speaker with raspberry pi for best results.

Please see our guidelines below for Raspberry Pi.
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide

If you have further questions please feel free to reach out to us.

Thanks
Priya

**Comment by gb160** [comment]
@priyagsenthil 
Thanks for the reply, tbh I'm not sure that the sdk version is applicable to me as I'm using Alexa via the install guide here:
https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi
The reason I'm hesitant to use an analogue speaker is because of the poor audio quality from the built in Pi hardware, it's pretty awful and my Bluetooth speaker is hands down a better option as far as audio quality is concerned.
as I said it was quite simple to fix this in the unofficial version I was using, I'll just keep my fingers crossed someone with better java knowledge than me can point me in the right direction and suggest a fix.

Thanks anyway.

**Comment by priyagsenthil** [comment]
Hi gb160,

So you are using the JAVA SampleApp and not the C++ SDK. The issue resolved in version 1.2 with Stretch was in C++ SDK. Will poke around more about the JAVA SampleApp. So are you seeing the data getting cut off all the time or is it only in some specific use cases.  Which analog speaker did you use with your pi?  We have tested with Boombug speaker and it generally works well and with good quality audio.  Please advise.

Thanks
Priya

**Comment by gb160** [comment]
Thanks for giving the issue your attention, it's every single response that the audio is getting clipped, my Bluetooth speaker (Bose) has an anologue input as well, so I've used it both analog and via Bluetooth, and via Bluetooth the quality is noticeably better, as I presume it doesn't use the pi's built in audio chip...I've noticed in other pi projects (OSMC) that the built in audio isnt the best quality so I always try to avoid using it when possible....I suppose it's what to be expected from an otherwise excellent little computer at that price.

Tbh I'm still not 100% sure that the issue lies within the sample app itself, or if it's how pulse audio/alsa is handling the Bluetooth audio, but considering a workaround was found on the unofficial version I was using I presumed that maybe the same kind of fix (padding or delaying the audio slightly) could in theory be implemented here, or if someone else had come across this issue and new of a way to address it.

**Comment by kencecka** [comment]
Hi @gb160,

Did you come to any conclusions on this?  I haven't researched the topic thoroughly, but it appears that this may be a known issue with raspbian stretch and bluetooth, unrelated to the AVS sample app: https://jp.raspberrypi.org/forums/viewtopic.php?t=191586

Workaround to consider: go back to the older jessie release of raspbian, or use a wired speaker.

Ken

**Comment by gb160** [comment]
@kencecka I was getting the same behaviour in Jessie as well, so in the end I ditched Bluetooth altogether and use a USB soundcard.

**Comment by scotthea-amazon** [comment]
Hello gb160,

It sounds like you have resolved this issue (although with a work-around).  I am closing the issue.  Please feel free to re-open it if you have further questions on this issue.

Thank you,
-SWH
