### ISSUE TITLE
Change language, now that English (India) is supported on Amazon Echo

### ISSUE THREAD

**Issue by shivaagarwal1** [alexa/alexa-avs-sample-app#1009]
Now that Echo is sold in India and understands English (India), is there a way to activate this for 1st Gen Echo devices as well? Don't want to spend another $150. Thanks in advance

**Comment by ramkb** [comment]
Hi,
This group is intended for Alexa AVS Sample App related issues and discussions. Your query will be answered in the forum post https://forums.developer.amazon.com/questions/96205/ Thanks for your understanding.
