### ISSUE TITLE
Alexa Javaclient Window Won't Open (Step 7)

### ISSUE THREAD

**Issue by thecatp** [alexa/alexa-avs-sample-app#1010]
I have already completed project and it worked perfectly the first time, I was able to talk to Alexa. Now I am trying to run it for the second time and when I get to the 2nd terminal window in Step 7 and run the command `cd javaclient && mvn exec:exec` it starts to build, however it only gets up to this line `[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---`. No microphone window ever opens up.

**Comment by priyagsenthil** [comment]
Hi,

Please retry the setup following the instructions from 

https://github.com/alexa/alexa-avs-sample-app based on the platform that you are using. Please check the microphone and sound settings on your device.  If you are still running into issues please provide more logs with the steps tried.

Thanks
Priya

**Comment by kencecka** [comment]
Hi @thecatp,

I'm going to close this issue.  Please re-open if you are still having problems.

Ken
