### ISSUE TITLE
Android Application

### ISSUE THREAD

**Issue by Siddhi3** [alexa/alexa-avs-sample-app#1012]
How can i run this app on an android phone??

**Comment by priyagsenthil** [comment]
Hi Siddhi3,

Which app are you trying to run?

Thanks
Priya

**Comment by Siddhi3** [comment]
Can i run this sample app on my android phone?

**Comment by priyagsenthil** [comment]
Hi Siddhi3,

We do not support the SampleApp on android.

Thanks
Priya
