### ISSUE TITLE
Failing to retrieve the access token

### ISSUE THREAD

**Issue by mwasson1** [alexa/alexa-avs-sample-app#1013]
on step 7 of this project we run the javaclient && mvn exec:exec it runs fine but when we got to the local host we get an error saying that there is an issue with getting an access token and that amazon is working to resolve it. any thoughts.

**Comment by priyagsenthil** [comment]
Hi,

Can you retry and update. When you get to the local host address it should ask for an LWA login and after successful login the refresh token should be updated. At what stage is it failing. Is it failing to ask for the LWA login or after login it fails to fetch the token. If its fails after login its possibly some issue with the credentials or could be even with the productId. Please retry and update the exact point where it fails.

Thanks
Priya

**Comment by kencecka** [comment]
Hi @mwasson1,

I'm going to close this issue.  Feel free to re-open if you are still having problems.

Ken
