### ISSUE TITLE
Missing File ca.crt in Android - Step 5B

### ISSUE THREAD

**Issue by DariuschDideban** [alexa/alexa-avs-sample-app#1014]
I'm working on the step by step solution and i am currently stuck at the end of step 5B. When I start the application it says: 

Error:(19, 1) Execution failed for task ':app:checkForRequiredFiles'.
> java.io.FileNotFoundException: The Certificate Authority public certificate file does not exist. Please make sure ./src/main/res/raw/ca.crt exists and contains the public certificate created during setup.

I went through the tutorial again, but in there we do not put this file at some point into the raw folder. Should this happen automatically while generating? Did I missed smt?

**Comment by kclchan** [comment]
Hi @DariuschDideban, the certificates are generated and copied to the folder when you run "./generate.sh" in Step 4, "Generating Self Signed Certificates".  Thanks!

**Comment by DariuschDideban** [comment]
Hey @kclchan thank you for your support! I made the mistake that I didn't replaced the YOUR_ lines in the ssl.cnf file. I actually wrote everything behind the '=' e.g. YOUR_COUNTRY_NAME #C = DE.
Well now it works, so thanks again! :)
