### ISSUE TITLE
alexa ja-jp is not a support locale

### ISSUE THREAD

**Issue by yangxy112683** [alexa/alexa-avs-sample-app#1017]
my raspberry 2B build avs successfully and can use in en-US; so I want to use it in Japanese, so I did 2 things after:
1. changed the config  in samples\javaclient\config.json
-"locale":"en-US",
+"locale":"ja-JP",
2.changed the config in samples\javaclient\src\main\java\com\amazon\alexa\avs\config\DeviceConfig.java

 public class DeviceConfig {
     private static final String DEFAULT_HOST = "https://avs-alexa-na.amazon.com";
     public static final String FILE_NAME = "config.json";
     private static final List<Locale> SUPPORTED_LOCALES = new ArrayList<>();
     static {
         SUPPORTED_LOCALES.add(Locale.US);
         SUPPORTED_LOCALES.add(Locale.UK);
         SUPPORTED_LOCALES.add(Locale.GERMANY);
+        SUPPORTED_LOCALES.add(Locale.JAPAN);
     }

but when I start the java client , it returns "ja-jp is not a support locale";
It means I can't use it in Japanese? How can I use the avs-sample in Japanese?

**Comment by mavamazon** [comment]
Hi!

Java Sample App does not support languages recently added to AVS (en-IN, en-CA, ja-JP). I suggest you to use [C++ AVS SDK](https://github.com/alexa/avs-device-sdk), it has better support for the latest features and updates more often.

**Comment by yangxy112683** [comment]
ok,thanks
