### ISSUE TITLE
Canada Locale Disabling Skills

### ISSUE THREAD

**Issue by benrules2** [alexa/alexa-avs-sample-app#1018]
My alexa.amazon.com account has somehow been set to Canadian English, and the Skills are all disabled as a result with a message to change my language to English(Canadian).

When I re-run the automated-install script the script has no option for Canadian English. Until this can be resolved I am unable to use any skills.

Presumably this is related to the new rollout of Alexa in Canada.

**Comment by mavamazon** [comment]
Hi!

First of all I encourage you to switch to our [C++ AVS Device SDK](https://github.com/alexa/avs-device-sdk). It is updated more often and has more features in general. Java Sample App does not support en-CA yet.

As for your account being switched to Canadian we are going to review that.

**Comment by prmodku** [comment]
What do you mean when you say your account has changed to Canadian English? Does that happen consistently? If so, then please let us know what were the sequence of steps that you did when this happened?

If you are talking about the sample app, then in order to change the locale back to US, you can update the config.json appropriately: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/config.json#L6

**Comment by benrules2** [comment]
When I say my account has changed, I mean when I logged in about a week ago my skills had been deactivated, with a message that my account does not match my language settings.

My language settings are still set as US-En in the sample app, but I think my alexa account has been set to Canada settings. Probably based on my shipping address and the upcoming alexa launch here.

I’ll check again in that confit file just to be sure. 

Thanks.. ben

**Comment by prmodku** [comment]
If you wish to continue testing with a US account, you can change your country in amazon content and devices settings.

**Comment by benrules2** [comment]
I see that that would fix the locale mismatch, but I've got about 5 other devices under that account too which I would rather not transfer as well. Are you aware of any plans to support Canada in the sample app? 

I understand supporting the sample is probably only intended to demonstrate the sdk, but I've been using it as my primary home automation controller for about a year now with custom skills added on.

**Comment by kencecka** [comment]
Hi @benrules2,

We will be adding support for the en-CA locale in a future release of the Java Sample app.  In the mean time, you will either need to use a US account, or edit the sources on your own to switch to en-CA.

Ken

**Comment by kjkh** [comment]
Hi @benrules2,

We have added support for en-CA in our latest release. Please re-open if there are further questions.
