### ISSUE TITLE
USB Soundcard Install option 

### ISSUE THREAD

**Issue by gb160** [alexa/alexa-avs-sample-app#1026]
Im using the java sample app on a Pi2 and Im surprised there isn't an option to use USB sound card for both mic input and audio output...after a few modifications im able to get the Alexa sounds to come through USB audio, but im getting errors  if im playing music/radio and try to give Alexa another command.

Has anyone been able to successfully implement this setup?
Id be very interested to know your steps.

**Comment by mavamazon** [comment]
Hi gb160,

The Sample App uses default input and output for the audio. This post could give you an idea what to do: https://github.com/alexa/alexa-avs-sample-app/issues/37

**Comment by gb160** [comment]
Yeah that's the post I used to get any audio from the USB, I'm guessing the people who claim to have it working haven't noticed the client errors if you try interrupting playback with a request to Alexa.

There's one guy who noticed this error and claims to have solved it by editing asound.conf, but he's not posted what changes he made.
@RogerZheng

**Comment by mavamazon** [comment]
Could you please provide some logs around the time you were experiencing the interruptions?

**Comment by gb160** [comment]
@mavamazon Sure, this is the error that appears in the client window when during playback I issue a request to Alexa or press the listen button : 
`Listen button pressed
Processing
10:25:50.560 [Thread-137] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: cannot obtain source audio line
	at javazoom.jl.player.JavaSoundAudioDevice.createSource(JavaSoundAudioDevice.java:128) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.JavaSoundAudioDevice.writeImpl(JavaSoundAudioDevice.java:148) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.AudioDeviceBase.write(AudioDeviceBase.java:133) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.decodeFrame(Player.java:220) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:120) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:104) ~[jlayer-1.0.1.jar:?]
	at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:933) [classes/:?]
Done`

Not sure if there is a more verbose log somewhere that might help?

**Comment by mavamazon** [comment]
Hi!

It seems that it is still related to audio configuration. Please let us know if there are new observations.

Andrey.

**Comment by gb160** [comment]
@mavamazon tbh I'm not sure it's an issue with configuration, as why would everything else be working? If there's nothing playing on Alexa then it all works just fine, to me it seems that the way the java app handles the built in audio hardware doesn't work so well with an external sound card, hence the errors, unfortunately java isn't one of my strong points otherwise I'd have an attempt at addressing it myself.

Something I noticed is that the problem doesn't occur if I start pulse audio running as a Daemon before I start the java app, the errors are gone but it introduces another issue where intermittently the start and confirm sounds from Alexa become distorted and almost robotic like.

Tbh it's becoming more of a headache than it's worth using the USB sound card, it's one issue after another for what seems like a very basic feature, but I can understand from a programming point of view it makes your life a whole lot easier to just support the built in hardware, rather than the headache of trying to support hundreds of different external audio devices.

**Comment by mavamazon** [comment]
Well, this is not really a matter of supporting devices, since we are relying on system's default input/output without actually knowing anything about the hardware. 

To me it looks like an exclusive device access conflict, like when system tries to acquire device for input while it has been already exclusively used for output. However I cannot claim that since I am not an expert in Pi configuration.

Andrey.

**Comment by gb160** [comment]
@mavamazon It's frustrating as the errors I'm getting are exactly the same as @RogerZheng , who claimed he fixed by editing his configuration files for Alsa, so you could well be right.
He didn't post exactly what he changed and is ignoring my requests for any information so I'll leave this issue open in the hope that he replies, or someone else stumbles on a solution for this....who knows, maybe it'll fix itself when the installation guide gets updated to support Raspbian Stretch.

**Comment by shivasiddharth** [comment]
The problem in your case would be the lack of dsnoop and dmix plugin. In that case, only one process can use the audio resource at a time. Try this asound.conf for USB DAC and also paste the same thing in .asoundrc as well.
https://github.com/shivasiddharth/Assistants-Pi/blob/master/audio-drivers/USB-DAC/scripts/asound.conf

**Comment by gb160** [comment]
@shivasiddharth Excellent stuff, worked like a charm!!
Out of interest, why are these plugins not needed using the built in sound hardware on the pi?

Im just glad I can finally ditch the built in hardware as the sound quality from my usb sound card is far superior.

**Comment by shivasiddharth** [comment]
@gb160 , The Pi does not have a dedicated DAC, but uses PWM for audio and hence that quality. That apart, dmix is for audio out and dsnoop for audio in. dmix does not work with onboard HDMI, and jack by default allows the mixing of audio. Still, you need to use the dsnoop when using the external mic.

**Comment by shivasiddharth** [comment]
@mavamazon , I find so many USB DAC issues reported. May be you can reference this issue in troubleshooting.

**Comment by gb160** [comment]
@shivasiddharth 100% agree, I read through so many issues trying to find a solution to this, and what is a pretty simple fix to implement.
It should definitely be referenced in the troubleshooting/faq imo.
