### ISSUE TITLE
Whether to support Portuguese

### ISSUE THREAD

**Issue by youfu88** [alexa/alexa-avs-sample-app#1035]
Hi,
Does it support  Portuguese?
Thanks!

**Comment by kencecka** [comment]
Hi @youfu88,

AVS does not currently support Portuguese.  You can find the list of supported languages [here](https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated), under "Accepted Key/Value Pairs".

Ken

**Comment by youfu88** [comment]
Hi @kencecka
Does AVS have a plan to support Portuguese? About what time?
Thanks

**Comment by kencecka** [comment]
Hi @youfu88,

There is not a schedule yet for adding support for Portuguese.

Ken

**Comment by scotthea-amazon** [comment]
The question appears to have been answered.  Please re-open this issue if it has been closed in error.
