### ISSUE TITLE
Add new skills (Node.js)

### ISSUE THREAD

**Issue by kbariotis** [alexa/alexa-avs-sample-app#1037]
How can I add new skills that point to the local server (Node.js)? Any resources on that?

Thank you

**Comment by elstryan** [comment]
Hi, 
Can you elaborate more on your use case? Are you trying to create a new skill for Alexa? The Node.js service which is in the project isn't actually for skills but is instead an implementation of our authentication protocol.

**Comment by kbariotis** [comment]
Yes sorry about that @elstryan I haven't really grasped the way Echo works. I wanted my Echo to route the request to a local server, but then I realized that the routing happens in the cloud.

Thanks
