### ISSUE TITLE
What is the notification sample?

### ISSUE THREAD

**Issue by reebayroo** [alexa/alexa-avs-sample-app#1038]
Hello all.

This repo is referenced as sample app for Notification Service but 
all I see are the folders: androidCompanionApp, companionService, iOSCompanionApp, javaclient and wakeWordAgent. Would you please point me to the right direction? What am I missing?

Thank you.

**Comment by kencecka** [comment]
Hi @reebayroo,

I'm not sure what specifically you are looking for, but the javaclient implements the [notifications interface](https://developer.amazon.com/docs/alexa-voice-service/notifications.html).  If you're wanting to review the code that implements it, you might want to start with these files:

* [NotificationsStatePayload.java](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/message/request/context/NotificationsStatePayload.java)
* [NotificationIndicator.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/NotificationIndicator.java)
* [NotificationManager.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/NotificationManager.java)
* [NotificationsViewController.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/ui/controllers/NotificationsViewController.java)
* [GraphicalNotificationsView.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/ui/graphical/GraphicalNotificationsView.java)
* [HeadlessNotificationsView.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/ui/headless/HeadlessNotificationsView.java)
* [NotificationsUIHandler.java ](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/ui/NotificationsUIHandler.java)

Ken

**Comment by reebayroo** [comment]
Thank you for the response @kencecka . It is still confusing to me how you prepare the payload. 

When I make a request "Ask Quote Maker to Create a notification" I see the a Response as result from the inputstream post
```
{
  "directive" : {
    "header" : {
      "namespace" : "Notifications",
      "name" : "SetIndicator",
      "messageId" : "89413d47-a2b1-4e51-b4ac-c1aac977d199"
    },
    "payload" : {
      "persistVisualIndicator" : true,
      "playAudioIndicator" : true,
      "asset" : {
        "assetId" : "default_notification_sound",
        "url" : "https://s3.amazonaws.com/notificationindicator-prod-na/default_notification_sound.mp3"
      }
    }
  }
```
what am I missing?

**Comment by scotthea-amazon** [comment]
Hello reebayroo,

I am not quite sure what you are asking.  My best interpretation is that you are asking Alexa "Ask Quote Maker to Create a notification" and your client is receiving the directive that you included inline in your last comment.  If that interpretation is correct, than the request appears to be making it to the **Quote Maker** skill, and **Quote Maker** is sending a notification to your client.

The received directive tells the client to enable a notification indicator (for example an LED), and to play a notification indicator sound.

You indicated above that you want to "send a notification and a message to the registered skill".  As far as I know, there is no interface for sending notifications or specific messages to the **Quote Maker** skill.

If, perhaps you just want to automate sending "Ask Quote Maker to Create a notification" to AVS, you could look at the Java Sample Application code for [sending a recognize request](https://github.com/alexa/alexa-avs-sample-app/blob/5261ef3f9cb0a4f4c2911bb50b418a10dc6e063c/samples/javaclient/src/main/java/com/amazon/alexa/avs/message/request/RequestFactory.java#L49):

If you want to hear the notification received from **Quote Maker**, you can retrieve it by asking: "Alexa, play my notifications".

Regards,
-SWH

**Comment by reebayroo** [comment]
Hey Scott, I am able to ask the java client and see that a notification in the Quote Maker skill, in the echo show, was created. I'm trying to understand how to write a code that 1-) sends a message to my skill - not quote maker - (That's what I meant by registered skill)  and 2-) Once my skill gets the event (or message, or intent), sends a directive to the echo to create a notification. 

Basically if the **quote maker** skill code was open sourced,  I think I would have been be able to figure that out.

**Comment by scotthea-amazon** [comment]
Hello reebayroo,

If you fill out this [Contact form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) we can get in touch with you directly to better understand what you are trying to accomplish, and see what we can do to help.

Regards,
-SWH

**Comment by reebayroo** [comment]
I see that notification api is not available to the public yet 

https://developer.amazon.com/blogs/alexa/post/833b9af4-26e6-47d2-a13d-bdbd9a257512/expanded-developer-preview-of-notifications-for-alexa-skills

**Comment by cafebabe2020** [comment]
I have similar question regarding if I can code to deliver notifications to my custom skill users.
For example, if my custom skill user did account linking to my e-commerce website,  this user ordered something and the order shipped today,  How can I send notification to this user. (Similar to Amazon Prime order notification) 
I was not able find quote maker code, but quote maker example seems to only create notification via custom skill code, which does not help my case. 
Can anyone point me to a place where the sample code demonstrate how to push notification to a device/user like the user in my above example?

**Comment by letsgithub** [comment]
Even we need help in sending notifications to alexa device of a user (echo, dot, etc.. not the other non amazon alexa device) from alexa skill we are building. I see quote maker doing it but, how its doing it is a blackbox

**Comment by amitdan** [comment]
Is it possible to send push notification to Echo dot or echo show  ? If yes can someone send link to sample code or github repo ?

**Comment by mikegrima** [comment]
Dear Amazon:

I am trying to make a fun side project that would have a Lambda function run on a cron to push a notification to an Echo with a custom MP3. The documentation on this page: https://developer.amazon.com/docs/alexa-voice-service/notifications-overview.html seems to indicate that this is possible, but doesn't explain how to actually make a skill to do it.

The confusion that myself and others here have is that there are zero examples on how to actually do this. There is a section named `Enable the Quote Maker Skill for Testing"`... which provides a link to an existing skill to a "Quote Maker"... It's not clear how this helps us make our own skills to actually send push notifications to Echos.

Can you please provide clear examples of source code and tutorials for skills that send push notifications?

Thank You
