### ISSUE TITLE
not connecting to ftp.halifax ( Please guys HELP an idiot beginner )

### ISSUE THREAD

**Issue by cornusandu** [alexa/alexa-avs-sample-app#1047]
Hello guys,
please keep in mind that i am extremely novice at Linux and i need step by step instructions if possible.
When i am trying to install alexa while installing it stops for a while and than it says Failed when is trying to connect to : [connecting to ftp.halifax.rwth-aachen.de (2a00:8a60:e012:a00::21)]
Can any of you guys tell me what is the problem? And please explain it to mi like to a 3 years old.
Thank you very much. Kind regards . 
Cornel

**Comment by shivasiddharth** [comment]
Are you trying to install it on a raspberry pi?

**Comment by cornusandu** [comment]
Yes, raspberry pi 3 . And later on when I get to the point of opening 3 terminal windows  on window 2 when I write down the part for java client I get an error that there is no MVN. I looked in the folder of Alexa on desktop, no MVN file and no exec.

**Comment by cornusandu** [comment]
bump

**Comment by shivasiddharth** [comment]
It is an issue with your Raspbian source list. 
open a terminal and type:
`sudo nano /etc/apt/sources.list`
Remove the contents that you see and paste the following:
```
deb http://archive.raspbian.org/raspbian stretch main contrib non-free
deb-src http://archive.raspbian.org/raspbian stretch main contrib non-free
```
Press ctrl+x and y to save
Now run the following in your terminal:
`sudo apt-get update`

After this, run through your alexa installation.

**Comment by cornusandu** [comment]
Hello again , I found the problem, it was my stupid internet provider. All ftp downloads were blocked. Than you very much for your great replies

**Comment by scotthea-amazon** [comment]
Hello cornusandu,

Thank you for letting us know you resolved the problem. I am closing the issue.  If I have closed it in error, please feel free to re-open it.

Best regards,
-SWH
