### ISSUE TITLE
Step 6a - Node.js

### ISSUE THREAD

**Issue by ahmedelmasri** [alexa/alexa-avs-sample-app#1052]
Hi,

I reached step: ["6a - Node.js"] and I am bit stuck. I have Alex Voice Service Window running but I can't go past this item here:

- A window should pop up with a message that says something similar to Please register your device by visiting the following website on any system and following the instructions: https://localhost:3000/provision/d340f629bd685deeff28a917. Don't press OK until you've obtained your tokens.

Aparently ["https://localhost:3000/provision/d340f629bd685deeff28a917"] this is an invalid URL and I believe the registeration code is invalid:

![image](https://user-images.githubusercontent.com/1706060/33911599-2bb64c3e-df93-11e7-9c41-90f17c5b6cd4.png)

I am also not sure where to get the Access Toke value in the client but perhaps that will be taken care of if the step above is overcome:

![image](https://user-images.githubusercontent.com/1706060/33911679-6412e42a-df93-11e7-83f2-452c8f068d00.png)

Any help would be so much appreciated,

-Ahmed

**Comment by ahmedelmasri** [comment]
It appears that I had a non-matching version of the VLC library. I fixed that in the POM.xml and I got the popup message:

![image](https://user-images.githubusercontent.com/1706060/33932922-90b57af4-dff4-11e7-9d6a-f7cfdb8a59f7.png)

Now that the demo is working, Can I design my own App get Alexa to answer from my own knowledge-base?

Thanks,

-Ahmed

**Comment by sanjayrd** [comment]
Hi @ahmedelmasri,

It looks like you may want to look into designing an Alexa skill if you want some sort of custom behavior with Alexa. See this [link](https://developer.amazon.com/alexa-skills-kit) for more info.

Thanks,
Sanjay

**Comment by ahmedelmasri** [comment]
Hi @sanjayrd,

Very nice of you to take the time to respond. I looked at the Alexa Skills, but they seem to be a bit more restricted. You can fill out a JSON template with your simple commands. I want to do something with more freedom. The sample Java client app here is really nice. Is there such a thing as a customized Alexa engine where you program it the way you want? 

Say: You would like to feed Alexa a set of known inputs, which the output can be computed via an algorithm written in any programming language: Example: can ask Alexa to give me all the named entities in a [PubMed ID: 29241199](https://www.ncbi.nlm.nih.gov/pubmed/29241199) (e.g., genes and disease) that have been mentioned in this article? As you see, there will be a lot of libraries in the background which will be called, not just a simple list of expected outcomes that are precomputed.

Thank you in advance,

-Ahmed

**Comment by sanjayrd** [comment]
H @ahmedelmasri,

The example you just described can be done with a skill. All skill requests get forwarded to your AWS lambda function, in which you can write code to do whatever you want. 

However, if you're looking to not use a skill, then you'll need to implement some sort of local speech recognition, followed by some sort of local natural language processing, finally followed by the routing of the request to your service, finally followed by a text-to-speech service that will translate your text into speech. Some services that may be helpful with this are: https://aws.amazon.com/lex/ and https://aws.amazon.com/polly/.

Thanks,
Sanjay

**Comment by ahmedelmasri** [comment]
Thank you very much, @sanjayrd! You are most helpful!!!

-Ahmed
