### ISSUE TITLE
Unable to decode the API key

### ISSUE THREAD

**Issue by PikkaPikkachu** [alexa/alexa-avs-sample-app#1054]
This is a part of Logcat:

I/com.amazon.identity.auth.device.api.authorization.AuthorizationManager: com.amazon.alexa.avs.companion calling authorize
12-14 04:25:19.713 2949-2949/? I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: getAppInfo : packageName=com.amazon.alexa.avs.companion
12-14 04:25:19.713 2949-2949/? I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: getAppInfoFromAPIKey : packageName=com.amazon.alexa.avs.companion
12-14 04:25:19.713 2949-2949/? I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: Finding API Key for com.amazon.alexa.avs.companion
12-14 04:25:19.715 2949-2949/? I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from assets directory
12-14 04:25:19.716 2949-2949/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.amazon.alexa.avs.companion
12-14 04:25:19.726 2949-2949/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: APIKey:<obscured>
12-14 04:25:19.726 2949-2949/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifyPayload for packageName=com.amazon.alexa.avs.companion
12-14 04:25:19.726 2949-2949/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Validating MD5 signature in API key:<obscured>
12-14 04:25:19.728 2949-2949/? I/com.amazon.identity.auth.device.utils.PackageSignatureUtil: num sigs = 1
12-14 04:25:19.730 2949-2949/? D/com.amazon.identity.auth.device.utils.PackageSignatureUtil.PII: Fingerprint checking:<obscured>
12-14 04:25:19.730 2949-2949/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Number of signatures = 1
12-14 04:25:19.730 2949-2949/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerprint checking:<obscured>
12-14 04:25:19.730 2949-2949/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding failed: certificate fingerprint can't be verified! pkg=com.amazon.alexa.avs.companion
12-14 04:25:19.730 2949-2949/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKey for pkg=com.amazon.alexa.avs.companion
12-14 04:25:19.730 2949-2949/? D/AndroidRuntime: Shutting down VM

I have already verified that my api_key.txt file is placed correctly. Also, ca.crt files match each other.
What could be the issue now?
Thanks for any help!

**Comment by sanjayrd** [comment]
Hi @PikkaPikkachu,

We are investigating the issue and will get back to you.

Thanks,
Sanjay

**Comment by sanjayrd** [comment]
Can you double check the api_key.txt file for whitespace? This is known to cause issues.

Thanks,
Sanjay

**Comment by PikkaPikkachu** [comment]
Actually, I figured that I was running the app in debug mode but using the api_key for release build type. 

I am closing this issue now. 

Thanks and regards,
Prakriti

**Comment by dendrocyte** [comment]
sorry I face the same issue. how to fix it? Please describe it in detail.
Another question is, Am I only available to test it in release mode?
