### ISSUE TITLE
No Timed Reminders

### ISSUE THREAD

**Issue by lestat1977uk** [alexa/alexa-avs-sample-app#1056]
Hi all,

Does anyone know if reminders can be set, i just get reminders are not supported on this device?

**Comment by kjkh** [comment]
Hi @lestat1977uk,

We currently do not support Named Timers and Reminders. If you wish to implement this functionality and start receiving the correct payload from AVS, you can enable Reminders as a capability:

1. Go to https://developer.amazon.com.
2. Sign in.
3. Alexa -> Alexa Voice Service.
4. Select your device and click Manage.
5. Click Capabilities.
6. Check _Named Timers and Reminders_.

**Comment by kjkh** [comment]
Closing issue. Please reopen if you have further questions.
