### ISSUE TITLE
audio output on Pi Zero W with seeedcard mic2

### ISSUE THREAD

**Issue by noemu** [alexa/alexa-avs-sample-app#1057]
I only hear a silent crack when the listening starts and nothing else.

Hardware:
Pi zero W with seeed-voicecard mic2
Software:
Linux raspberrypi 4.9.59+ #1047 armv6l with raspian stretch

If I say the Wakeword, the javaclient shows:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Device: pi_zero, DSN: 123456789
Alexa Voice Service - v20160207.6
Logged in.
Access token: ----
Listening
Processing
Done
```

But i hear nothing. The same if i press enter:
The wakeword Terminal shows following
```
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:KittAiSnowboyWakeWordEngine: handling pause
INFO:KittAiSnowboyWakeWordEngine: releasing portAudio
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:KittAiSnowboyWakeWordEngine: handling resume
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playba                                                                                                                                                             ck stream
ALSA lib pcm_direct.c:1055:(snd1_pcm_direct_initialize_slave) unable to install                                                                                                                                                              hw params
ALSA lib pcm_dmix.c:1064:(snd_pcm_dmix_open) unable to initialize slave
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only                                                                                                                                                              capture stream
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playba                                                                                                                                                             ck stream
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only                                                                                                                                                              capture stream
ALSA lib pcm_direct.c:1055:(snd1_pcm_direct_initialize_slave) unable to install                                                                                                                                                              hw params
ALSA lib pcm_dmix.c:1064:(snd_pcm_dmix_open) unable to initialize slave
INFO:WakeWordAgent: State set to IDLE(2)
```

the record and play works perfectly:
```
arecord -d 10 -f S16_LE -r 16000 test.wav
aplay test.wav
speaker-test -c2 -twav
```

in /boot/config.txt i've commented `dtparam=audio=on`
and the usb index=-1 is also commented

my alsarc in ~/
```
pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
    slave.pcm "dmixed"
    }

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    slave {
        pcm "hw:0,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
        format S16_LE
}
    ipc_key 1024
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:0,0"
        channels 2
    }
    ipc_key 666666
}
```

and aplay -l
```
**** List of PLAYBACK Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
aplay -L
```
null
    Discard all samples (playback) or generate zero samples (capture)
default
playback
capture
dmixed
array
sysdefault:CARD=seeed2micvoicec
    seeed-2mic-voicecard,
    Default Audio Device
dmix:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard,
    Direct sample mixing device
dsnoop:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard,
    Direct sample snooping device
hw:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard,
    Direct hardware device without any conversions
plughw:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard,
    Hardware device with all software conversions
```
and arecord -l
```
**** List of CAPTURE Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

With pulseaudio speaker-test doesn't work. So i removed it.

edit: i've seen now on https://alexa.amazon.de/spa/index.html#cards that alexa recieves all my questions and respons correctly. Only the sound output on the pi doesn't work.
Is there a way to test and debug the java sound output? Or get a better log from the javaclient?

**Comment by kjkh** [comment]
Hi  @noemu,

We don't have any tools to test sound output. Are you able to get any audio output at all? What type of audio output device are you using and have you tried connecting a different device?

**Comment by noemu** [comment]
audio output with sox , vlc, and aplay works perfectly. 
Only the avs javaclient doesn't give me any output.

I'm using a  ***ReSpeaker 2-Mics Pi HAT***.

Sry i don't have any diffrent device for the pi zero.

**Comment by kjkh** [comment]
This seems like an issue related to the ALSA config. Unfortunately, debugging ALSA configs is not something we can usually do effectively over GitHub issues due to the various combinations of microphones and speaker setups.

However, a few notes/suggestions:

- The application logs can be found at <java-sample-app-dir>/samples/javaclient/logs.
- I found this [tutorial](https://www.hackster.io/idreams/build-your-own-amazon-echo-using-a-rpi-and-respeaker-hat-7f44a0) which is attempting to do something similar, also using the ReSpeaker 2-Mics Pi HAT board. 
- This issue may provide some useful tips: https://github.com/alexa/alexa-avs-sample-app/issues/277.
- Attempt a fresh install.

**Comment by noemu** [comment]
i've tried a lot now. But nothing helped.

It seems to be a problem with the java playback or something with mp3 decoding. The log was clear, since java doen't throw any Error.
 I'm trying now a diffrent AVS client.

**Comment by mradulan** [comment]
@noemu , do you face the same issue on a different AVS Client?

**Comment by daviddave** [comment]
I had the same issue with my 2 microphone pi hat, What allowed audio to be outputted on it was through `sudo nano /etc/modprobe.d/alsa-blacklist.conf` and adding `blacklist snd_bcm2835` This disables the raspberry pis built in audio. Next  `nano ~./asound.rc` and paste the following 
`
pcm.!default {
    type hw
    card 0
}

ctl.!default {
    type hw
    card 0
}
`
Try removing your /boot/config.txt changes and it should work. Let me know how you get on.

**Comment by kclchan** [comment]
Hi @noemu, are you able to get past the problem you were having with @daviddave's suggestion?

**Comment by noemu** [comment]
so now i've got it running:

i've started with a fresh raspian strecth lite and installed the driver from [seeed-voicecard](https://github.com/respeaker/seeed-voicecard):

as suggested in [#1066](https://github.com/alexa/alexa-avs-sample-app/issues/1066) i've added the stretch part to the java installation (and installed dirmngr before the installation).

Then i set up the audio by:
1. adding ```blacklist snd_bcm2835``` to ```sudo nano /etc/modprobe.d/alsa-blacklist.conf``` (thanks daviddave)
2. activate the correct output ```sudo amixer cset numid=3 1``` (not sure if it's necessary)
3. removed the ~/.asoundrc (so the system is using the config from the seeed-driver in /etc/asound.conf)

4. Profit
