### ISSUE TITLE
Sample app for website

### ISSUE THREAD

**Issue by manojcena** [alexa/alexa-avs-sample-app#1058]
Hi,

can you please provide the sample working project for web i.e using JavaScript i am unable to find good documents for JavaScript.

**Comment by kjkh** [comment]
Hi @manojcena,

Unfortunately, we do not have a JavaScript AVS client at the moment.

**Comment by manojcena** [comment]
Hi @kjkh ,
from the following link https://github.com/miguelmota/alexa-voice-service.js?files=1  it says it is available and even that code is also  working  fine need better documentation  but you said no client at the moment.

**Comment by kjkh** [comment]
Hi @manojcena,

That project was built by an independent developer. The Alexa Voice Service communicates using HTTP/2, so any client which utilizes that transport protocol can communicate with the AVS endpoints.

**Comment by kjkh** [comment]
Closing ticket. If you have any further questions please feel free to re-open and we will assist you as best we can.
