### ISSUE TITLE
Can not get the StopCapture directive

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#1060]
Dear all.
Recently we found we put record audio data to AVS server , can not get the StopCapture directive if we don't send end boundary flag. BTW, about 2 weeks ago, we can get the StopCapture. But I don't know why we cannot get it after we send record audio data continuously with in recent weeks. 
Thanks a lot!

**Comment by kjkh** [comment]
Hi @howardguo,

Can you provide the application logs (<dir>/samples/javaclient/logs/application.log) for this request? We can take a look at the corresponding logs from AVS' side.

**Comment by howardguo** [comment]
No, we don't use the java client APP, we use our client write by myself. We have already run it several months, it worked well. But recently no StopCapture back to us. By the way, we use big-endian audio data pcm, because have no response if we use little-endian, is it right?

**Comment by kjkh** [comment]
Regarding the endianness question, we saw in your other post you're already aware of the spec on the AVS API site. As it states, you should be encoding the audio bytes in little endian. 

If you have some logs (preferably the x-amzn-requestid), we can take a look server side to search for any potential error messages regarding both the StopCapture and endianness issues.

**Comment by howardguo** [comment]
Yes, I have already change to little endian, it works well. But it still can not get the StopCapture if don't send the end-boundary that indicate audio data is finished.

**Comment by howardguo** [comment]
Got the issue, I will close this issue, thanks.

**Comment by ksanghai** [comment]
I am having similar issues. How did you resolve it? I was getting stopCapture before and now I don't get that event if I continuously stream audio to avs. Once I stop the audio stream to avs, I eventually get the stopCapture command. This was not the case 3-4 weeks ago. 

Here are my JSON header sent as a speech recognizer event:
                                     
b'--simple-avs-message-boundary\nContent-Disposition: form-data; name="metadata"\nConten
t-Type: application/json; charset=UTF-8\n\n{"event": {"header": {"dialogRequestId": "avs
-dialog-id-1514834151-1", "name": "Recognize", "messageId": "avs-message-id-1514834151-2
", "namespace": "SpeechRecognizer"}, "payload": {"profile": "FAR_FIELD", "format": "AUDI
O_L16_RATE_16000_CHANNELS_1", "initiator": {"type": "TAP"}}}, "context": [{"header": {"n
ame": "AlertsState", "namespace": "Alerts"}, "payload": {"activeAlerts": [], "allAlerts"
: []}}, {"header": {"name": "SpeakerState", "namespace": "Speaker"}, "payload": {"volume
": 50, "muted": false}}}]}'

**Comment by ksanghai** [comment]
Still trying to debug this issue - @howardguo, can you comment on how you solved this issue at your end?

**Comment by howardguo** [comment]
@ksanghai The issue is that client send&receive is in the same thread. If AVS server don't close the stream which client request, client downchannel will always be always blocked by sending audio data until  send the end boundary by client. So I make the send and receive process in two different thread, it worked well now.

**Comment by ksanghai** [comment]
ok. I have had the send and receive (downchanel) in a seperate thread and I was able to get stopcapture before. I haven't changed the code, its just suddenly a few weeks ago I stopped getting the stopCapture. I was thinking if it was some API change that caused it. Anyways, thanks for your comments. If you have any further suggestions, please let me know.
