### ISSUE TITLE
docker image for raspberry pi

### ISSUE THREAD

**Issue by khassel** [alexa/alexa-avs-sample-app#1063]
Hello,

don't know if this is the right place for sharing a docker-setup for raspberry pi:
[https://github.com/khassel/alexa_docker](https://github.com/khassel/alexa_docker)

If not, feel free to close this task ...

Karsten.

**Comment by kjkh** [comment]
Hi @khassel,

Thank you for sharing this and contributing to the community. We don't currently have a set procedure for highlighting this, but it will definitely help future users who wish to user docker.
