### ISSUE TITLE
One of the Allowed Origin URLs is invalid

### ISSUE THREAD

**Issue by Jayesh23Sawant** [alexa/alexa-avs-sample-app#1068]
![image](https://user-images.githubusercontent.com/34836779/34340657-41a16612-e9ae-11e7-9c0e-c471db5d46d2.png)

**Comment by mradulan** [comment]
The URL is correct. Are you not able to save it in the developer account?

**Comment by mradulan** [comment]
Can you try https instead of http?

**Comment by Jayesh23Sawant** [comment]
Thanks for the reply! The problem is solved :)

**Comment by jagan7157** [comment]
same problem iam getting ...can u explain how to solve pls...
