### ISSUE TITLE
JAVA+MAVEN installation issue

### ISSUE THREAD

**Issue by kdpatino** [alexa/alexa-avs-sample-app#1070]
Hello, 

I'm working in a **Rasbian Stretch** and in the JAVA+maven installation step I got this issue:

```
[INFO] Compiling 197 source files to /home/pi/alexa-avs-sample-app/samples/javaclient/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.739 s
[INFO] Finished at: 2017-12-27T17:07:57+00:00
[INFO] Final Memory: 7M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sample-java-client: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
I try to resolve with https://github.com/alexa/alexa-avs-sample-app/issues/528. but It doesn't work. 

Thank You.

**Comment by mradulan** [comment]
can you check if `mvn validate` is running successfully? If so, then run` mvn install`

**Comment by kdpatino** [comment]
Hello @mradulan 

I follow your suggestions:
```
pi@kernelAudio:~/github/alexa-avs-sample-app/samples/javaclient $ mvn validate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.556 s
[INFO] Finished at: 2017-12-28T16:50:24+00:00
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------
pi@kernelAudio:~/github/alexa-avs-sample-app/samples/javaclient $ 
```
Error when I did `mvn install`
```
pi@kernelAudio:~/github/alexa-avs-sample-app/samples/javaclient $ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample-java-client ---
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] Copying 5 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sample-java-client ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[INFO] Compiling 197 source files to /home/pi/github/alexa-avs-sample-app/samples/javaclient/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.853 s
[INFO] Finished at: 2017-12-28T16:49:38+00:00
[INFO] Final Memory: 7M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sample-java-client: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
pi@kernelAudio:~/github/alexa-avs-sample-app/samples/javaclient $ 
```

**Comment by mradulan** [comment]
@kdpatino ,did you run automated_install.sh correctly?
Can you try a script only for Java installation? it is as follows:

Origin=$(pwd)
Samples_Loc=$Origin/samples
Java_Client_Loc=$Samples_Loc/javaclient
echo "=========== Installing Oracle Java8 ==========="
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
chmod +x $Java_Client_Loc/install-java8.sh
cd $Java_Client_Loc && bash ./install-java8.sh

**Comment by kdpatino** [comment]
Hello @mradulan,

Yes, I make a ** Rasbian Stretch**  image from scratch and just run the **automated_install.sh**. 

Follow your instructions, I got:

```
pi@alexa:~/alexa-avs-sample-app $ Origin=$(pwd)
pi@alexa:~/alexa-avs-sample-app $ Samples_Loc=$Origin/samples
pi@alexa:~/alexa-avs-sample-app $ Java_Client_Loc=$Samples_Loc/javaclient
pi@alexa:~/alexa-avs-sample-app $ echo "=========== Installing Oracle Java8 ==========="
=========== Installing Oracle Java8 ===========
pi@alexa:~/alexa-avs-sample-app $ echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_MEASUREMENT = "es_CO.UTF-8",
	LC_PAPER = "es_CO.UTF-8",
	LC_MONETARY = "es_CO.UTF-8",
	LC_NAME = "es_CO.UTF-8",
	LC_ADDRESS = "es_CO.UTF-8",
	LC_NUMERIC = "es_CO.UTF-8",
	LC_TELEPHONE = "es_CO.UTF-8",
	LC_IDENTIFICATION = "es_CO.UTF-8",
	LC_TIME = "es_CO.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
pi@alexa:~/alexa-avs-sample-app $ chmod +x $Java_Client_Loc/install-java8.sh
pi@alexa:~/alexa-avs-sample-app $ cd $Java_Client_Loc && bash ./install-java8.sh
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.3 (stretch)
Version of Raspbian determined to be: stretch
Not running Raspbian Wheezy or Jessie. Exiting...
```
Thank You.

Regards,

Kevin Patino

**Comment by mradulan** [comment]
can you run the following commands?

# Remove any existing Java
sudo apt-get -y autoremove
sudo apt-get -y remove --purge oracle-java8-jdk oracle-java7-jdk openjdk-7-jre openjdk-8-jre

# Install Java from Ubuntu's PPA
# http://linuxg.net/how-to-install-the-oracle-java-8-on-debian-wheezy-and-debian-jessie-via-repository/
sudo sh -c "echo \"deb http://ppa.launchpad.net/webupd8team/java/ubuntu $UBUNTU_VERSION main\" >> /etc/apt/sources.list"
sudo sh -c "echo \"deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu $UBUNTU_VERSION main\" >> /etc/apt/sources.list"

KEYSERVER=(pgp.mit.edu keyserver.ubuntu.com)

GPG_SUCCESS="false"
for server in ${KEYSERVER[@]}; do
  COMMAND="sudo apt-key adv --keyserver ${server} --recv-keys EEA14886"
  echo $COMMAND
  $COMMAND
  if [ "$?" -eq "0" ]; then
    GPG_SUCCESS="true"
    break
  fi
done

if [ "$GPG_SUCCESS" == "false" ]; then
  echo "ERROR: FAILED TO FETCH GPG KEY. UNABLE TO UPDATE JAVA"
fi

sudo apt-get update
sudo apt-get -y install oracle-java8-installer
sudo apt-get -y install oracle-java8-set-default

**Comment by kdpatino** [comment]
Hello @mradulan ,

After a while I found a solution. Here are better instructions to install oracle-java.:
* https://www.linuxbabe.com/desktop-linux/install-oracle-java-8-debian-jessie-raspbian-jessie-via-ppa
* https://blog.sleeplessbeastie.eu/2017/11/02/how-to-fix-missing-dirmngr/

It works for me now in **Raspbian Stretch**.

Thank You for your support.

Regards,

Kevin Patino

**Comment by mradulan** [comment]
Closing the issue.

**Comment by NicoSoftware** [comment]
So I did the exact same to reinstall java8 but I'm still getting this error...
Any Ideas?


pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ sudo mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':10.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at com.amazon.alexa.avs.config.DeviceConfig.canOnlyDoHeadless(DeviceConfig.java:200)
	at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:192)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.102 s
[INFO] Finished at: 2018-03-10T21:46:28+00:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
