### ISSUE TITLE
alexa-avs-sample-app npm start error

### ISSUE THREAD

**Issue by RoboLlamas** [alexa/alexa-avs-sample-app#1071]
I keep getting this error after running 'npm start'

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:327
    throw err;
    ^

Error: Cannot find module 'destroy'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionService/node_modules/express/node_modules/send/index.js:14:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

any suggestions? 

Thanks

**Comment by mradulan** [comment]
can you check if the fields in config.js are same as in developer console?

**Comment by RoboLlamas** [comment]
Yes I have triple checked it and the client Id, client secret, and product ID are all correct.

**Comment by RoboLlamas** [comment]
Ok, so I did some things and solved that error. But now I am getting this error

pi@raspberrypi:~/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/pi/alexa-avs-sample-app/samples/javaclient/certs/server/node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-12-29T06_12_06_606Z-debug.log

**Comment by RoboLlamas** [comment]
Ok so I spent a bunch of time on this and finally got it working. First I reinstalled everything cause I had messed some things up. Then it turns out all I had to do was use sudo in the command... took me forever. Thanks for the help though!

**Comment by NicoSoftware** [comment]
Hey fella,
I'm having the same issue but it doesn't work with sudo npm start.
Can you describe what you've exactly did?
Thanks
