### ISSUE TITLE
Not a issue! But a big wish to the Linux Hackers, to get a notification when alexa here's anything

### ISSUE THREAD

**Issue by kikig1** [alexa/alexa-avs-sample-app#1075]
Hi Forum,
i hope it is no Problem to ask here such a thing, but i didn't know where else ;)

My Alexa Raspi App is part of a Magic Mirror Project, so far no Problem.

The Micro is Connected via Usb and so it is working every Time. The Audio out works via hdmi and the Monitor. But now the Problem: The Raspi puts the Monitor to sleep mode, when some minutes no one is seen in front of the Monitor (via pir sensor).

In this Moment Alexa can hear me but of course i can't here the Feedback.

Is there a chance to get a notification from the third shell, when the wakeword is hered? Maybe a hack for the third shell? Because there is activity, when the wakeword is hered. In this moment i have to send a command to the magic mirror, to put the monitor on.

Many thanks for each tip :)

best Regards.

**Comment by mradulan** [comment]
what is the magic mirror project? do you have any links? What is the third shell? Do you mean the 3 terminal windows of [Step 7](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi)?

**Comment by kikig1** [comment]
Hi,
the MagicMirror projekt is https://magicmirror.builders/ and the pir module is https://github.com/paviro/MMM-PIR-Sensor

But i think, the best and easiest way would be, to simulate a pir notifications. That is Linux, so this should be possible :)

Yes, i mean the third terminal, that starts the wakeword engine. I Think, this is the best way, to register when the wakeweard is hered and wake the mirror then? But maybe there is a better way?

**Comment by kclchan** [comment]
Hi @kikig1, maybe take a look at this thread #983.  There's some suggestions on adding a trigger when wakeword is detected.  Hope this helps!

**Comment by kikig1** [comment]
That should work.

Many thanks :)
