### ISSUE TITLE
Even for just testing, Is AVS running for only available countries?

### ISSUE THREAD

**Issue by jarvisjang** [alexa/alexa-avs-sample-app#1080]
Hello,

I'm living in South Korea.
Now I'm trying to test alexa-avs-sample-app. I followed up the all steps.
But the javaclient doesn't work well.

Even for just testing, Is AVS running for only available countries?

**Comment by kclchan** [comment]
Hi @jarvisjang, would you be able to elaborate what is not working well for you?  Thanks!

**Comment by jarvisjang** [comment]
There was a microphone issue. The test is successful.
