### ISSUE TITLE
Why does the wake word agent only work on Raspberry Pi?

### ISSUE THREAD

**Issue by xiurobert** [alexa/alexa-avs-sample-app#1090]
Title. I was just wondering because it would be much more convenient for it to be working on other operating systems.

**Comment by dhpp** [comment]
Hi @xiurobert,

Thanks for the suggestion.  We made the decision to target the Raspberry Pi as our main demonstration platform, however we also made efforts to write the WakeWordAgent in a portable way, so it should not be difficult for a developer to take the code to other platforms.  Also, the underlying sensory and kitt.ai engines are supported on other platforms.

However your feedback is appreciated, and we will consider this for future releases.  Thanks.

**Comment by xiurobert** [comment]
Thank you for the speedy response!
