### ISSUE TITLE
where will recording file store?

### ISSUE THREAD

**Issue by ketan1234567890** [alexa/alexa-avs-sample-app#1092]
Hello guys,
   I successfully run this Alexa on my pi2. but now i want to know that where my recording file store after saying alexa..

**Comment by dhpp** [comment]
Hi @ketan1234567890,

This is a good question - the SampleApp does not store the user speech on the device, but we transmit it to the AVS cloud service, so that Alexa may respond to the user.  There is no need for the user audio to be persisted on the local device.

Hope this helps.

**Comment by ketan1234567890** [comment]
Okk thanx @dhpp
But if i want to store that recording file locally on pi then what kind of changes i have to do in code
