### ISSUE TITLE
control gpio using this alexa avs sample app on pi

### ISSUE THREAD

**Issue by ketan1234567890** [alexa/alexa-avs-sample-app#1102]
Hello guys
  I want to control gpio pin of pi based on alexa command for home automation so can u please give me any link for that 
And also can i give native languages as a command like in hindi or gujrati..

**Comment by Alexnagel** [comment]
This is a very broad question, as you don't mention any language you have knowledge of. Probably Googling it yourself is easier. Here's an example for Python http://www.instructables.com/id/Control-Raspberry-Pi-GPIO-With-Amazon-Echo-and-Pyt/

No, those languages aren't available, https://developer.amazon.com/docs/custom-skills/develop-skills-in-multiple-languages.html

**Comment by bandkenamazoncom** [comment]
Thanks @Alexnagel for responding!

Please let us know if there are any followup questions.
