### ISSUE TITLE
Exception in thread "Thread-23" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension

### ISSUE THREAD

**Issue by rk-kant** [alexa/alexa-avs-sample-app#1106]
Hi,

I am getting the same issue while running java client.

following is the details of the same:

raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient#
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# javac -version
javac 1.8.0_161
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# grep alpn-boot.version *.xml
pom_other.xml: 
pom_other.xml: <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_other.xml: ${alpn-boot.version}
pom_other.xml: -Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar
pom_pi.xml: 
pom_pi.xml: <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_pi.xml: ${alpn-boot.version}
pom_pi.xml: -Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar
pom.xml: 
pom.xml: <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom.xml: ${alpn-boot.version}
pom.xml: -Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient#

I am not able to find the compatible alpn version with java version "1.8.0_161". Can you please help me out in this.

**Comment by khassel** [comment]
see https://github.com/alexa/alexa-avs-sample-app/issues/1093

**Comment by bandkenamazoncom** [comment]
Thanks @khassel!

**Comment by rk-kant** [comment]
Thanks @khassel 

I got the updated alpn version number from the suggested link.
