### ISSUE TITLE
Wake word agent giving error

### ISSUE THREAD

**Issue by rk-kant** [alexa/alexa-avs-sample-app#1107]
on 4th terminal session, I am running wakeWordAgent, which throughing following error:

root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# ./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-beta.10.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 Apr 2018 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:WakeWordAgent: thread started
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
^[[AINFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running

On 5th terminal session, I am running recording agent,
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/recordingAgent# sh run.sh 
cannot open audio device No such file or directory (No such file or directory)
cannot open audio device No such file or directory (No such file or directory)

Please help me in this

Much thanks in advance
Ravi Kant

**Comment by bandkenamazoncom** [comment]
Is the AVS client running?

**Comment by rk-kant** [comment]
Yes, 
Please find the following logs from terminal session 3

root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---

**Comment by bandkenamazoncom** [comment]
Sorry, you didn't mention it and the main line in the log was "Make sure AVS client is running"


This line is interesting:
```
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
```
Does your microphone work?  Can you get the SampleApp running with tap-to-talk?

**Comment by rk-kant** [comment]
I am not to locate tap-to-talk button on alexa. Can you help me out

**Comment by rk-kant** [comment]
I have followed following link for this:
https://github.com/conexant/alexa-avs-sample-app/wiki/Conexant4Mic-Raspberr-Pi

**Comment by bandkenamazoncom** [comment]
That link is empty.

**Comment by rk-kant** [comment]
https://github.com/conexant/alexa-avs-sample-app/wiki/Conexant4Mic-Raspberry-Pi

**Comment by rk-kant** [comment]
I got following prints on AVS Client


00:37:10.491 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.exception.AlexaSystemException: Unable to authenticate the request. Please provide a valid authorization token.
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:569) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:531) [classes/:?]

**Comment by bandkenamazoncom** [comment]
Did you set up a device profile on developer.amazon.com.

Were you able to put the proper information into `automated_install.sh`?

**Comment by rk-kant** [comment]
Yes, its all done. After all this is done, AVS client can run smoothly.

**Comment by bandkenamazoncom** [comment]
What state are you in now?  Is something still failing?

**Comment by rk-kant** [comment]
On the link which I have shared, I have reached till Step 9, Terminal Window 3.
While running Terminal Window 4 I am getting these prints for wake word engine.

Also I am not able record aything.
How to check if Mic is enabled in Alexa?

**Comment by rk-kant** [comment]
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# ./wakeWordAgent -e kitt_ai
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.cxsmtspk-pi-usb.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

INFO:KittAiSnowboyWakeWordEngine: thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:Not connected! Make sure AVS client is running
INFO:WakeWordAgent: thread started
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running

**Comment by rk-kant** [comment]
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# ./wakeWordAgent -e gpio
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:WakeWordAgent: thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
^CINFO:Kill signal received
INFO:Shutting down Wake Word Agent
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# 
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src#

**Comment by rk-kant** [comment]
I have tried all the 3 option for wake word engine. But nothing seems to be working. All are throwing one error or another.

**Comment by bandkenamazoncom** [comment]
Can you check to see if your microphone is working?

This might be useful, especially step 1:
https://diyhacking.com/best-voice-recognition-software-for-raspberry-pi/

Step 1: Checking Your Microphone
You need to first check whether your microphone records properly and if the mic volumes, etc are high. First, check if your webcam or microphone is listed using the command “lsusb“. Check if your mic/webcam comes up on the list.

Next, we need to set the mic recording volume high. To do this, enter the command “alsamixer” in the terminal. A neat graphical interface shows up, press the up/down arrow keys to set the volume. Press F6 (all), then select the webcam or mic from the list. Then again use the up arrow key to set the recording volume too high.

Now, you need to check if the recording takes place properly. Use the command “arecord -l” to check if your mic/webcam is listed. Then, use the command “arecord -D plughw:1,0 test.wav” to record sound. The sound will be recorded in the file “test.wav”. To listen to it, plug in your headphones to the pi and enter the command “aplay test.wav” in the terminal. If you’re able to hear the sound, your microphones works perfectly, else try adjusting the volumes and repeat the previous steps.

**Comment by rk-kant** [comment]
Nothing. I a, not able to record anything. How to record using Alexa. Mic on Alexa should record. How to enable on-board Mic of Alexas?

**Comment by bandkenamazoncom** [comment]
You need to have a working mic before Alexa is even in use.  Does the microphone work without Alexa?

**Comment by rk-kant** [comment]
I am running Alexa with Raspberrypi. You mean Mic connected to Raspberrypi should work, even if Alexa is not connected??

**Comment by mrmichaelhallett** [comment]
Raspberry pi has no built in mic.
Right?

**Comment by bandkenamazoncom** [comment]
In fact, the raspberry pi must have a microphone and it must be working before Alexa can use it.  There's no special drivers for the microphone in Alexa.

**Comment by rk-kant** [comment]
I am able to record now. But The recording I am not able to hear using Alexa Line Out. I can listen to the recording using raspberrypi audio jack.

**Comment by celinval** [comment]
I'm closing this issue, since the playback issue is tracked by #1114.
