### ISSUE TITLE
cant get access tocken

### ISSUE THREAD

**Issue by ketan1234567890** [alexa/alexa-avs-sample-app#1108]
Hello guys,
   I accidentally stop companion service before authentication. now i cant get authentication what i do now to up and running  it...???

**Comment by bandkenamazoncom** [comment]
Can you post some of the errors?  Is it possible to build a new refresh token?

**Comment by ketan1234567890** [comment]
No I think without authentication we cant get refresh token . but now i cant authenticate my alexa..

**Comment by bandkenamazoncom** [comment]
Can you make a new product ID?  I don't understand what exactly is going wrong.  Can you post some of the errors?

**Comment by ketan1234567890** [comment]
sorry for late reply
 i just format my entire pi and reinstall alexa again and now it works like charm!!!
