### ISSUE TITLE
Allow/restrict invocation to only one skill on a specific device

### ISSUE THREAD

**Issue by edoubart** [alexa/alexa-avs-sample-app#1113]
Let say I develop a custom skill and I want my device to only respond to that skill and ignore the others.

Is it possible to allow/restrict invocation to only one skill on a specific device?

Thank you

**Comment by frozenberg** [comment]
Hi @edoubart,

There is no way to outright restrict skills on a device. Skill enabling is only done through the account of the user. So if you are wanting _your_ device to only respond to one skill, that can be done, but you can't guarantee it for a device in general.

Fede

**Comment by edoubart** [comment]
Thank you so much for your quick answer @frozenberg! That's what I thought too, unfortunately this is not feasible at the moment.

**Comment by frozenberg** [comment]
No problem!
