### ISSUE TITLE
Alexa Sample App no longer working properly after updating Raspbian

### ISSUE THREAD

**Issue by smartieer** [alexa/alexa-avs-sample-app#1118]
After updating my Raspberry Pi (3B) to the latest version of Raspbian, the Alexa Sample app is no longer working. The companion service and Java client start and run without any errors, however, I am no longer able to click on the 'Tap to speak to Alexa' button. I know my mic input and sound output are working fine, because if I start the Kitt Ai wake word agent, I can still hear the wake tone when I say "Alexa". 

When I do say the wake word, however, I obviously get no response, and the output stays stuck at:

`INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)`

Any help would be appreciated!
Not sure if this is enough information, as I have very basic knowledge with this.
Thanks.

**Comment by mradulan** [comment]
which wake word engine are you using? KittAi or Sensory? Did you run the command `cd wakeWordAgent/src && ./wakeWordAgent -e <name-of-wakewordEngine>`

**Comment by smartieer** [comment]
I am using KittAi, and yes I used that command. As I said, I can hear the tone when I say “Alexa” but never get a response.

**Comment by smartieer** [comment]
I am using KittAi, and yes I used that command. As I said, I can hear the tone when I say “Alexa” but never get a response.

**Comment by mradulan** [comment]
this looks more of an output sound issue. Can you play any sound or music?

**Comment by mradulan** [comment]
For microphone run:
arecord -f S16_LE -Dplug:default test.wav
aplay test.wav

**Comment by smartieer** [comment]
Yes, that works, I can record and hear my voice fine. 
Here’s something else I forgot to mention; on the java client, the access token field is blank where there is usually a code, and the ‘login’ button is active. However, nothing occurs if try to click the login button.

**Comment by smartieer** [comment]
Solved! See here: #90 

The issue had to do with the ALPN and Java versions which must have updated with Raspbian.
I had to correct the versions numbers in the pom.xml file in the java client folder for it to work.

Alexa works perfectly as before now!
