### ISSUE TITLE
Cannot start MVN

### ISSUE THREAD

**Issue by GutnikGeorge** [alexa/alexa-avs-sample-app#1120]
This is what I get, all steps done:

[Thread-25] ERROR com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager - There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

**Comment by mradulan** [comment]
What is the OS on which you are running?
have you installed and validated mvn?
Did you run mvn validate, mvn install, and then mvn exec:exec?

**Comment by GutnikGeorge** [comment]
I have redone all steps in succeeded loading mvn.
