### ISSUE TITLE
One or more of the Allowed Origin URLs is invalid. Please use a valid URL

### ISSUE THREAD

**Issue by jagan7157** [alexa/alexa-avs-sample-app#1122]
![untitled](https://user-images.githubusercontent.com/35537108/35984996-9df3cf32-0d1b-11e8-9aaa-cb37f97b6f1a.jpg)

i face this type of problem...pls help to solve

**Comment by jagan7157** [comment]
its solved .....

**Comment by dc500** [comment]
@jagan7157 How did you fix it? I'm getting the same message.
