### ISSUE TITLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`

### ISSUE THREAD

**Issue by jagan7157** [alexa/alexa-avs-sample-app#1124]
hai friends i getting this type of error any one please help ..
                               

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd companionService && npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Port 3000 is already in use

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by mradulan** [comment]
can you check #1071 , the error is similar. Can you doing a npm install again?

**Comment by jagan7157** [comment]
sorry i not understanding what they are doing...can you explain breifly .....

**Comment by celinval** [comment]
Hi @jagan7157 ,

Are you running any other process that is using port 3000? You can run the following command to figure it out:

`netstat -tulpn`

Please look at the "Local Address" column and see if you can any entry that ends with **:3000**.
