### ISSUE TITLE
npm error, please help ..

### ISSUE THREAD

**Issue by NicoSoftware** [alexa/alexa-avs-sample-app#1127]
I get this error running npm start:
root@raspberrypi:/home/pi/alexa-avs-sample-app/samples/companionService# npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.59+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

it's a clean new raspbian image and I already did this the 3th time.
What Am I doing wrong??

**Comment by NicoSoftware** [comment]
While the Installation was running, it asked for a 'serial number'.
I'm not quite sure if I typed in the correct number.
Could that be the mistake?

**Comment by celinval** [comment]
Hi @NicoSoftware ,

Can you please run `npm install` from the "samples/companionService/" folder. After that, run `npm start`.

Thanks

**Comment by NicoSoftware** [comment]
It's already installed

**Comment by kencecka** [comment]
Hi @NicoSoftware,

I'm not sure precisely what's going wrong here, but before we dive into a bunch of details, have you tried running a clean install using automated_installer.sh?  There was another user seeing exactly the same errors you are in #524 who was able to get it running after reinstalling.

Ken

**Comment by NicoSoftware** [comment]
I've tried it now severall times with complete new stretch images. Didnt work. I've tried everything

**Comment by kencecka** [comment]
HI @NicoSoftware,

We should probably double-check some version information, as this install process normally works well.  Can you reply with a link to the raspbian image you are installing.  Also, are you using the most recent release of the Java Sample App from github?  Also, what hardware version are you using (which release of the Raspberry Pi)?  Can you post a log of the whole process you are following when you install on a new stretch image so we can review it for any error messages or problems that we might not have discussed already in this thread?

Thanks,
Ken

**Comment by NicoSoftware** [comment]
Hey,
I'm at work rn, but I always use the newest stretch Image from Raspberrypi.org, Noobs with Desktop on a Pi Zero.
And Yes I always use the newest AVS-sample-app.
I've noticed that the automated_install.sh always have some errors even tho I used my root user.
Thank you for taking the time!
Regards 
Nico

**Comment by sanjayrd** [comment]
Hi @NicoSoftware,

Any chance you can grab a Pi 2 or Pi 3, rather than a Pi Zero? Our [required hardware](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#required-hardware) section of the Raspberry Pi guide specifies this as a requirement.

Thanks,
Sanjay

**Comment by NicoSoftware** [comment]
I have a 3b but it's running openhabian, samba and mosquitto so I don't want to ruin the image ..

**Comment by celinval** [comment]
Hi @NicoSoftware,

Are you using the automated_installer.sh to install the java sample app? Can you please make sure you have the following file: samples/javaclient/certs/server/node.key? Also, can you open the samples/companionService/config.js and check that the variable "sslKey" has the correct path to the node.key file?

Thanks

**Comment by NicoSoftware** [comment]
Running this on a Raspberry Zero produced this issue. thank you for helping!
