### ISSUE TITLE
Alexa is forcing audio to HDMI regardless of pi configuration. Does anyone know have to change this?

### ISSUE THREAD

**Issue by aaronvejo** [alexa/alexa-avs-sample-app#1132]
I've changed things in alsamixer, amixer, and raspi-config but regardless the Alexa program will override my commands and force my audio out of my HDMI instead of my desired 3.5 jack. Any advice on how to change this?

**Comment by mavamazon** [comment]
Hi!

SDK uses the default system output. 

Can you please execute the following commands and add their output here:

cat ~/.asoundrc
aplay -l -L
arecord -l -L
arecord /tmp/test.wav
aplay /tmp/test.wav

Can you please run the two commands below and see if you hear a beep?

gst-launch-1.0 -m audiotestsrc ! autoaudiosink
gst-launch-1.0 -m audiotestsrc ! alsasink

Thanks

**Comment by aaronvejo** [comment]
Thanks, I reinstalled my OS and started from scratch and it works perfectly now.

**Comment by mavamazon** [comment]
Thank you for your feedback! I am closing the ticket. Feel free to reopen it if you have the same problem again.
