### ISSUE TITLE
Finding the right Raspian Image

### ISSUE THREAD

**Issue by NicoSoftware** [alexa/alexa-avs-sample-app#1139]
Since I'm trying to install alexa for several weeks now with different OS with the stretch java modifications, I wanted to ask if there's a correct Raspbian  Jessie/Wheezy Image to download. Both Raspian editions aren't supported anymore and therefore it's almost impossible finding a correct Download.
Has someone a Link?
Thank you

**Comment by mavamazon** [comment]
Hi @NicoSoftware!

Sorry, but we also has discontinued the support for the Jessie. The best option you should consider is to use the [AVS C++ SDK](https://github.com/alexa/avs-device-sdk) on Stretch.
