### ISSUE TITLE
Alexa speech output ignores volume settings

### ISSUE THREAD

**Issue by martinsteinorth** [alexa/alexa-avs-sample-app#1141]
The alexa speech output is always at max volume which makes it sound scratchy. Setting the volume via voice command only affects audioplayer playback like radio or other streams but not the alexa speech output itself.

This is somewhat related to #846 as the symptoms are identical.

External speaker is connected over the 3.5mm headphone jack of the conexant devkit board.

**Comment by mavamazon** [comment]
Hi Martin!
Could you please try to say "Alexa, volume 1", then "Alexa, briefing" and see if sound is still loud and distorted?

**Comment by martinsteinorth** [comment]
Hey @mavamazon,

thanks for your reply. Yes, the sound is still loud and distorted after your instructions. Playing radio over TuneIn works fine and respects volume setting. One more info: We are using the "older" Java Client that is in maintenance mode since January.

**Comment by mavamazon** [comment]
Martin,
The whole Java Sample App is in maintenance mode, i.e. it won't receive any updates anytime soon. I strongly encourage you to move to the [C++ AVS SDK](https://github.com/alexa/avs-device-sdk). It is in active development and we are working to close the functionality gap between SDK and our devices such as Echo.

**Comment by martinsteinorth** [comment]
Ok, I see, but we cannot switch to another SDK at the moment. Do you have a hint for me, where I can start debugging, so I can patch it on my own?

**Comment by kencecka** [comment]
Hi Martin,

Can you test using the headphone jack on the raspberry pi rather than the one on the Conexant board?  Does it exhibit the same distortion?  Are you able to adjust the speech volume when using the raspberri pi jack?  I'd like to isolate whether this issue is specific to the Conexant board, or a more general issue with the java app.

Ken

**Comment by martinsteinorth** [comment]
Hey all,

I'm again working on the project and had some time to debug. I know this is the old SDK but if someone struggles with the same issue, this might help:

Speech and Media playback are handled through different players. Only the media player is currently capable of respecting the general volume as it has a volume setting for the playback. 

Speech output however is being done with javazoom.jl.player which has no ability to change the volume. 

See: https://github.com/alexa/alexa-avs-sample-app/blob/df08ff7327adca9f9ae3077c0343c7f6e69a2816/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSAudioPlayer.java#L933

For the sake of simplicity I duplicated some of the javazoom player components into a seperate package and added volume control to the player class following this reference: http://www.javased.com/index.php?source_dir=JVerge/src/audio/javazoom/jl/player/Player.java

This works now.

Martin
