### ISSUE TITLE
mvn exec:exec Error

### ISSUE THREAD

**Issue by sm8224** [alexa/alexa-avs-sample-app#1144]
I have been trying to create the Raspberry Pi Echo.    I am currently at the step where you enter the mvn exec:exec to pop the window open and authenticate your device.    It is giving me an error:

The build could not read 1 project -> Help 1
'dependencies,dependency.version' for org.mortbay.jetty.alpn:apln-boot:jar is missing. @ line 59, column 16

any help would be appreciated.   I have googled this issue and tried many thing thus far.   I am very new to Linux and just trying to do something fun with my Raspberry.   

thank you

**Comment by sm8224** [comment]
To fix my issue, I upgraded from Wheezy to Stretch and started over.    this fixed the problem and the project is working correctly now.

**Comment by sanjayrd** [comment]
Awesome, great to hear @sm8224!
