### ISSUE TITLE
Is it possible to set up hands free(without touching/tapping any button) AVS in Windows computer using Java?

### ISSUE THREAD

**Issue by OrangOtang** [alexa/alexa-avs-sample-app#1150]

**Comment by OrangOtang** [comment]
Sensory or KITT.AI example is present for RasPi but I did not find anything for Windows. Someone please help me.

**Comment by scotthea-amazon** [comment]
Hi OrangOtang,

We do not have documented steps for doing this on Windows.  The AVS Java Sample App is in maintenance mode, so no one will be adding such steps to this project.

That said, if you were to get a Windows version of one of the wakeword engines, you might be able to adapt the sample app to work with them.

Thank you,
-SWH

**Comment by OrangOtang** [comment]
Thank you SWH

**Comment by scotthea-amazon** [comment]
Hi OrangOtang,

I am closing this issue since it appears your question was answered.  If I have closed it in error, please feel free to re-open it.  If you have further questions, please create a new issue.

Thank you,
-SWH
