### ISSUE TITLE
Alexa Kitt_Ai Not working

### ISSUE THREAD

**Issue by Piflyer** [alexa/alexa-avs-sample-app#1154]
Hi!
I have a Raspberry Pi Model 3 B running with the AIY kit, and it seems that the Kitt_AI doesn't work. The JavaClient works perfectly fine. Also, when downloading the file, the installer said to run this `cd /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src && sudo ./wakeWordAgent -e gpio` instead of the directions. I ran it, and had to adjust the daemon file (I was using the Pi Up My Life instructions), and it popped up this `INFO:main: Starting Wake Word Agent INFO:WakeWordAgent: State set to IDLE(2) INFO:WakeWordIPCSocket::mainLoop thread started INFO:WakeWordIPCSocket: init socket on port:5123 INFO:===> Connected to AVS client <=== INFO:WakeWordAgent: thread started INFO:WakeWordAgent: IPC Command received:3 INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
` which looked normal, but it didn't wake up when I said the wake word. Any suggestions?

**Comment by celinval** [comment]
Hi @Piflyer, 

Can you please make sure you follow all instructions from [this](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi) guide?

Thanks
