### ISSUE TITLE
How can I let AVS know that my device is with screen?

### ISSUE THREAD

**Issue by FengXMGeek** [alexa/alexa-avs-sample-app#1156]
I try to use "the tonight show" skill to play video In avs-sample-app project !
 I can reach a url :" https://s3.amazonaws.com/content-prod-tsjf-alexa-audio-us-east-1/Monologue.mp3" .
It`s not a video! But I can show a video in echo show with the some voice comand ！
Is these some parameters to tell cloud :"I`m a device with screen "?

**Comment by celinval** [comment]
Hi @FengXMGeek, 

Have you enabled display cards in your device? You can follow [these](https://developer.amazon.com/docs/alexa-voice-service/display-cards-overview.html#enable-display-cards) instructions.

**Comment by FengXMGeek** [comment]
@celinval  I have ! but I can`t get video from the json!

**Comment by celinval** [comment]
Hi @FengXMGeek,

Unfortunately, the AVS interfaces and avs-device-sdk project do not support the display of video yet. We do plan to add support to it in the future.
