### ISSUE TITLE
Please clarify "maintenance mode"?

### ISSUE THREAD

**Issue by E3V3A** [alexa/alexa-avs-sample-app#1157]
Hi, 
On your readme you say: `The AVS Java Sample App is in maintenance mode.` 
What does that mean?

**Comment by celinval** [comment]
Hi @E3V3A,

It means that we are not planning to release any new feature to the Java Sample App.

Thanks,
Celina

**Comment by E3V3A** [comment]
@celinval  Sure, but is that a permanent decision or something temporary? (Are we supposed to migrate away from this?)

**Comment by jairajiv** [comment]
@E3V3A  Yes, we are deprecating this repository in the coming weeks. Check out https://github.com/alexa/avs-device-sdk, if you are looking for a replacement.

**Comment by E3V3A** [comment]
Finally a straight answer. Thank you.  :+1:
