### ISSUE TITLE
connection to the sample app using the official "android app by amazon for alexa"

### ISSUE THREAD

**Issue by aashwinGaur** [alexa/alexa-avs-sample-app#1160]
Is there a way to connect the sample app via the amazon alexa app available on google play. I mean in my phone it shows that my raspberry pi is online and i can send voice commands to alexa through the phone . But the sample app creates a notification of it instead of acting on it . All I hear is the notification beep.
Is there a way to access those notifications through code ? Or should alexa respond to the commands sent through the phone .

**Comment by priyagsenthil** [comment]
Hi Aashwin,

Can we understand your use case better. Are you trying to use the microphone in the phone to send voice requests to AVS and expect the return audio to be played in raspberry pi device. If yes this is not a supported use case. Please advise what you mean by " i can send voice commands to alexa through the phone".

Thanks
Priya

**Comment by aashwinGaur** [comment]
every time i send a command using the alexa app on my phone, i hear a beep on the speakers attached to my raspbrry pi . How is that happening. Also the terminal running the java client updates with a notification recieved status .

**Comment by priyagsenthil** [comment]
What exactly do you mean by "send a command using Alexa app". There is no way to send audio from the Alexa app. How are you sending the command?

**Comment by aashwinGaur** [comment]
[http://www.zdnet.com/article/amazons-adds-voice-control-to-alexa-app-for-android/](url) update your app.. you might get the feature . 
![screenshot_2018-03-29-13-39-33](https://user-images.githubusercontent.com/34812792/38077734-9f7e7034-3357-11e8-9c93-91ee4a54e109.png)

**Comment by priyagsenthil** [comment]
Thanks for the screenshot. We will get back to you on our findings.

**Comment by priyagsenthil** [comment]
Hi aashwinGaur,

Are you trying to send voice command over android Alexa app and receive the output on a raspberry pi or are you trying to get the output from your phone.

Voice command over Andriod app -> output on a different Alexa end point (like RaspPi) is not supported. Are you saying even though this should not be supported it caused a notification on your device.

Voice command over Android app -> output on Android app -> supported. If this is not working we can route it to a different team that handles Android app endpoint.

Can you provide a step by step with exact utterance that you specified to your app? Were you app and device close by for both to pick utterances and were they not co located? Please advise.

-Priya

**Comment by aashwinGaur** [comment]
i was trying -->
Voice command over Andriod app ->  output on the RaspPi.
 I ssh'ed into my rasperry pi . started the java client in **terminal 1 **. This caused the avs sample app to start .
Then i launched my "android alexa app" . My raspberry pi is named "The machine". The android app stated that **the machine** was online . Then I tried sending a command using the app . it caused **a notification received status** in **terminal 1 **. Whatever be the utterance  when I  speak into the android app it  causes a notification.. with the speaker on the rasPi beeping . 
Its not possible for both the devices to pick up utterances as I do not have a microphone(i have ordered for one) attached to the rasPi. I am unable to listen to the notifications right now . When I do get a mic , I  might be able to tell what exactly  the device is  recieving.
