### ISSUE TITLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/w                                                                                        

### ISSUE THREAD

**Issue by gilles057** [alexa/alexa-avs-sample-app#1163]
Can somebody please help?

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alex                                                                                        a-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend                                                                                         them for the AVS app.

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/pi/Desktop/alexa-avs-sample-app/sa                                                                                        mples/javaclient/certs/server/node.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/compani                                                                                        onService/bin/www:21:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/w                                                                                        ww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start                                                                                         script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                        ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-04-08T18_04_40_633Z-debug.log

**Comment by BennyAvramson** [comment]
Hi @gilles057,

could you run `ls -l /home/pi/Desktop/alexa-avs-sample-app/sa mples/javaclient/certs/server` to see the ownership and permissions of the file `node.key`?

Thanks,
Benny

**Comment by gilles057** [comment]
Hi BennyAvramson,

thank you for helping.

Gilles
