### ISSUE TITLE
avs-sample-app build fail

### ISSUE THREAD

**Issue by furueili** [alexa/alexa-avs-sample-app#1164]
as title,
Please help thx

error: /Users/compal/Downloads/alexa-avs-sample-app-master-3/samples/iOSCompanionApp/Resources/App/ca.der: No such file or directory

**Comment by BennyAvramson** [comment]
Hi @furueili,

Could you elaborate on which platform you're running the SampleApp.
Also, where and how you're trying to run the iOSCompanionApp.

Thx,
Benny

**Comment by BennyAvramson** [comment]
Hi @furueili,

I'm assuming you're using Mac.
If so, as part of the installation process ([Step 4.6](https://github.com/alexa/alexa-avs-sample-app/wiki/Mac#4---generating-self-signed-certificates)) you should run the script `generate.sh`

The script should copy the `ca.der` file under `iOSCompanionApp/Resources/App/`
From the first screenshot you sent, it seems the file couldn't be found there.

- Have you run the script?
- Could you try running the installation process again and attach the output here?

Thanks,
Benny

**Comment by furueili** [comment]
I try to run gernerate.sh but got something wrong...
![2018-04-12 8 27 31](https://user-images.githubusercontent.com/1407724/38649860-64b5182a-3e2b-11e8-8cc6-a5d002ce9b31.png)
![2018-04-12 8 23 43](https://user-images.githubusercontent.com/1407724/38649747-f0afb3ea-3e2a-11e8-9b6d-b2a8642da331.png)
![2018-04-12 8 26 31](https://user-images.githubusercontent.com/1407724/38649822-3d35f4cc-3e2b-11e8-9414-2baa0e28e407.png)

**Comment by BennyAvramson** [comment]
Hi @furueili,

It's hard to read the output from the screenshots, especially since part of the information is cut off. Could you run the script again and **copy** the output here?

Thanks,
Benny

**Comment by furueili** [comment]
Its the openssl issue

modify openssl directory in generate.sh -> /usr/local/opt/openssl/bin/openssl

[(https://github.com/alexa/alexa-avs-sample-app/issues/1004)]
