### ISSUE TITLE
AlexaPi Authorisation Error

### ISSUE THREAD

**Issue by ewimp1** [alexa/alexa-avs-sample-app#1173]
Hello, I am following the steps in 

https://lifehacker.com/the-simplest-way-to-build-a-raspberry-pi-powered-amazon-1794218212 

to use my Raspberry Pi as an Echo dot.

Currently I am unable to authorise my devise: when I go to http://192.168.1.105:5050 I get the error:

The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

In my security profile on my Amazon developers account I have:

Allowed Origins | http://localhost:5050 | https://localhost:5050 | https://192.168.1.105:5050 
Allowed Return URLs https://localhost:5050/code | http://localhost:5050/code | https://192.168.1.105:5050/code | http://localhost:5050/authresponse | https://localhost:5050/authresponse | https://192.168.1.105:5050/authresponse | https://192.168.1.105/code | https://192.168.1.105/authresponse

I can't add the Raspberry Pi IP address without https. The port 5050 is the one I have been asked to go to when running sudo ./AlexaPi/src/scripts/setup.sh.

Also just to mention, I have tried to go to http://192.168.1.105:5050 in my laptop's browser. I am running the installation to the Pi through my laptop by SSH.

If anyone can help that would be great!

PS I am a complete newbie so assume I know nothing and simple answers would be much appreciated.

**Comment by ewimp1** [comment]
Thanks a lot!

Unfortunately it failed at the authorisation step with the SDK too. 

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

I'll try again tomorrow but do you think this is part of a wider issue with my request?

**Comment by bandkenamazoncom** [comment]
I'll check to see if it's a larger problem.  What region are you attempting to connect from?

**Comment by ewimp1** [comment]
Connecting from the UK.

**Comment by ewimp1** [comment]
BTW I just put an random number for DEVICE_SERIAL_NUMBER. For CLIENT_ID and PRODUCT_ID I used the client ID and security profile ID from my Amazon developer profile.

**Comment by bandkenamazoncom** [comment]
That is entered perfectly fine, thanks for adding it to the thread.

**Comment by ewimp1** [comment]
Hi so I think the PRODUCT_ID was wrong. There was an actual Product ID I should have used. I have no resolved the above issue.

Thanks for your help.
