### ISSUE TITLE
Not able to complete Terminal 2 in step 7?

### ISSUE THREAD

**Issue by romorocker** [alexa/alexa-avs-sample-app#1180]
So I am new to the raspberry pi, and I was hoping to make my own homemade Alexa to show my parents that learning about computers is not a waste of time.

I got all the way to the Terminal 2, and that's where I got into an issue. I was able to sig into Amazon, but instead of going to the localhost website I got a message saying the website cannot be reached.

Then going back to the java popup, I go to the link in the browser and still nothing I can't reach the website.

Can anyone please help me? Thanks!

**Comment by frozenberg** [comment]
Hi @romorocker,

The Java SampleApp is on the path to deprecation. You can set up Alexa on your pi with the C++ SDK: https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

That guide should get you up and running and parent-impressing in no time!

Fede

**Comment by romorocker** [comment]
@frozenberg 

Will it function the same, where Alexa works with voice commands and wake words?

**Comment by frozenberg** [comment]
Yep, it is a fully functional AVS client.

**Comment by romorocker** [comment]
Okay! And would I just start all over again with this new tutorial?

**Comment by frozenberg** [comment]
Yep!
