### ISSUE TITLE
Run mvn exec:exec  error

### ISSUE THREAD

**Issue by xuewenxu** [alexa/alexa-avs-sample-app#1182]
I was do it step by step by https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi.
when run mvn exec:exec, it appeard  error.
logs(run mvn exec:exec again) is :
  pi@raspberrypi:~/alexa_avs_sample_app/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Error: Could not find or load main class com.amazon.alexa.avs.App
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.470 s
[INFO] Finished at: 2018-05-03T09:56:14+00:00
[INFO] Final Memory: 8M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by frozenberg** [comment]
Hi @xuewenxu,

The Java SampleApp is on deprecation path. I highly recommend switching over to the C++ SDK. This [https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script](guide) will get you started on RaspberryPi in no time and with much less hassle.

Good luck,
Fede
