### ISSUE TITLE
Change default location from Seattle?

### ISSUE THREAD

**Issue by erosh** [alexa/alexa-avs-sample-app#1187]
Hi.
I'm using echo dot v2.
I changed the location to Belarus, Minsk.
But Alexa still think that I'm in Seattle

**Comment by mavamazon** [comment]
Hi!
How did you change your location? You should try changing the location on alexa.amazon.com site (it worked for me personally for the Moscow location).

**Comment by erosh** [comment]
Location on alexa.amazon.com site is the same as in my phone application - Belarus, Minsk.
But echo dot says that location is Seattle. Also metric/temperature system didn't apply. Weather forecasts are in F not in C.
Also phone app doesn't save city if street and region are both empty

**Comment by mavamazon** [comment]
Could it be that the device in your app and your echo dot are different devices? Can you see "now playing" showing the correct content being played at the moment?

**Comment by mavamazon** [comment]
Well, it seems that there is nothing more I can help you with - this repository and issue tracker is for Alexa integration into third party devices :) Anyway, please make sure you are following the steps described here:
https://www.amazon.com/gp/help/customer/display.html?nodeId=202015880
There is also a "Contact Us" button on the bottom left that could help you reach proper support team.

**Comment by kjkh** [comment]
Closing issue. Please feel free to reopen if there are further questions.
