### ISSUE TITLE
Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script. Windows 10

### ISSUE THREAD

**Issue by veddhaedsa** [alexa/alexa-avs-sample-app#1188]
`Listening on port 3000
Successfully retrieved registration code for Alesha / 123456789
fs.js:132
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:132:11)
    at Object.fs.close (fs.js:506:20)
    at C:\alexa\samples\companionService\node_modules\node-storage\index.js:160:10
    at fn (C:\alexa\samples\companionService\node_modules\async\lib\async.js:638:34)
    at Immediate.<anonymous> (C:\alexa\samples\companionService\node_modules\async\lib\async.js:554:34)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skye-\AppData\Roaming\npm-cache\_logs\2018-05-22T22_35_15_678Z-debug.log`

And this C:\Users\skye-\AppData\Roaming\npm-cache\_logs\2018-05-22T22_35_15_678Z-debug.log:

> 0 info it worked if it ends with ok
1 verbose cli [ 'A:\\node\\node.exe',
1 verbose cli   'A:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
7 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: A:\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\alexa\samples\companionService\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\C:\Program Files\Git\cmd;C:\Program Files\Sublime Text 3;%sSUBLIME%;C:\Users\skye-\AppData\Local\Microsoft\WindowsApps;C:\Users\skye-\AppData\Local\atom\bin;C:\Users\skye-\AppData\Local\GitHubDesktop\bin;C:\Program Files\Heroku\bin;C:\Users\skye-\.babun;C:\Users\skye-\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\adb;A:\xampp\php;A:\composer;C:\Program Files\PuTTY\;A:\node\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\C:\Program Files\Git\cmd;C:\Program Files\Sublime Text 3;%sSUBLIME%;C:\Users\skye-\AppData\Local\Microsoft\WindowsApps;C:\Users\skye-\AppData\Local\atom\bin;C:\Users\skye-\AppData\Local\GitHubDesktop\bin;C:\Program Files\Heroku\bin;C:\Users\skye-\.babun;C:\Users\skye-\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\adb;C:\Python27\;C:\Python27\Scripts;C:\Program Files\PostgreSQL\10\bin;C:\Users\skye-\AppData\Roaming\Composer\vendor\bin;C:\Users\skye-\Desktop\OpenSSL\bin;C:\Users\skye-\AppData\Roaming\npm;C:\Users\skye-\AppData\Local\Microsoft\WindowsApps;C:\apache-maven-3.5.3\bin;C:\OpenSSL-Win64\bin;C:\Program Files\VideoLAN\VLC;
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: C:\alexa\samples\companionService
10 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
13 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (A:\node\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (A:\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
15 verbose cwd C:\alexa\samples\companionService
16 verbose Windows_NT 10.0.17134
17 verbose argv "A:\\node\\node.exe" "A:\\node\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Help me thanks

**Comment by veddhaedsa** [comment]
my config.js:
`/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: "amzn1.application-oa2-client.ce8b24c1efef44af**********",
    clientSecret: "15628eff3f926faae71d44d63efab9269d670de6a67d3f4****",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey: "C:/alexa/samples/javaclient/certs/server/node.key",
    sslCert: "C:/alexa/samples/javaclient/certs/server/node.crt",
    sslCaCert: "C:/alexa/samples/javaclient/certs/ca/ca.crt",
    products: {
        "Alesha": ["123456789"],
    },
};

module.exports = config;
`

**Comment by kjkh** [comment]
Hi @veddhaedsa,

Can you try running `npm update` and seeing if that rectifies the issue? If not, can you run:

`npm --version`
`npm list`

and copy the outputs of that? Also, have you tried reinstalling npm and node.js?

Additionally, since the Java Sample App is in maintenance mode, no further features will be added. The AVS C++ SDK is better supported with new features being constantly added. Quick start guides for a variety of platforms can also be found here: https://github.com/alexa/avs-device-sdk.

**Comment by veddhaedsa** [comment]
@kjkh i've close this issue, since i move to ubuntu and everything works fine. Thank u for your answer ^^
