### ISSUE TITLE
Change language to Engligh

### ISSUE THREAD

**Issue by acoge** [alexa/alexa-avs-sample-app#1192]
I installed Alexa on a RasPi and the device respond in German.
I would like to change the language to English.

**Comment by scotthea-amazon** [comment]
Hello acoge,

If you are using SampleApp, you should be able to use the console commands to change the language:

1. enter 'c' and <enter> to get to the settings menu
2. enter '1' and <enter> to select a language option
3. enter '1' (for US English) or '2' (for UK English) and <enter>
4. Ask Alexa something (speaking in English)

Please let us know if that help!
-SWH

**Comment by acoge** [comment]
Thank you very much it works !
