### ISSUE TITLE
WAKE_WORD_PAUSED(6) maybe because of a not supported java version?

### ISSUE THREAD

**Issue by McNose** [alexa/alexa-avs-sample-app#1193]
Hi everybody,

this ist strange, seems like nobody has the same problem like me. Or maybe I am just not very smart.
I tried stretch and jessie on my PI3.
For example my fresh install of jessie has got java 1.8.0.65 installed.
When I install the avs-sample-app, it updates the java version to 1.8.0.171 which is a not supported version.

So, when I say alexa, I can hear the "ping" but then nothing happens anymore. The wakeword agent stays at "State set to WAKE_WORD_PAUSED(6)".
The internet says that this happens if the java version is not supported by the AVS-sample-app.
And the support stops at java 1.8.0.162.

How can I stop the AVS-sample-app installing the newest version of java?
I tried to downgrade it on my own, but didnt had success.

How do you install the avs-sample-app?
Do you have the same issue?

Thank you guys.

**Comment by McNose** [comment]
I just made a try and deleted the line 492 "sudo apt-get update" in the automated_install.sh.
My java version kept the 1.8.0.65 but the error still occurs.

Any ideas?

**Comment by McNose** [comment]
Maybe you guys can see something in my javaclient logfile from logs/application.log

23:55:26.097 [main] INFO  com.amazon.alexa.avs.AVSController - Creating Wake Word IPC | port number: 5123
23:55:27.110 [main] INFO  com.amazon.alexa.avs.AVSController - Created Wake Word IPC ok.
23:55:27.123 [main] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
23:55:27.276 [main] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
23:55:29.158 [main] INFO  com.amazon.alexa.avs.http.AVSClient - HttpClient starting
23:55:30.224 [main] INFO  com.amazon.alexa.avs.http.AVSClient - HttpClient started
23:55:30.371 [pool-7-thread-1] DEBUG com.amazon.alexa.avs.NotificationManager - Loaded notification indicator state from disk
23:55:41.523 [Thread-1] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - New IPC client was accepted, current of current clients is 1
23:55:54.637 [Thread-25] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Received wake word detected
23:55:54.637 [Thread-25] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Wake Word Detected ......
23:55:54.639 [Thread-26] INFO  com.amazon.alexa.avs.ui.controllers.ListenViewController - Wake Word was detected
23:55:54.640 [Thread-26] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
23:55:55.749 [Thread-26] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "9d9843fd-ca29-4d8f-9ced-0ca64e6eb796",
      "dialogRequestId" : "c2ca19fe-8c47-46cf-b4a2-bf0dd3ed8727"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
23:55:55.765 [Thread-26] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
23:55:55.766 [Thread-26] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output

**Comment by McNose** [comment]
The alpn-boot.version seems to mach in my pom.xml

1.8.0u65 | 8.1.6.v20151105

**Comment by McNose** [comment]
Here is the debug after saying "Alexa"

command: cd ~/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e kitt_ai

INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
INFO:KittAiSnowboyWakeWordEngine: thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started
INFO:KittAiSnowboyWakeWordEngine: Wake Word Detected
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:KittAiSnowboyWakeWordEngine: handling pause
INFO:KittAiSnowboyWakeWordEngine: releasing portAudio
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)

it stops after the "beep".

**Comment by scotthea-amazon** [comment]
Hi McNose,

It looks like the wakeword was detected because tour log shows that a recognize request is getting generated.  Perhaps if you attached (preferred over dumping the log text a a comment) a complete client log we could correlate that to service side activity and see whether the recognize request is actually received.

Thank you,
-SWH

**Comment by McNose** [comment]
Hi SWH,

thank you for your help.
Where do I find the complete client log?
I had a look at alexa.amazon.de but could only find the history.
The last entry in the history is some weeks ago.

Thank you
McNose

**Comment by McNose** [comment]
Maybe I forgot to mention that everything worked fine a couple of month ago.
I needed to reset my raspberry and now it is not working anymore.
I have tried a clean install of jessie and stretch and directly installed the latest AVS version.

Can nobody help?

**Comment by McNose** [comment]
I just found and installed the avs-device-sdk which works fine.

I am really happy. Thank you guys for devolping such great things!
