### ISSUE TITLE
Bad request INVALID_REQUEST_EXCEPTION

### ISSUE THREAD

**Issue by yuyubaba** [alexa/alexa-avs-sample-app#1199]
when i request EVENT.https://avs-alexa-na.amazon.com/v20160207/events 
i send body first:
 --CUSTOM_BOUNDARY_TERM
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{"event": {"header": {"namespace": "SpeechRecognizer","name": "Recognize","messageId": "8BA1B7EA-CD11-48C9-B1F6-DBBA11AF83CF","dialogRequestId": "16E4D016-E90D-45D7-90BE-6884F19CE2E5"},"payload": {"profile": "NEAR_FIELD", "format": "AUDIO_L16_RATE_16000_CHANNELS_1"}},"context": [{"header": {"namespace": "AudioPlayer","name": "PlaybackState"},"payload": {"token": "","offsetInMilliseconds": 0,"playerActivity": "FINISHED"}}, {"header": {"namespace": "SpeechSynthesizer","name": "SpeechState"},"payload": {"token": "","offsetInMilliseconds": 0,"playerActivity": "FINISHED"}}, { "header" : { "namespace" : "Alerts", "name" : "AlertsState" }, "payload" : { "allAlerts" : [ ], "activeAlerts" : [ ] } }, {"header": {"namespace": "Speaker","name": "VolumeState"},"payload": {"volume": 25,"muted": false}}]}

and then send the audio data chunk as follow:

buffer.append("--\(boundary)\r\n".data(using: String.Encoding.utf8)!)
                buffer.append("Content-Disposition: form-data; name=\"audio\"\r\n".data(using: String.Encoding.utf8)!)
                buffer.append("Content-Type: application/octet-stream\r\n\r\n".data(using: String.Encoding.utf8)!)
                buffer.append(audioData!)
                buffer.append("\r\n".data(using: String.Encoding.utf8)!)
                buffer.append("--\(boundary)--\r\n".data(using: String.Encoding.utf8)!)

but got Exception:
{"header":{"namespace":"System","name":"Exception","messageId":"5c94af71-d700-41d6-a7cf-d5d687d5ac99"},"payload":{"code":"INVALID_REQUEST_EXCEPTION","description":"Bad Request"}}

please help me find the reason that i got the Exception.Thank you! :)

**Comment by kclchan** [comment]
HI @yuyubaba, are you seeing this issue with the alexa-avs-sample-app?

I notice that the Recognize event you are sending are missing some fields.  Please take a look at this:
https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize

Thanks,
Kenneth

**Comment by yuyubaba** [comment]
I'm very confused. When the user clicks on the start button, I start to create a request, first send part of the JSON header/body and request Header, and then upload the data stream of the audio to the chunk packet one by one. If you can help me confirm which fields are missing, I have a good understanding of the current situation.@kclchan

**Comment by kclchan** [comment]
Hi @yuyubaba, sorry, it's still unclear to me what you are trying to do.  Are you using the alexa-avs-sample-app?  Or are you trying to build you own application and send an event to AVS?  If it's the later, please take a look at code below and you can trace what needs to be done:

https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L302

Initially I thought you are missing the "initiator" in the Recognize event, but it seems more likely it's the audio data stream you send in the event that's causing some problems.

And please note that the Java SampleApp is on deprecation path. I highly recommend switching over to the C++ SDK.

**Comment by kclchan** [comment]
Hi @yuyubaba, I'm closing this issue and will continue the discussion in #1201.  Thanks!
