### ISSUE TITLE
i only go status code: 204. what's the problem ?

### ISSUE THREAD

**Issue by yuyubaba** [alexa/alexa-avs-sample-app#1200]
i only got status code: 204. what's the problem ?
Authorization = "Bearer Atza|IwEBIJLlOZp8QKFePGvAuVo3KNyOlSsgCAUBwwujMjP6_XgBFET43xFz788oxdTbYVYIDakrn8EMaGUxO1u4Tv2cwdwf9lJGd_d_sZtT7ViIU4YV7-U48bIT5fGhpM5r2YWU9LOG1NF6ty7ZCZDB5laXsoMu4yVpl_oaX_MUlZGEs72JMdQFS4tF4T7CsZc-I7i9zhaIBXdcxyWa01i7J67Oc0sJccqK_DVyeAxOrd9I4UoK6ItEJjgE9w8qxSEeC2Opi9Ip_CLBLMoT98KJtswQnMKAdIA3xi5Gu_sh6Jrm-Ir3yjIb85BoVlZivc7sn-X5WHFznCJv3T_AKZXHgTTL6xF35TCzY48xJbdD-AOgTdzaEWRD7PIUuRD7y4Q_n5Rmjgx-jpHGxhLACPiOnAx__JDDGncmNlEhfLcPhjsai4UiWeYU_misQNiMCVw86WdpKD_aoibIgNwXer84rrX1R1d6";
    "Content-Type" = "multipart/form-data; boundary=233455666444";
--233455666444
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{"event": {"header": {"namespace": "SpeechRecognizer","name": "Recognize","messageId": "B18602C4-5611-4A99-8C2B-14C1A6DC7CF7","dialogRequestId": "0365F5B7-AFEB-4D41-BA19-4B0B7E093CF6"},"payload": {"profile": "NEAR_FIELD", "format": "AUDIO_L16_RATE_16000_CHANNELS_1"}},"context": [{"header": {"namespace": "AudioPlayer","name": "PlaybackState"},"payload": {"token": "","offsetInMilliseconds": 0,"playerActivity": "FINISHED"}}, {"header": {"namespace": "SpeechSynthesizer","name": "SpeechState"},"payload": {"token": "","offsetInMilliseconds": 0,"playerActivity": "FINISHED"}}, { "header" : { "namespace" : "Alerts", "name" : "AlertsState" }, "payload" : { "allAlerts" : [ ], "activeAlerts" : [ ] } }, {"header": {"namespace": "Speaker","name": "VolumeState"},"payload": {"volume": 25,"muted": false}}]}

**Comment by kclchan** [comment]
HI @yuyubaba, are you seeing this issue with the alexa-avs-sample-app?

I notice that the Recognize event you are sending are missing some fields.  Please take a look at this:
https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize

Thanks,
Kenneth

**Comment by yuyubaba** [comment]
I'm very confused. When the user clicks on the start button, I start to create a request, first send part of the JSON header/body and request Header, and then upload the data stream of the audio to the chunk packet one by one. If you can help me confirm which fields are missing, I have a good understanding of the current situation.

**Comment by kclchan** [comment]
Hi @yuyubaba, I'm closing this issue and will continue the discussion in #1201.  Thanks!
