### ISSUE TITLE
No beep on start of request

### ISSUE THREAD

**Issue by Dimmerworld** [alexa/alexa-avs-sample-app#1204]
Recently installed this on my raspberry PI, everything else works fine besides the activation beep which is non-existent. When I try and turn it on in the app, it just switches off.

Any ideas?

**Comment by BennyAvramson** [comment]
Hi @Dimmerworld,

Please note that the alexa-avs-sample-app is on deprecation path. I highly recommend switching over to the avs-device-sdk instead.

You can follow [this guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script) on how to get started on the raspberry Pi3.

Please let me know if the avs-device-sdk option can work for you.

Thanks,
Benny

**Comment by Dimmerworld** [comment]
Whoops wrong repo
