### ISSUE TITLE
segmentation fault on 'BUILDING SDK' step 

### ISSUE THREAD

**Issue by corentoulf** [alexa/alexa-avs-sample-app#1209]
Hi,

I'm trying to build AVS on a Raspberry Pi 2 model B (running Raspbian GNU/Linux 9 (stretch)).

I'm following this [tutorial](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script)

When it comes to the building SDK step, I got the following error (right after) :

```
==============> BUILDING SDK ==============

setup.sh : ligne 215 : 12521 Erreur de segmentation  cmake "$SOURCE_PATH/avs-device-sdk" "${CMAKE_PLATFORM_SPECIFIC[@]}" -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" -DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include" -DCMAKE_BUILD_TYPE=DEBUG
```
Can you help me on interpreting this error ? What does it mean...?

Thank you.

**Comment by corentoulf** [comment]
closing cause I posted it in the wrong place.
you can find it [here](https://github.com/alexa/avs-device-sdk/issues/878)

**Comment by celinval** [comment]
Hi @corentoulf,

Are you trying to build the avs-device-sdk? If you are, can you please create an issue in the [avs-device-sdk forum](https://github.com/alexa/avs-device-sdk/issues) instead?

Thanks,
Celina

**Comment by corentoulf** [comment]
Hello,
Indeed, that’s what I did :)
