### ISSUE TITLE
Alexa not responding after some time

### ISSUE THREAD

**Issue by theskyliner** [alexa/alexa-avs-sample-app#1215]
hey guys,

love this project! on boot everything works like a charm, but when some time passes, alexa does not respond anymore.
when I restart all the services everything works again fine again, and after some time alexa wont react to the wake word.

Any ideas? Is the raspberry (version 3) falling asleep or something?

In the terminal I found a java error amongst others:
```
Exception: java.lang.outOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-XAWT"
```

thanks in advance

**Comment by visayamv** [comment]
Hi @theskyliner ,

The alexa-avs-sample-app in JAVA is in the path for deprecation. Could you switch over to C++ SDK avs-device-sdk which has additional features coming in monthly and which is maintained by the team.

Please see https://github.com/alexa/avs-device-sdk for details on how to get started with the C++ SDK.
