### ISSUE TITLE
Not going to Amazon Shopping app

### ISSUE THREAD

**Issue by lvguowei** [alexa/alexa-avs-sample-app#1216]
I have amazon shopping app installed and signed in, but after calling authorize I'm only directed into browser for signin, anyone knows why I'm not directed to the Amazon Shopping app instead?

**Comment by visayamv** [comment]
Hi @lvguowei , I'm afraid the Amazon Shopping App is not something we can help you with. This forum is only for Alexa Java Sample App related issues.

I suggest you contact Amazon Support at https://www.amazon.com/gp/help/customer/display.html
