### ISSUE TITLE
Integrating with IFTTT: Is it possible to change the word "trigger" on every IFTTT command?

### ISSUE THREAD

**Issue by bogartescobar** [alexa/alexa-avs-sample-app#1222]
It's quite not convenient to say something like, "Alexa trigger on the lights"

**Comment by faengelm** [comment]
If your Home Automation system integrates with Alexa, like SmartThings...

You can say, "Alexa... Turn on the Lights"

**Comment by dhpp** [comment]
Hi @bogartescobar, the Java Sample App is no longer supported, as described in the README.md [here](https://github.com/alexa/alexa-avs-sample-app/blob/master/README.md).  We suggest you migrate to the updated C++ Client SDK which you may find [here](https://github.com/alexa/avs-device-sdk).
Your question also seems more directed towards SmartHome and Skills, so I would consider taking your question to the appropriate support forums for those domains.
