### ISSUE TITLE
Adding animating LEDs on Alexa's voice response

### ISSUE THREAD

**Issue by bogartescobar** [alexa/alexa-avs-sample-app#1223]
Is there any way to add an animating LED (like a NeoPixel stick...) to the system? I'm doing this as a school project and I think it would be cool to have an LED lighting up on Alexa's responses,

**Comment by dhpp** [comment]
Hi @bogartescobar, the Java Sample App is no longer supported, as described in the README.md [here](https://github.com/alexa/alexa-avs-sample-app/blob/master/README.md).  We suggest you migrate to the updated C++ Client SDK which you may find [here](https://github.com/alexa/avs-device-sdk).

Also, with that in mind, have you seen our guide page on this subject [here](https://developer.amazon.com/docs/alexa-voice-service/indicate-device-state-with-leds.html)?  It sounds like what you're looking for.

I'll close this ticket - if you do migrate to the C++ SDK (which really is recommended), feel free to post further questions and thoughts on our support forums for that product [here](https://github.com/alexa/avs-device-sdk/issues).
