### ISSUE TITLE
Set up response LED indicators

### ISSUE THREAD

**Issue by bogartescobar** [alexa/alexa-avs-sample-app#1224]
I found this [https://developer.amazon.com/docs/alexa-voice-service/indicate-device-state-with-leds.html](https://developer.amazon.com/docs/alexa-voice-service/indicate-device-state-with-leds.html) but I think it only applies to AlexaSDK and not this alexa-avs-sample-app

how to i put 2 LEDs to indicate Alexa's response?

**Comment by dhpp** [comment]
Hi @bogartescobar, yes you're correct, that article provides guidance on integrating LEDs with the C++ Client SDK for Alexa.  The alexa-avs-sample-app is no longer supported, as stated on the README.md as found [here](https://github.com/alexa/alexa-avs-sample-app/blob/master/README.md).

Could you please clarify your question further?  It's not quite clear to me what you are asking.
