### ISSUE TITLE
Voice responds with delay

### ISSUE THREAD

**Issue by jnpalonen** [alexa/alexa-avs-sample-app#1226]
Hi,

I have Raspberry Pi B3+. Installed your app and it's great!! Well done you guys!!
How ever I'm having issue with voice delay. Not sure if it's a app issue or my setup issue but I'm still going to ask from you. :)

It doesn't matter if I use wake word "Alexa" or manual button in Java app it's always the same. 
For example:
I say: "Alexa, what time is it?"
Alexa says: "..s twelvefifteen pm"
I say again: "Alexa, what time is it?"
Alexa says: "...vefifteen pm"

So answer from Alexa never comes fully and it's always missing few second (2s to 3s) from beginning. I tried to figure out what's going on. I found out that Alexa answers normally (it says sentence from the very first word to last) but there's some sort of delay in audio that causes this problem. Like Eminem says: but the words won't come out..

I opened test mp3 file with vlc and pressed play. I paused mp3 file and left vlc still open to background. Then I asked from Alexa:
I say: "Alexa, what time is it?"
Alexa says: "Time is  twelvetwenty pm"
I say again: "Alexa, what time is it?"
Alexa says: "Time is  twelvetwenty pm"

It seems like audio output is in use and audio comes immediately out when mp3 file is paused background. Without vlc and mp3 file pause it takes couple of seconds to wake audio up.

Anyone knows what's the deal with this? I'm sorry if this has nothing to do with your great app but it might be something that someone else is also experiencing. 

Thanks, Jani

**Comment by dhpp** [comment]
Hi @jnpalonen, thanks for the question.  Unfortunately, we no longer support our Java Sample app, as we describe in the README.md [here](https://github.com/alexa/alexa-avs-sample-app/blob/master/README.md).  We recommend that users migrate instead to our C++ Client SDK, for which our target reference platform is the same as yours, the Raspberry Pi.  This SDK is fully featured with respect to AVS, and is offered by us as a reference implementation of an AVS Client.  You may find it [here](https://github.com/alexa/avs-device-sdk).

Let us know if you need any further guidance, thanks.
