### ISSUE TITLE
Audio actions not supported on devicd

### ISSUE THREAD

**Issue by japetos** [alexa/alexa-avs-sample-app#1228]
Hello, connected vie android alexa app and tried to create audio routine. but i always here alexa saying that audio actions are not supported. what shall i do?

**Comment by celinval** [comment]
Hi @japetos,

Routines are not supported by the Alexa AVS Java Sample App. Besides that, this app has been deprecated. Please consider using the [AVS Device SDK](https://github.com/alexa/avs-device-sdk/) instead.

Thanks
