### ISSUE TITLE
Custom wakeword stopped working without obvious reason

### ISSUE THREAD

**Issue by henriz** [alexa/alexa-avs-sample-app#1229]
Hi,

I'm running the app on a Raspberry Pi Zero W. Installed as per instructions, and using kitt_ai and the wakeword 'Alexa', the app runs fine, although it sometimes crops the answers. This i can live with.

However, I wanted a different wakeword. So I played around with it, made a few keyword files on the website, and tested them. They worked. The word I ended up with, was 'Computer'. This worked fine.

Then I shutdown the pi, put it in it's case I printed for it, started it agan and.. the wakeword does not work anymore.

The startup of the wakeword engine is the same, the messages it gives on starting are the same, and so forth. 

If I now replace the custom wakeword alexa.umdl with the original alexa.umdl, it works again, with the wakeword 'Alexa'.

However, it will not recognize any of the custom wakewords I tested before and which worked before.

The code changes as suggested in the installation of a custom wakeword, are still in the code. To be sure I did a 'make clean', followed by a make again. Still, it does not work.

So why is the original alexa.umdl working, but the custom alexa.umdl not? It has worked flawlessly.

**Comment by visayamv** [comment]
Hi @henriz , when you say it worked before? do you mean that your device will respond when you ask it a question with the custom wakeword (i.e. when you say 'Computer, what time is it?) it will respond?

**Comment by henriz** [comment]
No, I ment the whole app, including the wakeword. So  I could say 'Alexa, what's the weather' and it would respond with weather report. Using the "Computer" wakeword, I could say "Computer, what's the weather', and it would respond.

So "Computer what time is it" resulted in it telling me the time.

If you log in here: https://snowboy.kitt.ai/dashboard, you can create your own wakeword file. You then replace the alexa.udml in /ext/resources by that file, and it then uses that wakeword.

It will still answer questions if I use a key to activate it, but it completely misses the wakeword.

At first I thought the casing might have somehow blocked the microphones, but removing it from the casing again, didn't make it work again.

I'm now in the process of reinstalling the whole thing from scratch again.

**Comment by visayamv** [comment]
Hi @henriz , the cloud will verify if the wakeword is "Alexa", as noted in the following document:

https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#speechrecognizer-context

I would think the cloud would reject any other wake words.

**Comment by henriz** [comment]
That's true for Dot's. Not for raspberry pi's running this sample app. It doesn't communicate with the cloud at all for it's wakeword.

Again, this worked fine and also should work fine. I

**Comment by henriz** [comment]
Here you can see it working when I had it working fine:
https://youtu.be/SKWlULE46dE

**Comment by henriz** [comment]
The java client and companion app, and c++ wakeword agent.

It's not really usefull putting up logs, as there's nothing to see there when it simply doesn't detect the wakeword. Logfiles are the same, with the difference that when it works, it logs detecting a wakeword, and when it doesn't work, it obviously doesn't.

I'm not being stubborn, but I don't have the non-working setup anymore currently. As I said, I went for a fresh reinstall. That should be ready shortly. I expect it to be working again then.

No clou as to why it stopped working. The weird thing was that it was working with the original alexa udml ('Alexa, what's the weather') but stopped working with the created udmb for 'computer'. Which, as you saw on the video, worked fine before I put the whole thing in a casing.

**Comment by visayamv** [comment]
Hi @henriz , thanks for the clarification. Is it working when you try the snowboy demo code and target the "Computer" model?

Demo code should be found in snowboy's source directory under:

examples/C++

**Comment by henriz** [comment]
I'm sure I'm looking in the right place, but there's no examples folder in this git repository, nor a 'snowboy'?

I'd really like to get rid of the java crap if possible.

**Comment by visayamv** [comment]
Hi @henriz , I'm glad you're setup is working now. 

The Java sample app is actually being deprecated and has been replaced by the C++ sample app which is available here: https://github.com/alexa/avs-device-sdk/wiki

Let me know if you need more help.

**Comment by henriz** [comment]
Thanks for the info, I am in the process now of trying the C++ version, but right of the bat, I think the used voice recognition package is not supported on ARM6 (=Raspberry Pi Zero) as the binaries are compiled for ARM7. This 'old version' DOES run on a pi zero W.

**Comment by faengelm** [comment]
Hello Visayamv,

I understand that you are deprecating the Java sample and SDK.

 

As a developer using Android Studio to develop Android apps for deployment on Android devices, I don’t see how the C++ samples are going to assist me.

 

Please explain your support level for Android developers

 

Regards,

Frank

**Comment by visayamv** [comment]
@faengelm , the C++ SDK has Android support. Please see this page for more information: https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide
