### ISSUE TITLE
Alarms 1 hour late

### ISSUE THREAD

**Issue by cr0wm4n** [alexa/alexa-avs-sample-app#1237]
incorrect app

**Comment by aumatsui** [comment]
Hi cr0wm4n. Which kind of request are you making to Alexa? Are you saying "set an alarm for 1 hour" or are you specifying the actual time when the alarm was supposed to go off?

Can you check if this behavior is not related to the location setting of your device or the actual time on your device?

Also, please provide DEBUG9 logs and the version of the SDK that you are using.

**Comment by aumatsui** [comment]
Hi cr0wnm4n, can you confirm that this issue was actually indented to be posted on the AVS Device SDK for C++? I see you created this issue there:

https://github.com/alexa/avs-device-sdk/issues/1068

**Comment by cr0wm4n** [comment]
its ok i fixed it :)

**Comment by cr0wm4n** [comment]
fixed my mistake :)
