### ISSUE TITLE
Is there a final solution to mvn exec:exec failure?

### ISSUE THREAD

**Issue by faustveritas07** [alexa/alexa-avs-sample-app#1241]
Has anyone solved this error yet?
All posts are closed because of not giving a feedback or there are no real answers.

pi@raspberrypi:~/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.106 s
[INFO] Finished at: 2018-11-24T23:08:00+01:00
[INFO] Final Memory: 8M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 139 (Exit value: 139) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Anyone?

**Comment by AsimZulfiqar67** [comment]
I was facing the same error and then i come to know about this official tutorial, https://developer.amazon.com/docs/alexa-voice-service/ i am trying this and i am sure it will work .

**Comment by mavamazon** [comment]
Hi!
Sorry, but Java Sample App is in process of deprecation now. I strongly advise you to switch to [AVS C++ SDK](https://github.com/alexa/avs-device-sdk). This SDK is being actively developed and updated with most recent features.

**Comment by ond0pe** [comment]
It there a solution? I have the same problem and nothing works.

**Comment by faustveritas07** [comment]
I deleted vlc media player,  all connected libraries and it worked :D

śr., 12.12.2018, 16:58: ond0pe <notifications@github.com> napisał(a):

**Comment by celinval** [comment]
Thanks for letting us know!
