### ISSUE TITLE
javaclient cant connect to companionService

### ISSUE THREAD

**Issue by chalda** [alexa/alexa-avs-sample-app#125]
Getting "There was a problem connection to the Companion Service. Trying again in 2 seconds.."

the service is running on default localhost:3000. I can hit it in the browser. ive tried to toggle the value in config.json of the javaclient to no avail.

**Comment by chalda** [comment]
![rasppi](https://cloud.githubusercontent.com/assets/1203046/14478511/79eed216-00e4-11e6-92e3-5fb918b52d3b.PNG)

**Comment by ajotwani** [comment]
@chalda have you seen this? https://github.com/amzn/alexa-avs-raspberry-pi/issues/35#issuecomment-202419281. It's probably your ssl.cnf file. Here's what the ssl.cnf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b

**Comment by chalda** [comment]
Hi,
so that was originally my problem when the generate script didnt work but this is my current ssl.cnf:

**Comment by ajotwani** [comment]
Added an FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors

**Comment by chalda** [comment]
actually so i had to delete the line:
$ENV::COMMON_NAME
from my ssl.cnf cause it was throwing errors. replaced it with a simple string instead. may be that is the problem?

**Comment by keleric** [comment]
Yes. That line should be in the ssl.cnf. I'd recommend starting with a blank slate ssl.cnf file and only modifying commonName, countryName, and down.

**Comment by ajotwani** [comment]
+1 to what @keleric said. Here's what the ssl.cnf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b.

**Comment by pakyinsun** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pysun@emailpys.gq
    Domain pakyinsun.gq has exceeded the max emails per hour (22/21 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:18488)
	by ns2.kloud51.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-c374-pysun=pakyinsun.gq@sgmail.github.com>)
	id 1ar5tr-002EmZ-3M
	for pysun@pakyinsun.gq; Fri, 15 Apr 2016 17:43:15 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=VT2xZk2Hs7Yk5hbkEijVFESl+a0=; b=i1wp6RezEQewEfWu
	V4Nenqb/en3WywIFKjmXmWYUMpFLlhCKQcGwDDAkcqCNuOuo0+uqe79tJCnvyLTl
	jVfs5NSnDBQwfRR+3Wkl4/I89M+GxWf9h2rCGH72Kq4tPdTGNH/Lf6ZhD3BkthCu
	bRY97pu6gyp/ICxjIY06EMuSqOY=
Received: by filter0835p1mdw1.sendgrid.net with SMTP id filter0835p1mdw1.1931.57110B7B56
        2016-04-15 15:40:43.957712689 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id o7PKkP4uQUmGWuQXKgorRA
	for <pysun@pakyinsun.gq>; Fri, 15 Apr 2016 15:40:43.825 +0000 (UTC)
Date: Fri, 15 Apr 2016 08:40:43 -0700

**Comment by ashi2014** [comment]
I am experiencing the same issue where the java client cannot connect to the Companion Service.
I have checked the FAQ section on Companion Service as well as issues #35 and #44, and double-checked all the points suggested.

My ssl.cnf file is as follows. Could you please let me know if you see anything awry here?
`[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                		    # C=
stateOrProvinceName     = CA                                # ST=
localityName            = SF                                # L=
organizationName        = YOUR_ORGANIZATION                 # O=
organizationalUnitName  = YOUR_ORGANIZATIONAL_UNIT          # OU=`

**Comment by bmcder01** [comment]
It seems a few of us are getting to what would appear to be the penultimate step with this project, but are unable to get it working. Tantalising and frustrating. @ashi2014  @chalda or anyone else have you found a solution yet? Thanks.

**Comment by ksanghai** [comment]
ssl certs are date sensitive. I had to update my date to the current date/time on my board and I was able to get past this error.

**Comment by ajotwani** [comment]
@bmcder01 @ashi2014 @chalda let us know if you're still have trouble getting this to work?

**Comment by ashi2014** [comment]
I was able to get this to work by starting over and following the updated instructions (including formatting my SD card and installing Raspbian jessie). Thanks!

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by ANANDSKRISHNAN** [comment]
C:\abysis\alexa\samples\companionService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\abysis\alexa\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000

**Comment by ANANDSKRISHNAN** [comment]
Getting "There was a problem connection to the Companion Service. Trying again in 2 seconds.."
kindly help

**Comment by ANANDSKRISHNAN** [comment]
[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                 # C=
stateOrProvinceName     = WA            # ST=
localityName            = SEATTLE                         # L=
organizationName        = AVS_USER                 # O=
organizationalUnitName  = AVS_USER          # OU=

**Comment by bilalmuhammad-ips** [comment]
I copied this verbatim and it still doesn't work for me. Still complaining about line 14

Product ID: sample_device
Serial Number: 123456
Password for Keystores (won't echo): Generating RSA private key, 4096 bit long modulus
.....................++
...............................................................................++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736148362120:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
Generating RSA private key, 2048 bit long modulus
.......................................+++
.....................................................................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736148362120:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
Signature ok
subject=/C=US/ST=NY/L=NY/O=IP/OU=EE
Getting CA Private Key
CA certificate and CA private key do not match
140736148362120:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/x509/x509_cmp.c:355:
unable to load certificates
Generating RSA private key, 2048 bit long modulus
...................................................................+++
...........................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736148362120:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
Signature ok
subject=/C=US/ST=NY/L=NY/O=IP/OU=EE
Getting CA Private Key
CA certificate and CA private key do not match
140736148362120:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/x509/x509_cmp.c:355:
Generating RSA private key, 2048 bit long modulus
...................................................+++
................................................+++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
140736148362120:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 14
error on line 14 of config file 'ssl.cnf'
No certificate matches private key
Wed Nov 08 ~/Downloads/alexa-avs-sample-app-master/samples/javaclient>
