### ISSUE TITLE
NPM Start Error

### ISSUE THREAD

**Issue by kdorsey0718** [alexa/alexa-avs-sample-app#128]
Okay - I'm stumped. Below is the error code. Let me know if you have any suggestions.

pi@picho:~/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService $
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/home/pi/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService/config.js:24
    sslCert: '/home/pi/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.29
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Documents/Alexa/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log

**Comment by ajotwani** [comment]
Can you check you don't have any typos, missing quotes in the config files - config.js, config.json, and also ssl.cnf?

**Comment by kdorsey0718** [comment]
Well, I've taken a look but a second set of eyes probably wouldn't hurt. (SSL password has intentionally been asterisk-ed out). Let me know if you see anything! I appreciate the help.

http://imgur.com/a/U86Jm

**Comment by ajotwani** [comment]
@kdorsey0718 Just took a quick look, and noticed that your Product ID is not the same in config.json and config.js files. They need to match. See the "Cannot connect to the Companion Service” errors FAQ on the ReadMe for more info.

**Comment by kdorsey0718** [comment]
@ajotwani I made those changes and still couldn't get through. I backtracked everything, removed all of the certificate files and such. Created new profiles, new certs, made the necessary changes, and now I am receiving the same problem. Any thoughts?

**Comment by ajotwani** [comment]
@kdorsey0718 Mind sharing your config.js and config.json files after redacting the client ID and secret?

**Comment by sshtel** [comment]
On Raspberry pi, I edited package.json like this.
start: "nodejs ./bin/www"

I don't know why node command does not work, but nodejs command works well.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by BhushanRockzz** [comment]
I got the same issues while installing the alexa voice services. Can you just tell me how to resolve the error!
