### ISSUE TITLE
No prompt to register device on step No. 10

### ISSUE THREAD

**Issue by smalleni** [alexa/alexa-avs-sample-app#183]
After running mvn exec:exec, there is no dialogue box presented as mentioned in step no.10 that lets the user register the device and allow access to the security group. Instead an Alexa voice service window as depicted in 10.6 shows up but has no value in the bearer token. On speaking it is stuck in processing forever.

**Comment by olsonk** [comment]
I ran into this problem and had to update Java in order to get it working properly. Make sure you have the latest JDK from the readme.

**Comment by ajotwani** [comment]
@smalleni like @olsonk said, please run the JDK installation script - 

$ ./install-java8.sh

Let us know if that fixes it. Thanks!

**Comment by KavishBhatia** [comment]
I am also stuck into this problem
when i run mvn exec:exec       i get
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

**Comment by ajotwani** [comment]
@KavishBhatia have you tried this?

$ ./install-java8.sh

**Comment by KavishBhatia** [comment]
@ajotwani i tried this and it says not raspbian OS

**Comment by kylepotts** [comment]
@KavishBhatia edit the install.sh file where is says | grep Raspbian to |grep Debian and it should work. Worked for me.

**Comment by KavishBhatia** [comment]
@kylepotts i did all the steps again and now i'm stuck into a different problem 
[https://github.com/amzn/alexa-avs-raspberry-pi/issues/205](url)

**Comment by Eddie-Hartman** [comment]
I'm having this issue too after having set up a new pi that I want to use. I installed the JDK and updated everything. I pretty much followed the steps and have already set up two other Pis like this before (they are no longer running) and don't know what's wrong.

**Comment by kevinwidjaja21** [comment]
@KavishBhatia I also experiencing that problem. I have repeat the steps multiple times and still have the same issue. I also experiencing same issue when i uses the modified version of Sam Machin code. Have you solve this problem? Sorry, this is my first time with raspberry pi.

**Comment by KavishBhatia** [comment]
@kevinwidjaja21 i was following the steps they gave before changing to these. I was stuck so i left it for 2-3 weeks now when i sae this again the procedure was changed and i am not able to do any good by this new change

**Comment by kevinwidjaja21** [comment]
@KavishBhatia Great news, i am finally able to connect to amazon via the link and get authorization. However, the solution is a bit weird because i don't understand what's wrong in the first place. Basically, i used my secondary modem from different ISP. Can anyone explain this?

**Comment by SatyajitKumar** [comment]
Hi Guys,

I am using window system i.e. window 7 and java version. Whenever  i am trying to run the companionService i.e on node js program its saying this error below :+1: C:\Users\satyajit.kumar.sethy>cd C:\Users\satyajit.kumar.sethy\Downloads\REFEREN
CE_IMPLEMENTATION\samples\companionService

C:\Users\satyajit.kumar.sethy\Downloads\REFERENCE_IMPLEMENTATION\samples\compani
onService>
C:\Users\satyajit.kumar.sethy\Downloads\REFERENCE_IMPLEMENTATION\samples\compani
onService>
C:\Users\satyajit.kumar.sethy\Downloads\REFERENCE_IMPLEMENTATION\samples\compani
onService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\Users\satyajit.kum
ar.sethy\Downloads\REFERENCE_IMPLEMENTATION\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend
 them for the AVS app.

_tls_common.js:65
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:65:17)
    at Server (_tls_wrap.js:733:25)
    at new Server (https.js:17:14)
    at Object.exports.createServer (https.js:37:10)
    at Object.<anonymous> (C:\Users\satyajit.kumar.sethy\Downloads\REFERENCE_IMP
LEMENTATION\samples\companionService\bin\www:31:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\satyajit.kumar.s
ethy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/w
ww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start
script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-s
ample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service


Is anything i need to do more, or anything i am missing ? for me its show stopper....Please Please suggest anyone how to resolve ?

**Comment by illperipherals** [comment]
Can you verify your certificates (encoding, line endings, permissions)? Are you self-signing?

**Comment by SatyajitKumar** [comment]
Hi IllPeripherals, thaks for your response..
Yes i am doing self-signing.

Regards,
satyajit.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
