### ISSUE TITLE
Error on Amazon page

### ISSUE THREAD

**Issue by tampano** [alexa/alexa-avs-sample-app#185]
Hi, amazing project and very well explained. The only issue I'm having is I get an error after authenticating on the Amazon page and clicking ok after navigating to the provisioning address. Sorry if it's not a code-related issue but I didn't know where to post it.

**Comment by ajotwani** [comment]
@tampano what error are you getting?

**Comment by jamesmcn** [comment]
I believe I'm encountering the same problem
<img width="625" alt="screen shot 2016-05-27 at 6 56 37 pm" src="https://cloud.githubusercontent.com/assets/774608/15624439/d29628d0-243c-11e6-913b-239e313f3402.png">

**Comment by jamesmcn** [comment]
My problem is resolved. I was using a different value for the Device Type ID on developer.amazon.com and in the config files. After changing "device_id" in the config files to match the value I gave on the developer console, I am able to complete the login flow.

**Comment by tampano** [comment]
Yep, I passed that stage for the reason you said (thank you) but now the very moment I click "start listening" I get a small alert window with a red sign and just a "OK" button to click, and I get a beep sound. Once I click the "OK" button the listening window shows "processing" forever. Any idea?

**Comment by jamesmcn** [comment]
Since I don't use the `pi` user, I had to add the user running the Amazon code to the `audio` group:

`$ usermod -a -G alexa_robot audio`

**Comment by tampano** [comment]
it's most probably an issue with the microphone:
- no usb mic connected = error beep + red sign alert
- usb mic connected = beep after "start listening" but also other beep after few seconds and apparently nothing happens in voice recognizing

any suggestions on how to check if the mic is recording correctly? I guess it's recognized, since the error alert doesn't show up, but i don't know how to check if it's properly receiving audio

**Comment by jamesmcn** [comment]
[This StackExchange post](http://raspberrypi.stackexchange.com/a/40832/42725) explains how to test and re-arrange your audio devices. However I never experienced the error beep or red sign that you are seeing.

I had to create an `/etc/modprobe.d/alsa-base.conf` file with the following contents, then reboot before my Samson USB mic worked:

```
# sets indices but doesn't reoder
option snd_usb_audio index=0
option snd_bcm2835 index=1

# reorders
options snd slots=snd-usb-audio,snd-bcm2835  
```

**Comment by shenery** [comment]
I'm having the same error on amazon page. I checked the config file and it reads device_id and DNS123456. Really not sure what to do to get it working.

**Comment by ajotwani** [comment]
@shenery you still having issue with this?

**Comment by Halfbreed1279** [comment]
I am working on a pi echo project and I am receiving an error message when trying to register my device. I have made it up to step 10 I have made it past the "mvn exec:exec" and received the pop up window with the https://localhost address. Once I copy and paste into Url, I am getting an error page that the localhost can not connect or has been refused. Could anyone please assist me with this issue?

Thank you

**Comment by MMM430** [comment]
"My problem is resolved. I was using a different value for the Device Type ID on developer.amazon.com and in the config files. After changing "device_id" in the config files to match the value I gave on the developer console, I am able to complete the login flow."

How can you change the Device Type ID in the config files, how can you access the config files and where do you find them?

**Comment by elstryan** [comment]
The config file is located here: https://github.com/alexa/alexa-avs-raspberry-pi/blob/master/samples/javaclient/config.json

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
