### ISSUE TITLE
Why PI 2

### ISSUE THREAD

**Issue by rickardliljeberg** [alexa/alexa-avs-sample-app#2]
Why is the PI 2 needed over old PI 1 ?

**Comment by jamesarm97** [comment]
I don't know personally but I would guess it would be for speed and memory since that is the main differences.

**Comment by ajotwani** [comment]
+1 to speed and memory, but more importantly because Pi 1 does not have an Ethernet port. Also, Pi 2 has four USB ports (compared to only one in Pi 1), which come in handy for plugging in the microphone, wifi, keyboard and mouse. 

Having said that, it should run just fine on Pi 3 as well.

**Comment by redfive2012** [comment]
The Pi 1 B+ has an ethernet port and 4 USB ports. It has the same
form-factor as the v2 and v3 Pi's as well.


*Nelson Butterworth*

**Comment by rickardliljeberg** [comment]
I imagined it might be the ports but I have a PI 1 with usb mic and usb wifi. I can ssh/vnc instead of using keyboard mouse.

So if thats why it would be nice to know.
If it's the speed however then it's no point trying.

**Comment by tjrobinson** [comment]
Has anyone tried it on a Raspberry Pi 3 yet?

**Comment by hkdobrev** [comment]
> Has anyone tried it on a Raspberry Pi 3 yet?

:+1: I came here to ask about PI 3. I've ordered one and I was wondering whether there's a reason it won't work on it.

**Comment by jamesarm97** [comment]
Wow, that says how long it has been since I have used an original pi. No Ethernet port, didn't remember that one.

**Comment by redfive2012** [comment]
I know of no reason why it shouldn't work. The Pi 3 is essentially the same
as the Pi 2, just faster and with built-in WiFi and BT. It's 64-bit capable
while the 2 is 32-bit only, but with only 1GB RAM, there's really no reason
to use a 64-bit OS.


*Nelson Butterworth*

**Comment by Gadgetoid** [comment]
The original Pi model B had an Ethernet port. The cut down A did not- but this didn't come until later. I suspect it's much more to do with CPU speed and available memory. I'd be very surprised if it didn't just work on a Pi 3- will certainly be giving it a try tomorrow!

It's a shame the Pi Zero isn't up to snuff- although once you've hooked up a speaker and some sort of networking the compact form factor is a little defeated! This may be an interesting role for Compute Module 3.

**Comment by anjishnu** [comment]
Why do you think Pi Zero is not up to snuff?

**Comment by redfive2012** [comment]
It's only slightly faster than the original Pi 1 Model A, has no ethernet
jack, no audio port, and barely a single USB port.


*Nelson Butterworth*

**Comment by anjishnu** [comment]
While the ports will be a problem, I would not be surprised if the compute is not.

**Comment by sleepingscorpion** [comment]
It could be the arm v6 vs arm v7 architecture and the underlying libraries, worth testing if anyone has a pi v1b?

**Comment by moodybass** [comment]
Can confirm works on RPi 3 just fine.

**Comment by louis-adiputra** [comment]
Since the programs are written in Java and Node.js, I tried it on Windows. With a bit of tweaking (added path to VLC in %PATH%, make sure paths in config files begin with "c:/") it runs fine.

**Comment by anjishnu** [comment]
@louis-adiputra if you could submit the exact tweaks as a pull request to the README it might be helpful for a lot of people who want to try this out first without buying a RPi.

**Comment by erikhopf-amzn** [comment]
@louis-adiputra @anjishnu - instructions for installing on Linux, Mac and Windows (w/o Pi) are available here: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/java-client-sample

**Comment by vlasov01** [comment]
I was able to make it working with a minor tweaks on another ARM-based device (armv7l) from Samsung ARTIK 10 / Fedora 22.

**Comment by ranalabs** [comment]
I was able to get it working on the Pi 1. The only tricky part was getting nodejs working - step 2.5 won't work with ARMv6 so you have to use node from adafruit / debian backports.

**Comment by aManFromOuterSpace** [comment]
Instructions work just fine for the Pi 1 Model B. Great work and thanks for sharing.

**Comment by duncangeere** [comment]
Could you elaborate a little on getting node from adafruit / debian backports? I'm trying to get it working on a Pi 1, but getting a bunch of 'Illegal Instruction' errors.

**Comment by ranalabs** [comment]
I added Adafruit's repository: https://learn.adafruit.com/node-embedded-development/installing-node-dot-js

Also, add Debian backports. https://packages.debian.org/wheezy-backports/nodejs

Finally, make sure to apt-get remove --purge the nodejs package installed previously. It took a few times before I got the right version of node working, otherwise npm install would just return a segmentation fault.

**Comment by duncangeere** [comment]
I added the Adafruit repository fine using the instructions on that page. The Debian backports - how do I go about adding those? I tried using the curl command with that url, but I got a syntax error. 

Also, will I need to un-curl (if that's a thing) the "https://deb.nodesource.com/setup" repo source from step 2.5? If so, how do I do that?

Forgive me if these questions are a little basic, only got my Pi recently and I don't have heaps of experience in the Linux terminal.

**Comment by ranalabs** [comment]
Edit the /etc/apt/sources.list file (nano or text editor, but as root) and comment out any entries you don't want. What I did was I commented out all except the two (adafruit and debian backports) and ran sudo apt-get update. Then sudo apt-get install nodejs. It should force the older version to install. This was very late in the evening so I'm not exactly sure which repo got it right, but one eventually did. Don't forget to go back into your sources.list to set your other sources back to normal so you can install other packages as needed.

**Comment by gregwa1953** [comment]
I can verify that it works on a Pi V1b.  
The biggest problem was that 'nvm' wasn't installed on my version of jessie.  Once I had that installed, I didn't have to do anything different from the current documentation (3/27/16 18:30MDT).

Hope this helps to clarify things.

**Comment by gabe817** [comment]
Gregwa1953 - when you say it works on the P1 V1b with the current documentation, except for installing nvm, are you saying you didn't have to install the Adafruit repository and the Debian backports as mentioned above?

**Comment by gregwa1953** [comment]
That's correct. Only had to install npm and nvm outside of the
documentation.

**Comment by JTG20** [comment]
I have also managed to install it on the raspberry pi 1 with installing the nvm outside the documentation

**Comment by hakanoodle** [comment]
Would this work with a BeagleBone Black?

**Comment by sleepingscorpion** [comment]
Its java/nodejs based, so dont see why not...

**Comment by willdye** [comment]
I'm in the process of installing and running AVS on my Raspberry Pi Zero, and the experience has been... glacial. The "mvn install" command, for example, took 5.5 hours. Starting up the GUI + AVS sever + AVS client app + a browser has bogged the system down so badly that even a single keystroke on the console takes several minutes to respond. I started it several hours ago, and the client hasn't even popped up a window yet. It eventually responds to keystrokes and mouse movements, so my guess is that it's thrashing badly, but I'm reluctant to fire up the tools needed to evaluate the situation in detail.

My configuration is pretty much off-the-shelf, with few changes to the OS and settings except to overclock it and remove unused packages such as Wolfram and the Minecraft games. While it's still possible that some config change on my part has made my Pi Zero particularly slow, I suspect that the machine is simply not a good platform for the current Alexa software. I love the zero, but I plan to use it for command-line jobs. A modern GUI is very sluggish on it, even before adding Java and AVS. You might as well spend a few bucks more and get a Pi 3.

**Comment by anjishnu** [comment]
A GUI free AVS demo application seems worth aspiring for. Python CLI perhaps?

**Comment by gregwa1953** [comment]
@anjishnu Check out issue #60.  A user by the name of @rprocha has some workarounds that you might find intriguing.  He is in process of creating some documentation on how to get the demo unit to respond to the "wake word" as well as auto start up.  
It might take him a few days, but i'm guessing the wait will be worth it.

**Comment by lennysh** [comment]
@anjishnu You mean, like [this one](https://github.com/lennysh/AlexaPi/tree/lennysh-music-patch-1)?

**Comment by akirakudobmt** [comment]
I have problem with RPI1b, can anyone show me how to install npm after install node js from adafruit ?

**Comment by harveysandiego** [comment]
Built (but not tested) on a Raspberry Pi Zero, as others have already mentioned guide is fine, I just needed to install npm.  In fact, I am running my system headless using X11 forwarding for the graphical element, the only changes I made was to replace localhost with my IP so I could access the CompanionService from a browser for authentication, need to get a USB sound card and them am going to test :smile:

**Comment by joetech** [comment]
Confirmed working on RPi1b

**Comment by Bedour** [comment]
Managed to get it work on Raspberry Pi 1 Model B.

Had the same issues that @ranalabs was talking about but managed to fix it doing the following:
http://weworkweplay.com/play/raspberry-pi-nodejs/

So node -v results in v4.2.1

And for **Step 5** I typed `npm instal` instead of `npm install`. One **L** and it worked!

As for **Step 9**  part _Run the client app_ I typed `mvn -e -X exec:exec`

Hope this helps @duncangeere or anyone else!

**Comment by peternann** [comment]
Everyone has a Pi 1 Model B it seems...
Confirmed running here too on Pi 1 Model B. Slow to come up, but fine once up and first interaction completed. (Audio is stuttered on first Listen).
My only deviation from instructions I recall was to install node as @Bedour mentioned above. To cut to the chase for everyone else, once Raspbian is installed, and Internet connected, in the shell type:
```
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
``` 
Oh, and to state the bleeding obvious - The minor version of JDK has changed since the instructions - Change the '77' to whatever you DL from Oracle.

P.S. There was already a java/javac installed by the time I hit that in the instructions, but it didn't work (Certificate related NoSuchMethodError) and I needed to install latest jdk as per instructions.

Thanks for this example Amazon. Nice indeed! I like the cut of your jib.

**Comment by mycargus** [comment]
Making my way through this project on Pi 1 Model B. The VNC instructions in this tutorial didn't work. VNC server installed fine but I couldn't get it running or connect with a client.

This did the trick: https://www.raspberrypi.org/documentation/remote-access/vnc/README.md

**Comment by Eddie-Hartman** [comment]
I am trying to switch out my Pi 3 for a Pi1b+ and I'm getting a "Could not find or load main class com.amazon.alexa.avs.AVSAPP" any help?

**Comment by RJDay** [comment]
Is this available for the Raspberry Pi Compute Module? Thank you!

**Comment by AC52** [comment]
Is it GPIO 18 that has to go to ground via a switch or just pin 18.
i can't get mine to work, i am using a B+ ver 1.2. everything works up until that point.

**Comment by patthiel** [comment]
A lot of people with Pi 1 Model B replying.. Has anyone that installed on pi zero had success using/developing on it? Seeing as it's basically the same clock speed as the pi 1 model b, hoping it'll be comparable.

**Comment by blaineoliver** [comment]
I would say a big issue is if you have a RPi B 256MB. I have that, a 512MB and a PI2. I may have to give up on the 256MB one and use either my 512 or the PI2 as the swap is being nuked

**Comment by fuzion666** [comment]
hi all 
ive tried this on the pi zero and cant get it to work has anyone been able to do it and if yes how? for audio im using usb audio output and separate usb mic im also using a piwi zero hub for extra usb and of course wifi.
ive got it running great on a pi3

**Comment by bchuckles** [comment]
parse_user_input 1 1 1
USER_RESPONSE=$?
if [ "$USER_RESPONSE" = "$NO_ANSWER" ]; then
  sudo amixer cset numid=3 2
  echo "Audio forced to HDMI."
else
  sudo amixer cset numid=3 1
  echo "Audio forced to 3.5mm jack."
fi

You would have to force the audio track to be the output of your USB speaker dongle

https://github.com/bchuckles/AlexaPi

I ran this on a pi zero back before Amazon had a tutorial on how to do it. The difference is that the hardware between a Pi zero and others is different, clock speed and everything else you are looking to much into it. Its just doing API calls, I honestly think anything but the Zero is overkill for this project.

**Comment by chsims1** [comment]
What is the state of play on the pi zero?  I think that I'd like to have a play, but don't want to reinvent the wheel.

**Comment by keleric** [comment]
Unfortunately, Pi Zero is not officially supported. You're welcome to try to make it work (I know other people who have filed Github issues about it - use the search feature to find them), but I can't give you much help. Sorry!
