### ISSUE TITLE
Typo in javaclient sample

### ISSUE THREAD

**Issue by galactoise** [alexa/alexa-avs-sample-app#207]
https://github.com/amzn/alexa-avs-raspberry-pi/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/message/request/RequestFactory.java#L42

I believe "Regonizer" should be "Recognizer"

**Comment by ajotwani** [comment]
Fixed with https://github.com/alexa/alexa-avs-sample-app/commit/9c6294f58b52fd9d16ea1f99d5ba45b5cccc4dd4
