### ISSUE TITLE
Waiting for localhost when logging in to amazon

### ISSUE THREAD

**Issue by KavishBhatia** [alexa/alexa-avs-sample-app#220]
![photo_0161762108xfazum](https://cloud.githubusercontent.com/assets/8553451/16350625/7f39fce6-3a7d-11e6-9198-76d68cb4825f.jpg)

Please help. I'm not able to know what is the problem. I am stuck on this window and after sometime it says that connection to server was reset.

**Comment by ajotwani** [comment]
@KavishBhatia just checking - you still have issues with this?

**Comment by KavishBhatia** [comment]
@ajotwani now i was not getting the link, so i tried the process again and now i'm not able to get the new procedure you have updated

**Comment by ajotwani** [comment]
@KavishBhatia we've made the process easier now with a lot of the stuff configurations hard coded. I'd recommend cloning the repo again, and starting from scratch. Should be pretty straight forward.

**Comment by KavishBhatia** [comment]
@ajotwani Ok. Then i'll try again from the beginning.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by plongthanh** [comment]
@ajotwani 
This issue occur on my environment, too.
I'm using alexa-avs-sample-app for Linux PC, and this PC is connected to a proxy.
My source code version is 2016-11-29

Could you give me some suggestions?

**Comment by keleric** [comment]
How is the PC connected to a proxy? How are you accessing it?

**Comment by plongthanh** [comment]
@keleric

> How is the PC connected to a proxy?

I just connect lan port to the proxy

> How are you accessing it?

Normally, I configure network proxy for my PC then I can connect to internet.
But for the javaclient app, I'm not sure how it connect via proxy.
