### ISSUE TITLE
Run python scripts from AVS?

### ISSUE THREAD

**Issue by UltimateOgee** [alexa/alexa-avs-sample-app#232]
Goal: Run code that is on the raspberry pi from an intent in AVS

Progress (and what I have learned so far):
Here is the java code to make a python scripts run from java on a raspberry pi machine from a separate PC on the SAME NETWORK

public static void main(String[] args) throws InterruptedException {
        String hostname = "<MY IP ADDRESS HERE>";  //found this by typing Hostname -I into the pi
        String username = "pi";
        String password = "PASSWORD!";
        try {
            Connection conn = new Connection(hostname);
            conn.connect();
            boolean isAuthenticated = conn.authenticateWithPassword(username, password);
            if (isAuthenticated == false) {
                throw new IOException("Authentication failed.");
            }
            Session sess = conn.openSession();
            sess.execCommand("sudo python /home/pi/Desktop/script1.py");
            sess.close();
            conn.close();
        } catch (IOException e) {
            e.printStackTrace(System.err);
            System.exit(2);
        }
    }

This code works when I run on a windows machine on the same network as the raspberry pi. It runs the python script after establishing a connection.

My question is "How do I establish a connection with the Pi from a AVS skill that is a lambda function?"

Help is greatly appreciated!

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
