### ISSUE TITLE
USB microphone not detected 

### ISSUE THREAD

**Issue by kenken64** [alexa/alexa-avs-sample-app#237]
[ 4928.539210] input: C-Media Electronics Inc.       USB PnP Sound Device as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:0D8C:013C.005E/input/input93
[ 4928.596896] hid-generic 0003:0D8C:013C.005E: input,hidraw0: USB HID v1.00 Device [C-Media Electronics Inc.       USB PnP Sound Device] on usb-3f980000.usb-1.2/input2
[ 5048.067998] usb 1-1.2: USB disconnect, device number 112
[ 5048.407412] usb 1-1.2: new full-speed USB device number 113 using dwc_otg
[ 5048.514189] usb 1-1.2: New USB device found, idVendor=0d8c, idProduct=013c
[ 5048.514209] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 5048.514223] usb 1-1.2: Product: USB PnP Sound Device
[ 5048.514236] usb 1-1.2: Manufacturer: C-Media Electronics Inc.      
[ 5048.515363] snd-usb-audio 1-1.2:1.0: cannot find the slot for index 0 (range 0-0), error: -16
[ 5048.515384] usb 1-1.2: cannot create card instance 0
[ 5048.515412] snd-usb-audio: probe of 1-1.2:1.0 failed with error -16
[ 5048.524305] input: C-Media Electronics Inc.       USB PnP Sound Device as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:0D8C:013C.005F/input/input94
[ 5048.577954] hid-generic 0003:0D8C:013C.005F: input,hidraw0: USB HID v1.00 Device [C-Media Electronics Inc.       USB PnP Sound Device] on usb-3f980000.usb-1.2/input2
[ 5161.078962] usb 1-1.2: USB disconnect, device number 113

**Comment by ajotwani** [comment]
@kenken64 just checking- you still having issues with the USB microphone?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
