### ISSUE TITLE
pom.xml alpn comment out of date

### ISSUE THREAD

**Issue by hyandell** [alexa/alexa-avs-sample-app#243]
The current pom.xml states:

    

However the README implies 1.8.0_91 should be okay, and the latest JDK is 1.8.0_101

pom.xml needs updating?

**Comment by hyandell** [comment]
Reading more, looks like pom.xml could be updated to say it supports through 1.8.0_91 (while later versions need to visit the Jetty page).

**Comment by CoderFX** [comment]
Then what? Instruction are unclear

**Comment by ajotwani** [comment]
Closing this. Should be resolved with the automated install script introduced in https://github.com/alexa/alexa-avs-sample-app/commit/9c6294f58b52fd9d16ea1f99d5ba45b5cccc4dd4
