### ISSUE TITLE
Error in step 8 when i try to "npm start", i keep getting errors. i have tried to look other submitted issues but none of their suggestions have fixed it for me.  Any and all suggestions will be greatly appreciated

### ISSUE THREAD

**Issue by CopperBeeches** [alexa/alexa-avs-sample-app#250]
http://i.imgur.com/eCSV4oQ.png

**Comment by Ztnepres** [comment]
I got mine working. Try going back to Step 4: Make sure your JDK ALPN versions match. The JDK is no longer 1.8.0_91 but 1.8.101

**Comment by CopperBeeches** [comment]
Ztnepres when i try to "./install-java8.sh" it says permission denied.  How do i fix that

**Comment by CopperBeeches** [comment]
@Ztnepres nevermind once i ran "sudo chmod +x install-java8.sh"  then "./install-java8.sh"it somehow worked

**Comment by anujdutt9** [comment]
Hey, did you get this working ?? I checked step 4 as well, everything is right.

**Comment by CopperBeeches** [comment]
@anujdutt9 No i can't

**Comment by CopperBeeches** [comment]
i can't seem to figure out how to update java without an error or permission denied

**Comment by madaono** [comment]
@Ztnepres thanks,u help me a lot,all solved

**Comment by Ztnepres** [comment]
@CopperBeeches what is your name of the directory with all the alexa service files? make sure the directory is labeled as "alexa-avs-raspberry-pi-master" without the quotes. Then try npm start again

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
