### ISSUE TITLE
Alexa on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by anujdutt9** [alexa/alexa-avs-sample-app#254]
Hi. I am trying to install this setup on Ubuntu 14.04 LTS. I got till step 8 without any errors and some knowledge of linux but as I do an   "npm start", it gives a number of errors. Can you please help me on this ???
Thanks : )

![screenshot from 2016-08-11 14_53_18](https://cloud.githubusercontent.com/assets/11924142/17600921/aefb34e2-5fd3-11e6-8143-5ce44e0cf061.png)

**Comment by ajotwani** [comment]
@anujdutt9 Looks like it's complaining about not finding the certificates. Did you follow the instructions to generate the certificates? https://github.com/alexa/alexa-avs-raspberry-pi#5---generate-self-signed-certificates

**Comment by anujdutt9** [comment]
Yes I followed each and every step. But still got this error :(

**Comment by ajotwani** [comment]
@anujdutt9 We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by anujdutt9** [comment]
@ajotwani  Thanks Amit. I'll definately try this out. Hands free is a much better way to go than a push button.
Thanks :)

**Comment by rickybrent** [comment]
This is amazing! I was able to build it on Ubuntu (amd64), but had to remove Sensory. KITT.AI's hands free works, though; it's really cool.

**Comment by blacksaturn1** [comment]
What version did you have great results with?  I not able to play back any music even though it is approved on Ubuntu 16.0.4.  Any ideas to troubleshoot?

**Comment by rickybrent** [comment]
e8d2bfb5767fa21d4b6b40ae01f081bc5836fc34, but I did not try to play back music; approval is still pending for me. (Ordering things, asking the weather and so on works.)

Probably-unhelpful wild guess, perhaps it could be VLC-related? I noticed I do not have the  LD_LIBRARY_PATH and VLC_PLUGIN_PATH enviromental variables set as described here despite having the packages:
https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/reference-implementation-guide

**Comment by rdpoor** [comment]
@rickybrent: do you have a branch that's tweaked to run on Ubuntu?  (I'm going down that same path and find there's a lot more than just commenting out the Sensory code, including GPIO, wiringPi, etc.)

**Comment by rickybrent** [comment]
@rdpoor Sure, I made a fork here: https://github.com/rickybrent/alexa-avs-sample-app

I downloaded and compiled wiringpi rather than uncomment it -- you can get a snapshot here: 
https://git.drogon.net/?p=wiringPi;a=summary
The exact one I used was https://git.drogon.net/?p=wiringPi;a=snapshot;h=b1dfc186efe327aa1d59de43ef631a2fa24e7c95;sf=tgz

(That didn't add gpio pins to my thinkpad, of course, but it did let me compile and run!)

**Comment by rdpoor** [comment]
@rickybrent Su-weet!  Thanks much -- I'll give it a whirl.

**Comment by rdpoor** [comment]
@rickybrent 95% there.  At the risk of hijacking this issue (well, it's clear I already have...) did you have to do anything special to make the sound output work?  I'm running Ubuntu under VirtualBox and haven't had trouble with the audio before.  I can see the KITT watch word detection happen, but there's no audio output.

**Comment by keleric** [comment]
The wake word agent is only supported on the Raspberry Pi. You might be able to get it working on Ubuntu, but it is not currently supported.

As far as your initial issue, the path is wrong. It's trying to find the certificate on the pi (No such directory, /home/pi ....), but you're clearly running this app out of /home/ad...

**Comment by rdpoor** [comment]
@keleric: Yes, but see @rickybrent 's comments above.  I managed to get the demo to work with wake words under Ubuntu using his recipe.

**Comment by keleric** [comment]
Great! Glad it's working now.

**Comment by goldsteinsveta** [comment]
@rickybrent hi, I've tried the code you've forked, but was not able to compile Wake Word Agent.
At [`make -j4`](https://github.com/rickybrent/alexa-avs-sample-app/blob/master/automated_install.sh#L521) I get this:

/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libwiringPi.so: undefined reference to `crypt'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:408: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

So I'm not able to execute `./wakeWordAgent -e kitt_ai`, nor `sudo ./wakeWordAgent -e gpio` in the end.
(tried with Ubuntu 16.04.3 LTS x86_64, 1. kernel 4.4.0-87-generic and 2. kernel 4.4.0-66-generic)

Can you maybe provide me with information how exactly did you compiled RPI things for Linux? Sorry I'm very much new to this: did you compile it on your Linux or on the Raspberry Pi?

Thanks!

**Comment by npusr** [comment]
@rickybrent Thank its works for me...

**Comment by Creedzy** [comment]
I'd like to mention that the compilation worked for me on Ubuntu 14.04 with VirtualBox 5.2.6. Also tried on 16.04 and 17.10 but it didnt seem to work on those. As far as I saw from different posts and the installation logs, its because the version of g++ was 3.4 while 14.04 had 2.8
