### ISSUE TITLE
Alexa won't play sound through Bluetooth speaker

### ISSUE THREAD

**Issue by YoitsuKamijo** [alexa/alexa-avs-sample-app#259]
Someone has asked this before, but I am reissuing again because it didn't seem to be solved. So I successfully connected my bluetooth speaker and I was able to play sound from the web through the speaker, however, when I ran alexa, the sound still came out of my HDMI, despite the output is set to the bluetooth. Any hint?

**Comment by Tiqni** [comment]
Hi YoitsuKamijo,

I couldn't find in the code how they are managing the audio output, so I guess they are using the default one in the Raspberry Pi (often is the JACK output) with ALSA support. Unfortunately, to be able to hear from your Bluetooth speaker, you have to make it as default audio using **PulseAudio** support (I wrote a post explaining this http://youness.net/raspberry-pi/bluetooth-headset-raspberry-pi), but I'm still not 100% sure that this will work with their Java client...

I hope that this at least will save your time and effort.

**Comment by sunnysharma03** [comment]
https://www.raspberrypi.org/magpi/bluetooth-audio-raspberry-pi-3/

This will solve your Bluetooth problem.

**Comment by sysofwan** [comment]
+1 I think this is related to this [bug](https://bugs.launchpad.net/ubuntu/+source/sun-java6/+bug/457144). Bluetooth sound uses PulseAudio, but JDK does not support it. A recompilation with OpenJDK might work.
