### ISSUE TITLE
Error in build the app

### ISSUE THREAD

**Issue by LarryFos** [alexa/alexa-avs-sample-app#261]
I get errors when I try to install mvn , here is the file I get
pi@localhost:~/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! path /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient/npm-debug.log
pi@localhost:~/Desktop/alexa-avs

**Comment by ajotwani** [comment]
@LarryFos We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 14th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
