### ISSUE TITLE
Line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported

### ISSUE THREAD

**Issue by JoyBoss** [alexa/alexa-avs-sample-app#264]
So, when I press the 'start listening' button after generating the token, I get the following error:
Line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported

I Have a Raspberry Pi 3 running Raspbian Jessie, and both my USB sound card and mic are working, checked.
If you have any idea what is causing the error or how to fix it, please do take the time to answer. 

![github](https://cloud.githubusercontent.com/assets/11850721/18756442/f26cc9b0-80bd-11e6-98c7-828e1915e886.jpg)

**Comment by ajotwani** [comment]
Have you looked at these - https://github.com/alexa/alexa-avs-sample-app/issues/229 and https://github.com/alexa/alexa-avs-sample-app/issues/50?

**Comment by bill-orange** [comment]
I have tried to use my USP sound device as the speaker output every way I can think of without any luck.  I have my microphone plugged into the USB sound device and the powered speakers plugged into the PI.  That's the only way I was able to get it to work.  

Worse yet any experiments with other configurations resulted in having to reformat the uSD and start again.

**Comment by JoyBoss** [comment]
Thanks a lot. I'll try all of this and if any of it works I'll close the thread.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
