### ISSUE TITLE
Problem when login in on the Setup web screen

### ISSUE THREAD

**Issue by TheFonix** [alexa/alexa-avs-sample-app#267]
I'm having the same issue, but i already have the device name set to my_device, as soon as i hit the ok button to get the key from the AlexaPi it shows up with

We're sorry!
An error occurred when we tried to process your request

**Comment by nullptr023** [comment]
I'm having the same issue. have you found out why? Please help us.

**Comment by TheFonix** [comment]
Nope seems to be little support for this other then people telling me to change client ID's which I've already tried :(

**Comment by nullptr023** [comment]
I already fix mine. try to check the credentials maybe you mistype something. That's where I fix mine.

**Comment by ajotwani** [comment]
@TheFonix just checking, you still having issues with this?

**Comment by TheFonix** [comment]
indeed

**Comment by TheFonix** [comment]
No i sorted it, Sorry
