### ISSUE TITLE
MVN error "system property is not set"

### ISSUE THREAD

**Issue by jamesrequa** [alexa/alexa-avs-sample-app#270]
I am following the recently revised guide and got all the way down to where you have three terminal tabs open on the second terminal window when I run this command in terminal:

cd javaclient && mvn exec:exec 

I am then getting the following error: 

-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script m

**Comment by tstephansen** [comment]
Add this to ~/.bashrc

`export M2_HOME=/opt/apache-maven-3.3.9`
`export M2=$M2_HOME/bin`
`export PATH=$M2:$PATH`

Save .bashrc and run source ~/.bashrc from the terminal (or close all terminals and reopen)

**Comment by jamesrequa** [comment]
That fixed the issue for me, thanks!
