### ISSUE TITLE
Resource requirements

### ISSUE THREAD

**Issue by suravakonda** [alexa/alexa-avs-sample-app#273]
Apologies if this is not the right place for this question. If so, please let me know where I can post the question.

Good to see the wake word detection added for the Raspberry Alexa prototype. With this added, does Amazon team or anyone else who integrated have the processor usage (with sensory/kitt.ai) and memory footprint for Java client app and Java Runtime Environment on Raspberry Pi?

**Comment by suravakonda** [comment]
can anyone reply on this?

**Comment by roccomuso** [comment]
+1

**Comment by keleric** [comment]
On my Raspberry Pi 3 model B, It used ~300mb of memory, and never went beyond 20% CPU usage.
