### ISSUE TITLE
Wiki pages point to raspberrypi pages on setting up VNC on Platforms that have been removed

### ISSUE THREAD

**Issue by martingollogly** [alexa/alexa-avs-sample-app#274]
From the following wiki https://github.com/alexa/alexa-avs-sample-app/wiki/Setup-SSH-&-VNC

namely these links have been removed

- Mac: See https://www.raspberrypi.org/documentation/remote-access/vnc/mac.md
- Windows: https://www.raspberrypi.org/documentation/remote-access/vnc/windows.md
- Linux: https://www.raspberrypi.org/documentation/remote-access/vnc/linux.md

I have raised a comment on the commit on the raspberrypi repo to ask if they should just point you now to the main vnc page or if they will restore the pages.

Here is the commit from raspberrypi that deleted the page that were linked from this repo's wiki

https://github.com/raspberrypi/documentation/commit/36e5427c47cd20b53d54a011dfe51ee341a0a133#diff-1636075d8dfa58d1bc2449899f65e06c

**Comment by martingollogly** [comment]
The comments been updated for the deletion to explain why

"They were removed because we felt that the same instructions could apply to any platform - download VNC Viewer, and enter the IP / hostname. As RealVNC's viewer supports each of these platforms in the same way, and you get the best results when connecting to a RealVNC Server with a RealVNC viewer, there was reduced need for platform-specific instructions."

So maybe its worth updating the wiki just to point to the one main link main link:

https://www.raspberrypi.org/documentation/remote-access/vnc/

**Comment by martingollogly** [comment]
Cheers @ajotwani for the quick response.

Github wikis can't be forked and couldn't figure out how to push the change myself without permissions

**Comment by ajotwani** [comment]
Yeah. GitHub wikis are a bit weird :) Fixed - https://github.com/alexa/alexa-avs-sample-app/wiki/Setup-SSH-&-VNC/_compare/1ac3825a166020650945d2dc7ae57ba65fdff2a6
