### ISSUE TITLE
AVS mutes Raspberry Pi audio

### ISSUE THREAD

**Issue by D3rpi** [alexa/alexa-avs-sample-app#276]
Hello,

I installed AVS yesterday and it was working pretty well but when I woke up this morning, I noticed that it wasn't working as planned. Every time I try to play something with the voice service may it be by triggering the listen button or through the alexa web app, it mutes by Raspberry Pi's audio(the default sink).  So I have to go back and manually enable it again. On re enabling the audio, I send a command to alexa and it mutes my audio again. 
I know it's not being caused by the wake world agent because I shut the agent down and was still having the same problem. I think restarting the voice service will fix the issue but I want to know if there's anything I can do to help diagnose this problem. 

Thank you,

**Comment by ajotwani** [comment]
Hi @D3rpi which wake word are you using - Sensory or KITT.AI?

**Comment by D3rpi** [comment]
@ajotwani I'm using KITT.AL

**Comment by D3rpi** [comment]
Update, this is very strange. I had left it running the whole day and when I came back from work gave it another try and it was back to normal again.
