### ISSUE TITLE
MVN issue

### ISSUE THREAD

**Issue by aaldoori** [alexa/alexa-avs-sample-app#278]
i did everything as described
but when i type
mvn -version
this appears
-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME e            nvironment variable and mvn script match.

**Comment by tstephansen** [comment]
See my answer in #270. That should fix it for you.

**Comment by SuperJonotron** [comment]
Experienced the same issue, referenced #270 link and it resolved but a a new error showed up.

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.496 s
[INFO] Finished at: 2016-10-07T18:51:01-07:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by darianbjohnson** [comment]
I'm having the same problem: Error: Could not find or load main class com.amazon.alexa.avs.AVSApp

**Comment by tstephansen** [comment]
If @darianbjohnson's answer doesn't completely solve it for you then try running "mvn validate", "mvn install", and then "mvn exec:exec". I'm not very familiar with maven so I didn't even realize that validate compile was an option. Anyone know if validate compile does the same thing as install?

**Comment by SuperJonotron** [comment]
mvn validate, mvn install combination fixed it for me

**Comment by aaldoori** [comment]
@tstephansen i have already tried your method
and mvn validate 
mvn install
mvn exec:exec

yield this

[INFO] Scanning for projects...
m[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.411 s
[INFO] Finished at: 2016-10-10T09:35:44+00:00
[INFO] Final Memory: 4M/13M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/pi). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
pi@raspberrypi:~ $ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.409 s
[INFO] Finished at: 2016-10-10T09:35:52+00:00
[INFO] Final Memory: 4M/13M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/pi). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by aaldoori** [comment]
and there is this new issue
cd javacli          ent && mvn exec:exec
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-          maven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-m          aven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom (8 KB at 6.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-          parent/28/mojo-parent-28.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-p          arent/28/mojo-parent-28.pom (26 KB at 266.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-p          arent/3/codehaus-parent-3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-pa          rent/3/codehaus-parent-3.pom (5 KB at 89.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-          maven-plugin/1.2.1/exec-maven-plugin-1.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-m          aven-plugin/1.2.1/exec-maven-plugin-1.2.1.jar (37 KB at 397.2 KB/sec)
[INFO]                                                                             
[INFO] ------------------------------------------------------------------          ------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------          ------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-clien          t ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-          toolchain/1.0/maven-toolchain-1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-t          oolchain/1.0/maven-toolchain-1.0.pom (4 KB at 57.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-          plugin-api/2.0/maven-plugin-api-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-p          lugin-api/2.0/maven-plugin-api-2.0.pom (601 B at 11.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven/          2.0/maven-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2          .0/maven-2.0.pom (9 KB at 122.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/comm          ons-exec/1.1/commons-exec-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commo          ns-exec/1.1/commons-exec-1.1.pom (11 KB at 107.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/comm          ons-parent/17/commons-parent-17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commo          ns-parent/17/commons-parent-17.pom (31 KB at 301.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/7/apa          che-7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/7/apac          he-7.pom (15 KB at 201.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-          toolchain/1.0/maven-toolchain-1.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/ple          xus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.ja          r
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/comm          ons-exec/1.1/commons-exec-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-t          oolchain/1.0/maven-toolchain-1.0.jar (33 KB at 138.5 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commo          ns-exec/1.1/commons-exec-1.1.jar (52 KB at 195.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plex          us-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar           (191 KB at 557.9 KB/sec)
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation           which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment          .java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
        at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------          ------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------          ------
[INFO] Total time: 16.069 s
[INFO] Finished at: 2016-10-10T09:55:09+00:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------          ------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:          exec (default-cli) on project sample-java-client: Command execution faile          d. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the           -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, ple          ase read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExe          cutionException

**Comment by aaldoori** [comment]
@SuperJonotron so it's the same error
what should we do ??

**Comment by manoj-raj** [comment]
thanks @SuperJonotron your steps resolved the issues for me

**Comment by richardle1988** [comment]
Hi @aaldoori : I issued mvn validate and mvn install, then mvn exec:exec.
Below error still occurs. How can I fix it?
Please help me to solve

`pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn validate[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.434 s
[INFO] Finished at: 2017-02-16T11:44:04+08:00
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn install[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample-java-client ---
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sample-java-client ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sample-java-client ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ sample-java-client ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ sample-java-client ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sample-java-client ---
[INFO] Building jar: /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.2.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ sample-java-client ---
[INFO] Installing /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.2.jar to /home/pi/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.2/sample-java-client-20160207.2.jar
[INFO] Installing /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/pom.xml to /home/pi/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.2/sample-java-client-20160207.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.858 s
[INFO] Finished at: 2017-02-16T11:44:25+08:00
[INFO] Final Memory: 8M/21M
[INFO] ------------------------------------------------------------------------
i@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:108)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.422 s
[INFO] Finished at: 2017-02-16T11:45:09+08:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
