### ISSUE TITLE
Can't authorize

### ISSUE THREAD

**Issue by Jompiet** [alexa/alexa-avs-sample-app#283]
Hi,

I took it on myself to try this project as my first Raspberry Pi project, and am thus not very proficient with linux and all its ins and outs. I managed to complete every step succesfully until I arrived at step 7. When I run the first terminal everything works fine and the service starts listening on port 3000. When I run the second terminal, I get prompted to the authorization webpage and this is where it goes wrong. After I completed this step: _If you're running Raspbian Jessie with Pixel desktop (and with Chromium browser), you may get a warning from the browser. You can get around it by clicking on Advanced -> Proceed to localhost(unsafe)._ I get the follwing message in my browser instead of a login page: 

{"error":"MissingParams","message":"The following parameters were missing or empty strings: code"}

cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[1600:1631:1007/180106:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[1741:1741:1007/180107:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process

I checked both secuirity codes and those are correct, I have also added 

Allowed Origins: https://localhost:3000
Allowed Return URLs: https://localhost:3000/authresponse

to my security profile.

Most likely I am making some sort of trivial mistake here, apologies in advance, this is my second day using linux.

**Comment by amauridimaia** [comment]
I get the log in field on my browser and can successful log in amazon but in the terminal window I got the same as you: 
[1600:1631:1007/180106:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[1741:1741:1007/180107:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process

**Comment by Jompiet** [comment]
Fixed it by deleting everything and starting again at step 4. Turns out I mixed up 2 security profiles. If anyone else gets this error. Be sure to check your ID's entered at step 5. I had mistakenly put in my my_device security ID's instead of the newly created security profile in step 3.
