### ISSUE TITLE
Anyway to turn do the Alexa Beep response, it is louder than the voice itself

### ISSUE THREAD

**Issue by cejaay** [alexa/alexa-avs-sample-app#285]
Anyway to have the alexa acknowledgement beep softer? or less loud/harsh, or possible disable?

I am able to turn down volume on my raspberry and in some alexa apps, but cant find way to change or lower volume on beep.

**Comment by kymotsu** [comment]
I've been wondering the same thing or even change it. My tone even stutters on my Pi2 for some reason.

**Comment by D3rpi** [comment]
Agreed, lowering the beep volume would be good. The only way around this so far is hooking up a bluetooth speaker. The beeps will still go through the 3.5mm audio and the output to Alexa's commands should go to to your BT speaker. That's how it was on when I was running the earlier version of this project.
I haven't used my BT speaker with this version yet but will try it out and let you know.

**Comment by cejaay** [comment]
i'll test a bluetooth speaker next. i'm surprised alexa won't continue a conversation. i asked who was the 12th pres of Us and she told me. asked who was his wife next and she was confused. so far only found google assistant follows conversations.

**Comment by D3rpi** [comment]
So I connected my bluetooth speaker. The good news is tunein and iheartradio audio goes to the Bluetooth speaker with the beeps still going to the line out. 
Now the problem with that is all alexa responses also go to that line out.

**Comment by keleric** [comment]
The easiest solution would probably be to swap out the beep sound file.

**Comment by kymotsu** [comment]
That would be great but, I have a suspicion that it's much easier said than
done.

**Comment by keleric** [comment]
I don't think so. You can replace the start sound with whatever you want.

1. Go to samples > javaclient > src > main > resources > res.
2. Open start.mp3 in Audacity
3. Amplify it in the negative direction
4. Re-save.

**Comment by keleric** [comment]
Alternatively, you can just disable the sound. Delete this line: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L502

**Comment by kymotsu** [comment]
That's good to here I looked for the file but didn't have much luck. Not
that I knew where I should be looking though...

**Comment by teknoviking** [comment]
I am using the Java Client and in my build the sound files are located at - /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/res   I hope that helps!
