### ISSUE TITLE
Alexa and Wemo

### ISSUE THREAD

**Issue by bill-orange** [alexa/alexa-avs-sample-app#287]
Has anyone gotten Alexa on the PI or any other platform to work with Wemo's Insight device (version 2 firmware)?  Alexa is supposed to work with WeMo without needing a skill.  So far I can not get the WeMo device to be detected.  I have checked that uPNP is getting through and that everyone is on the same network.

I have attempted detection with Alexa on the PI and with the iPhone app.  My Nest detected easily once the skill was loaded.

**edit **

I was able to get the WeMo to work using IFTTT as an intermediary. Its awkward but it does work.

Bill

**Comment by keleric** [comment]
See #162
