### ISSUE TITLE
wakeword agent can not run

### ISSUE THREAD

**Issue by westwind** [alexa/alexa-avs-sample-app#289]
When I run wakeword agent via command "./wakeWordAgent -e sensory", 

I got the following message
```
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.1 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 Jan 2017 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:WakeWordAgent: thread started
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
```

But the client is running actually, I do not have any idea to fix this issue, 
is there anyone have the same issue? thank you

**Comment by keleric** [comment]
Did you bring up the companion service? That's the first thing that needs to be started.

**Comment by YaminMalkawi** [comment]
Did you run the automated_install.sh script and answered No for wake word engine?

Please check "config.json" file in "samples/javaclient" and make sure that "wakeWordAgentEnabled" is set to true.

**Comment by westwind** [comment]
yes, I bring up the companion service. Then start the simple app, and I also check the service is running, because I can talk with alexa when I click "Listen" button. Then start the wake word engine, I still get the message

**Comment by westwind** [comment]
@YaminMalkawi I not ckeck the config.json file in "samples/javaclient" yet, I will check it later. Thanks for your comment

**Comment by westwind** [comment]
@YaminMalkawi Thanks for your comment, my wake word agent is work

**Comment by westwind** [comment]
This Issue is solved, Close this issue
