### ISSUE TITLE
Wake Word Engine Not Working

### ISSUE THREAD

**Issue by moviemanic** [alexa/alexa-avs-sample-app#292]
My Raspberry Pi 3 was working just fine with the sensory engine. However after a reboot now neither engine works, but the button still works fine. With sensory I'm getting "pcm.c:694: snd_pcm_close: assertion 'pcm'  failed"

**Comment by bill-orange** [comment]
When I tried using a USB sound device for speaker output, I got the same error message. PCM is the sound control panel. 

When I turned off PCM and plugged my speakers into the PI, I was unable to dismiss the error. I ended up plugging speakers into the PI and my mic into the USB sound device, reformatting the uSD and starting all over. 

So in summary, I am pretty sure your error is the result of speakers and mic in an unsupported setup but I have no easy solution. 

As far as I can tell and I have not tested many things, HDMI sound output and 3.5 mm jack sound output are the only two supported configurations. I have not found a graceful way to recover from an unsupported configurations.

**Comment by moviemanic** [comment]
I changed my audio output to my pnp USB sound card in the hopes of better audio, and that's when the problem arose as far as I can tell, but even after changing it back and restoring my .asoundrc file to defaults the error persists.

**Comment by bill-orange** [comment]
Yes, that was my experience also. Changing it back did it resolve the problem. 

I restored the sound hardware to the supported configuration reformatted the uSD and and started all over. I did not find a more graceful solution to getting it working again.

**Comment by westwind** [comment]
I had the same issue before. 
I use command "cat /proc/asound/cards" to check my the device id, 
and modify ~/.asoundrc setting to match the device id. 

for example
```
$ cat /proc/asound/cards
0 [ALSA]: bcm2835 - bcm2835 ALSA
                 bcm2835 ALSA
1 [U0x46d0x81d]: USB-Audio - USB Drivce 0x46d0x81d
                               USB Device 0x46d0x81d at usb-3f980000.usb-1.3, high speed
```
It's should use USB Device, so we need modify ~/.asoundrc config to the fallowing
```
pcm.!defoult {
    type hw
    card 1
}
ctl.!defaoult {
    type hw
    card 0
}
```

maybe you can try this method

**Comment by Ayysir** [comment]
@westwind doesnt work, katt_ai errors out

**Comment by Nitee** [comment]
I'm currently going through a fresh install due to this. Everything was working my setup was as follows:

1 USB Microphone and 1 3.5mm audio jack

However, I wanted to get better audio so I got a USB sound card ($5 Sabrent 3D sound) and was trying to use the USB microphone as well, but to no avail and wake word was now broken. I tried many different solutions that didn't solve anything. I even plugged in a microphone into the sound card and removed the USB microphone but that didn't work. I'm now reinstalling and hoping if I set it up with the USB Soundcard only, it will work again.

**Comment by Ayysir** [comment]
My mic works my sound output is the issue. Little-endian bs

**Comment by hotwheelzffx** [comment]
Having the same issues as above. I have a USB Microphone and a HiFiBerry Digi+ DAC on my Raspberry Pi 3. The following config seems to work (sometimes). However, I have to set my .asoundrc to read-only. Something is modifying that file on boot and prevents everything from working. When .asoundrc is set to read-only you can't really boot into the desktop GUI. Alexa recognizes the microphone and attempts to say something back but I don't get any audio. My MPD client, however, does output music.

pcm.usb
{
    type hw
    #card YOURDEVICENAME shown with arecord -l;
   card Device #this is my USB microphone instance
}

pcm.external
{
    type hw
    #card YOURDEVICENAME shown with aplay -l
    card sndrpihifiberry
}

pcm.!default
{
    type asym
    playback.pcm
    {
        type plug
        slave.pcm "external"
    }
    capture.pcm
    {
        type plug
        slave.pcm "usb"
    }
}

ctl.!default
{
    type asym
    playback.pcm
    {
        type plug
        slave.pcm "external"
    }
    capture.pcm
    {
        type plug
        slave.pcm "usb"
    }
}

**Comment by hotwheelzffx** [comment]
Following up: USB Microphone and a HiFiBerry Digi+ DAC on my Raspberry Pi 3. I was able to get this working by installing PulseAudio.
sudo apt-get install VLC
sudo apt-get install pulseaudio
sudo apt-get install pavucontrol
The running it with: pulseaudio -D
Then starting the Alexa services.
If you still don't hear sound, check on the PulseAudio mixer application. Alexa looks like it routes thru VLC. Make sure you have the volume up on that entry.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
