### ISSUE TITLE
Xlib errors Randr missing, and others

### ISSUE THREAD

**Issue by cejaay** [alexa/alexa-avs-sample-app#296]
Please delete this issue, I am reloading the Alexa app and see if that fixes the issue.

**Comment by keleric** [comment]
What happens? Does the popup occur telling you to go to an address? At what point does it fail? Also, are you running this over SSH or on the Pi directly?

**Comment by cejaay** [comment]
I am running this via Tightvnc.. that could be the issue, I will try directly or rdp.

**Comment by cejaay** [comment]
I tried via rdp and it fails, i ran it via rdp fine over weekend.
Same errors.
