### ISSUE TITLE
Hang when command processing starts

### ISSUE THREAD

**Issue by 3dpowers** [alexa/alexa-avs-sample-app#299]
I'm not sure why the Java windows will hang after it starts to try to process a command.

**Comment by erikhopf-amzn** [comment]
3dpowers -- can you provide additional details:
* Are you working off Pi2 or Pi3?
* Is this a fresh Raspbian install? If not, what version of Raspbian are you running?
* Lastly, can you provide a screengrab of where it hangs?

**Comment by 3dpowers** [comment]
Rpi3 fresh install of latest pixel build. No errors appear after it hangs.

**Comment by 3dpowers** [comment]
I somehow got it to work by reinstalling pixel and the git sample app

**Comment by erikhopf-amzn** [comment]
@3dpowers did you do anything different this time? Such as booting with the mic/speaker plugged in or running apt-get upgrade/update prior to installation?

**Comment by 3dpowers** [comment]
I reflashed the image.. That's all

**Comment by ajotwani** [comment]
Closing as resolved.
