### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by jwginge** [alexa/alexa-avs-sample-app#302]
I say "Alexa, add something to my calendar."

She tells me she can't find a calendar linked to this account and to go to the settings on my Alexa app. I have done this and linked my google calendar but she cannot find it. Is this deliberate with the AVS or is there something I can do to get calendar functionality?

Thanks,
JWGinge

**Comment by keleric** [comment]
It's not deliberate. AVS should work perfectly fine with calendars. What steps did you use to link the calendars? What does Alexa say when you ask what events are coming up?

**Comment by jwginge** [comment]
I should mention I'm in the UK. A family member of mine has an Amazon Echo and I'd already sync'd my Google Calendar in the Alexa app, using the same login as the one I use for Amazon Developer. Alexa tells me she can't see a calendar set up and to go to the settings in my Alexa app.

**Comment by keleric** [comment]
Ah, that would explain it! We're still in the process of rolling out UK support for AVS (currently scheduled for early 2017). What I think has happened is that you've set everything up with your Echo, which is set up for UK. However, AVS still defaults to US, and the two setups don't share data. I'm not sure there's a fix until we finish rolling out UK support. Sorry!

**Comment by jwginge** [comment]
Hopefully that's it. Looking forward to your UK support! 

Thanks for the help keleric
