### ISSUE TITLE
new install, terminal 2, bash: mvn:  command not found

### ISSUE THREAD

**Issue by cejaay** [alexa/alexa-avs-sample-app#303]
Closing this case, will try reinstalling project in the future, thanks for everyones help.

**Comment by keleric** [comment]
You need to install maven, and make sure that your PATH can find the 'mvn' executable.

**Comment by cejaay** [comment]
I reinstalled everything,, no more maven issue, so odd that everything worked friday and i tested it out, and nothing but problems since monday.

I have  a new error:

terminal window 2, when launching its commands.

error: could not find or load main class.org.codehaus.plexus,classworlds.launcher.launcher

and then returns to prompt $

not sure what to do now.

have reinstalled twice and same error, after erasing entire desktop folder for alexa and reinstalling from script.

**Comment by jimseelan** [comment]
Did some check and its now working.
On the "automated_install.sh" need to change the variable as
Companion_Service_Loc=$Samples_Loc/companionService

also need to do a a "sudo npm cache clean" 
and need to do the sudo install npm on "/companionService"

**Comment by cejaay** [comment]
thank you.

Do I need to do these steps myself, or will the automated_install.sh now
perform them.

i assume you updated the automated install with the new variable.

- let me know if i need to perform - also need to do a a "sudo npm cache
clean"
and need to do the sudo install npm on "/companionService" myself

**Comment by cejaay** [comment]
i am reinstalling now, with the updated automated install sh you changed.

i am not quite sure how to do the rest.

I assume after the install finishes that i run:

sudo npm cache clean   at a bash prompt

and then?

sudo install npm on "/companionService  (is that the right command?) with
the word 'on' in it?

**Comment by cejaay** [comment]
i reinstalled and did automated install,

i also did sudo npm cache /clean

could not get the command: sudo install npm on "/companionService" to work

terminal 1 was listening on port 3000

ran terminal 2   mvn exec:exec and it scanned for project and got a build
failure with no POM in samples directory.

perhaps this is due to me not doing the install npm command on
companionservice..

unsure.. hopefully ill get this working again
