### ISSUE TITLE
Step 7: npm: command not found

### ISSUE THREAD

**Issue by chus3r** [alexa/alexa-avs-sample-app#305]
I've run the install and when trying to run npm start in step 7 I get the following.
`bash: npm: command not found`

I didn't see any errors during or after running the install script. What am I missing?

**Comment by erikhopf-amzn** [comment]
Hi chus3r -- are you running Pi2b or Pi3? Also are you working with the latest version of Raspbian?

**Comment by chus3r** [comment]
It's a Pi3. I'm going to make sure everything is updated and start fresh tomorrow when I get back to the office. I'll update here as soon as I get a fresh look at everything.

**Comment by chus3r** [comment]
Good news @erikhopf-amzn it looks like you were correct. After reinstalling Jesse I am able to get past step 7. I will close this issue and move on to my next one. Thanks!
