### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by Eddie-Hartman** [alexa/alexa-avs-sample-app#309]
I've had this working a few times before. I updated to the new version with a fresh raspbian install and did everything by the books. Some things need changed like making files executable, (chmod +x) and using sudo for commands. Anyway, NPM start gives me this error after a bit (more specifically, after trying to use the service after going to the amazon links and getting the device tokens).

Listening on port 3000
error:  { [Error: Not Found] status: 404 }

Also, the kitty_ai wakeword tool is not working and I get 

sudo ./wakeWordAgent -e kitt_ai
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
ERROR:Failed to open PortAudio stream.Device unavailable
ERROR:KittAiSnowboyWakeWordEngine: Initialization error:Failed to open PortAudio stream.
ERROR:WakeWordAgent: exception in constructor: Failed to open PortAudio stream.
ERROR:main: Exception happened: Failed to open PortAudio stream.
INFO:Shutting down Wake Word Agent

but I wanted to see if fixing the first issue fixes the second.

**Comment by jimseelan** [comment]
Me too getting the same NPM error.
Listening on port 3000
error: { [Error: Not Found] status: 404 }

**Comment by Titz80** [comment]
Me too getting this status 404.
Anybody a idea how to solve it?

**Comment by ohhitsazombie** [comment]
same issue here as well. what microphone are you guys using? i am using the playstation eye. i think it has something to do with that...

**Comment by Eddie-Hartman** [comment]
It has nothing to do with the mic.

**Comment by ohhitsazombie** [comment]
only reason i said that is when i open the alsamixer i get an error when i try to select my playstation eye as the sound card. when i changed my audio input source to my TV it started to work and the service ran.

**Comment by Titz80** [comment]
Yes, i use the playstation eye as well. In alsamixer i get the an error too.

**Comment by Eddie-Hartman** [comment]
I use the recommended mic.

**Comment by ErikBanner** [comment]
I'm having the same issues here. Both 404 and device unavailable.

**Comment by ohhitsazombie** [comment]
so i determined it has something to do with kitt_ai. i ran sensory just fine, the only problem is it expires in 90 days. anyone else have any luck with this?

**Comment by ErikBanner** [comment]
In the end I just reinstalled the raspbian os and went  through the install script then everything works. It was actually easier to do that than trying to fix broken environment. Except that I get some other alsa errors but things are working and there's post regarding how to remove those errors. I just left them be for now.

**Comment by Titz80** [comment]
Erik, do you have the playstation eye cam too? So many people with problem with that mic, so i dont think that a reinstallation of OS and scripts will help me.

**Comment by ErikBanner** [comment]
No it's not eye cam. You are right maybe it won't work for you guys :(

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Eddie-Hartman** [comment]
Reopen this. As far as I know, nothing has changed. If I'm wrong, please correct me. Thanks.

**Comment by keleric** [comment]
The error: { [Error: Not Found] status: 404 } does not prevent the sample app from working. It's a red herring. As far as the microphone goes, we can't really help. Ultimately, the sample app is just using whatever Raspbian selects as the default ALSA microphone.

**Comment by markperdue** [comment]
I was seeing the same issue. In my case, I was following the command from the alexa output of automated_install.sh which said to use:

`Run the wake word agent: cd /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src && sudo ./wakeWordAgent -e <engine_type>`

I found that removing the sudo fixed all the issues. The command that ended up working for me was
`cd /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e kitt_ai`

**Comment by Eddie-Hartman** [comment]
@keleric I already mentioned this in another thread, but I'll say it again here. I am using the exact set up and followed the instructions word for word and my setup will not work. Somewhere along the line a commit broke this code in general because I can't even get mine to work without using a wake word now. I've had the working multiple times before at multiple different stages of development. I am using the microphone that is recommended and it's not detected. Then why is the microphone even recommended if it's not going to work? Did you guys even try to follow your own instructions to set this up and see if it works?
