### ISSUE TITLE
Amazon Wont Accept My Device

### ISSUE THREAD

**Issue by Teamtyler2** [alexa/alexa-avs-sample-app#312]
I have been working on this for a bit on a raspberry pi and i cant get passed the AVS login i get to the okay button and when i pressed it i get were sorry were working on it

**Comment by jdjimmy** [comment]
Same here...

**Comment by Teamtyler2** [comment]
@jdjimmy I understand the issue now please send images of the button and the developer console to fix this issue

**Comment by Teamtyler2** [comment]
It not called a button XD it the amazon listen thing by java in the corner

**Comment by jdjimmy** [comment]
@Teamtyler2 - Thanks! I corrected a typo in the Product ID. It works great now.
