### ISSUE TITLE
Maven Error on running java client

### ISSUE THREAD

**Issue by majith** [alexa/alexa-avs-sample-app#313]
Installed the latest version, got the following error while running javaclient:
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script match.

I looked at maven install and it looks ok.
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ echo $M2_HOME
/opt/apache-maven-3.3.9

**Comment by majith** [comment]
A comibnation of the solution described in https://github.com/alexa/alexa-avs-sample-app/issues/270 and  a sequence of mvn validate , mvn install , mvn exec:exec fixed it for me. Closing.

**Comment by ramakrishna-y** [comment]
I am also having the same issue. When I run mvn, I get the same error. I was not able to run mvn -version also.

-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script match.

Not sure where to set this multiModuleProjectDirectory property? Can anyone help me?
