### ISSUE TITLE
UK Alexa

### ISSUE THREAD

**Issue by scoobyd00** [alexa/alexa-avs-sample-app#315]
Got this working great on my PI but the problem is that it defaults to the US. 

When i try and setup things in the app it isnt recongised by alexa. The only options that are working are location and metric units.

Skills dont work, im unable to discover other devices (ie to control lights), flash briefings are all usa even if i select the uk ones in the app.

Is there anyway to get it to link to our UK app so we can use the UK specific skills, music, news etc etc

**Comment by alibasta** [comment]
Did you fixed this @scoobyd00?

**Comment by scoobyd00** [comment]
I didn't try any longer as I purchased an Amazon dot
