### ISSUE TITLE
ALPN Jetty table is hard to find

### ISSUE THREAD

**Issue by Coaxial** [alexa/alexa-avs-sample-app#322]
Why not link to it directly in the Wiki: https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html instead of linking to jetty's website to a page where there is no such table?

**Comment by erikhopf-amzn** [comment]
@Coaxial curious, specifically which instructions are you referring to? The link is available in the code (http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions). Since this is unclear, I'd love to go in and make adjustments where applicable.

**Comment by Coaxial** [comment]
I was referring to that page: https://github.com/alexa/alexa-avs-sample-app/wiki/Mac, §6.3

> Confirm that the ALPN version matches your JDK version using the table located at eclipse.org/jetty. If the versions match no further action is necessary. If the versions do not match, update the pom.xml file with the correct ALPN version.

The link there points to what I assume is the Jetty homepage where there is no such ALPN table. It would be easier to point to https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html directly, where the actual table is.

**Comment by erikhopf-amzn** [comment]
@Coaxial - Thanks for calling this out. I've added a direct link to the version table in each doc set (Linux, Mac, Windows).
