### ISSUE TITLE
Does the current javaclient sample app stream the audio in both directions?

### ISSUE THREAD

**Issue by dly9014** [alexa/alexa-avs-sample-app#324]
I understand the javaclient streams the audio into AVS vs sending it all at once. Does the sample app play the alexa response as a stream as well, instead of buffering the whole thing and playing it? I understand that is how to get the best possible response time.

**Comment by keleric** [comment]
Yes and no. Alexa's speech is not streamed in the sample app, though that is certainly an optimization that you can make. However, music and audio books are streamed.
