### ISSUE TITLE
How to use the javaclient to submit pre-recorded questions

### ISSUE THREAD

**Issue by dly9014** [alexa/alexa-avs-sample-app#325]
While waiting for Echo push notifications for a year now, I extended https://github.com/sammachin/AlexaPi to essentially enable push by submitting pre-recorded questions to AVS when triggered by an event. The problem I face is that response time is slow, typically 5-10 seconds. I believe the approach used in the javaclient sample app here address those performance issues by streaming the audio to AVS (and maybe also streaming the response back? I asked this question separately). So response time is much better than AlexaPi. So I'm hoping to leverage it. Has anyone modified the sample app so that it sends an mp3 to AVS vs interactive voice?

**Comment by alexsalnikov** [comment]
Submitted sound to avs server is:
wav file in this format
16bit Linear PCM (LPCM16)
16kHz sample rate
Single channel
Little endian byte order
they usually very small like 100kb

and received format is:
mp3
Audio file with ID3 version 2.4.0
MPEG ADTS
layer III, v2
48 kbps, 24 kHz, Monaural

1 - there possibility it takes more time to process mp3
2- or mp3 files that you send is very big

**Comment by keleric** [comment]
If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. Thanks!
