### ISSUE TITLE
sign in to amazon = error

### ISSUE THREAD

**Issue by mpskierbg** [alexa/alexa-avs-sample-app#326]
Hello, I get to the second terminal, and sign into amazon, press okay and then it goes to an error screen. nothing specifying what error. I did not click the ok button on the last popup.  i dont know what to do. please help.

**Comment by acidhax** [comment]
Make sure you added the allowed URLs in your amazon developer panel

**Comment by mpskierbg** [comment]
the local hosts?

**Comment by mpskierbg** [comment]
[7045:7090:1017/023914:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[4:4:1017/023915:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
[46:46:1017/023915:ERROR:ppapi_thread.cc(310)] Failed to load Pepper module from /usr/lib/chromium-browser/libpepflashplayer.so (error: /usr/lib/chromium-browser/libpepflashplayer.so: cannot open shared object file: Permission denied)
[4:4:1017/024000:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
[4:4:1017/024000:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()

this is whats in the terminal after i get the error on amazon

**Comment by mpskierbg** [comment]
Anyone have any ideas?

**Comment by SilleDE** [comment]
Manual:
    Allowed Origins: https://localhost:3000
    Allowed Return URLs: https://localhost:3000/authresponse

I have added the  rasperrys ip in my amazon developer panel

    Allowed Origins: https://192.168.1.x:3000
    Allowed Return URLs: https://192.168.1.x:3000/authresponse

**Comment by mpskierbg** [comment]
Ok so try adding my IP address before the allowed urls?

**Comment by mpskierbg** [comment]
I tried it still doesn't work.

**Comment by mdnegan** [comment]
ok for me i found a fix,(did not get much further now i am trying to figure audio issues),not sure it it will work for you guys ,my issue was i had input incorrect data (step 5 if i remember right) in the productID= section of the automated_install.sh file and inputting Security Profile ID in this field instead DoH!.
Hope this helps others.

**Comment by mpskierbg** [comment]
Can you kindly rephrase what you did? I am not quite clear to what you mean. I know the file and what was needed in step 5 but don't know what you put there.

**Comment by mpskierbg** [comment]
heres what mine looks likle
   ```
 "#!/bin/bash
#-------------------------------------------------------
# Paste from developer.amazon.com below
#-------------------------------------------------------

# This is the name given to your device or mobile app in the Amazon developer p$
ProductID=Raspberry_P

# Retrieve your client ID from the web settings tab within the developer consol$
ClientID=amzn1.application-oa2-client.3025d4cb2d574258b6ad8773ec928c8d

# Retrieve your client secret from the web settings tab within the developer co$
ClientSecret=37ea3e601820b020474a002563b7c01dead0d066ed7fcb1b7f8d0ae39dc752a9

#-------------------------------------------------------
# No need to change anything below this...


```

**Comment by mdnegan** [comment]
it looks right so likely something else,just one thing is the Raspberry_P line correct as guide its meant to be like ProductID="RaspberryPi3 (likely this does not matter But,just in case its a typo) would not be surprised if there some line of code somewhere that points to names like RaspberryPi3 or my_device as i have seen mentioned in a number of guides n forums,i am properly wrong,i am curious tho, the pi i am using is a pi3,is your pi also a pi3 or other model ?

**Comment by mpskierbg** [comment]
OK I'll try it. I am using a raspberry pi

**Comment by mpskierbg** [comment]
Didn't work. I think I figured out the issue. But don't have time to run through it.

**Comment by michaelkhan3** [comment]
I'm having the exact same issue can you let me know what your solution was? I have a sneaky suspicion that it maybe be due to my location in Ireland but I'm not sure. Would appreciate any help

**Comment by foozilla** [comment]
Setting the ProductID to the **Device Type ID** from the **Device Type Info** tab in automated_install.sh and rerunning it fixed this issue for me.

**Comment by TobyMacdonnnell** [comment]
Hi I'm getting the same error and all the settings so far appear to be correct... I can click on "listen" in the AVS client, which provides the "ping" but I then get an error from the AVS client:

"java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException"

Any thoughts anyone?

I've made sure the product ID is correct etc, and the Amazon Dev account signs in fine with the "device tokens ready" response...

I'm so close!! :(

Any help appreciated. Thanks.

**Comment by TobyMacdonnnell** [comment]
It looks like it works ok without the wakeWordAgent running... how odd...

Any thoughts?

Thanks

**Comment by rubbinsracin** [comment]
Having the same issue.  Soon as I click okay to let the pi call alexa it shows an amazon error.  Checked previous entries and all seem good.  Anybody have thoughts on how to get past this step?  Much appreciated

**Comment by Harley04** [comment]
Hi I am severe sight impaired and am getting this error message at the 2nd terminal Please help.


pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/pi/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/pi/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/pi/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/pi/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/pi/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/pi/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/pi/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/pi/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/home/pi/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:183)
	at com.amazon.alexa.avs.App.<init>(App.java:47)
	at com.amazon.alexa.avs.App.<init>(App.java:36)
	at com.amazon.alexa.avs.App.main(App.java:31)

**Comment by kencecka** [comment]
Hi @Harley04,

Are you trying to run this on raspbian stretch?  If so, there are known issues with compatibility that will be addressed in a future release.  You may want to consider switching back to one of the older jessie releases.

Ken

**Comment by Harley04** [comment]
Cheers Ken I WILL TRY THAT OUT!

**Comment by Harley04** [comment]
Sorry about the caps I didnt see it was on!!!

**Comment by Harley04** [comment]
Hi Ken after a long battle I now have Alexa. CHEERS mate

**Comment by mikey1878** [comment]
Can I ask what version you used, I am having the same problem

**Comment by Harley04** [comment]
I just picked one from 2016

**Comment by mradulan** [comment]
Closing the issue. If the problem still persists, please reopen.

**Comment by ishyambaldha** [comment]
Facing the same isuue:

ubuntu@technexion:~$ chromium-browser
[11527:11527:0928/140951.171173:ERROR:CONSOLE(145)] "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://localhost:3000') does not match the recipient window's origin ('https://www.google.co.in').", source: chrome-search://most-visited/single.js (145)
[11527:11543:0928/140951.274963:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for localhost failed err=-8179
[11527:11542:0928/140958.397066:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for amazon.com failed err=-8172
[11527:11680:0928/140958.399631:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for amazon.com failed err=-8172
[11527:11542:0928/141000.265445:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for www.amazon.com failed err=-8172
[11527:11680:0928/141000.300948:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for www.amazon.com failed err=-8172

Please help.

**Comment by Harley04** [comment]
Sorry i am blind and have to rely on others.

**Comment by ishyambaldha** [comment]
I am able to solve this issue. It was a problem with firewall service. It was blocked by a firewall.
