### ISSUE TITLE
Discovering Devices

### ISSUE THREAD

**Issue by SpiderSpartan** [alexa/alexa-avs-sample-app#327]
Has anyone tried discovering smart home devices with this? I don't have any official devices, but I've followed a couple of examples on setting up a pi as a device ([ha bridge](https://github.com/armzilla/amazon-echo-ha-bridge), [WeMo](http://www.instructables.com/id/Hacking-the-Amazon-Echo/)).  I've been setting them both up on the same pi, so that may be an issue too, but the software appears to run fine. I'm not sure if it's an issue with the AVS sample or the device setup. Anyone had any luck with setting these up together?

**Comment by tazz131** [comment]
I have had no luck.

I have two devices, Harmony remote and a Nest thermostat.

I feel like I've tried just about everything I could to get them working, and the Pi never finds my devices when I do a device search with Alexa.

**Comment by bill-orange** [comment]
I don't believe the WeMo will detect on this Alexa implementation. There are alternatives  approaches. 

Regarding NEST, you can load a skill for NEST. It's easiest to load the Alexa app on your iPhone to load the skill off the phone App. There is an Android App too. 

Regarding WeMo you can connect to the WeMo using ifttt. Go to their web site for instructions on setting it up. 

You may find ifttt worth playing with irrespective of Alexa. When my house reaches 87 degrees my phone rings. "The house is 87 degrees. I don't care but it must be dreadful. " useless but too funny.

**Comment by damien-mclaughlin** [comment]
These aren't all that smart, but i've tested TP-Link HS100 smart plugs and both work fine with AVS Alexa once you have added them to your network with the Kasa app and then enabled them to Alexa using the Kasa skill (both of these are new and unregistered previously with either my DE / UK account, the link if for the German version, but i'm sure TP produce the same model for all regions.) 
https://www.amazon.de/gp/product/B01I59FOIU/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
