### ISSUE TITLE
Error building  AVS by SSH

### ISSUE THREAD

**Issue by YOUN3SS** [alexa/alexa-avs-sample-app#328]
Step 2 fails while doing it with remote SSH.

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
        at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.071s
[INFO] Finished at: Mon Oct 17 19:41:01 UTC 2016
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

How can I run the java client without HMDI display?

Thanks.

**Comment by majanoff** [comment]
I've got the same issue, and tried the remedies from other sites with no luck. Is it possible something has changed so that the instructions no longer are valid? I've tried this multiple times with the same outcome.

**Comment by mitchross** [comment]
You need to be VNC'd in or have a monitor hooked up. The terminal program prompts a Java GUI  window to capture the token.

**Comment by maj53** [comment]
This worked. Thank you very much.

**Comment by YOUN3SS** [comment]
I tried today with VNC but I get the same error. So I think that VNC/SSH are not OK with the current Java client, if you want to go back to the HDMI display, type this command:

export DISPLAY=:0.0

**Comment by mdnegan** [comment]
had same issue when using vnc,putty and ssh extension,But worked with rdp to xrdp using modules sesman-Xvnc worked fine.

**Comment by ajotwani** [comment]
Closing as resolved.
