### ISSUE TITLE
Wake Word Engine compilation fails

### ISSUE THREAD

**Issue by bstarcev** [alexa/alexa-avs-sample-app#329]
Showing terminal output for the Word Engine compilation:

========== Installing Companion Service ==========
node-uuid@1.4.1 node_modules/node-uuid

debug@2.2.0 node_modules/debug
└── ms@0.7.1

body-parser@1.12.4 node_modules/body-parser
├── content-type@1.0.2
├── bytes@1.0.0
├── depd@1.0.1
├── qs@2.4.2
├── raw-body@2.0.2 (bytes@2.1.0)
├── on-finished@2.2.1 (ee-first@1.1.0)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── iconv-lite@0.4.8

express@4.12.4 node_modules/express
├── merge-descriptors@1.0.0
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── fresh@0.2.4
├── methods@1.1.2
├── escape-html@1.0.1
├── range-parser@1.0.3
├── vary@1.0.1
├── content-type@1.0.2
├── parseurl@1.3.1
├── finalhandler@0.3.6
├── serve-static@1.9.3
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── etag@1.6.0 (crc@3.2.1)
├── send@0.12.3 (destroy@1.0.3, ms@0.7.1, mime@1.3.4)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.12)
========== Preparing External dependencies for Wake Word Agent ==========
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/portaudio.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/pa_util.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/lib/libportaudio.a’: No such file or directory
========== Compiling Wake Word Agent ==========
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[ 15%] [ 15%] [ 23%] [ 30%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/main.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngine.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:100: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: **\* [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: **\* [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] [ 11%] [ 17%] [ 23%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/main.cpp.o
Building CXX object CMakeFiles/wakeWordAgentTest.dir/testIPCFactory.cpp.o
Building CXX object CMakeFiles/wakeWordAgentTest.dir/testLogger.cpp.o
Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/testKittAi.cpp:15:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
[ 29%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
CMakeFiles/wakeWordAgentTest.dir/build.make:100: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o' failed
make[2]: **\* [CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: **\* [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Nitee** [comment]
I'm currently going through a fresh install due to this. Everything was working my setup was as follows:

1 USB Microphone and 1 3.5mm audio jack

However, I wanted to get better audio so I got a USB sound card ($5 Sabrent 3D sound) and was trying to use the USB microphone as well, but to no avail and wake word was now broken. I tried many different solutions that didn't solve anything. I even plugged in a microphone into the sound card and removed the USB microphone but that didn't work. I'm now reinstalling and hoping if I set it up with the USB Soundcard only, it will work again.

**Comment by bchuckles** [comment]
Bump!

**Comment by abhisheksimion** [comment]
I am getting the same errors and not able to use Wake word engine. @bchuckles I am not getting the prompt where it asks for a newer version of "X" (What is X here?).

Can anyone help please?

**Comment by bstarcev** [comment]
I solved the problem by the fresh install of Jessie OS.

**Comment by abhisheksimion** [comment]
@bstarcev I started with a fresh install of Jessie OS too, but before starting any of the steps given in official document, I did `sudo apt-get update`. Is this the culprit, any idea?

**Comment by abhisheksimion** [comment]
@ajotwani @erikhopf-amzn I tried with a new Pi with new sdcard, but still the same problem. Any kind of help would e greatly appreciated.

**Comment by bstarcev** [comment]
My is working fine and I did not do apt-get update after installation. I am afraid I will not be able to help you.

Good luck

Borislav

**Comment by abhisheksimion** [comment]
@bstarcev: Can you just tell me what version of compiler you are using. Mine is 4.9.2.
gcc --version: (Raspbian 4.9.2-10) 4.9.2

**Comment by bstarcev** [comment]
Mine gcc is the same version gcc (Raspbian 4.9.2-10) 4.9.2

It is a real puzzle. 

Borislav

**Comment by keleric** [comment]
PortAudio clearly didn't install correctly. Try deleting the kitt.ai directory that gets created as part of the automated install, and rerunning automated_install.sh.

**Comment by syauqy** [comment]
Try to download manually PortAudio archive at http://portaudio.com/archives/ , choose the pa_stable_v19_20140130.tgz file. Then put the archive to ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++' and run the install portaudio using sudo ./install_portaudio.sh

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Dec 17th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!

**Comment by ljishen** [comment]
I solved this problem by using this patch
```
diff --git a/automated_install.sh b/automated_install.sh
index 8a36829..376308c 100644
--- a/automated_install.sh
+++ b/automated_install.sh
@@ -558,8 +558,8 @@ mkdir $External_Loc/resources
 
 cp $Kitt_Ai_Loc/snowboy/include/snowboy-detect.h $External_Loc/include/snowboy-detect.h
 cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/portaudio.h $External_Loc/include/portaudio.h
-cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
-cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_util.h $External_Loc/include/pa_util.h
+cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/src/common/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
+cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/src/common/pa_util.h $External_Loc/include/pa_util.h
 cp $Kitt_Ai_Loc/snowboy/lib/$OS/libsnowboy-detect.a $External_Loc/lib/libsnowboy-detect.a
 cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/lib/libportaudio.a $External_Loc/lib/libportaudio.a
 cp $Kitt_Ai_Loc/snowboy/resources/common.res $External_Loc/resources/common.res
```

Also, another patch file for `portaudio` is missing, so just add [portaudio.patch](https://raw.githubusercontent.com/Kitt-AI/snowboy/10b53585407061ab72886a2c5b8542edc02364dc/examples/C%2B%2B/patches/portaudio.patch) to `alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/patches/`

**Comment by houtianze** [comment]
I think `automated_install.sh` needs to be updated according to the previous post.

**Comment by PeterGMat** [comment]
OK - for a complete Newbie - how do I use these patches - do I add them the the script file or run them in a terminal session or what ???

**Comment by helladarion** [comment]
Hi @PeterGMat, 

I made a simple script that might do the trick, I'm testing it right now.
I made a fresh install of the raspbian-jessie-2017-03-02 
clone the git from alexa with 

inside the directory alexa-avs-sample-app run the following:

`sed -i "s_git clone https://github.com/Kitt-AI/snowboy.git_&\n\necho '========== Getting patch for Kitt-Ai ==========='\nmkdir -p snowboy/examples/C++/patches/ \&\& cd snowboy/examples/C++/patches/\nwget https://raw.githubusercontent.com/Kitt-AI/snowboy/10b53585407061ab72886a2c5b8542edc02364dc/examples/C%2B%2B/patches/portaudio.patch_" automated_install.sh`

This command is going to include the path for the snowboy inside the automated_install.sh

**Comment by theghostofelvis** [comment]
automated_install.sh :
I edited directly the file automated_install.sh and changed the 2 lines

 portaudio.patch:
make a sudo nano portaudio.patch and copy the code from the link into the file. copy the file to 
alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/patches/
it could be that You have to create the patches directory ! . Give the right user and rights! ( user pi and executable)

I have to make these steps also to get it work :

sudo apt-get install python-pyaudio python3-pyaudio sox

and  change .asoundrc  to this ( .asoundrc  is found in homedir of pi)

pcm.!default
{
  type asym
  playback.pcm {
    type hw
    card 0
    device 0
  }
  capture.pcm {
    type plug
    slave {
      pcm {
        type hw
        card 1
        device 0
      }
    }
  }
}


wakeword is working now for me with sensory!
cd ~/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e sensory

**Comment by theghostofelvis** [comment]
I edited directly the file automated_install.sh and changed the 2 lines ( - means delete these 2 line and + insert these 2 instead!

-cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
-cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_util.h $External_Loc/include/pa_util.h
+cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/src/common/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
+cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/src/common/pa_util.h $External_Loc/include/pa_util.h

**Comment by yu207** [comment]
What I did was to go to:
/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/common
copy all the .h files you need to make the wakeWordAgent (for me these were pa_ringbuffer.h and pa_util.h) to:
alexa-avs-sample-app/samples/wakeWordAgent/ext/include
and then go back to:
alexa-avs-sample-app/samples/wakeWordAgent/src
to run make.

**Comment by machinista** [comment]
@yu207 your fix is good - thanks.

**Comment by KilrBe3** [comment]
@yu207 What is, 'to run make' ? Understood all til that.

**Comment by PeterGMat** [comment]
I have tried all of the above and nothing seems to solve the problem for me. In looking at the terminal during the execution of the automated_install script it seems that there is one file missing that trips it up - that is wiringPi.h 
I think if I can get that it may work - can anyone tell me where to get it ?
Thanks

**Comment by theghostofelvis** [comment]
try 
sudo apt-get install wiringpi

**Comment by PeterGMat** [comment]
Thank you Elvis - that seems to have sorted it - should WiringPi be in the default Jessie download or is it part of the automated install 
Anyway it is now all working - now to trash my old radio alarm clock and install the Pi
Thanks again

**Comment by yoyo7373** [comment]
@theghostofelvis when you edited those 2 lines where were they in automated_install.sh? I've basically tried every solution in this post and I'm using raspbian stretch.

**Comment by simonpfrank** [comment]
I have the same problem on stretch but on a Raspberry Pi 2. there seems to be mixed errors in this thread so mine are 
MakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have tried the solutions from @theghostofelvis and @yu207 which don't fix it, is this a Stretch issue as Jessie seems to be OK ?

Tried the solution from @ljishen and @helladarion but same problem.
