### ISSUE TITLE
Changing location values in automated_install

### ISSUE THREAD

**Issue by al0al0al0** [alexa/alexa-avs-sample-app#331]
I have a running avs prototype on raspberry pi 3, but I now want to change the timezone/country to one which is not supported currently + has not been announced to be supported in near future like some github issues I've seen.

Are there any complications on changing _Country_, _State_ and _City_ values in [automated_install.sh](https://github.com/alexa/alexa-avs-sample-app/blob/master/automated_install.sh) and running the script on an already working prototype? Will this help change the device location?

Thanks.

**Comment by sunnysharma03** [comment]
http://www.geeklee.co.uk/update-time-zone-on-raspberry-pi-with-raspbian/
This might work !

**Comment by al0al0al0** [comment]
The time zone on the pi 3 was updated before avs was installed. The alexa device location still shows US in the amazon alexa app. Because of this if we ask Alexa what time it is, the response is US time. There is no provision to change country in the amazon alexa app. The only other place I've found a country field is in the automated_install.sh file.

**Comment by fraser73** [comment]
To change your Alexa's locale, logon to alexa.amazon.co.uk (from memory) and go to settings, select your alexa (if you've got more than one) and edit your device location. I've done it and mine now thinks it's in the UK.

**Comment by al0al0al0** [comment]
Changing via app is restricted to us/uk and coming soon to a couple of countries. I want a way to change it another country which doesnot have alexa app

**Comment by keleric** [comment]
- That will not change the location. Those are just values that are bundled into the certificate creation.
- Why do you want to change the location to somewhere that isn't supported?

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Dec 1st. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
