### ISSUE TITLE
-Dmaven.multiModuleProjectDirectory system property is not set. 

### ISSUE THREAD

**Issue by ambrosechoy** [alexa/alexa-avs-sample-app#332]
Check $M2_HOME environment variable and mvn script match.

Hi all,

Has anyone come across this issue on Raspberry Pi 3 installation? If so, any clues as to how I could fix it? 

I've tried this already: 
sudoedit /etc/profile.d/maven.sh

and made sure the paths were there:
export M2_HOME=/opt/apache-maven-3.2.5
export PATH=$PATH:$M2_HOME/bin

Any ideas?

Thanks,
Ambrose

**Comment by sjrydz** [comment]
@ambrosechoy 
Are you sure the version of maven is 3.2.5? The version I installed just a few days ago is 3.2.9.

**Comment by ambrosechoy** [comment]
@srydz my bad, you're right, it is 3.2.9 that I have installed. It's just typo when I entered it here

**Comment by sjrydz** [comment]
@ambrosechoy 
One typo deserves another. I should have said 3.3.9 not 3.2.9 :-)

**Comment by ambrosechoy** [comment]
@sjrydz haha, oops! Any idea how I could fix it tho?

**Comment by sjrydz** [comment]
@ambrosechoy 
Check the ".bashrc" file in your home directory and make sure you have the following entries (if not add them at the end):
export M2_HOME=/opt/apache-maven-3.3.9
export M2= $M2_HOME/bin
export PATH=$M2:$PATH

**Comment by ambrosechoy** [comment]
@sjrydz thanks for the suggestion, still didn't work though :(

**Comment by sjrydz** [comment]
@ambrosechoy 
Another thing to check. 
/etc/profile.d/maven.sh should have the following entries:
export M2_HOME=/opt/apache-maven-3.3.9
export PATH=$PATH:$M2_HOME/bin

**Comment by ambrosechoy** [comment]
@sjrydz Yup, just checked, that's all in there already...

**Comment by robmseibert** [comment]
Try using sudo to run mvn

**Comment by ambrosechoy** [comment]
@robmseibert Great, that worked! Although I've hit a build failure issue instead but at least sudo man got past this issue! Thanks :)

**Comment by bg3maker** [comment]
ambrosechoy - how did you get past the build failure issue after running sudo mvn exec:exec
