### ISSUE TITLE
Not able to change location and Time 

### ISSUE THREAD

**Issue by sunnysharma03** [alexa/alexa-avs-sample-app#337]
My device is working fine but I'm not able to get local information and time is also not corrected, I've try to change my developer account timezone and location but even though It's not working.

**Comment by mdnegan** [comment]
know you likely tried this,but did you try changing the lines in the automated_install.sh file ?

**Comment by RoboticsHobbyist** [comment]
Hi, I had the same issue here. For 2-3 days I kept going over everything. Turns out that the one setting I missed is actually set by using the Amazon Alexa app for my Android phone.

One I installed the app, I found the setting under settings then device localization. This solved the issue for me. Hope it helps.

**Comment by b33rgit** [comment]
Are you in the U.K.? I bet uve got the same issue as me (see 343). My device initially showed online but as soon as I updated the location it started showing offline in Alexa. I've narrowed it down to something to do with the apps and services changing on Amazon but can't resolve it

**Comment by Pernat1y** [comment]
Have the same issue.
Also, i don't see, where this variable somehow used:

```
root@rpi2deb:~/alexa-avs-sample-app# grep -e Country -e State -e City automated_install.sh
# Your Country. Must be 2 characters!
Country='UA'
State='Kiev'
City='Kiev'
root@rpi2deb:~/alexa-avs-sample-app#
```

**Comment by sunnysharma03** [comment]
The amazon Alexa app is not available in my region and when I got the app from other sources, the app is not responding

**Comment by mdnegan** [comment]
have you ,,,tried cough,vpn

**Comment by sunnysharma03** [comment]
@mdnegan sorry I am not familiar with these words can you elaborate it ? Thanks

**Comment by sunnysharma03** [comment]
I got the answer actually Alexa is not in my country even if You change install.sh file values it won't work. You can change your device location by using this link , if it is working in your country then you will be able to change your location
http://alexa.amazon.com/spa/index.html
