### ISSUE TITLE
Javaclientsetup step build failure

### ISSUE THREAD

**Issue by frerkb** [alexa/alexa-avs-sample-app#339]
Hi, after having the project installed and the webservice is running properly, I am getting the error as shown in the screendump. It seems that something is wrong with my java or maven or whatever. I am running ubuntu mate 16.04 on a rpi3. Can anyone please help with this? Thanks in advance!
![bildschirmfoto 2016-10-20 um 00 03 37](https://cloud.githubusercontent.com/assets/22946226/19539559/4bd48e32-965a-11e6-9e15-bdae00b383fb.png)

**Comment by stantang986** [comment]
i got same problom, anyone can help

**Comment by frerkb** [comment]
I tried it with raspbian jessi instead of ubuntu and it worked without any issues...
