### ISSUE TITLE
wakeword engine error

### ISSUE THREAD

**Issue by frerkb** [alexa/alexa-avs-sample-app#340]
when installing the project I am getting the error as shown in the screendump. Can someone please have a look and let me know what needs to be done? Thanks! By the way, I am running on ubuntu mate 16.04 on a rpi3.
![bildschirmfoto 2016-10-20 um 00 17 19](https://cloud.githubusercontent.com/assets/22946226/19539650/d108f570-965a-11e6-8a6f-8d08929d20e7.png)

**Comment by Spifey** [comment]
I'm getting this error as well. The project will not build.
![screenshot at 2016-10-20 01_12_34](https://cloud.githubusercontent.com/assets/22950897/19547039/8966d568-9662-11e6-94f1-83085d1352cb.png)

**Comment by irthomasthomas** [comment]
This library is for the pi and debian, there is no ubuntu compatible version yet.
https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/D-dvcGBYMPU

**Comment by irthomasthomas** [comment]
You can try here https://github.com/flooie/AlexaPi/tree/voice-command, but I haven't had much success so far on ubuntu 14.04.

**Comment by frerkb** [comment]
Great, thanks for your feedback. Basically, this means that I have now stopped my private Alexa project. Currently, I am not really motivated to set up debian and to migrate everything from ubuntu. Maybe, ubuntu support will be added in the future - or I will be glad to get one of the echo devices that Amazon is offering to chosen people in Germany...

**Comment by Spifey** [comment]
Thank you irthomasthomas, I switched over to raspbian and now everything works perfectly. I do hope that it will support ubuntu in the near future.

Frerkb, Thank you for all the time you put into this project. I am enjoying this very much. I am going to be  working on a way to automate the process without having to click on anything. Again thanks frerkb!

**Comment by frerkb** [comment]
@Spifey Thanks for your feedback. After I had read your comment, I was so motivated that I took a spare SD card and installed raspbian jessi - and as you said it worked without any issues. As you said. Thanks for that!
