### ISSUE TITLE
Location and amazon apps and services issue

### ISSUE THREAD

**Issue by b33rgit** [alexa/alexa-avs-sample-app#343]
Hi,

I'm in the UK and I've got this all set up and working on my Pi but having a problem to do with the localisation.

I've updated all the settings in the automated_install.sh script to a GB address but the default Seattle address must be set somewhere else too as after setting up the device has the 98109 zip code in the alexa dashboard on the website and the app. If I update it to a UK/GB address my whole amazon account switches to the UK apps and services and then the device disappears from the apps and service on amazon.com and isn't there on the UK apps and services dashboard on amazon.co.uk. alexa.amazon.com also then automatically re-directs to alexa.amazon.co.uk on signing in but the device isn't listed so I can't install skills etc.

I've tried as many permutations as I can think of, starting off with the Pi in the US by leaving the automated install file as US and then updating later, starting out with my amazon account and services already set to UK (then it never appears) and non work to get the pi set to be in the UK and that i would have access to it from alexa.amazon.\* and in the app so I'm a bit stuck. This is stopping me being able to install the UK skills and set any localisation to get the correct time/weather etc.

For now im just leaving it as if i am in the US but would like to fix it eventually. Does anyone know anywhere else in the installation/configuration where localisation is set (I've searched and can't find anywhere) or any other suggestions on the order to set it up?

Many thanks!

**Comment by RoboticsHobbyist** [comment]
Hi, I had the same issue here in the US.  For 2-3 days I kept going over everything.  Turns out that the one setting I missed is actually set by using the Amazon Alexa app for my Android phone. 

One I installed the app, I found the setting under settings then device localization.  This solved the issue for me.  Hope it helps.

**Comment by b33rgit** [comment]
Yep I can see that exact setting but if I change it to a UK one my apps and services on Amazon.com switches to the UK one but the device never reappears in devices on the Amazon.co.uk apps and services and the device shows offline in the Alexa app on my phone and in the browser (which auto redirects to .co.uk on sign in)

**Comment by fredfree** [comment]
I'm based in the UK as well and have this exact issue. I've poured over everything in this code, the app, etc... It seems that it might be related to the API version used in this build. Can anyone confirm if this code is based on API version 1 or 2? I believe Version 2 should have this resolved from the other builds I've seen.

Anyone have any advice on how to get passed this problem plse? I can speak with Alexa but can't run any services / skills so at this point pretty pointless and we can't progress in testing a commercial product as a result for our devices. 

Much appreciated.

**Comment by chillaks83** [comment]
I had similar issue. I installed an older version of Alexa app (2 versions before) and it works like a charm on android now

**Comment by keleric** [comment]
AVS has not officially launched in the UK yet. Please try again sometime early next year when we roll out UK and DE support!
