### ISSUE TITLE
Error with mvn exec:exec

### ISSUE THREAD

**Issue by mahim1245** [alexa/alexa-avs-sample-app#345]
Hi,

I am arriving at terminal window 2 and having trouble when entering in "mvn exec:exec"

Here is the output:

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/pi/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/pi/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/pi/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/pi/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/pi/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/pi/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/pi/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/pi/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/home/pi/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

```
at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:240)
at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:138)
at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:129)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:106)
at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
```

**Comment by sunnysharma03** [comment]
Hi @mahim1245  I too got the same problem , you just need to install the vlc 
Follow these commands :

Get VLC media player by typing:

sudo apt-get install vlc-nox vlc-data

Unable to fetch errors If you run into some "Unable to fetch" errors while trying to install VLC, try the following:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install vlc-nox vlc-data

NOTE: Running sudo apt-get upgrade might take a while. Grab a snack!


Make sure VLC is installed correctly

Type the following into the terminal:

whereis vlc
This will provide you with the installation path.

Most programs are stored in /usr/bin. On my Pi, I see:

vlc: /usr/bin/vlc /usr/lib/vlc /usr/share/vlc /usr/share/man/man1/vlc.1.gz
Set the environment variables for VLC

Type the following into the terminal:

export LD_LIBRARY_PATH=/usr/lib/vlc
export VLC_PLUGIN_PATH=/usr/lib/vlc/plugins
Check if the environment variables were set successfully

echo $LD_LIBRARY_PATH
> /usr/lib/vlc

echo $VLC_PLUGIN_PATH
> /usr/lib/vlc/plugins

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by koolkarni** [comment]
~/Desktop/alexa-avs-sample-app/samples/javaclient$ echo $LD_LIBRARY_PATH
/usr/lib/vlc

~/Desktop/alexa-avs-sample-app/samples/javaclient$ echo $VLC_PLUGIN_PATH
/usr/lib/vlc/plugins



Still I am getting 

Desktop/alexa-avs-sample-app/samples/javaclient$ mvn exec:exec 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path ([file:/home/nik/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/nik/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar, file:/home/nik/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/nik/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/nik/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/nik/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/nik/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/nik/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/nik/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/nik/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/nik/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/home/nik/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/nik/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/nik/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:248)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:141)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:171)
	at com.amazon.alexa.avs.App.<init>(App.java:65)
	at com.amazon.alexa.avs.App.<init>(App.java:53)
	at com.amazon.alexa.avs.App.main(App.java:48)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.670 s
[INFO] Finished at: 2017-04-27T00:37:34Z
[INFO] Final Memory: 11M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lvan-jone** [comment]
@sunnysharma03  @ajot   @mahim1245 Hello, my mac system, and the landlord encountered the same problem, how to solve.
I do according to the instructions, the following is my configuration, @sunnysharma03 said the order I can not be implemented, the system may not be the same bars.

LvandeMacBook-Pro:bin lvan$ echo $VLC_PLUGIN_PATH
/Applications/VLC.app/Contents/MacOS/plugins
LvandeMacBook-Pro:bin lvan$ echo $VLC_PATH
/Applications/VLC.app/Contents/MacOS/lib


More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:248)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:141)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:171)
	at com.amazon.alexa.avs.App.<init>(App.java:65)
	at com.amazon.alexa.avs.App.<init>(App.java:53)
	at com.amazon.alexa.avs.App.main(App.java:48)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.756 s
[INFO] Finished at: 2017-05-07T12:42:50+08:00
[INFO] Final Memory: 11M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
LvandeMacBook-Pro:javaclient lvan$ sudo apt-get install vlc-nox vlc-data
Password:
sudo: apt-get: command not found
LvandeMacBook-Pro:javaclient lvan$ whereis vlc
LvandeMacBook-Pro:javaclient lvan$ sudo apt-get update
sudo: apt-get: command not found
LvandeMacBook-Pro:javaclient lvan$ sudo apt-get upgrade
sudo: apt-get: command not found
LvandeMacBook-Pro:javaclient lvan$ sudo apt-get install vlc-nox vlc-data
sudo: apt-get: command not found
