### ISSUE TITLE
App works on Emulator but not on actual Android phone

### ISSUE THREAD

**Issue by kananin** [alexa/alexa-avs-sample-app#346]
Is it possible to run this app on my actual android phone. It works fine on simulator. It just fails on actual android device. 
I am able to get the screen which asks for device address and gives connect button. However it refuses connnection for https://10.0.2.2:8443 -- > failed to connect connection failed:ETimedout

I entered my phones ip address in ssl file. I tried to use https://10.0.0.xxx:8443 still 
failed to connect

Any help ?

Thanks,
Nisha

**Comment by keleric** [comment]
10.0.2.2 means "localhost" for the Android emulator. You need to give the IP address of the Raspberry Pi.

**Comment by keleric** [comment]
Please close the issue if this solves your problem.

**Comment by kananin** [comment]
Thank you for getting back. I am using android phone, what ip do I need to give? I have my android (moto g) connected to my laptop via USB and set to developer mode, I am trying to run the app from Android studio using my actual phone as the device to test it. I am not sure which ip I need to give and where can I find that ip.

Any help is highly appreciated!

**Comment by keleric** [comment]
Run this on the Pi: ifconfig wlan0 | grep inet

**Comment by kananin** [comment]
Thank you again. I will try this and update the status here

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Dec 1st. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
