### ISSUE TITLE
Raspberry Pi Alexa always shown as offline

### ISSUE THREAD

**Issue by DawningDeath** [alexa/alexa-avs-sample-app#349]
I created my Raspberry Pi Alexa some days ago, but no matter what I try it shows as 'offline' in the app and website. I'm located in Germany, and assumed it might just not work before the product launch here - but now alexa.amazon.de is live and the German app as well, and first users report to have the German Echo running - but my RaspPi Alexa still shows 'offline'. It seems due to this quite a few of the skills and voice actions just won't work. I verified my Amazon account is in Germany, as well as the Android account (for the Alexa app). I redid the voice service install after changing the install script to Germany, but my Alexa always shows as offline, no matter what I do.
The RaspPi Alexa works in general fine (wakeword, voice recognition, answering) just many of the regular features seem off. Any help is really appreciated!

**Comment by markbeee** [comment]
Non-Amazon devices always show as offline (except for Cowatch) as far as I saw with all my devices. German language is only available to some developers to test skills and as far as I can guess it will not be available on non-Amazon devices with the official start of german Amazon Echo.

**Comment by DawningDeath** [comment]
Okay, this explains a lot ;-) So basically I might just have to wait even longer for German :-/

Thanks!

**Comment by umarwazir** [comment]
I am in the UK, and my homebrew device is also shown as offline...

**Comment by mrtheduke** [comment]
Doesn't work with the U.K. Version of the app, but if you seek out the apk for the US version, that works (the latest version doesn't but the penultimate one does)

**Comment by keleric** [comment]
AVS has not yet launched internationally. After the official launch, the UK and DE should show up as online (assuming your AVS client was coded correctly)

**Comment by OllieGup** [comment]
Hey guys.
This is just the post I've been looking for.
I installed alexa on the pi recently and it worked fine using the wake word.
Since I restated my pi I don't know how to restart the alexa service.  Does anyone know???

**Comment by keleric** [comment]
Run the companion service: cd companionService && npm start
Run the AVS Java Client: cd javaclient && mvn exec:exec
Run the wake word agent: cd wakeWordAgent/src && ./wakeWordAgent -e <engine_type>
    where engine type option is one of the following: kitt_ai or sensory

**Comment by OllieGup** [comment]
You're the man!
Cheers

**Comment by pieman123** [comment]
its because the alexa service on pi is running through the US servers not UK. Im having this issue myself. If you log into amazon.com alexa website the device shows up and is ONLINE

**Comment by faisalch** [comment]
was running on UK site, changed to US Amazon site and now shows online

**Comment by OllieGup** [comment]
How exactly do I change this?
