### ISSUE TITLE
AVS and Sample App Communication Step Issue

### ISSUE THREAD

**Issue by nbibin001** [alexa/alexa-avs-sample-app#350]
Hello,

```
I am trying to follow the process to setup alexa on my Raspberry Pi 3. I think I am running into an issue in Step 7
where we are trying to run the sample App to communicate with AVS. So here is what I was trying

On Terminal window 2 gave the below 2 commands
cd ~/Desktop/alexa-avs-sample-app/samples
cd javaclient && mvn exec:exec
Clicked "Yes" on the popup, it opened up the Amazon login page on the browser, I entered my Amazon account credentials, it went to the next page
where it showed "When you click Okay we'll provide Alexa Voice Service Sample App Security Profile" . So I clicked "Okay" there. And then it went to
an error page as shown below. Not sure why this is happening. I think it took my Amazon login properly. Could you please suggest ? Appreciate your help. 
```

![amazon_login](https://cloud.githubusercontent.com/assets/15659590/19752769/c8560bde-9bcd-11e6-803c-152c97e04bfe.PNG)

**Comment by umarwazir** [comment]
I have the same problem. Is there a solution? Is this a server-side issue?

**Comment by michaelkhan3** [comment]
I also have the same problem. This guy seems to have solved it #326 but he didn't explain how. Hopefully someone else can

**Comment by michaelkhan3** [comment]
Also have a look at #185. I think I have the product id set correctly but I must check again.
If you look at the image below, the Product id is actually the Device Type ID you chose not the Security Profile ID 
![image](https://cloud.githubusercontent.com/assets/4420471/19788301/5d99ce20-9c9f-11e6-906f-56212b47d434.png)

**Comment by foozilla** [comment]
I was having the same problem and was able to correct it after seeing the pic @michaelkhan3 posted. ProductID should be set to the **Device Type ID** listed on the **Device Type Info** tab. After correcting that in automated_install.sh, I ran ./automated_install.sh again and was able to auth the pi. The Alexa client is now up and running.

**Comment by umarwazir** [comment]
I got it to work. My mistake was pretty boneheaded: was writing http:// rather that https://
The device is ok. Feels nice to get it working, but is a bit deaf (cheap microphone, I suppose). Also, not very smart ( says sorry a lot). Finally, can't get it to work with the Alexa app, or otherwise update its location info.
Still, it was fun to make.

**Comment by umarwazir** [comment]
Dude, this NLP AI is as smart as a paste-eating art student...

**Comment by michaelkhan3** [comment]
@umarwazir If you are looking for a better microphone try getting a used Playstation 3 eye camera. It has  a 4 microphone array which is much better at detecting your voice from other noise then normal microphones.

**Comment by umarwazir** [comment]
Thanks Michael! It looks great, especially for six quid!

**Comment by ajotwani** [comment]
Closing as resolved.
