### ISSUE TITLE
SSL.cnf not in openssl folder

### ISSUE THREAD

**Issue by varunm100** [alexa/alexa-avs-sample-app#352]
I downloaded Win64 OpenSSL v1.1.0b on my 64-bit pc in the link given but after installation I could not find the ssl.cnf file.

**Comment by varunm100** [comment]
Any help is helpful thanks :)

**Comment by RaphaelStArnaud** [comment]
The ssl.cnf refered by the Alexa instructions is in the alexa-avs-sample-app\samples\javaclient

**Comment by varunm100** [comment]
OHHHHHH

On Thu, Nov 10, 2016 at 9:01 PM, Raphael St-Arnaud <notifications@github.com

**Comment by ajotwani** [comment]
Closing as resolved.
