### ISSUE TITLE
alexa wakeWordAgent using CPU 100%

### ISSUE THREAD

**Issue by niallmca** [alexa/alexa-avs-sample-app#356]
Is this normal?  seems to be working fine.  everything else using <10% CPU. except wakeWordAgent which is using > 100% CPU

thanks

**Comment by niallmca** [comment]
pi@NestPitouch:/var/www/html/cgi-bin $ top

top - 21:17:19 up 1 day,  3:30,  3 users,  load average: 1.12, 1.23, 1.46
Tasks: 215 total,   1 running, 214 sleeping,   0 stopped,   0 zombie
%Cpu(s): 29.8 us,  1.4 sy,  0.0 ni, 68.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:    947740 total,   888280 used,    59460 free,    71664 buffers
KiB Swap:   102396 total,    15024 used,    87372 free.   352648 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                             
 3081 pi        20   0   54476   8868   6668 S 116.0  0.9   1695:41 wakeWordAgent                                       
 1994 pi        20   0   42940  18028   8784 S   2.0  1.9  27:54.22 Xvnc-core                                           
 2855 pi        20   0  468796  99576  73612 S   1.3 10.5  30:15.05 chromium-browse                                     
  568 root      20   0   29400  12212   7808 S   1.0  1.3  13:55.13 vncserver-x11-c                                     
23769 pi        20   0    5216   2516   2092 R   1.0  0.3   0:00.29 top                                                 
 1298 root      20   0   29112   7684   4204 S   0.7  0.8   8:32.73 wicd                                                
 3157 pi        20   0  321008  87808  47552 S   0.7  9.3  55:39.21 kweb                                                
  450 message+  20   0    5776   3024   2572 S   0.3  0.3   3:42.99 dbus-daemon                                         
 1625 root      20   0   19076  11548   7172 S   0.3  1.2   3:26.48 wicd-monitor                                        
 2723 pi        20   0  122372  30528   8476 S   0.3  3.2   2:38.62 npm                                                 
 2793 pi        20   0  454288  82108  23572 S   0.3  8.7   2:49.11 java                                                
18707 www-data  20   0  113028  11944   7272 S   0.3  1.3   0:00.71 apache2

**Comment by SpartanTech** [comment]
Also curious on to this. Is there a delay we can add somewhere to decrease wake word cpu usage? snowboy advertiess only 14% on their website, yet snowboy uses ~103 with it being used as a framwork. Sensory also uses a lot with run speed around ~130

This is causing audio delays in my pulseaudio output. (Bluetooth and of course analog as well)

**Comment by keleric** [comment]
The wake word agent is currently not the most efficient. For a temporary solution, try adding a sleep for 50 ms on line 69 and recompiling: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/wakeWordAgent/src/WakeWordAgent.cpp#L69

**Comment by alexsalnikov** [comment]
because RPI3 have 4 cores you need to Normalize TOP value by dividing by 4 
116 /4 = 29% CPU usage
http://unix.stackexchange.com/questions/146085/top-command-on-multi-core-processor

**Comment by niallmca** [comment]
Right: I noticed also on the desktop the CPU load is < 30%.
So 'top' was just showing  1 of 4 CPUs.

Many thanks for clarifying..!
