### ISSUE TITLE
 (Raspberry Pi) -- no compiler provided in this environment -- mvn exec:exec 

### ISSUE THREAD

**Issue by Corkskru** [alexa/alexa-avs-sample-app#357]
Hi,

I am following the steps to setup the AVS on my Nano Pi Neo. However, I get the error saying "no compiler is provided in this environment. Perhaps you are running on?" when I type in "cd javaclient && mvn exec:exec".
I have set  the java_home variables in bashrc. 
Any help appreciated

**Comment by alexsalnikov** [comment]
from automated_install.sh
This code base is dependent on several external libraries and virtual environments like Kitt-Ai, Sensory, ALSA, Atlas, Portaudio, VLC, NodeJS, npm, Oracle JDK, OpenSSL, Maven & CMake
i guess you will need to update your Nano Pi Neo linux version and be sure to install GCC and Make toolchains, then you will need to modify automated_install.sh so it will install all other dependencies 
for maven and etc see if wakeWordAgent c++ code could be compiled bc some of code comes precompiled for ARMv7 Instruction set of Raspberry PI 3

**Comment by keleric** [comment]
Unfortunately, the sample app is not officially supported on the Nano Pi Neo. You may be able to get it working, but we're unlikely to be able to help. Sorry, and good luck!
