### ISSUE TITLE
mvn exec:exec ERROR

### ISSUE THREAD

**Issue by MagiCats** [alexa/alexa-avs-sample-app#358]
When I do:
cd javaclient && mvn exec:exec I get:
-Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script match.
How do I fix this so Alexa will work?

**Comment by MagiCats** [comment]
Never Mind I found an older post telling me how to solve the issue.

**Comment by the100guy** [comment]
can you link the older post please?
