### ISSUE TITLE
Need instructions for doing this with JBL Flip 2

### ISSUE THREAD

**Issue by thecoffeehog** [alexa/alexa-avs-sample-app#359]
Hi, can we somehow use a bluetooth speaker with mic to do this? Any instructions will be great.

**Comment by keleric** [comment]
You might need to modify how the sample app get microphone data (AudioCapture.java) and how it plays data (through Raspbian). You'll also need a bluetooth dongle, since Raspberry Pi does not come with native bluetooth.
