### ISSUE TITLE
Multiple Alexa Pis?

### ISSUE THREAD

**Issue by rgruskin** [alexa/alexa-avs-sample-app#360]
Does anyone know if it is possible to have multiple Pis to be setup with this Alexa App on the same developer account and same network?  I want to put a few of these around my house.  

I seem to have issues with this but haven't fully debugged it yet.  I wanted to ask before I put too much effort in.  If possible, can you let me know what the procedure is for this?

Thanks.

**Comment by keleric** [comment]
Very possible. Just change the DSN on each one so that each raspberry pi is a unique device.
