### ISSUE TITLE
 An error occurred when we tried to process.

### ISSUE THREAD

**Issue by chinmoyrick** [alexa/alexa-avs-sample-app#365]
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Run the companion service: 
cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start
Run the AVS Java Client:
 cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
Run the wake word agent:
 cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e <engine_type>
    

where engine type option is one of the following: kitt_ai or sensory##335

**In this part I face an error..**
You'll be taken to a Dev Authorization page, confirming that you’d like your device to access the Security Profile created earlier.
**Click Okay.**

You will now be redirected to a URL beginning with https://localhost:3000/authresponse followed by a query string. The body of the web page will say device tokens ready.
  
**In my Case..
na.account.amazon.com**
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

**Comment by elstryan** [comment]
Which mechanism are you using to authenticate? Is the node service? 

Have you gone through the steps here: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#6a---nodejs

Generally what this error means is there is a mismatch between your config file and the product information defined under developer.amazon.com. Specifically you should verify that the productId in your config.json matches the ID on developer.amazon.com.

Additionally here's a similar thread with some useful steps to try #350

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 7 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by automationdanny** [comment]
I'm having the same issue.

**Comment by automationdanny** [comment]
How do I correct this? Need steps.
