### ISSUE TITLE
change annoying prompt sound

### ISSUE THREAD

**Issue by thaihenry** [alexa/alexa-avs-sample-app#374]
Have everything working ok, very happy, except for the overly loud beep sound after the wake work and response.

anyone know where in the code I can change the sound being used each time after the wake word.

Thank you in advance.

**Comment by kelliott121** [comment]
I believe the sounds are sourced from /samples/javaclient/src/main/resources/res/*.  Changing start.mp3 and stop.mp3 to whatever sound files you want to use should work.

**Comment by thaihenry** [comment]
Thank you so much  will try that.

**Comment by thaihenry** [comment]
Unfortunately that did not work.   changed the sounds and rebooted.  Looked for system sounds but I could not find any that matched the same sound.

**Comment by thaihenry** [comment]
I had more time to look at this.  When you install the software and run it for the first time.  the mp3 files are copied to the  /samples/javaclient/target/classes/res/*.

those are the ones that need to be changed
