### ISSUE TITLE
Sensory wake word agent not loading! Illegal command

### ISSUE THREAD

**Issue by Luke19** [alexa/alexa-avs-sample-app#375]
When I use the command cd wakeWordAgent/src && ./wakeWordAgent -e sensory (after cd into desktop of course) on my raspberry pi I get this output...

INFO:main: Starting Wake Word Agent INFO:WakeWordAgent: State set to IDLE(2) INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.1 | model file: ../ext/resources/spot-alexa-rpi.snsr 
Illegal instruction

Anyone know why or a step by step on how to fix it? Would be very appreciated thank you ☺

**Comment by alexsalnikov** [comment]
from your log wakeWordAgent have some issues to load alexa recognition model "spot-alexa-rpi.snsr"
you can copy one of the models from
wakeWordAgent\sensory\alexa-rpi\models
   spot-alexa-rpi-20500.snsr
   spot-alexa-rpi-21000.snsr
  spot-alexa-rpi-31000.snsr
and rename to spot-alexa-rpi.snsr

**Comment by Luke19** [comment]
Thanks for the reply

Copy it to where exactly? I just renamed one of those files and it didn't work

**Comment by alexsalnikov** [comment]
under samples\wakeWordAgent\ext\resources
you should have spot-alexa-rpi.snsr file that used in sensory wakeworld engine to recognize Alexa world
when you run automated_install.sh it's pulls out all source code from sensory github with 3 models 
so you can choose one from under wakeWordAgent\sensory\alexa-rpi\models
copy it to samples\wakeWordAgent\ext\resources and rename to spot-alexa-rpi.snsr

**Comment by Luke19** [comment]
So I have to overwrite the one that is already there?

**Comment by alexsalnikov** [comment]
Yes, you overwrite the one you have there with clean trigger model from
sensory repo

**Comment by Luke19** [comment]
Didn't work, should I try one of the other models?

**Comment by alexsalnikov** [comment]
try to install fresh raspbian linux on other sd card make update to latest version and then clone alexa sample and run automated_install.sh

**Comment by Luke19** [comment]
Okay I'll try that, should I do the same again with regards to copying one of the models across again?

**Comment by alexsalnikov** [comment]
no really, automated_install.sh should do everything

**Comment by goodpunk6** [comment]
I hope it works.

**Comment by Luke19** [comment]
well it failed again, i have recompiled it onto a brand new SD card and i still get the same output as last time

**Comment by Luke19** [comment]
On the other hand the kitt_ai begins to start up then suddenly says shutting down wake word agent? i know thats still bad but it's better than before so something has changed!

**Comment by alexsalnikov** [comment]
Do you run apps in terminal windows in this order ?
1 - companionService with npm start
2 - javaclient with mvn exec:exec
3 - wakeWordAgent with ./wakeWordAgent -e sensory &

**Comment by Luke19** [comment]
Yes they all ran in that order
I think it may have been due to the fact the java client wasn't working properly, I will attempt again tomorrow

**Comment by Luke19** [comment]
IT FINALLY WORKS! thanks for all your help guys 👍

**Comment by goodpunk6** [comment]
What did you do to fix it??

**Comment by Luke19** [comment]
Just did a fresh install on a new SD card and used the kitt_ai wake word agent instead
If it helps, what I did differently is:
Downloaded the other NOOBS on the raspberry pi website ( https://www.raspberrypi.org/downloads/noobs/ ) and also make sure you update it before you begin cloning the alexa voice service

**Comment by Volthaus** [comment]
Hi guys. I'm in the same boat here. /wakeWordAgent -e sensory (command not found) Libraries are there but not what I need of course. Question for Luke19: You went into Snowboy directory? What was your path from there? Could you elaborate on your fix please? Ths seems to be a common issue and if you have the resolution you deserve a tip of the wizard hat my friend. So can ya help a brother out?

**Comment by Luke19** [comment]
All I did was get a brand new 8GB SD card and downloaded the latest version of noobs onto it from the website on my laptop, I then put it into my pi and selected rasbian Jessie to download.

I then updated to the latest software using sudo apt get update. It then asked me about downloading something else as well which i just selected the default (i think it was yes but it tells you) i then went on to install amazon alexa onto my raspberry pi as it shows in the step by step guide

I then selected the kitt_ai instead of the sensory wakeword and it works and ive never encounter any problems since 

Make sure all terminals are working correctly (dont worry about the error sign on the first terminal) and before starting the wake word terminal press listen on the java script (that appears once youve got your tokens) just to check alexa is working (say something simple like hi just for a response) 
Try a few times cause sometimes it doesnt work on the first try.
If it doesnt work after a few tries turn it off and try again tomorrow

When it does work then set up the wake word kitt_ai

**Comment by Luke19** [comment]
Thats all i did, it may not help at all but thats all ive done

It might be worth going into ls of the alexa documemts to check youve got the 'wakewordagent' in green at the bottom

**Comment by Luke19** [comment]
Hope this helps and good luck ahah

**Comment by cnapmak** [comment]
Had the same issue were the wakeWordAgent will not start so I read somewhere that it's the latest version of rabsbian that's causing these issues. So I downloaded the image file from a version thats 6 mothns old on to my raspberry  and both wakeWordAgents work perfectly on two separate raspberries. I did not update Raspbian.

**Comment by orobsonpires** [comment]
I got the same problem. Is there any other solution despite to use an old image version of Raspbian?
