### ISSUE TITLE
Need Sudo su?

### ISSUE THREAD

**Issue by morejava** [alexa/alexa-avs-sample-app#376]
Do I need sudo su before executing....

cd ~/Desktop/alexa-avs-sample-app
. automated_install.sh

???????

**Comment by antanisblinda** [comment]
yes. it will install a bunch of stuff too so you need root/sudo access to use apt.
from my experience, the companionapp command and the javaclient command require sudo as well (on a raspbian). The wakewordagent can run under "pi"

**Comment by keleric** [comment]
No, don't do sudo su. The automated install script will prompt you for sudo automatically as part of running it.
