### ISSUE TITLE
Sensory Word Wake limit

### ISSUE THREAD

**Issue by ajkatz83** [alexa/alexa-avs-sample-app#377]
I think I may have read in the license that Sensory was only a shareware program and could only be used so many times. I ask because I can only give the AVS so many commands before I look back onto my Pi that is running the AVS and I check the word wake engine and see that it says "iteration exceeded" or something to that effect--I'll have to check out the actual message when I get back--but in case anyone has seen something to that effect, I take it one can only use some many commands before the shareware is exceeded or is there a way around this?

**Comment by RaspiRepo** [comment]
This Sensory library allows 120 days and then need to download updated library as per sensory folder ReadMe file,
