### ISSUE TITLE
wakeword not installing

### ISSUE THREAD

**Issue by gingermcninja** [alexa/alexa-avs-sample-app#378]
I ran though the instructions for getting alexa up and running on my Raspberry 3 and after a number of false starts managed to get the java client working. However, my latest problem is that the wakeword engine isn't built. When I tried to make it myself I get the following problem:

```
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ sudo cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ sudo make
Linking CXX executable wakeWordAgent
CMakeFiles/wakeWordAgent.dir/main.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:388: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea how to get this up and running?

**Comment by Hauteknits** [comment]
Re-run the original automated_install.sh, don't exit the window until it says "To start, run these commands in three seperate windows." My install took upwards of an hour.

**Comment by CaptainGingerBeard** [comment]
Yes, I've re-run the install several times but still end up with the same error. Do I need to run the installer as root?

**Comment by morejava** [comment]
Same here... I've run it in root and still get the error for kitt_ai and
sensory

**Comment by alexsalnikov** [comment]
My suggestion will be use new SD card and install last version of Raspbian [https://www.raspberrypi.org/downloads/raspbian/](url)
when you log to terminal of linux run: 
$ sudo apt update
$ sudo apt upgrade
then clone alexa sample app and run install for it with 
$ sudo ./automated_install.sh >install.log
see that install log pass without a problems should get to lines 
========= Finished ==========
and some text after it

**Comment by keleric** [comment]
You should be using the automated_install.sh script, not sudo cmake. There was a linker error when trying to build the wake word binary, but there isn't enough context in these lines to debug it. Try running the automated_install.sh script from a clean checkout and outputting the result to a file. If it's still broken, then that log file will help debug it.

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 28th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!

**Comment by RacingChicken** [comment]
I have the same issue. Whenever I try to install it ito comes out saying this: (see attachment)
![20170129_210742](https://cloud.githubusercontent.com/assets/25406088/22407885/01217082-e667-11e6-802c-0d5a026165bf.jpg)
Please help me really want to get this to work.
Thank you
Jack
