### ISSUE TITLE
Build Failure @sanple -java-client

### ISSUE THREAD

**Issue by normatt** [alexa/alexa-avs-sample-app#383]
Almost got there then I got stuck here. Any help will be appreciated

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.407s
[INFO] Finished at: Fri Sep 23 09:45:41 UTC 2016
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by MadHeretic22** [comment]
Same error here. Help appreciated.

**Comment by CaptainGingerBeard** [comment]
Have you tried running it as root? You can switch to root with the command 'sudo su'

**Comment by ChrisKoh83** [comment]
In my case, I reinstalled everything...

`cd ~/Desktop/alexa-avs-sample-app
. automated_install.sh`

And it works

**Comment by MadHeretic22** [comment]
Same here, works now.

**Comment by normatt** [comment]
Thanks for the input tried and got further but 'no cigar' decided to wipe Raspberry Pi clean do a fresh install of Jessie and then updated it.
I'll see if that makes a difference.

**Comment by normatt** [comment]
Finally got it working on the 5th clean install and I have no idea what I i did differently. Thanks to all for the input
