### ISSUE TITLE
fauxmo

### ISSUE THREAD

**Issue by niallmca** [alexa/alexa-avs-sample-app#386]
Hello, 

Will this work with fauxmo.py ..?
I have it running, but "Alexa, Discover Devices" doesn't discover my 'wemo'
Anyone know if this only works with actual Echo..?

Thanks.
Best regards,
Niall.

**Comment by dnhkng** [comment]
seems like it wont work, see: https://github.com/alexa/alexa-avs-sample-app/issues/162

I also have a fauxmo device, and am now looking into IFTTT

**Comment by niallmca** [comment]
Thanks for confirming my suspicions:)

After quite a few hours I had already given up on fauxmo 
I'm also starting to look at mqtt and Ifttt instead.

Best regards,
Niall

**Comment by niallmca** [comment]
looks like ifttt doesn't work with Alexa outside US :(
Any more ideas?!

Thanks.
Best regards,
Niall.

**Comment by niallmca** [comment]
just got IFTTT working with the browser version of the Alexa skill testing tool https://echosim.io/
But, when I try with my own homebrew Alexa, then I just get "sorry, I don't see that IFTTT trigger"

**Comment by niallmca** [comment]
ok, just got this working with my home-brew Alexa on RPI3.
https://ifttt.com/applets/44876282d-alexa-to-ada-lamp-off
(need to authenticate with IFTTT, and make sure you're using the same Amazon account
as on the Alexa).

I can say "Alexa, trigger the light off" ... and the adafruit button on the dashboard will turn to off.
Now, it's just a matter of a call to a web service to actually turn the light off :)

**Comment by keleric** [comment]
See: https://forums.developer.amazon.com/questions/44118/is-avs-capable-for-smart-home-skill-control.html#answer-45662
