### ISSUE TITLE
No info in regards to running wakeWordEngine in Windows install doc

### ISSUE THREAD

**Issue by mwpreston** [alexa/alexa-avs-sample-app#387]
Anyone fancy letting a guy know how to compile/run this on windows - trying to port all this to an Intel Compute Stick - everything else is working but I can't go on in life clicking 'Listen' :)

**Comment by mwpreston** [comment]
should this even work?  Just don't know how to get the wakewordagent up and going on windows - the rest of it is working perfect

**Comment by keleric** [comment]
The wake word agent does not run on Windows, unfortunately.
