### ISSUE TITLE
Step 7 Terminal 2

### ISSUE THREAD

**Issue by tradewindsre** [alexa/alexa-avs-sample-app#389]
I followed the steps exactly but I get the following at Step 7 Terminal 2:

pi@raspberrypi:~ $ cd /Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exe c:exec
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 2.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 95.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -deploy-plugin/2.7/maven-deploy-plugin-2.7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- deploy-plugin/2.7/maven-deploy-plugin-2.7.pom (6 KB at 59.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -deploy-plugin/2.7/maven-deploy-plugin-2.7.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- deploy-plugin/2.7/maven-deploy-plugin-2.7.jar (27 KB at 170.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -site-plugin/3.0/maven-site-plugin-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- site-plugin/3.0/maven-site-plugin-3.0.pom (20 KB at 181.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -plugins/21/maven-plugins-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- plugins/21/maven-plugins-21.pom (13 KB at 116.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -site-plugin/3.0/maven-site-plugin-3.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- site-plugin/3.0/maven-site-plugin-3.0.jar (112 KB at 428.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (5 KB at 55.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- antrun-plugin/1.3/maven-antrun-plugin-1.3.jar (24 KB at 215.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 KB at 149.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -plugins/16/maven-plugins-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- plugins/16/maven-plugins-16.pom (13 KB at 136.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/ 15/maven-parent-15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/1 5/maven-parent-15.pom (24 KB at 209.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (204 KB at 571.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -dependency-plugin/2.1/maven-dependency-plugin-2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- dependency-plugin/2.1/maven-dependency-plugin-2.1.pom (8 KB at 91.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -dependency-plugin/2.1/maven-dependency-plugin-2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- dependency-plugin/2.1/maven-dependency-plugin-2.1.jar (104 KB at 518.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -release-plugin/2.0/maven-release-plugin-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- release-plugin/2.0/maven-release-plugin-2.0.pom (8 KB at 83.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven -release/2.0/maven-release-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven- release/2.0/maven-release-2.0.pom (7 KB at 66.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/ 16/maven-parent-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/1 6/maven-parent-16.pom (23 KB at 222.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.p om
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.po m (15 KB at 160.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven -release-plugin/2.0/maven-release-plugin-2.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven- release-plugin/2.0/maven-release-plugin-2.0.jar (38 KB at 329.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-p lugin/1.2.1/exec-maven-plugin-1.2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-pl ugin/1.2.1/exec-maven-plugin-1.2.1.pom (8 KB at 82.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/ 28/mojo-parent-28.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/2 8/mojo-parent-28.pom (26 KB at 248.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/3 /codehaus-parent-3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/3/ codehaus-parent-3.pom (5 KB at 48.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-p lugin/1.2.1/exec-maven-plugin-1.2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-pl ugin/1.2.1/exec-maven-plugin-1.2.1.jar (37 KB at 335.8 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolcha in/1.0/maven-toolchain-1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolchai n/1.0/maven-toolchain-1.0.pom (4 KB at 34.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin- api/2.0/maven-plugin-api-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-a pi/2.0/maven-plugin-api-2.0.pom (601 B at 7.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0/mav en-2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0/mave n-2.0.pom (9 KB at 96.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-uti ls/2.0.5/plexus-utils-2.0.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-util s/2.0.5/plexus-utils-2.0.5.pom (4 KB at 38.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/2.0 .6/plexus-2.0.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/2.0. 6/plexus-2.0.6.pom (17 KB at 176.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exe c/1.1/commons-exec-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec /1.1/commons-exec-1.1.pom (11 KB at 115.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-par ent/17/commons-parent-17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-pare nt/17/commons-parent-17.pom (31 KB at 247.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-uti ls/2.0.5/plexus-utils-2.0.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exe c/1.1/commons-exec-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec /1.1/commons-exec-1.1.jar (52 KB at 200.4 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-util s/2.0.5/plexus-utils-2.0.5.jar (218 KB at 759.4 KB/sec)
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which r equires it.
at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:2 04)
at java.awt.Window.(Window.java:536)
at java.awt.Frame.(Frame.java:420)
at java.awt.Frame.(Frame.java:385)
at javax.swing.JFrame.(JFrame.java:189)
at com.amazon.alexa.avs.AVSApp.(AVSApp.java:101)
at com.amazon.alexa.avs.AVSApp.(AVSApp.java:94)
at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.435s
[INFO] Finished at: Thu Nov 24 15:15:33 UTC 2016
[INFO] Final Memory: 8M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (d efault-cli) on project sample-java-client: Command execution failed. Process exi ted with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE xception
pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples/javaclient $ cd
pi@raspberrypi: $ cd /Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
at java.awt.Window.(Window.java:536)
at java.awt.Frame.(Frame.java:420)
at java.awt.Frame.(Frame.java:385)
at javax.swing.JFrame.(JFrame.java:189)
at com.amazon.alexa.avs.AVSApp.(AVSApp.java:101)
at com.amazon.alexa.avs.AVSApp.(AVSApp.java:94)
at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.835s
[INFO] Finished at: Thu Nov 24 15:17:19 UTC 2016
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples/javaclient $ http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
-bash: http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException: No such file or directory
pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples/javaclient $

The step indicated a browser window would open up but it never did.

Any idea what to do?

Thank you in advance!! ,

**Comment by RaspiRepo** [comment]
Looks like you are trying to run Javaclient and everything from remote terminal i.e. ssh from another system ?  To run Alexa Java client need GUI desktop this error "Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which r equires it.
at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:2 04)"

If your raspberry PI not connected with Monitor, please connect it and then check your PI booted with Graphics desktop.   if you don't setup graphics desktop by default you can change this by running
 $raspi-config 
change from cli to graphis UI.

Once you rebooted with UI then you can open terminal application then exactly run all 3 terminal window commands.
In case some thing else let us know.
I had similar issue on RPi2 with remote ssh terminal and then locally (with PI desktop) I can run Alexa success fully

**Comment by tradewindsre** [comment]
That worked!!! Thank you so much!!
