### ISSUE TITLE
Uninstallation instructions

### ISSUE THREAD

**Issue by navigonic** [alexa/alexa-avs-sample-app#392]
Curious, not that I currently want to, but after seeing the script run for a good 45 min I can only speculate towards the system edits. Are there any uninstallation instructions?

**Comment by keleric** [comment]
Not really, though you can look at the install script to see exactly what it's doing. Essentially, it boils down to delete the samples directory, uninstall the dependencies that automated_install.sh installs, and hope that you had ~/.asoundrc backed up, because that's gone forever.
