### ISSUE TITLE
Does the Wake Word Agent work on Windows 10?

### ISSUE THREAD

**Issue by jameslo627** [alexa/alexa-avs-sample-app#396]
I followed the instructions here
https://github.com/alexa/alexa-avs-sample-app/wiki/Windows
The "Start Listening" button is still there.
Is there any information can guide me to enable wake word agent just like on Raspberry Pi?

Thank you.

**Comment by keleric** [comment]
No, the wake word agent doesn't currently work on Windows 10.

**Comment by jameslo627** [comment]
Any plan from Amazon to enable it on Windows10?
There is a configuration setting "wakeWordAgentEnabled" in the file config.json.
Set it to true but didn't change the behavior.

**Comment by keleric** [comment]
Sorry, I can't comment on any potential future plans. The wakeWordAgentEnabled flag in the config.json file doesn't have that particular effect - it just toggles whether the sample app attempts to communicate with a wake word agent or not.
