### ISSUE TITLE
After a couple days the wake word on Alexa stops working?

### ISSUE THREAD

**Issue by tradewindsre** [alexa/alexa-avs-sample-app#398]
Alexa seems to stop responding to voice after a couple of days. Since I have disconnected the monitor, keyboard, and mouse I have no idea why. Do I need to keep hooking up the monitor, etc every time to redo the three terminal steps every time it stops or can I just do something through SSH? Its a big pain to drag the monitor back in the room, etc.. 

I appreciate any help!

**Comment by RaspiRepo** [comment]
To access Pi desktop remotely you can follow this below steps on your pi.

$sudo apt-get install xrdp

On your windows use "Remote Desktop Connection" application and connect to Pi using PI LAN IP address, user name and password.

For Mac OS Microsoft has free software "Remote Desktop".

NOTE:  There are issues people are reporting to use xrdp. Other option mentioned like tightVNC, VNC server/VNC viewer etc.

**** others reported like below 
------------------------------
and then open the file /etc/xrdp/xrdp.ini and in [xrdp1] section change username to username of the user for which you want to log in, leave ask for password and other option as default. I created a user called vnc for remote desktop connection and it looks like that:
[xrdp1]
name=sesman-Xvnc
lib=libvnc.so
username=vnc
password=ask
ip=127.0.0.1
port=-1

When connecting from a windows machine you need to specify screen resolution if you use the default windows RDP client settings the connection will be broken before you can even log in. In the windows client you do not put the credentials, as you will be asked for them when the connection is initialized. If you specify in the configuration file the username, the only thing you will be asked will be a password.
-----------------------

**Comment by tradewindsre** [comment]
Thank you...Is this different from using SSH via Putty?

Assuming I can connect via "Remote Desktop Connection" does this mean I can do the three terminal steps from my windows computer rather than having to hook up the monitor and keyboard directly to the pi?

I couldnt get Java to install properly (Terminal 2 step) remotely via SSH so I had to work directly on the Pi...do you think this new way through the Remote Desktop Connection will change that?

Thank you,

**Comment by RaspiRepo** [comment]
Yes, that's correct.  Once you setup remote desktop access you can use putty OR remote desktop client on your PC.  Once you can login into PI then you can open Terminal on the PI (PI has Terminal application) which is same as your Putty terminal.

You don't need to connect Monitor/keyboard/mouse on PI if RDP worked out. This is what you wanted.

Java installation can be done any method (including thru Putty). But to run Alexa JavaClient  PI should be booted with its desktop.

**Comment by alexsalnikov** [comment]
the first terminal window you run npm server that receives access token from AVS
this token will expire after some time, this why you will need to restart everything

**Comment by umma08** [comment]
@alexsalnikov how long does the token last? bit of a pain if i have to go through the whole startup procedure in terminal every two days. :-(

**Comment by tradewindsre** [comment]
Only about two days...then I have to bring in a monitor..bring in a 
keyboard etc and redo steps 1-3...it IS a pain lol

Landmark Appraisal & Realty Group, Inc. <http://www.landmarkres.com>

Matt Thoren / President/Broker
mthoren@landmarkres.com <mailto:mthoren@landmarkres.com>/ 561-373-2186

Landmark Appraisal & Realty Group, Inc.
Office: 561-853-2129 / Fax: 561-853-2203
301 Clematis Street Suite #3000 West Palm Beach, FL 33401
http://www.landmarkres.com

Linkedin <https://www.linkedin.com/pub/matt-thoren/11/233/477>

**Comment by umma08** [comment]
@tradewindsre what a pain. I know that there is another thread #471 that links to #431 . it seems they are making headway with an automatic login reboot version. Might be worth checking that out. I haven't tried it myself, but it seems from #431 that some are making headway.

**Comment by keleric** [comment]
FYI, If you go through the companion app flow once, you never need to re-authenticate with the companion service. That should take care of at least one of your pain points.

If you're interested in a headless sample app, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. Thanks!
