### ISSUE TITLE
Javaclient exec:exec Error, not find main class

### ISSUE THREAD

**Issue by jolimk** [alexa/alexa-avs-sample-app#399]
> Help me please. Im trying to install in Raspi3 and having this issue- 

When running:

`pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec`

I get error:

`Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher`

> Any advice would be highly appreciated! Thanks a lot

**Comment by RaspiRepo** [comment]
May be re run auto script and see. Looks like some class files missing

**Comment by jolimk** [comment]
Sorry I'm new to all the raspberry Pi world. What do you mean by "auto script" and how do I run that? Thanks a lot and sorry for the ignorance on the matter.

**Comment by jolimk** [comment]
@raspirepo thank you. How do I do that?

**Comment by RaspiRepo** [comment]
Step 6: 
cd ~/Desktop/alexa-avs-sample-app
. automated_install.sh

**Comment by jolimk** [comment]
I have already done that, it took about 30 minutes. It doesn't work. I've started over like three times with no success.

**Comment by keleric** [comment]
Something clearly went wrong with the install script. If you attach a text file with its output, we might be able to determine the problem better.

**Comment by jolimk** [comment]
So do I run that and paste the entire code here? I thing it might get too
long. But when I get home I'll do it. Thanks a lot.

**Comment by keleric** [comment]
You can attach files by dragging them into this box. Just attach a text file.

**Comment by jolimk** [comment]
There it goes. Everything seems fine to me! 
[automated_install.sh .pdf](https://github.com/alexa/alexa-avs-sample-app/files/637616/automated_install.sh.pdf)

**Comment by jolimk** [comment]
@keleric Look, now I get 2 errors in STEP 7

Error in Window 2:
`
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ cd ~/
Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient &&
 mvn exec:exec
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ `

Error in Window 3:
`
pi@raspberrypi:~ $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd wakeWordAgent/src &
& ./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.1 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 27 Mar 2017 00:00:00 GMT
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
wakeWordAgent: pcm.c:694: snd_pcm_close: Assertion `pcm' failed.
Aborted
`

**Comment by alexsalnikov** [comment]
my suggestion will be to take new sd card make fresh install of raspbian
then 
$ sudo apt update
$ sudo apt upgrade
$ sudo reboot

clone alexa sample & run automated_install.sh

then check if your microphone works and you can record any audio stream
$  arecord -l
$ arecord --duration=2  --file-type=wav > temp.wav

Then run in in separate terminals in this order
token app -> the npm part
avs app -> the mvn part
trigger app -> the wake word engine part

**Comment by jolimk** [comment]
Still same error:

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ 


There must be something I´m doing wrong!!!

**Comment by alexsalnikov** [comment]
delete current clone and then 
try to clone alexa code once again
then run 
cd ~/Desktop/alexa-avs-sample-app
chmod +x automated_install.sh
. automated_install.sh

**Comment by jolimk** [comment]
Ok I found the error. I was trying to use a microphone via 3.5mm instead of
USB. I purchased a USB microphone 🎤 hope it gets here soon!!

**Comment by keleric** [comment]
@jolimk Is your problem fixed?

**Comment by jolimk** [comment]
Yes! I just formatted the whole thing and started over. I think the issue
was cause when updating/upgrading the system the internet connection may
have failed for a couple of seconds. Just start over! Hope it helps!
