### ISSUE TITLE
Active Listening

### ISSUE THREAD

**Issue by jnpetersen** [alexa/alexa-avs-sample-app#4]
I see you have to click start listening, is it possible to make it actively listen like the echo?

**Comment by MinnSoe** [comment]
It looks like multiple input channels would be needed for beam-forming the audio (to identify distinct sound sources and noise reduction). Recognising the wake-word is another thing and it would be great to see what they've come up with.

The Echo appears to use an array with 7 microphones. The challenge here would be to somehow capture multiple sources simultaneously on a Raspberry Pi. You'd need a microphone array, ideally a USB one given that it's an RaspPi. Something like a PS3 Eye or a Kinect would do, though both uses 4 microphones. 

It definitely sounds possible but not trivial; I haven't really tried multichannel audio (more than two) on a RaspberryPi. Maybe somebody else can chime in?

**Comment by Orionx86** [comment]
@MinnSoe He's not asking about multichannel audio; he's asking about not having to click the button, to have it always listening. @jnpetersen I haven't looked at the code yet but I'll update if I find anything.

**Comment by MinnSoe** [comment]
@Orionx86 @jnpetersen I haven't seen anything that handles wake-word detection so far. Of course it's possible to constantly stream the audio without clicking the button (with a few modifications). Though that would deviate from the AVS interaction model and you would probably hit the API limits very quickly.

I was running ahead of myself with the multi-channel input. Essentially, what I should have said is yes but it looks like you'll have to implement wake-word detection. And, if you want anything that performs like the echo - you'll also have to implement something that works in the far-field.

I've looked through the client very quickly and I haven't seen anything so far that can do this. Perhaps I've overlooked it, I would be happy to be wrong.

**Comment by col** [comment]
AVS doesn't support any 'wake word' style functionality as this is something that would need to work client side. It's just not practical to implement the wake word using a cloud service. No idea if this is something Amazon will release later or something they plan to keep proprietary. It's disappointing though as the always on nature of the Echo, and now the Dot, is what makes them so cool.

There is another option though. There is another OpenSource speak to text project called Jasper. I think it would be possible to take the wake word functionality from that project and integrate it with this one. It would take a bit of effort but in theory it would work.

**Comment by 4ntony** [comment]
The way to do key word voice recognition is to turn the sound input into graphical input and use a picture recognition library. Train the library with the key word and then search for the "picture" of the keyword from a sound stream. I would guess that 'Alexa' was chosen as the keyword because of it's distinct and easily recognised sound.

**Comment by xuchen** [comment]
Sorry for coming late into this discussion. We just released a hotword (or "wake word" as Amazon calls it) detector specifically for voice triggering an action:

https://snowboy.kitt.ai

It has Raspberry Pi support and Python bindings/wrapper (through SWIG). Though no Java wrapper yet:

https://github.com/kitt-ai/snowboy

We'd very much appreciate a pull request for Alexa/Pi integration.

**Comment by benwoodley** [comment]
I have been looking for ways to do this, and my solution is this: [voice command pi git](https://github.com/StevenHickson/PiAUISuite)
But because theres no official support for such a thing in either version of alexa on the pi (yet :)) you need a second pi to do this really.. I'm not sure how you would make a single microphone work with both alexa and voice commands at once. Yes, I realise this is a very convoluted way (I quite literally tried it out by sticking the gpio output from one into the button input on the other) but its a nice experiment and its good to know it can be done.
I realise this is absolutely not a solution for everybody (if anyone) but if your really eager to yell "Alexa order me a domino's" when meters away from the button, can't be asked to get up, and you just don't have the cash to buy a talking pringles tube then this could the be (temporary) solution for you!

**Comment by benwoodley** [comment]
xuchen, that would be perfect for the python version of Alexa on the Pi (AlexaPI) by Sam Machin. The for it git is referenced above by gregwa too. If that could be implemented into either of these it would be an incredible step forward.

**Comment by xuchen** [comment]
@benwoodley thanks for the pointer. We are already working with the AlexaPi guys on integration, including both wake word support and voice/silence detection.

If you could feed an audio buffer in RAM to the Snowboy hotword detector, it would detect whether a wake word is present in that audio buffer. Snowboy doesn't necessarily need to access the microphone. Hope it helps.

**Comment by Thelle** [comment]
@xuchen - very cool - any new on AlexaPi integration?

**Comment by xuchen** [comment]
@Thelle it's already integrated by @flooie on https://github.com/flooie/AlexaPi/tree/voice-command

I'm pretty sure someone within Amazon was working on integrating Snowboy into this project.

**Comment by Rian9771** [comment]
Hi all, i just started with my Raspberry pi and i believe i picked the best project. I used the github link given by @xuchen (flooie's voice command alexa with snowboy). I got it working after having a few problems with microphone. I tried logging into https://snowboy.kitt.ai/ but it wouldn't go past the "Login with" popup. 

How would one change the wake word from Alexa to something else? I saw a trigger_phrase = "alexa" in main.py and was super happy but that didn't work.  :(

I apologize in advance if i am not making any sense. Like i said, this is my first project and this is very new and COOL   :) 

Thank you in advance!!!

**Comment by xuchen** [comment]
@Rian9771 snowboy login is down now because of an expired SSL certificate. We are working on a fix now but it might take a couple of days -- sorry for the inconvenience!

Once the website is up, you can feel free to define and record your own hotword.

**Comment by Rian9771** [comment]
Thank you @xuchen . I will wait for the site to be online. If there is any docs on how to record a new hotword and replace the one with flooie's, do let me know. 

Thank you

**Comment by TheFonix** [comment]
Any news on this? or is it still a WIP?

**Comment by rajington** [comment]
[There's a new update using TrulyHandsFree from Sensory and Snowboy from KITT.AI](https://developer.amazon.com/public/community/post/Tx1WVAG8L2OOXF0/Alexa-Voice-Service-Introduces-API-Update-that-Makes-It-Easier-to-Build-Hands-Fr)

[Lifehacker just published a guide too, pretty awesome!](
http://lifehacker.com/how-to-build-your-own-amazon-echo-with-a-raspberry-pi-1787726931)

Great job @ajotwani, I think this one can be closed.

**Comment by ajotwani** [comment]
Closing as resolved.

**Comment by grtessman** [comment]
Check out Re-Speaker on kickstarter for a microphone array.
