### ISSUE TITLE
wakeWordAgent compile error.

### ISSUE THREAD

**Issue by mars9180** [alexa/alexa-avs-sample-app#400]
hello all, I tried to run the wakeWordAgent program on my Linux, but I encountered an error while compiling, hoping to get your help. My steps are as follows:

bill@bill:/home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src$ cmake .
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src
bill@bill:/home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src$ 
bill@bill:/home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src$ make
Scanning dependencies of target wakeWordAgent
[  7%] Building CXX object CMakeFiles/wakeWordAgent.dir/main.cpp.o
[ 15%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
[ 23%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
In file included from /home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src/WakeWordEngineFactory.cpp:17:0:
/home/use_mmx/alexa/alexa-avs-sample-app-master/samples/wakewordAgent/src/KittAiSnowboyWakeWordEngine.h:18:28: fatal error: snowboy-detect.h: No such file or directory
 #include "snowboy-detect.h"
                            ^
compilation terminated.
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
make: *** [all] Error 2

**Comment by alexsalnikov** [comment]
if you want to make changes in wakeword engine and then compile it 
i'm suggesting to cut out all dependencies and cmake part from automated_install.sh

# Preconfigured variables
OS=rpi
User=$(id -un)
Group=$(id -gn)
Origin=$(pwd)
Samples_Loc=$Origin/samples
Wake_Word_Agent_Loc=$Samples_Loc/wakeWordAgent
Kitt_Ai_Loc=$Wake_Word_Agent_Loc/kitt_ai
Sensory_Loc=$Wake_Word_Agent_Loc/sensory
External_Loc=$Wake_Word_Agent_Loc/ext

cd $Origin


echo "========== Preparing External dependencies for Wake Word Agent =========="
mkdir $External_Loc/include
mkdir $External_Loc/lib
mkdir $External_Loc/resources

cp $Kitt_Ai_Loc/snowboy/include/snowboy-detect.h $External_Loc/include/snowboy-detect.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/portaudio.h $External_Loc/include/portaudio.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_util.h $External_Loc/include/pa_util.h
cp $Kitt_Ai_Loc/snowboy/lib/$OS/libsnowboy-detect.a $External_Loc/lib/libsnowboy-detect.a
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/lib/libportaudio.a $External_Loc/lib/libportaudio.a
cp $Kitt_Ai_Loc/snowboy/resources/common.res $External_Loc/resources/common.res
cp $Kitt_Ai_Loc/snowboy/resources/alexa.umdl $External_Loc/resources/alexa.umdl

$Sensory_Loc/alexa-rpi/bin/sdk-license file $Sensory_Loc/alexa-rpi/config/license-key.txt $Sensory_Loc/alexa-rpi/lib/libsnsr.a $Sensory_Loc/alexa-rpi/models/spot-alexa-rpi-20500.snsr $Sensory_Loc/alexa-rpi/models/spot-alexa-rpi-21000.snsr $Sensory_Loc/alexa-rpi/models/spot-alexa-rpi-31000.snsr

cp $Sensory_Loc/alexa-rpi/include/snsr.h $External_Loc/include/snsr.h
cp $Sensory_Loc/alexa-rpi/lib/libsnsr.a $External_Loc/lib/libsnsr.a
cp $Sensory_Loc/alexa-rpi/models/spot-alexa-rpi-31000.snsr $External_Loc/resources/spot-alexa-rpi.snsr

# copy content of ext folder to wakeWordAgent\tst\ext
# probably for testing
mkdir $Wake_Word_Agent_Loc/tst/ext
cp -R $External_Loc/* $Wake_Word_Agent_Loc/tst/ext
cd $Origin

echo "========== Compiling Wake Word Agent =========="
# compile wakeWordAgent
cd $Wake_Word_Agent_Loc/src && cmake . && make -j4

# compile wakeWordAgentTest
# cd $Wake_Word_Agent_Loc/tst && cmake . && make -j4

**Comment by nehrenholz** [comment]
Thanks, alexsalnikov, I opened wakeWordAgent\ext\include to find only snsr.h

Where can I retrieve the other .h files?
 ...This is my first pi project so I'm learning on the go.

**Comment by alexsalnikov** [comment]
Before you try to compile with cmake
you need to run automated_install.sh
this script suppose to load all dependencies and copy files at right location 
and it's also runs cmake to compile wakeWordAgent
after this if you make changes in some source code of wakeWordAgent
i guess you can then run cmake,
if not i suggest to look inside automated_install.sh and create like compile.sh
script that contains relevant part for wakeWordAgent compilation

**Comment by nehrenholz** [comment]
Thanks, I ran automated_install.sh many many times and it would fail with Cmake and wakeWordAgent therefore all my dependencies are missing. I have been manually making files and copying in the header file source code and trying to figure out what is missing but there must be a better way. So far I have been finding missing snowboy and port audio files but I'm not sure about everything else that might be missing. Is there a way to compile wakeWordAgent manually outside of automated_install.sh? I'll start looking into the script inside automated_install.sh

Cheers

**Comment by nehrenholz** [comment]
Thanks for the help! My problem has been resolved as a hardware problem causing brown-outs during certain parts of the compiling. Everything is up and running now.

**Comment by alexsalnikov** [comment]
Awesome
