### ISSUE TITLE
change time and location

### ISSUE THREAD

**Issue by arnauldb** [alexa/alexa-avs-sample-app#402]
I installed alexa on my Pi, it is working fine, but how can I change my location,  is it only possible ? I live in Paris, so I'd like to have e.g. Paris' weather when asking "what's the weather"...

thank you,

**Comment by illperipherals** [comment]
You might look at the third-party skill Big Sky.

**Comment by arnauldb** [comment]
:-) anything more ? do you have a link to add this third party skill Big Sky ?

**Comment by D3rpi** [comment]
It's not going to work unless the amazon echo officially comes to the country you're in. 
Just say "What's the weather in Paris" for now.

**Comment by RaspiRepo** [comment]
Hi arnauldb

You can try with Amazon alex app from apple store (iPhone) or google play store for android
https://play.google.com/store/apps/details?id=com.amazon.dee.app&hl=en

In this app you can add your RPI device or it may detect automatically if you use same amazon username/password on this app.

Once you signed in then set home address location, from then onwards Alexa will tell your local weather. 

Also you can add your office address then ask traffic report.  I have done this (US). if Alexa API service not blocked in your city (I don't know other country)  you should able to synch up Alexa device and app on your phone.  

https://itunes.apple.com/us/app/amazon-alexa/id944011620?mt=8&ign-mpt=uo%3D2

This link is specific to US. Try from your phone.
Hope you can get this

**Comment by arnauldb** [comment]
> What's the weather in Paris

that's my problem, I keep having the weather forecast for seattle even if I say "What's the weather in Paris" or wherever...

**Comment by D3rpi** [comment]
That is strange because if I say "What's the weather in Paris" on mine, I get the Paris, France weather.

**Comment by arnauldb** [comment]
ok, sorry for having bothered you with this, I finally succeeded having the weather in Paris...once. I guess there is a problem with my french pronunciation or my mic...

**Comment by sw11mike** [comment]
I found a great set of instructions on another forum for changing the location and measurement units. These worked for me to change my location to London, UK: 

http://www.echotalk.org/index.php?topic=228.0

**Comment by arnauldb** [comment]
thanks sw11mike, I will look at this this week-end.
