### ISSUE TITLE
Failed to start companion service client (mvn exec:exec)

### ISSUE THREAD

**Issue by blee19** [alexa/alexa-avs-sample-app#404]
Was completely fine during the process, following everything diligently until I ran to the step of the second terminal window - when you run cd javaclient/ && mvn exec:exec. I got the java window to open (Alexa Voice Service - v20160207.0) but when I press 'OK' when asked about opening the URL, nothing happens. Then I copy/paste that url into a browswer, and I get an error - a blank screen except for 

{"error":"MissingParams","message":"The following parameters were missing or empty strings: code"}.

There's also an error appearing in the 2nd terminal window - after I visit the localhost:3000/.... site, it says,

Failed to start companion service client.

How can I fix this?

**Comment by alexsalnikov** [comment]
did you run 
cd ~/Desktop/alexa-avs-sample-app/samples
cd companionService && npm start

before running of cd javaclient/ && mvn exec:exec

**Comment by blee19** [comment]
Yes! I did those exactly... Let me know what else i can do to answer your questions

**Comment by alexsalnikov** [comment]
after you run mvn exec:exec
application will start and you will see Alexa Voice Services App
it will create pop up message "Login to Register/Authenticate your Device"
you should press "yes"
now you wait for web browser to start it should take you to login page on amazon site
after login you should see token created
now you can minimize browser screen
and press "ok" button on new pop-up message box
after it Bearer token should be populated with security text

**Comment by jhoelzl** [comment]
I have the problem that the popup (as it is written in the documentation) does not appear when running `mvn exec:exec`. I only get the window "Alexa Voice Service" with my Device and DSN and an empty input field for the Bearer Token. When i click "Listen" (two times) the app is in the "Processing" Mode, but nothing happens.

**Comment by joncasagrande** [comment]
Hi, I am getting 
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

Does anyone knows what is wrong

**Comment by sw11mike** [comment]
I've got the same error as blee19

- run mvn exec: exec
- see first pop up titled "Alexa Voice Service"
- see second pop up titled "Login to Register/ Authenticate your Device" with a browser URL to open
- open provided URL in browser, resulting in error:

("error":"MissingParams","message":"The following parameters were missing or empty strings: code")

i.e. it doesn't get as far as the Amazon log in page. 

I've repeated this error on a clean Raspian build.

**Comment by tsathish123** [comment]
I am also having issue in getting a token.

1. run mvn exec: exec
2. see first pop up titled "Alexa Voice Service"
3. see second pop up titled "Login to Register/ Authenticate your Device" with a browser URL to open
4. open provided URL in browser,
5. A pop up window with "cancel" or "continue". I selected continue option.

Now there is no response. It stays in the same screen indefinitely. If i went to server terminal (companion service), there i got the error like

Failed to post request: getaddrinfo ENOTFOUND api.amazon.com api.amazon.com:443
Failed to post request: getaddrinfo ENOTFOUND api.amazon.com api.amazon.com:443
Failed to post request: getaddrinfo ENOTFOUND api.amazon.com api.amazon.com:443
Failed to post request: getaddrinfo ENOTFOUND api.amazon.com api.amazon.com:443

I am using linux build with companion service for the server. Please give your comments to solve this issue.
