### ISSUE TITLE
Spotify and Pandora show App Support Not available

### ISSUE THREAD

**Issue by bytechaser** [alexa/alexa-avs-sample-app#412]
Spotify and Pandora show App Support Not available in the Alexa app on Android.

Not sure why, suggestions?

**Comment by erikhopf-amzn** [comment]
Today, AVS doesn't support Spotify and Pandora.

**Comment by anujdeshpande** [comment]
- Does that mean it supports iHeart radio or any of the other music streaming devices (anything that would go on the Content channel) ?
- Also, by AVS do you mean this reference implementation or the API in general ?

**Comment by elstryan** [comment]
- AVS does support iHeart radio and tuneIn. AVS also supports Amazon Music if you request it when you create your device.
- These comments are for the API in general

**Comment by chenxiaoqun** [comment]
The AVS 1.1 release note says Spotify and Pandora, why it is still show “App Support Not available”
