### ISSUE TITLE
Are the android and iOS companion apps "supported"?

### ISSUE THREAD

**Issue by OptimalPaul** [alexa/alexa-avs-sample-app#414]

**Comment by max-erler** [comment]
Yes, the android and iOS apps are supported for authenticating the sample app. Instructions on how to use them can be found in this repository's wiki. I'm not sure what OS you're using, but here is the link for Linux: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#5---choose-your-authentication-method
