### ISSUE TITLE
npm start issue for Windows 10

### ISSUE THREAD

**Issue by AlexaDemo** [alexa/alexa-avs-sample-app#417]
I follow the steps and I am stuck. Can you help please??

Error: ENOENT: no such file or directory, open 'C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService\UsersintelDocumentsAlexaProjectalexa-avs-sample-app-masteralexa-avs-sample-app-mastersamplesjavaclientcertsserver
ode.key'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService\npm-debug.log

**Comment by AlexaDemo** [comment]
below is my debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService\node_modules\.bin;C:\Users\intel\Documents\Proinclude\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;C:\Program Files\nodejs;C:\Program Files\Proinclude\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;C:\OpenSSL-Win64\bin;C:\Users\intel\AppData\Roaming\npm;C:\OpenSSL-Win64\bin;C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService\node_modules\iconv-lite
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
12 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
14 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
16 verbose cwd C:\Users\intel\Documents\AlexaProject\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\companionService
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs alexa-voice-service-sample-companion-service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls alexa-voice-service-sample-companion-service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by AlexaDemo** [comment]
I was able the solve the previous part mentioned above by using the command npm update. 
Now, I am stuck again when I run mvn exec:exec command. I read the others and I did mvn clean and mvn install. I still have the error below. Please help




C:\Alexa\alexa-avs-sample-app\samples\javaclient>mvn -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.095 s
[INFO] Finished at: 2016-12-18T00:27:33-08:00
[INFO] Final Memory: 6M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:94)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Comment by notvishwanth** [comment]
hi there, 
Try using the below command after mvn install
mvn validate

**Comment by erikhopf-amzn** [comment]
@AlexaDemo did you run `mvn install` prior to running `mvn exec:exec`? See: https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 20 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!

**Comment by darkzbaron** [comment]
Hi there, facing the same issue on Win10
