### ISSUE TITLE
Change language, now that german is supported on Amazon Echo

### ISSUE THREAD

**Issue by PatrickSteiner** [alexa/alexa-avs-sample-app#419]
Now that Echo is sold in Germany and understands german, is there a way to activate this for this project as well? Feels strange to have to change language only because changing a room. ;-)

Patrick

**Comment by max-erler** [comment]
An upcoming release will include a drop down select and mandatory config field for setting and changing the account locale. Stay tuned.

**Comment by PtrBld** [comment]
Can you tell when this feature will be available?

**Comment by schnub69** [comment]
That would be very nice 👍 hope it comes out soon!

**Comment by shrewm** [comment]
Any news on this one?
Appreciate reply thanks!

**Comment by keleric** [comment]
Internationalization is scheduled for early this year. I can't give you more precise timelines than that, but keep an eye on this repo for changes!

**Comment by unfassbarstephan** [comment]
YEAH! Now, avs supports german language!

read more: [https://developer.amazon.com/blogs/post/f6d79f37-1de1-4369-9660-c4347a91e76b/avs-now-available-for-the-uk-and-germany](Alexa Voice Service Now Available for the UK and Germany)

**Comment by shrewm** [comment]
@unfassbarstephan so what does this mean for the avs-sample? does it now work out of the box?

**Comment by Alexnagel** [comment]
@shrewm Correct, pull the latest changes and run the `automated_installer.sh` again. You'll be able to select your locale.

**Comment by unfassbarstephan** [comment]
@Alexnagel Nice, thats it?

**Comment by Alexnagel** [comment]
@unfassbarstephan As far as I know yes, haven't tried it myself yet

**Comment by Dtrieb** [comment]
German language works for me with no problems!
