### ISSUE TITLE
Not building on fresh install. reboots pi repeatedly.

### ISSUE THREAD

**Issue by shortsguy** [alexa/alexa-avs-sample-app#420]
Hello,
This is my second attempt to build this project and it keeps failing. 
I get CMakeXXX errors, npm errors, and when it starts compiling the companion services it gets to 26% and reboots my pi3 repeatedly. I run autoinstall.sh and keep getting same errors.

I clean the .m2 to fix errors, and when it does finally compile and I open the three terminals and run the first command it fails and I get errors. 

I just did a full clean fresh install of Raspbian and did an apt-get update && upgrade before starting the install.

Any reason why this fails on a very fresh install?
I will post output logs in comments.

**Comment by shortsguy** [comment]
[ERROR] Failed to parse plugin descriptor for org.apache.maven.plugins:maven-resources-plugin:2.3 (/home/pi/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/2.3/maven-resources-plugin-2.3.jar): zip file is empty -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException
========== Installing Companion Service ==========
npm WARN deprecated node-uuid@1.4.1: use uuid module instead
npm ERR! cb() never called!
npm ERR! not ok code 0
========== Preparing External dependencies for Wake Word Agent ==========
========== Compiling Wake Word Agent ==========
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/main.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngine.cpp.o

**Comment by naderinou** [comment]
I have same problem over here :/

**Comment by shortsguy** [comment]
Fixed. 
I did an apt-get update && apt-get  upgrade
something in that fixed it.

**Comment by elstryan** [comment]
Thanks for the suggestion @shortsguy . I'll close this issue for now. Feel free to re-open it if you need anything else from us.
