### ISSUE TITLE
Playback via VLC stream, volume is 0

### ISSUE THREAD

**Issue by hotwheelzffx2** [alexa/alexa-avs-sample-app#422]
I have Alexa running on a Raspberry Pi 3. Everything seems to work OK.
However, when playing Prime music or iHeart Radio stream, the volume is reset to 0 between each song.
Is there a way to force volume at 100%?

**Comment by hotwheelzffx2** [comment]
I think I was just being dumb. I had to tell Alexa to set volume to X and it seems to stick there.

**Comment by max-erler** [comment]
Are you still having an issue with this? Sounds like you were able to find a resolution.

**Comment by hotwheelzffx2** [comment]
I rebuilt the Alexa apps this weekend. and I don't remember it being a problem before. Once I told Alexa to set the volume, the next track or stream would always play. I am using PulseAudio, so I did set the following in my /etc/pulseaudio/default.pa
`set-sink-volume 0 +3%`
I don't think that made any difference.

**Comment by jwhite** [comment]
I'm having the same issue.  If I do 'what is the news' I don't hear anything.  If I open up the pulseaudio volume control the volume for vlc is set to zero.

**Comment by hotwheelzffx2** [comment]
Try: Alexa, Set Volume to 5. This seemed to maintain the volume level between streams.

**Comment by jwhite** [comment]
That seems to be working until I modified my config.json.  Then it was reset and I had to issue the command again.

**Comment by limhenry** [comment]
found the solution for this issue. https://github.com/alexa/alexa-avs-sample-app/pull/443
