### ISSUE TITLE
companionApp : javasecurityCert... : Trust anchor for certification path not found

### ISSUE THREAD

**Issue by qkzk** [alexa/alexa-avs-sample-app#423]
Hello,

a few monthes ago I managed to install alexa on a raspberry pi 3. I also enabled the companionApp auth certification, allowing me to run alexa on boot. It worked fine !

Since the SD card fried I had to do it again.

I did everything as inscructed in the raspberry Pi installation, except I used the companionApp, following the linux part of the tutorial.  
Everything seems to be set up correctly except in pom.xml where I can't find the correct alpn-boot version [here](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions).  
My jdk version is 8u111 (= 1.8.0u111) but there's no corresponding alpn-boot version. Since I can't guess it myself, I left it at 8.1.7.v20160121.

I also added the local ip of my android phone :
`IP3        = 192.168.0.35`  
in ssl.cnf

mvn runned fine but I always get that error in the companionApp : 

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`

Is there something I can do ?

Thanks !

**Comment by max-erler** [comment]
That sounds like the exception you would see when using an invalid or expired certificate. Try generating a new SSL cert by running the install script again. You may need to delete the old cert first before a new one will be generated. If that still doesn't work, you can try generating the certs yourself using the linux guide here: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#4---generating-self-signed-certificates
