### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by nordbergr** [alexa/alexa-avs-sample-app#424]
I didn't find this mentioned exactly in other issues but, every time I try to authenticate the pi after logging in when running `mvn exec:exec`  I get this error message after a successful log in:  Error: Can't set headers after they are sent.

I ran through the steps a few times to make sure it wasn't an error in following the directions of the set up but this is always the result.

`
npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:68:17
    at IncomingMessage.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:297:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0`

Also, for anyone wondering, running `npm owner ls alexa-voice-service-sample-companion-service` results in "admin party!".

**Comment by kpazoles** [comment]
I'm getting this same error every time I try to authenticate.

**Comment by gurhancagin** [comment]
I have the exact same problem. i couldn't figure out still the issue. any one can help?

**Comment by kpazoles** [comment]
I didn't exactly figure it out but my solution was to delete and then re-clone the github.  The first time I ran the install I got a message that something had been updated and did I want to download the most recent version, and I said yes.  I thought maybe that was an issue so I watched for it the second time i did the install and didn't even see the message. 

After re-cloning and re-installing everything worked fine.

**Comment by nordbergr** [comment]
I tried re-cloning but i get the same problem :/

**Comment by PJo777** [comment]
Having the same issue. 😣

**Comment by chasekap13** [comment]
What I did to solve this was Sudo install npm like this : 'sudo apt-get install npm' and then reran the Alexa install and it solved the problem.

**Comment by nordbergr** [comment]
@PJo777 So I ended up deleting everything and starting over.  I ran the commands with sudo and everything seems to be working now.  I'm going to close this issue.

**Comment by kwokkawai** [comment]
@nordbergr what sudo command you have run to resolve this issue?

**Comment by nordbergr** [comment]
@kwokkawai It's been a while so I'm not sure.  Knowing myself, probably all of them.
