### ISSUE TITLE
SSL Security Errors

### ISSUE THREAD

**Issue by trisys3** [alexa/alexa-avs-sample-app#425]
I keep getting SSL certificate warnings when I try to go to the URL in the 2nd step. On Google Chrome, up until about 10 minutes ago, I got the "Your connection is not private" error but I was able to override this by going to Advanced->Proceed to localhost(unsafe), but then I got an error I have never seen before, "This site can't provide a secure connection" and I am not able to override it. I'm not sure what changed: I did not update Chrome, but I reran the automated install. I had done this before, though, so maybe one of the dependent packages recently upgraded?

I was never able to override the warning I got on Firefox. I have not tried Internet Explorer, Safari, Chromium, or any other browser.

Is there a way to provide certificates in the repository, or would this involve someone paying, either Amazon or us? Otherwise, what else can we do to avoid this error? Is there a way to do this via `curl`, at least until that gets patched to avoid this kind of hackery with SSL?

**Comment by elstryan** [comment]
Yes the warnings in your browser are because the certificates are self signed. When you get to the "This site can't provide a secure connection" can you try restarting chrome?

**Comment by trisys3** [comment]
Sorry, busy with work during the week. Restarting Chrome seems to have worked, or perhaps it was restarting my compuer in the 2-3 times during the last 2 1/2 weeks. Also, this seems to happen on some browsers, but not others. It happened on my Ubuntu Google Chrome, but not my Raspberry Pi Chrome (or perhaps Chromium, not sure).

Regardless, I do not think users should be limited in using this application based on what browser they happen to like using. If you do not agree, as many browsers are free and you only need the browser for about 2 seconds if you remember your password, feel free to close.
