### ISSUE TITLE
javaclient: Jetty documentation does not list ALPN version information for latest JDK

### ISSUE THREAD

**Issue by uklumpp** [alexa/alexa-avs-sample-app#426]
I installed the latest JDK, version 1.8.0.112. Jetty documentation doesn't list build 112 yet. I had to look up the matching ALPN version in the Jetty source code [here](https://github.com/jetty-project/jetty-alpn-agent/blob/master/src/main/java/org/mortbay/jetty/alpn/agent/Premain.java).

Patch for Windows.md with that information:
[0001-Clarifying-some-steps-in-javaclient-documentation.patch.txt](https://github.com/alexa/alexa-avs-sample-app/files/660005/0001-Clarifying-some-steps-in-javaclient-documentation.patch.txt)

The patch also clarifies the location of ssl.cnf. Certificate generation failed for me 
at first because I edited the file in OPENSSL_CONF instead of the one that generate.bat references.

**Comment by TwistedTransistor** [comment]
Just use 8.1.9.v20160720

**Comment by uklumpp** [comment]
Didn't work for me, I had to use 8.1.10.v20161026. I have it working, just wanted to document where I got that information from.

**Comment by TwistedTransistor** [comment]
I'm running 1.8.0.111-b14 (shown as 8u111 at the JDK download page).

Maybe that's the difference.

**Comment by keleric** [comment]
Documentation updated
