### ISSUE TITLE
AlexaPi and Echo linked to one account

### ISSUE THREAD

**Issue by NickWright25** [alexa/alexa-avs-sample-app#429]
What, if any, could the effects be on the devices and the account by linking both devices to the account?

**Comment by max-erler** [comment]
The only real effects are that any account-wide settings you change on one device will also be reflected on the other. For example, we will soon release the ability to change your locale from our sample app. This would also change your locale on your Echo. Other than that, any Alexa skills that you have enabled on your account will be enabled for both the sample app and your Echo.
