### ISSUE TITLE
mvn exec:exec failure.

### ISSUE THREAD

**Issue by shortsguy** [alexa/alexa-avs-sample-app#430]
I have the npm start running in one Terminal but in Terminal 2 I have this error.

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:java
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.484s
[INFO] Finished at: Tue Dec 20 13:32:30 AST 2016
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project sample-java-client: Unable to parse configuration of mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:java: Cannot assign configuration values to array of type java.lang.String: [-Xbootclasspath/p:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, -Dlog4j.configurationFile=file:////home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/log4j2.xml, -classpath, Classpath {}, -Djna.library.path=${env.VLC_PATH}, com.amazon.alexa.avs.AVSApp] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ 

I know it is mvn exec:exec but i wanted to see the error.
Any help is appreciated.

**Comment by m-faridi** [comment]
I was getting errors as well. I ended up rerunning the setup (automated_install.sh) and it fixed whatever was missing for me.

**Comment by asleniovas** [comment]
I am having exactly the same issue... I re-ran automated_install.sh, and still receiving the same error. Terminal 1 works for me as well.

**Comment by asleniovas** [comment]
Managed to make it work somehow. Deleted the avs folder and rebooted my Pi, afterwards cloned the app again and followed the process from there.

**Comment by elstryan** [comment]
Glad to hear its working for you now @asleniovas. I'll close this issue for now. Please let us know if there is anything else we can do to help you.
