### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by notvishwanth** [alexa/alexa-avs-sample-app#434]
I can see many people have open issues, but my case hasnt been anywhere, cannot make sense of what's happening too, please help

>C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService>npm start
> alexa-voice-service-sample-companion-service@1.0.0 start C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService
> node ./bin/www
This node service needs to be running to store token information memory and vend them for the AVS app.
fs.js:731
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Object.<anonymous> (C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService\bin\www:22:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService\npm-debug.log
C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService>npm -v
3.10.9

npm-debug.log file: 
>0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\vj051160\Downloads\softwares\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;C:\OpenSSL-Win64\bin;C:\Program Files\nodejs\;C:\Users\vj051160\AppData\Local\Microsoft\WindowsApps;C:\Users\vj051160\AppData\Roaming\npm
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
12 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
14 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
16 verbose cwd C:\project\external\AVS\alexa-avs-sample-app-master\samples\companionService
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs alexa-voice-service-sample-companion-service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls alexa-voice-service-sample-companion-service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Overview: Read isn't working for some reason

**Comment by GenericUK** [comment]
Looks like a permissions error. Run as administrator

**Comment by notvishwanth** [comment]
@GenericUK This has been run in administrator mode, but i've found out the problem, it seemed i did not run the npm and node.js as expected, closing this issue now! thanks 👍
