### ISSUE TITLE
extending the alexa sample app

### ISSUE THREAD

**Issue by notvishwanth** [alexa/alexa-avs-sample-app#436]
hi there, I would like to thank amazon team for the nifty avs sample app, however, i would like to play with it a bit more and get more responses. 
Is there anyway to change the code in the java application?
I would like to say "open google chrome" and the avs sample app must be capable of opening it, is this kind of requests possible in sample app? 
If not, how should i proceed in creating avs which will be more complex? 
I'm processing this in Personal computer, and not external source like Pi
Help appreciated :) 
thank you :)

**Comment by Metonimie** [comment]
I'm also interested in adding skills to the sample-app.

**Comment by cih997** [comment]
Hi Guys,

I don't have Echo / Dot so I could not use https://github.com/bwssytems/ha-bridge.

I created my custom commands with https://github.com/johnwheeler/flask-ask (quick guide video https://www.youtube.com/watch?v=cXL8FDUag-s).

I suggest reading samples here https://github.com/johnwheeler/flask-ask/tree/master/samples.

Also I could not make command like "Alexa, MYCOMMAND" to work, instead this worked: "Alexa, ask MYCOMMAND".

@notvishwanth with flask-ask I was able to create my custom commands and actions (in Python). Opening google chrome is doable of course.

Good luck!

**Comment by notvishwanth** [comment]
@cowboysdude : The default location is US, ask like this "what's the weather today in <your location> it worked for me :)
@cih997 Thanks! i have already implemented a manual for my website in javascript, using ASK, i will look into your notes and try to implement it :) thanks

**Comment by elstryan** [comment]
You can change the location of your device at alexa.amazon.com. 

1) Navigate to alexa.amazon.com and sign in with the same credentials that you used to log into alexa on your pi
2) Click Settings
3) Select the name of your device
4) Edit the device location field
