### ISSUE TITLE
Wakeup Word sensory not working (Raspberry Pi), but mic and speaker works desktop button

### ISSUE THREAD

**Issue by lgee2411** [alexa/alexa-avs-sample-app#440]
New to using this so apologies if this isn't worded correctly.  I used the alexa blog yesterday to create this on my Raspberry Pi3 and all was good,  However I can't get the wakeup Word terminal to work at all it just gives an error message although the button desktop works fine and I've been having fun it

![capture](https://cloud.githubusercontent.com/assets/24863003/21581443/3fad72f4-d02a-11e6-8f8c-0c0c139146a4.JPG)

Any help or advice appreciated

**Comment by elstryan** [comment]
This error occurs when the wakeWordAgent is not able to detect the microphone. 

1. Can you verify that you have plugged in a USB microphone?
2. Can you try plugging in your USB microphone into a different USB port and rebooting?

Additionally you can look at this related forum which looks to be the sample issue: https://github.com/alexa/alexa-avs-sample-app/issues/379

**Comment by lgee2411** [comment]
I have a USB microphone plugged in and can press the listen button on screen and talk to Alexa with any problem the issue comes when I try and start the wakeWordAgent which simply errors itself out all the time.

**Comment by ninjastu2u** [comment]
I have usb microphone ,if I press the listen button it beeps but no sound recording , if I plug the USB microphone into my pc it says it's working ?
