### ISSUE TITLE
Sorry, I have trouble playing music in your library.

### ISSUE THREAD

**Issue by Monster-Zou** [alexa/alexa-avs-sample-app#445]
19:26:53.315 [pool-193-thread-1] ERROR com.amazon.alexa.avs.AVSAudioPlayer - Error playing: https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m=m&dmid=233749325&c=cf&f=ts&t=10&bl=256k&s=true&e1=1483474500000&e2=1483475400000&v=V2&h=47a9cfa94a67fc1ce7146ef2a5ee787fcd372b43f75511caa005bd1b5095f35a
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory

After running alexa continuously 24 hours, the error occurs. Anyone encountered the same problem?

**Comment by elstryan** [comment]
Sorry you're running into this issue. I'll get the developer team to look into the issue. To help us debug can we get more information: which platform are you running the code on when you do this? Are you running any other applications on your system at the time this occurs?

**Comment by Monster-Zou** [comment]
@elstryan Thanks for reply. I ran this code on raspberry pi 3 and there is no other program running at the same time. I cannot reproduce the problem right now since it occurred only once. But I think it should not be an occasion. Thanks.

**Comment by keleric** [comment]
Unless this issue is reproducible, I'm going to close the issue. If you discover repro steps, please open it again and we'll look into it! Thanks.
