### ISSUE TITLE
automated_install.sh: 240: automated_install.sh: Syntax error: "(" unexpected (expecting "do")

### ISSUE THREAD

**Issue by jazzcrack** [alexa/alexa-avs-sample-app#447]
1. git clone https://github.com/alexa/alexa-avs-sample-app.git
2. cd alexa-avs-sample-app/
3. sh automated_install.sh

Result: 
automated_install.sh: 240: automated_install.sh: Syntax error: "(" unexpected (expecting "do")

**Comment by Brookke** [comment]
Just got the same error

**Comment by lslamp** [comment]
Guys, you have to edit the file before you run it. Most important you have to add the following information.

# This is the name given to your device or mobile app in the Amazon developer portal. To look this up, navigate to https://developer.amazon.com/edw/home.html. It may be labeled Device Type ID.
ProductID=RasberryEcho

# Retrieve your client ID from the web settings tab within the developer console: https://developer.amazon.com/edw/home.html
ClientID=amzn1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# Retrieve your client secret from the web settings tab within the developer console: https://developer.amazon.com/edw/home.html
ClientSecret=

DeviceSerialNumber='RasberryEcho'

This information is extracted from your login from the developers portal.

Once this is updated then run the script and answer the questions.
Lawrence
#-------------------------------------------------------

**Comment by jazzcrack** [comment]
With my ProductID, ClientID and ClientSecret from developer.amazon.com I get the same result.

**Comment by jazzcrack** [comment]
@Brookke Thx

**Comment by SeanChristopherConway** [comment]
@Brookke When I saw this answer and realized how stupid I had to re-evaluate my perception of how good a developer I thought I was. Cheers dude!
