### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by Eddd97** [alexa/alexa-avs-sample-app#452]
Hi! I've been trying to use the companion app on Android for Authorization, but I am facing a weird issue: I get "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found" on Android app. I tried creating new certs, adding my phone's ip to ssl.cnf (I installed the app on my phone), change the provisioningMethod to companionApp, but I keep getting this error. What am I missing?

**Comment by keleric** [comment]
Can you try replacing the Android app's copy of ca.crt? It's in androidCompanionApp/app/src/main/res/raw/. It should be the same file as the javaclient/certs/ca/ca.crt.

**Comment by Eddd97** [comment]
Thank you! Worked like a charm!
