### ISSUE TITLE
Wake word goes into idle

### ISSUE THREAD

**Issue by Tjmcnutt** [alexa/alexa-avs-sample-app#453]
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.1 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 Apr 2017 00:00:00 GMT
wakeWordAgent: pcm.c:694: snd_pcm_close: Assertion `pcm' failed.
Aborted

Is there an easy fix?

tim

**Comment by Tjmcnutt** [comment]
Removed (rm -v) AVS file and reinstalled.  Everything works great.

**Comment by Tjmcnutt** [comment]
After unplugging the RPi, I can't get alexa as to work again.

**Comment by keleric** [comment]
Same issue? Have you seen this thread? https://github.com/amzn/alexa-avs-raspberry-pi/issues/50

**Comment by ro8bert** [comment]
hi @Tjmcnutt , could you say how you solved it? Thanks.

**Comment by nordcomputer** [comment]
Got it to work once with one Microphone (USB) - switched to another Microphone and it stopped working. Seems like needs the WakeWord Detection explicite a Microphone, that supports 16kBit?

**Comment by elstryan** [comment]
Right now AVS requires that the audio to be captured in 16bit LPCM with a 16kHz sample rate (https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speechrecognizer#recognize). Looks like you managed to get your issue resolved by trying a different microphone. I'll close this issue for now - please feel free to re-open if you are still having problems.
