### ISSUE TITLE
Run behind proxy

### ISSUE THREAD

**Issue by guidoffm** [alexa/alexa-avs-sample-app#454]
I have tried to run this on Raspberry behind ah HTTP proxy. I had set the variables http_proxy and https_proxy to point to the proxy server. But I could not manage to get this running. Anyone with experiences in that?

**Comment by keleric** [comment]
Unfortunately, using the sample app behind a proxy is not something we can really help with. It's outside the scope of this support channel, since you're trying to use the sample app in an unsupported way. Closing this issue due to a lack of activity.
