### ISSUE TITLE
Amazon Music

### ISSUE THREAD

**Issue by Smaragd27** [alexa/alexa-avs-sample-app#456]
Hey,
Is it somehow possible to play music from Amazon prime music using the raspberry alexa?
Because it tell's me that i have to apply for it.

thanks, Smaragd27

**Comment by KonradIT** [comment]
According to [their setup page](https://github.com/alexa/alexa-avs-sample-app/wiki/Conexant2Mic-Raspberry-Pi) you should be able to:

    Say "Alexa", then wait for the beep. Now say "Play Z100."

**Comment by blacksaturn1** [comment]
What is iHeart radio is also not playing?

**Comment by macacob** [comment]
Amazon Music just started working on my Raspberry Pi Alexa yesterday out of the blue.  I don't believe I ever requested it but I am enjoying using it.

**Comment by blacksaturn1** [comment]
I realized on Linux, that the VLC software volume keeps going to zero when any music streaming occurs.  Any ideas on how to control the volume?
