### ISSUE TITLE
Alexa and Flash Briefings

### ISSUE THREAD

**Issue by Beagleboy1** [alexa/alexa-avs-sample-app#461]
Hi,
I've got a Pi2 running Alexa without too many difficulties. 
However I cannot get the flash breifings to work? I've used the app on my phone and also through the alexa.amazon.co.uk website. All are switched on but Alexa says otherwise. Is this something that the UK Pi version cannot do?

UPDATE - I can't actually get any information off the app onto Alexa, she can't find my skills or calendar

TIA

Sandy

**Comment by tscott16** [comment]
I'm presuming your device is showing as 'Offline' in the 'Settings' menu too? Have you tried downloading the US Alexa Companion apk?

**Comment by Beagleboy1** [comment]
Yes it is! 
I am trying to use a US login to the Amazon voice pack which seems to work, but I cannot get the ios phone app to work with that so I have been using the windows app in a incognito window, but I cannot get the UK based skills so its a bit catch 22.
Using the US login I get 'online' tho

**Comment by umma08** [comment]
i would love a fix for this as well. 

I am to access my Pi-alexa through the alexa.amazon.co.uk web interface. It remembers my location, and my settings for metric temperatures, and distances, and it remembers my settings for the Flash briefings (on the web interface) when i log out/log in. 

However, the actual Pi-alexa does not seem to sync up with all the settings on the web interface - even though it has the correct device name. 

the pi-alexa remembers my location/metric settings but not the flash briefings/installed skills. It makes me think that they are syncing for some things, and not others.

anyone any ideas?

**Comment by keleric** [comment]
At this time, we do not support access to the Alexa Voice Service (AVS) from outside the United States. When support for the UK launches (early this year), you should be able to access those features that you've mentioned.
