### ISSUE TITLE
Crashes when stopped

### ISSUE THREAD

**Issue by wrinkle-wrinkle** [alexa/alexa-avs-sample-app#463]
I am using a USB soundcard for playback and a webcam as the microphone.  Everything works perfectly.  I am able to say Alexa and she responds great.  However, whenever I try to stop the audio, such as when it is playing music, I will say Alexa, Stop.  At this point it crashes and the javaclient outputs this error:

```
12:47:12.624 [Thread-293] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: cannot obtain source audio line
	at javazoom.jl.player.JavaSoundAudioDevice.createSource(JavaSoundAudioDevice.java:128) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.JavaSoundAudioDevice.writeImpl(JavaSoundAudioDevice.java:148) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.AudioDeviceBase.write(AudioDeviceBase.java:133) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.decodeFrame(Player.java:220) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:120) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:104) ~[jlayer-1.0.1.jar:?]
	at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:916) [classes/:?]
```

and the wakeWordAgent spits out this: 

```
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
INFO:WakeWordAgent: State set to IDLE(2)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:KittAiSnowboyWakeWordEngine: handling pause
INFO:KittAiSnowboyWakeWordEngine: releasing portAudio
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:KittAiSnowboyWakeWordEngine: handling resume
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

Any idea what my issue might be? and how I might fix it?  Any help would be greatly appreciated.

**Comment by alexsalnikov** [comment]
I have the same issue.
The issue happens in this scenario,

I ask, “Alexa play z100”, I hear “ Here z100, and then music starts to play”.
Then in middle of playback I bargain, I ask “what's the weather now”
And javaclient crash

here the messages from /samples/javaclient/logs/application.log
the avs sample version is:  Latest commit e8d2bfb

17:33:23.676 [RequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "directive" : {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "Speak",
      "messageId" : "d08d6859-adb4-45dc-bceb-8da44e4eb785",
      "dialogRequestId" : "9573f2f4-168b-446d-a16c-0f1a6e6b2312"
    },
    "payload" : {
      "url" : "cid:DeviceTTSRenderer_dbc71da1-6c57-4f29-a4c6-04d351d9ddbe_1309142454",
      "format" : "AUDIO_MPEG",
      "token" : "amzn1.as-ct.v1.Domain:Application:Notifications#ACRI#DeviceTTSRenderer_dbc71da1-6c57-4f29-a4c6-04d351d9ddbe"
    }
  }
}
17:33:23.683 [DependentDirectiveThread] INFO  com.amazon.alexa.avs.AVSController - Handling directive: SpeechSynthesizer.Speak
17:33:23.686 [DependentDirectiveThread] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechStarted",
      "messageId" : "427c8280-c9a1-470f-8030-302759ef0613"
    },
    "payload" : {
      "token" : "amzn1.as-ct.v1.Domain:Application:Notifications#ACRI#DeviceTTSRenderer_dbc71da1-6c57-4f29-a4c6-04d351d9ddbe"
    }
  }
}
17:33:23.711 [Thread-160] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: cannot obtain source audio line
	at javazoom.jl.player.JavaSoundAudioDevice.createSource(JavaSoundAudioDevice.java:128) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.JavaSoundAudioDevice.writeImpl(JavaSoundAudioDevice.java:148) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.AudioDeviceBase.write(AudioDeviceBase.java:133) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.decodeFrame(Player.java:220) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:120) ~[jlayer-1.0.1.jar:?]
	at javazoom.jl.player.Player.play(Player.java:104) ~[jlayer-1.0.1.jar:?]
	at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:916) [classes/:?]
17:33:23.767 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 204
17:33:23.767 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0ed27efffe520f11-00004bef-0001bb96-3ce596c20554055d-b12b372d-27


17:33:23.767 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - This response successfully had no content.
17:33:26.643 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 204
17:33:26.643 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0ed27efffe520f11-00004bef-0001bb96-3ce596c20554055d-b12b372d-29


17:33:26.643 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - This response successfully had no content.

**Comment by keleric** [comment]
Unfortunately, right now we only support audio output via HDMI or 3.5mm jack (on the RPi). As you have discovered, USB sound output is problematic. If you end up fixing the problem, please respond with the fix! Until then, I'm going to close this issue.
