### ISSUE TITLE
On Raspberry PI 3 and latest sample app: getting LED(s) to turn on and off during user speech input

### ISSUE THREAD

**Issue by psybertech** [alexa/alexa-avs-sample-app#468]
I believe I have read that before the wakeword was added, you could use an LED on a specific GPIO pin that would turn on during user voice input.
But, I think that is no longer there at least when using the snowboy kitt-ai and the latest builds.
Am I correct in that assumption?

Regardless of the past....

Is there anyway that I can use the snowboy kitt-ai and have my own GPIO pins used? (I need three for my 3 color one). 
I'd love to be able to either simply use a GPIO pin or pins of my choosing. 
_If the ability currently exists hardcoded to X pin, I may be out of luck since I am limited due to my project having an LCD screen attached to the GPIO header, so I can only use certain pins. But if it does, are they 24 & 25? I can't access them with the LCD attached at the moment._

I'd even be happy with being able to trigger a script or scripts at the start of and end of user input.

Does anyone have any info or suggestions to get the LED to fire?

Thank you

**Comment by cnapmak** [comment]
I would love to be able to do something similar, I'm wondering if there is a way for a raspberryEcho to trigger its own gpio pins with the use of AVS. So I can run a relay or a sensor for temperature and humidity.

**Comment by keleric** [comment]
@cnapmak, what exactly are you trying to do? Are you trying to control / read the status of GPIO pins with Alexa? Or do you want to trigger GPIO pins when Alexa does something?

If it's the former, you should look into the Alexa Skills Kit: https://developer.amazon.com/alexa-skills-kit . You can create a skill that knows how to talk to your Raspberry Pi, and by extension, the GPIO pins.

If it's the latter, your options are more limited. You'll have to manually modify the sample app to trigger the LEDs when it makes sense.

**Comment by Sureshee** [comment]
Hi,
I have one question related to this, Is it possible/ is there a way to trigger Alexa internally, based on the status change in GPIO, to notify a text.
