### ISSUE TITLE
Alexa Account location

### ISSUE THREAD

**Issue by pieman123** [alexa/alexa-avs-sample-app#469]
Hi all, I am from the UK however, alexa has registered to the american amazon account. is there a way of directing alexa through the UK side/transfer it over? The skills i wish to implement are only available in the UK.

**Comment by umma08** [comment]
I had the same problem. Go to alexa.amazon.co.uk and sign in with your amazon account (the developer account). This will show your alexa device ID. Click on Home, and then customise Alexa, and then enter your street address and your time zone. The alexa will remember this (and survives reboot)

However, that is as much as it can do - i cannot seem to get the Flash briefings, or any updated Skills to work.

**Comment by keleric** [comment]
When internationalization launches, these issues should disappear. If you're still seeing them after that launch, please file a new Github issue.
