### ISSUE TITLE
ALPN is not compatible with Java 8u111

### ISSUE THREAD

**Issue by bslava** [alexa/alexa-avs-sample-app#470]
Hello,

The installation documentation (for Linux) requires installation of JDK version 8 from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). So I installed **Java SE** Development Kit 8**u111**. Unfortunately the last version, supported by ALPN is **OpenJDK** version 1.8.0**u102**. I'm not familiar with this package and do not know how to proceed.

Please help.

Thanks,
Slava

P.S. You created a great installer for RaspberryPi (automated_install.sh). Please create such an installer for Linux. The current installation procedure is time complex, time consuming and error prone.

**Comment by iamprem** [comment]
+1

**Comment by antoniordz** [comment]
ALPN 8.1.9.v20160720 worked for me in UBUNTU. Java ver 1.8.0_121

**Comment by keleric** [comment]
The latest version of the ALPN supports the latest version of Java, despite the fact that it isn't officially in the table.
