### ISSUE TITLE
Start Alexa on Boot on Raspberry Pi

### ISSUE THREAD

**Issue by winkredible** [alexa/alexa-avs-sample-app#471]
How do I go about starting Alexa automatically on the Raspberry Pi 3? I have followed installation and execution instructions on the github page.

**Comment by lslamp** [comment]
go to this feed. It is very good but there are unresolved issues with the auto start process.

https://github.com/alexa/alexa-avs-sample-app/pull/431

Lawrence

**Comment by keleric** [comment]
If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. Thanks!
