### ISSUE TITLE
Change Wake Word

### ISSUE THREAD

**Issue by xozai** [alexa/alexa-avs-sample-app#473]
Is there a way to change the default wake word?

**Comment by bionemesis** [comment]
So according to the kitt.ai documentation, you can do it if you're using kitt.ai. But the documentation isn't clear on how. So I did some digging and figured it out. After getting everything up and running and responding to Alexa...

Visit https://snowboy.kitt.ai/ and register/login. Go through the process to create your own hotword. Naturally, you're going to use "Computer", right? Download the created "Computer.pmdl" file and rename it to "alexa.umdl". Stop wake word detection on your device and replace the file "~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/resources/alexa.umdl" with the renamed file you just downloaded (I backed up the existing file, just in case). Then restart wake word detection and you're good to go.

It, it, responds to computer... :)

**Comment by bionemesis** [comment]
And for added fun. Replace the .mp3 files in ~/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/res/ with better options. I went through some Star Trek options and have some suggestions:

start.mp3 > http://www.trekcore.com/audio/computer/input_ok_3_clean.mp3
stop.mp3 > http://www.trekcore.com/audio/computer/input_ok_2_clean.mp3
error.mp3 > http://www.trekcore.com/audio/computer/input_failed_clean.mp3

Check out http://www.trekcore.com/audio/ for a BUNCH more.

**Comment by bionemesis** [comment]
FYI, the wake word detection is not as good as it was when using Alexa now that I've replaced it with my own. This is to be expected as the voice model has only my voice, whereas the Alexa model provided out of box, I assume, has hundreds of voice samples. Apparently Snowboy will create a public model if 500 samples are provided.

**Comment by xozai** [comment]
Thanks @bionemesis .  I am trying this today.

**Comment by bionemesis** [comment]
My mistake, I gave the wrong folder to upload the voice model. It should be "~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources/".

**Comment by bogdancraciun** [comment]
I'm having the same problem, after I have changed the hotword as described in issue 473. I guess the problem might be related to the fact that I have created the new *.umdl in the browser on the RPi, which implies giving access right to Chrome on my mic.

But I have restarted my pi, revoked Chrome access to the mic, and I still get this messages. I have also tried running ./wakeWordAgent -e kitt_ai as root (not sudo), but that doesn't work either.

**Comment by charlesjevans** [comment]
Thanks for the instructions. Can't believe how hidden this information was. I found the wake word on my Raspberry Pi in: /.local/lib/python2.7/site-packages/snowboy/resources/snowboy.umdl
Then I replaced the *.umdl with one I downloaded from the snowboy website, rebooted, and it worked! Now my Raspberry Pi responds to "Roxanne".
