### ISSUE TITLE
Delete test device in AVS

### ISSUE THREAD

**Issue by lvonder** [alexa/alexa-avs-sample-app#474]
Hi, 
My raspberry pie test is interfering with my Echo Dot. I can't install any skills because German is not supported for this project.
How can I delete my test app? Under the Amazon Developer page I can't delete it and via the Alexa app it is also not possible.
Any ideas?
Thanks

**Comment by lslamp** [comment]
@lvonder go to the following URL, 
https://www.amazon.com/mycd
On this page you should see 3 tabs across the page. the middle tab is YOUR DEVICES. From here you can deregester, they should then be deleted
![image](https://cloud.githubusercontent.com/assets/6013759/21965075/7765052a-db58-11e6-9e46-ea03836fd2cd.png)
![image](https://cloud.githubusercontent.com/assets/6013759/21965093/be63ebda-db58-11e6-8cce-02acbff9053f.png)

Hope that this helps

**Comment by lvonder** [comment]
Thanks. I only tried to deregister within my German Amazon account and there it was not listed.
Now via the Amazon.com website it worked. 
Thx!
