### ISSUE TITLE
Headless Smart Speaker Authorization 

### ISSUE THREAD

**Issue by Kinjalk** [alexa/alexa-avs-sample-app#478]
I am building smart speaker using alexa. I get  Authorization code expired error after and hour. I know I should update the code but I don't know how to do it . How to transfer Authorization code form my website (companion website ) to my product.

**Comment by Kinjalk** [comment]
And after sending the code to product do I need to run some script to get new access token and refresh token every 60.

**Comment by jwhite** [comment]
You can authorize using a companion app (and then you only have to authorize once.)

**Comment by keleric** [comment]
When your access token expires on the device, you should be fetching a new access token via the refresh token that comes with the access token. If you're following the model our sample app takes, then the companion service has a copy of the refresh token, and the device (/ sample app) contacts the service and asks for a new access token. The companion service then takes care of exchanging the refresh token for a new access token, and it returns that to the device. Alternatively, you can use the code challenge method of authorization, described here: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-product-from-an-android-or-ios-mobile-app
