### ISSUE TITLE
Get started guide for WINDOWS platform-Stuck in STEP 4: "Generating Self Signed Certificates" 

### ISSUE THREAD

**Issue by adriancalvob** [alexa/alexa-avs-sample-app#479]
I´m stuck in step 4 "Generating Self Signed Certificates" , in the "Get started" guide for Windows platform. The problem is specifically in point 4/5:

4. Open a command prompt.
5. Change directories to {REFERENCE_IMPLEMENTATION}\samples\javaclient.

Previously we have installed OpenSSL software (step 4.1), configured the environment variable adding OpenSSL bin to the Windows PATH (step 4.2) and edited the ssl.cnf configuration file replacing the "YOUR_" (step 4.3).

URL Step 4: 
https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#4---generating-self-signed-certificates

After complete above steps, I don´t understand: what directories we have to change and where we have to change the directories? but that could be because I don´t know what does "{REFERENCE_IMPLEMENTATION}\samples\javaclient" refer to... 

I imagine that it's related to the folder we get after extract the download zip´s content (step 2:  Clone the Sample App) because we can find the folder "javaclient" in the following location:

alexa-avs-sample-app-master\samples\javaclient

but I don´t have any idea what is {REFERENCE_IMPLEMENTATION}; I have been searching on Google and I think it can be related to the "package.json" we have installed previously...

I have been reading about similar doubts and problems in the other "alexa-avs-sample-app"´s issues but I haven´t found a solution for continue with the next step. I would appreciate any ideas to solve it. Thanks in advance.

**Comment by keleric** [comment]
{REFERENCE_IMPLEMENTATION} is where you downloaded the git repository to (the zip file). There should be a directory "samples" directly under the root of the github repository. Your initial guess was correct.

**Comment by keleric** [comment]
From the instructions:

> Clone the sample app into the directory of your choosing. Open command prompt, navigate to the appropriate directory and type the following:
> 
> git clone https://github.com/alexa/alexa-avs-sample-app.git
> 
> Further instructions will reference this location as {REFERENCE_IMPLEMENTATION}.
