### ISSUE TITLE
ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.

### ISSUE THREAD

**Issue by shishirranjan08** [alexa/alexa-avs-sample-app#483]
Hi ,

I am based out of Bangalore(India)I am using my laptop to use this alexa service.followed all the steps as mentioned on the website.
node js server is running very fine. Have used eclipse to run the java client . while running the java client from eclipse  I have provided the VM argument- -Djna.library.path="C:\Program Files\VideoLAN\VLC".

Once I run the java client it comes up and all the token exchange happens. As instructed in the writeup normally I should see "start listen" button but I do see only "listen button". Even though I click on the listen button wait for a cue and speak , post that it's shows that its doing some processing but after some time I receive the Time out exception.
javaversion - 1.8 and all the steps mentioned has been followed very religiously.

below is the snippet of the same.

05:22:02.311 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:539) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 7 more
05:22:22.319 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.

Please do let me know If i am missing any thing.

I am pasting all the screenshots for your convenience.

node.js server running.
![image](https://cloud.githubusercontent.com/assets/13236029/22187778/625bb810-e132-11e6-8001-4e726b9aab9b.png)

eclipse config details:
![image](https://cloud.githubusercontent.com/assets/13236029/22187784/7f9283f0-e132-11e6-8150-ba71b77a09df.png)

vlc player screenshot:

![image](https://cloud.githubusercontent.com/assets/13236029/22187804/c9b8627e-e132-11e6-9e71-3c5e57911f33.png)

error log with vlc player screenshot:

![image](https://cloud.githubusercontent.com/assets/13236029/22187820/eecf02de-e132-11e6-8340-62488ef3fcab.png)

VLc player timeout exception

![image](https://cloud.githubusercontent.com/assets/13236029/22187830/fecc0966-e132-11e6-9c5a-a3d3723137f7.png)

**Comment by keleric** [comment]
Unfortunately, AVS is not currently supported in India. That's the most likely reason you're seeing TimeoutExceptions.

**Comment by giterliu** [comment]
@shishirranjan08 Have you ever tried to access the service through the US proxy server?

**Comment by tweaty100** [comment]
@keleric if this is not supported in india then is there any reason so that it will work on dragonboard 410c as i am also facing similar issue as @shishirranjan08 what to do now? they have to tell this earlier ,they have to mention it earlier right before delivery to any other country .
@giterliu  how touse the u.s proxy server as i am in INDIA (DELHI) AND HAVE CHANGED THE COUNTRY TO INDIA but still not working .please help and reply as soon as possible.

Thanks in advance

**Comment by tweaty100** [comment]
does this problem solved then please tell me the solution for this?i am still stuck in this problem please 

thanks

**Comment by Deepika0109** [comment]
@keleric 

With the latest announcement by Amazon AVS is now supported to INDIA. But i am still facing the same timeout issue. Please let me know
