### ISSUE TITLE
Client ID 400 Bad Request, client ID is correct.

### ISSUE THREAD

**Issue by Aezwen** [alexa/alexa-avs-sample-app#485]
When going to the localhost page I get:
We're sorry!
An error occurred when we tried to process your request.

400 Bad Request
Unknown client_id

I double checked but the client ID is correct.

**Comment by keleric** [comment]
Where did you get the client id? What does it look like (feel free to XXXX the last bunch of characters)
What about your client secret? Have you double-checked that it is correct?

**Comment by Aezwen** [comment]
There was an error in my Client Secret, I didn't look there for errors because it said unknown client id rather than client secret.

Thanks, sorry for taking time. It works now.. Except for the wakewordagent but that is another issue.

**Comment by keleric** [comment]
Glad it's working!
