### ISSUE TITLE
Error while starting javaclient

### ISSUE THREAD

**Issue by omagarwal25** [alexa/alexa-avs-sample-app#486]
So first I do the second terminal command and after I sign in to amazon I get a error form cromeium saying localhost refused to connect. I tried everything cromeium suggested It didn't work. All help will be appreciated.
![image](https://cloud.githubusercontent.com/assets/25329723/22262259/1713ca46-e268-11e6-9b9a-950e3b61fc44.jpg)

**Comment by keleric** [comment]
1. Is the companion service still running? You should not stop it until you're done using the sample app
2. Check your internet - I've found that RPi's have terrible connections that often drop out.

**Comment by omagarwal25** [comment]
@keleric yes the companion service is still running I will try use enthnet  wire with time

**Comment by omagarwal25** [comment]
I meant this time

**Comment by omagarwal25** [comment]
@keleric I tried suggestion 2 it didnt work but I  looked at the companion service this is what came up.
![image](https://cloud.githubusercontent.com/assets/25329723/22301220/28aca92a-e322-11e6-85f1-1860f162fcc6.jpg)

**Comment by omagarwal25** [comment]
Can someone please help

**Comment by keleric** [comment]
According to the stack trace, it looks like there was an unknown problem retrieving the access tokens. Can you do the following?

- Verify that the clientId and client secret in config.js match exactly what's in the developer portal's security profile section
- The security profile might not be associated with the alexa:all permissions or the product id you are trying to sign into.
-- To fix: Go to the developer portal, find the device that you're trying to log into. Under the "Security profile" tab, click on the dropdown and select the appropriate security profile. Do this even if the correct profile is already selected!

If that fails, please send us the product id, DSN, and time that you tried to log in (include timezone!) so we can debug it on our end.

**Comment by omagarwal25** [comment]
Also I am I UK if that changes anything

**Comment by omagarwal25** [comment]
In

**Comment by Hex-3-En** [comment]
Don't know wheater thats the solution, but your node version looks a bid weird. Maybe you should follow e.g. this:
http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/#install-node
to get a correct up to date version

**Comment by JacobHuschilt** [comment]
I am also having this same issue, with identical error messages. I will try re-installing node, though I don't believe that's the issue.

**Comment by JacobHuschilt** [comment]
I wiped the pi, and reinstalled everything and it works as advertised now, I'm not exactly sure what went wrong. Perhaps a dependency was out of whack or something? Regardless it works fine now.

**Comment by elstryan** [comment]
Hi @JacobHuschilt , 
Glad to hear that you resolved your issue. Marking this issue as close for now. Please re-open if you need anything else.
