### ISSUE TITLE
500 response when trying to retrieve access token from AWS.

### ISSUE THREAD

**Issue by samuelgh** [alexa/alexa-avs-sample-app#488]
## WHAT
During the setup of the alexa sample service on a raspberry pi 3 the aws service responds with a error page while trying to get access token from aws. 

## EXPECTED
> Step 4. You'll be taken to a Dev Authorization page, confirming that you’d like your device to access the Security Profile created earlier. 
Click Okay.

> Step 5. You will now be redirected to a URL beginning with https://localhost:3000/authresponse followed by a query string. The body of the web page will say device tokens ready.

## ACTUAL
After clicking Okay step 5 failes with a 500:response code instead.
![error](https://cloud.githubusercontent.com/assets/6417650/22286066/3e938d00-e2ee-11e6-8387-edabba4cce0e.png)

**Comment by keleric** [comment]
Here are a few things to check:

- Make sure the redirect url is correct and whitelisted! A common mistake is it should be HTTPS, not HTTP. Check your security profile's web settings to verify that the values are correct.
- The security profile might not be associated with the alexa:all permissions or the product id you are trying to sign into.
-- To fix: Go to the developer portal, find the device that you're trying to log into. Under the "Security profile" tab, click on the dropdown and select the appropriate security profile. Do this even if the correct profile is already selected!

If that fails, please send us the product id, DSN, and time that you tried to log in (include timezone!) so we can debug it on our end.

**Comment by samuelgh** [comment]
Thanks for your input keleric.

I messed up and used the security profile name instead of the device type id. It works like a charm with the correct information. 

Perhaps changing the 500-code to a 4XX may give you less annoying issues like this in the future. ;)
