### ISSUE TITLE
Spotify is not supported?

### ISSUE THREAD

**Issue by MopheusDG** [alexa/alexa-avs-sample-app#490]
Hi, I linked my Spotify account on http://alexa.amazon.com/ but it reports "App Support Unavailable". I saw some old report about this but it's closed. Anyway I can help get this working ?

Thanks.

**Comment by keleric** [comment]
Unfortunately, Spotify is not currently supported by AVS. If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. Thanks!
