### ISSUE TITLE
Bluetooth with alexa installed on raspberry pi.

### ISSUE THREAD

**Issue by elblogbruno** [alexa/alexa-avs-sample-app#492]
Is it possible to use a bluetooth dongle on raspberry pi and use it with alexa to connect to your phone?
Anyone has tried it?
Thanks

**Comment by keleric** [comment]
At this time, you cannot duplicate the Echo's bluetooth controls with AVS. If this is something you really care about, I encourage you to create a feature request here: https://forums.developer.amazon.com/spaces/185/index.html
