### ISSUE TITLE
No LED(RGB) Support?

### ISSUE THREAD

**Issue by LucasLundJensen** [alexa/alexa-avs-sample-app#494]
I am wanting to start a project with a Raspberry Pi 3 which includes Alexa and some RGB once I say "Alexa" just like the real Echo does, but is that not supported in the newer versions?

I don't seem to be able to find it anywhere, only in older versions before voice activation was added.

Is it possible to add? Does anyone have a "modded" version of the configs that makes it possible to do so?

**Comment by keleric** [comment]
The sample app never had LED support. If you want that, you'll have to add it yourself or find a forked project that already did that. Simply modifying the configs will not help.

**Comment by keleric** [comment]
See #468

**Comment by Henlav** [comment]
Can someone explain how to add led support to the application?

**Comment by elstryan** [comment]
We don't directly support this yet in our sample app but I did some searching and this seems like a good guide for how to add LEDs to a raspberry PI: https://www.raspberrypi.org/learning/physical-computing-guide/connect-leds/ 

After you're able to change the state of an LED in your project. You could use this method when the app starts recording to turn on the LED: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L260

and this method when the app stops recording to turn off the LED: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L548 

Hopefully this high level guidance is enough information for now. I'll close this issue for now. Feel free to re-open if you need more information.
