### ISSUE TITLE
Spotify is not supported oon this device

### ISSUE THREAD

**Issue by k3nnny** [alexa/alexa-avs-sample-app#498]
Hey people!

I have an issue that alexa on my RPi says "Spotify is not supported on this device" however I changed it as default on alexa app (android) and even the changelog says: "December 8, 2016: The sample app is now officially certified for media and music services."
Am I do something wrong or is it a common issue?

**Comment by jacobdu215** [comment]
Ran into that too :/ Hope its fixed soon..

**Comment by erikhopf-amzn** [comment]
@k3nnny @jacobdu215 - Spotify is not a supported by AVS at this time. However, you do gain access to TuneIn, iHeartRadio, and Audible during device registration.

**Comment by k3nnny** [comment]
@erikhopf-amzn I see. Thank you for your reply. In this case I won't try to make it work. :D

**Comment by jimbroze** [comment]
Is there a plan to support Spotify in the future? And a potential timescale?
