### ISSUE TITLE
npm error step 7

### ISSUE THREAD

**Issue by severin-bruhat** [alexa/alexa-avs-sample-app#500]
Hi,

I encountered this issue on step 7 (cd companionService && npm start) : -bash: npm: command not found. So i did an apt-get instal npm and then new error : 

 alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

Any idea ?

**Comment by pi2bone** [comment]
me too !

**Comment by scotteik36** [comment]
I'm getting the same issue.

**Comment by darkouz** [comment]
I have the same problem. Is there someone with a fix ?

**Comment by darkouz** [comment]
Hi again guys, I think I solved the problem.
try 

$npm install express

There should be two other errors 
Error: Cannot find module 'bodyparser'
Error: Cannot find module 'debug'

Do the same thing.

Let me know if it worked for you too

**Comment by KapiTanirau** [comment]
Hey guys,

Had similar issue and found a simple fix. Rather than  proceeding with 
"Step 4: Clone the sample app

Open terminal, and type the following:

cd Desktop
git clone https://github.com/alexa/alexa-avs-sample-app.git"

I just downloaded on my PC from  https://github.com/alexa/alexa-avs-sample-app.git

Unzipped it and put it on a USB drive and installed it from the USB drive to my Raspberry Pi and then simply followed the rest of the instructions.

Works perfect.

**Comment by scotteik36** [comment]
I tried 
$npm install express
that didn't change anything

I did Kapi's method of just downloading on my Mac then putting on a USB drive, dragging onto my desktop and I noticed that the . automated_install.sh ran differently and now i was able to run the nom code as normal. progressing through now

thanks

**Comment by severin-bruhat** [comment]
hi guys, 

I did as darkouz said, server is running
progressing through now...

thank you

**Comment by Archetype90** [comment]
This is still an issue. 
For whatever reason the PI does not identify the alexa-avs-sample-app/samples/companionService/package.json as valid JSON, even though it is - confirm by both visual inspection and http://jsonlint.com/.

It is certainly OK to manually install the packages, but this question will continue to come up until that problem is resolved. Not sure if it is a PI issue, NPM issue, or what.

**Comment by ambelbasha** [comment]
I'm having the same problem
npm-debug.log looks like this:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 error Error: ENOENT, open '/home/pi/package.json'
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Linux 4.9.35-v7+
7 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error cwd /home/pi
9 error node -v v0.10.29
10 error npm -v 1.4.21
11 error path /home/pi/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]
Any help?

**Comment by vaibhavbhanawat01** [comment]
After running command "npm start" i am getting this error

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm start
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:185:19)
    at Object.urlParse [as parse] (url.js:101:5)
    at Object.validateUrl [as validate] (/usr/lib/nodejs/nopt.js:164:13)
    at validate (/usr/lib/nodejs/nopt.js:212:24)
    at validate (/usr/lib/nodejs/nopt.js:179:11)
    at /usr/lib/nodejs/nopt.js:101:12
    at Array.map (native)
    at /usr/lib/nodejs/nopt.js:67:15
    at Array.forEach (native)


/usr/share/npm/lib/npm.js:32
    throw new Error('npm.load() required')
          ^
Error: npm.load() required
    at Object.npm.config.get (/usr/share/npm/lib/npm.js:32:11)
    at exit (/usr/share/npm/lib/utils/error-handler.js:49:40)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:324:3)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
