### ISSUE TITLE
Never answers question

### ISSUE THREAD

**Issue by SeanOMik** [alexa/alexa-avs-sample-app#501]
I press the "Listen" button on the java window and say "What is one plus one" in the microphone, but I the java script window just says processing and the bar moves left and right across the window. I did sign into the AVS thing. I do see that the bearer token is empty. On this: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi I see that his bearer token is filled. Is that causing the problem? And if so, how do I fix it?

**Comment by SeanOMik** [comment]
Nobody?

**Comment by SamuelBrucksch** [comment]
Token text fild needs tobe filled. Its filled automatically if sign in worked.
