### ISSUE TITLE
Debug prints 

### ISSUE THREAD

**Issue by AnjanaJoshi** [alexa/alexa-avs-sample-app#502]
How to add debug prints in java ? I am relatively new to java. I tried using log.info but I get nothing on the console. I want to trace the code flow of Alexa avs app. please help

**Comment by elstryan** [comment]
Hi, 
Right now the logger is configured to only [print errors to the console](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/log4j2.xml#L20). 

There are a few ways you can view your log statements: 
1) In the same directory that you run mvn exec:exec (javaclient) their should be a file under log/application.log. You can check that file for your logs
2) You can update the config that I linked in the start of this post to send info logs to stdout

Let me know if you need anything else.
