### ISSUE TITLE
Wake word not detected using kitt_ai nor using sensory

### ISSUE THREAD

**Issue by ro8bert** [alexa/alexa-avs-sample-app#505]
Hi, my alexa runs well, but not the wake word (it's like it's deaf). When I use the play button works well, but not with the wake word. My mic is well recorgnized and compatible, and arecord records well.
Maybe I can trigger the button "play" separately, like opening a script or sth, because I have kitt_ai working fine in other projects.

Here's the output using kitt_ai:

INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)     <----- I THINK THIS IS THE PROBLEM, IT STAYS ON IDLE
NFO:KittAiSnowboyWakeWordEngine: thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:WakeWordAgent: thread started
INFO:===> Connected to AVS client <===

Any idea?
Thanks in advance

**Comment by scotteik36** [comment]
I'm getting a similar problem. I can run Alexa using the java applet. But i cannot get either wake word agent to start. kitt_ai is giving me: ERROR: Filed to open PortAudio stream.Device unavailable
and sensory is giving me: Assertion 'ppm' failed.

I'm using a PnP usb mic and HDMI audio output.

**Comment by ro8bert** [comment]
I could solve my problem replacing the alexa.umdl file (in etx/resources, i think) for a custom alexa.pmdl file, and changing its extension to .umdl

**Comment by scotteik36** [comment]
@ro8bert 
ok I found that file but it is blank. where do i get the custom alexa.pmdl file? or what do i put in this file? also... this did not resolve the issue so why did you close this thread?
