### ISSUE TITLE
Spotify not supported for this device

### ISSUE THREAD

**Issue by jimbroze** [alexa/alexa-avs-sample-app#508]
It is my understanding that since the update on December the 8th, the sample app is able to support music streaming services as noted in the changelog: "The sample app is now officially certified for media and music services." However, when attempting to play songs on Raspbian Alexa replies "Spotify is not supported for this device", despite a Spotify premium account being connected on the alexa.amazon website.

**Comment by Alexnagel** [comment]
Please see #498
