### ISSUE TITLE
I don't get a bearer token.

### ISSUE THREAD

**Issue by SeanOMik** [alexa/alexa-avs-sample-app#510]
The text box that says bearer token is empty after I sign in from AVS. My java version is correct. If it matters I am running this on a Raspberry Pi 3 Model B, or attempting to. I have been working on this for almost a week now and I haven't been able to get it working

**Comment by Alexnagel** [comment]
Could you show what's in the terminal when starting the java client? Up till when you'd normally click on listen.

**Comment by SeanOMik** [comment]
Here I put it in pastebin: http://pastebin.com/SEkGZZ69

**Comment by Alexnagel** [comment]
Multiple errors are complaining about not able to read/wite at the end of that output. 
Please check the permissions of the `alexa-avs-sample-app` directory and subdirectories. 

You could execute `chmod 755` to set looser permissions for each directory, if that doesn't work set them to `775`. Using the `-R` option in `chmod` makes it recursive, preventing you need to execute it on each dir

**Comment by SeanOMik** [comment]
YES! It works! Thanks sooo much. So much easier that Jasper. Thanks again!
