### ISSUE TITLE
Amazon login error

### ISSUE THREAD

**Issue by janner6** [alexa/alexa-avs-sample-app#513]
Hi I've been working through the install of Alexa on my raspberry pi 3 model B and it's been going ok until now. I'm up to step 7 terminal 2 I put my credentials into the Amazon login page and then click OK on the next page. Next I get a "I'm sorry there's been an error" webpage. I've tried a few ways but I always get this error. Any ideas?

**Comment by Alexnagel** [comment]
Maybe some of the options discussed in #5 could help?

**Comment by janner6** [comment]
Thanks Alexnagel that helped me get a fix. 

I made another security profile with the device ID as "my_device" and it loaded first time.

Thank again
