### ISSUE TITLE
Command mvn exec:exec - Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

### ISSUE THREAD

**Issue by johnbardeen** [alexa/alexa-avs-sample-app#518]
I'm new to RPi and I'm building Alexa for the first time. I'm almost done but there's this error troubling me. I've seen a lot of other threads in the issues section, but none of them have satisfactorily answered my issues. Please provide me a step by step guide. Thanks in advance :)

When I execute _cd javaclient && mvn exec:exec_
This is displayed - 

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/pi/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/pi/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/pi/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/pi/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/pi/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/pi/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/pi/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/pi/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/home/pi/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:244)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:140)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:140)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:113)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)

**Comment by Alexnagel** [comment]
Did you use the `automated_installer.sh`? That should set the environment correctly, in this case setting the vlc library path. It says it right there in the output.

Re-running the `automated_installer.sh` and checking the output for errors should be a good start

**Comment by johnbardeen** [comment]
@Alexnagel Thanks for the suggestion. But I've tried with the automated_installer.sh several time. I get the same error every time I do it.
Is there any way to set the vlc library path manually?

**Comment by Alexnagel** [comment]
The `automated_installer.sh` executes the needed command, it doesn't give any error or warnings? 

You'd need to execute the following, taken from automated_installer.sh:
- `sudo sh -c "echo \"/usr/lib/vlc\" >> /etc/ld.so.conf.d/vlc_lib.conf"`
- `sudo sh -c "echo \"VLC_PLUGIN_PATH=\"/usr/lib/vlc/plugin\"\" >> /etc/environment"`
- `sudo ldconfig`

**Comment by briandbl** [comment]
发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: johnbardeen  <notifications@github.com>
 

 
 发送时间: 2017-02-06 00:10:06
 

 
 收件人: alexa/alexa-avs-sample-app  <alexa-avs-sample-app@noreply.github.com> 
 

 
 抄送: Subscribed  <subscribed@noreply.github.com> 
 

 
 主题: Re: [alexa/alexa-avs-sample-app] Command mvn exec:exec - Exception inthread "main" java.lang.RuntimeException: Failed to load the native library.(#518)
 



@Alexnagel Thanks for the suggestion. But I've tried with the automated_installer.sh several time. I get the same error every time I do it.
 Is there any way to set the vlc library path manually?

**Comment by johnbardeen** [comment]
@Alexnagel The `automated_installer.sh` does not give any errors. It executes correctly.

I tried executing all the commands you gave to set the library path. But the error still persists.

![2017-02-06-125202_1824x984_scrot](https://cloud.githubusercontent.com/assets/25562249/22647832/83f9202c-ec6b-11e6-9f49-e55fc841f264.png)

Maybe I'll re install raspbian and try Alexa again. Hopefully, this time the vlc library paths will be set correctly :)

**Comment by Archetype90** [comment]
I had a very similar issue with VLC .dll files. I am using 64-bit Windows 10, and my issue was that I had a 32-bit version of VLC installed. After downloading the 64-bit version of VLC, installing, and setting the environment variable the problem was fixed. I am not sure if a similar solution would be viable for a Raspberry Pi, but it can't hurt.

**Comment by johnbardeen** [comment]
Hello @Alexnagel and @Archetype90 , I just re-installed Raspbian on the SD Card and now that error is gone. A new error has occured, but I guess I'll have to open a new thread for that.
Anyway, thanks for the help.
And for everyone out there facing this error, just re install Raspbian :)

**Comment by ersingencturk** [comment]
from terminal try : sudo apt-get install vlc
