### ISSUE TITLE
Get Alexa to switch audio outputs on PI

### ISSUE THREAD

**Issue by 1liminal1** [alexa/alexa-avs-sample-app#519]
Hi guys, 

Wondering if there is a way to get AVS to switch audio outputs on the PI?

For example, switch output HDMI Audio to an AVR from a small speaker on the headphone jack after asking Alexa to play music from i heart radio.

**Comment by Alexnagel** [comment]
Yes that would be possible, you'd have to alter source code of the javaclient. 
I think it would be somewhere in the `AVSAudioPlayer` file, something around `handlePlay`. But I don't know exactly how you'd see the difference between speech output and music output. There's probably a directive or something for it.

**Comment by 1liminal1** [comment]
I was more thinking of just asking Alexa to switch output after asking it to turn on the amp, or setting a scene in yonomi to turn on the amp and change the output to play though the amp, then when you switch off the amp it goes back to the headphone jack

**Comment by Alexnagel** [comment]
That'd be easier, you'd have to create a skill for that. Creating some code on your Pi to change the output when the skill is called, using lambda as a gateway or you could have the Pi as HTTP endpoint.

**Comment by 1liminal1** [comment]
mmm thanks, something to think about

**Comment by Firedan1176** [comment]
The target audio output is assigned when you first run the `automated_install.sh` script and it asks whether you're using 3.5mm or HDMI. The script simply runs the following command: `sudo amixer cset numid=3 2`. Nothing else is changed. Therefore, you should just be able to run this in a terminal and your output should be configured correctly.

**Comment by bweatherhead** [comment]
Hello I think I have a similar issue. Right now I've got a justboom amp board mounted on my pi. I have two speakers coming off the amp. I would like to set that as the output sound, but when setting up AVS on the pi it only gives me two options for audio output, mini hdmi and 3.5mm jack. I've been searching for a few days for solutions. How can I set the audio output so it goes through my amp and speakers? Thanks!

**Comment by Firedan1176** [comment]
Bweatherhead, I'd suggest looking at the FAQ for your amp at https://www.justboom.co/faqs/. You can change the audio output by typing `sudo raspi-config` in the terminal, going to Advanced, and changing the audio output. let me know if that works, based off of the solutions on the FAQ.

**Comment by bweatherhead** [comment]
Alright I tried that. Now how do I reset the audio output that I was prompted about during AVS setup? Do I have to reinstall and go through those prompts again?

**Comment by bweatherhead** [comment]
Thank you very much for you help so far!

**Comment by bweatherhead** [comment]
Decided to reinstall. When it came to the prompt about audio output the only two options were still 3.5mm jack and HDMI audio output. What am I missing? Where do I need to go to select my justboom amp as the output?

**Comment by Firedan1176** [comment]
Did you try the recommendations for updating your kernel using apt-get in the terminal? I would suggest completely reading the FAQ I posted if you haven't.

**Comment by Firedan1176** [comment]
No, you do not need to reinstall AVS. If you scroll up, you will find my first comment where I said all you need to do is type a command in the terminal. AVS does not do anything internally, that I am aware of.

The reason you do not see your amp as an option in the installer for AVS is because the installer only cares about 3.5mm or hdmi. You will have to change it using a command from the terminal yourself. For that screen from the installer, you might as well select a random one.

I am not sure how to correctly change the output. That will most likely be listed under the FAQ of the amp's website, or at their forums, if they have one.

The audio output has nothing to do with AVS. The installer simply changes how your pi will output audio, not the AVS application.

Let me know if you find anything on the FAQ/forums and if you still have problems.

**Comment by bweatherhead** [comment]
I tried everything on the FAQ. OS is up to date on pi. Added a few lines to the config.txt file in the boot directory (suggested o the FAQ). Under the audio settings in sudo raps-config the only options showing up are the 3.5 jack and HDMI still. Thanks for your patience. I am pretty new to the raspberry pi (liking it a lot so far). Any other suggestions? Thanks!

**Comment by Firedan1176** [comment]
Check out https://www.justboom.co/software/configure-justboom-with-raspbian/

**Comment by Firedan1176** [comment]
Try this:

Make sure your amp is completely up and running and change the audio output to auto in raspi config. Reboot and see if that works. If not, I have no other recommendations.

**Comment by bweatherhead** [comment]
I'll keep trying stuff out with the sound. Ran into another problem. Wasn't letting me register my device (kept saying "can't process request right now"). Just to make sure I'm doing everything right, these are the three codes I need when putting in my account info during setup correct?
<img width="273" alt="screen shot 2017-05-02 at 5 26 44 pm" src="https://cloud.githubusercontent.com/assets/10283874/25640201/b82e0432-2f5c-11e7-98b5-15c6ad9461ad.png">

**Comment by Firedan1176** [comment]
You don't need the security profile ID. The first field that the installer will ask for is the product ID. This is what you called your raspberry pi when you registered it before you made the security profile.

**Comment by bweatherhead** [comment]
Awesome thank you so much for your patience. You've been really helpful!

**Comment by 1liminal1** [comment]
I've been following this thread for a while and keep thinking to myself, just get an Echo Dot. I did, so much more responsive then running it on a Pi. 

But now I under stand what you're actually trying to do and you are a genius!!

I've been wanting to do something slimier but use Forked-Daapd to output music from en echo dot to SharePort, it works ok, cant control the connection though, but it does give me multi room audio. But this is a great idea for an outdoor standalone player. I love it!

Please let me know how stable it is?

**Comment by bweatherhead** [comment]
Hello, while I appreciate your praise I must admit I am far from genius. Do you have any idea as to how I would change the audio output to an amplifier?

**Comment by 1liminal1** [comment]
LOL, its pretty genius

Anyway, you must be able to do it. 

But first do you know if the just boom amp is working? 

Have you followed this?

https://www.justboom.co/software/configure-justboom-with-raspbian/

If that's working ok and you can get sound, have a look around on how to make it the only sound device available on the Pi. They select the headphone jack as the audio output and hope that AVS does not hardcode the on board sound. 

Im going to try this as well, but it will be a few weeks till I get my Zero Amp Hat

**Comment by Firedan1176** [comment]
1liminal1, you can not play Pandora on Alexa using AVS on a raspberry pi. iHeartRadio and a few others work, however.

**Comment by 1liminal1** [comment]
Your right!

I was thinking of spotify, but thats not going to work. 

Dam it!! Not sure why they make it so hard!
