### ISSUE TITLE
 java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.createExtension

### ISSUE THREAD

**Issue by C-Volume** [alexa/alexa-avs-sample-app#520]
I  run mvn exec:exec return the error (windows)

how deal with....

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-16" java.lang.NoSuchMethodError: sun.security.ssl.Su
pportedEllipticCurvesExtension.createExtension(Ljava/security/AlgorithmConstrain
ts;)Lsun/security/ssl/SupportedEllipticCurvesExtension;
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshake
r.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:
1487)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.
java:1351)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387
)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:
559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.cal
lService(CompanionServiceClient.java:203)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.get
RegistrationCode(CompanionServiceClient.java:156)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.requestRegistrationCode(CompanionServiceAuthManager.java:76)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.startNewProvisioningRequest(CompanionServiceAuthManager.java:68)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.startRemoteProvisioning(CompanionServiceAuthManager.java:63)
        at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95)

**Comment by Alexnagel** [comment]
Could you check if you have the correct ALPN version for your JDK. See below link, bullet 3.
https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#6---run-the-sample-app

**Comment by btkramer9** [comment]
Has anyone found a fix to this? I'm having the exact same problem. And yes I've checked ALPN matches the JDK

**Comment by elstryan** [comment]
Did you do a mvn install after updating the ALPN version?

**Comment by btkramer9** [comment]
I resolved it but didn't pinpoint exactly what solved it. I had multiple jdks on my computer and there was no JAVA_HOME defined in the system. I also had mismatching dsn and product id numbers in config.js and config.json

**Comment by elstryan** [comment]
Thanks! I'll close this issue and we'll keep our eye out for this in the future.

**Comment by mburm** [comment]
I have the same problem on a Rasberry Pi 2. config.js and config.json have matching dsn/productId, ALPN is correct, followed by mvn install. Other ideas?

**Comment by BennyAvramson** [comment]
@mburm, Please run following commands from within `javaClient` directory and paste the output here:
```bash
java -version
javac -version
grep alpn-boot.version *.xml
```

**Comment by mburm** [comment]
@BennyAvramson  There you go!

pi@raspberrypi:~/alexa-avs-sample-app/samples/javaclient $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
pi@raspberrypi:~/alexa-avs-sample-app/samples/javaclient $ javac -version
javac 1.8.0_65
pi@raspberrypi:~/alexa-avs-sample-app/samples/javaclient $ grep alpn-boot.version *.xml
pom_other.xml:    
pom_other.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_other.xml:      <version>${alpn-boot.version}</version>
pom_other.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
pom_pi.xml:    
pom_pi.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_pi.xml:      <version>${alpn-boot.version}</version>
pom_pi.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
pom.xml:    
pom.xml:    
pom.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom.xml:      <version>${alpn-boot.version}</version>
pom.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>

**Comment by BennyAvramson** [comment]
Check [SampleApp README](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/README.txt ) and change the `alpn-boot.version` in `pom.xml` accordingly (e.g. for 1.8.0_65 it's `8.1.6.v20151105`)

**Comment by ambelbasha** [comment]
Benny Avramson i think there is an isssue with the java version. This probably will help : http://www.rpiblog.com/2014/03/installing-oracle-jdk-8-on-raspberry-pi.html. I manage to run mine but i'm getting another error . Good luck !

**Comment by ambelbasha** [comment]
I already dit that . Thanks !

**Comment by rk-kant** [comment]
Hi,

I am getting the same issue while running java client.

following is the details of the same:

raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# 
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# javac -version
javac 1.8.0_161
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# grep alpn-boot.version *.xml
pom_other.xml:    
pom_other.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_other.xml:      <version>${alpn-boot.version}</version>
pom_other.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
pom_pi.xml:    
pom_pi.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom_pi.xml:      <version>${alpn-boot.version}</version>
pom_pi.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
pom.xml:    
pom.xml:    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
pom.xml:      <version>${alpn-boot.version}</version>
pom.xml:              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# apt-get update
E: Malformed line 6 in source list /etc/apt/sources.list (dist parse)
E: The list of sources could not be read.
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient# apt-get install vlc-nox vlc-data
Reading package lists... Done
Building dependency tree       
Reading state information... Done
vlc-data is already the newest version.
vlc-nox is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/javaclient#

**Comment by rk-kant** [comment]
I am not able to find the compatible alpn version with java version "1.8.0_161". Can you please help me out in this.
