### ISSUE TITLE
Raspberry Pi 3 Jessie/Pixel -- npm start issues

### ISSUE THREAD

**Issue by mohits-chaayos** [alexa/alexa-avs-sample-app#526]
I'm running this on a Raspberry Pi 3 and failed on step 7. I've gone through the closed and open issues with NPM on this forum and it looks like my issue is a new one, hence posting. If someone can help, please do

**Issue**
"> npm start" does not seem to work and ends in an error. Here is the error message:
`root@Alexa:/home/pi/Desktop/alexa-avs-sample-app/samples/companionService# npm start
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.38-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
`

**Error Log**:
Here is the output from the npm-debug.log file

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@1.4.21
> 3 info using node@v0.10.29
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart alexa-voice-service-sample-companion-service@1.0.0
> 6 info start alexa-voice-service-sample-companion-service@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
> 9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
> 9 error Exit status 1
> 10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
> 10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
> 10 error not with npm itself.
> 10 error Tell the author that this fails on your system:
> 10 error     node ./bin/www
> 10 error You can get their info via:
> 10 error     npm owner ls alexa-voice-service-sample-companion-service
> 10 error There is likely additional logging output above.
> 11 error System Linux 4.4.38-v7+
> 12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 13 error cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> 14 error node -v v0.10.29
> 15 error npm -v 1.4.21
> 16 error code ELIFECYCLE
> 17 verbose exit [ 1, true ]
>

**Comment by shikhar-chaayos** [comment]
Never mind Issue is resolved. Please do a npm install first and then do npm start.
