### ISSUE TITLE
Please include wiringpi in the install script

### ISSUE THREAD

**Issue by martinfandel** [alexa/alexa-avs-sample-app#531]
Hi,

please include wiringpi in the install script. Otherwise the compile of the wakeword fails.

Thank you!

BR

Martin

**Comment by jordan-heier** [comment]
This is related to pull request https://github.com/alexa/alexa-avs-sample-app/pull/438. Will keep this issue open until the pull request has been accepted.

**Comment by scotthea-amazon** [comment]
This is a duplicate of #438.   That issue will be closed when the pull request is included in a release.  Closing this issue.
