### ISSUE TITLE
/usr/bin/ld: cannot find -lasound

### ISSUE THREAD

**Issue by BenjiKCF** [alexa/alexa-avs-sample-app#534]
I am trying to run this line of code

`cd wakeWordAgent/src && ./wakeWordAgent -e kitt_ai`

and then it shows No such file or directory. Getting back to the autoinstall and there is a message

`Linking CXX executable wakeWordAgentTest
/usr/bin/ld: cannot find -lasound
collect2 error: ld returned 1 exit status
CMakeFiles/wakeWordAgentTest.dir/build.make:538L recipe for target 'wakeWordAgentTest failed`

I am running it on a raspberry pi 3 with noobs. Not sure what is it about, anybody has the same problem?

**Comment by Alexnagel** [comment]
Seems like you're missing the development package for asound. Try `sudo apt-get -y install libasound2-dev`

**Comment by kjkh** [comment]
Closing issue. Feel free to re-open if you have further questions.
