### ISSUE TITLE
Issue in authencitation

### ISSUE THREAD

**Issue by chinmayshah99** [alexa/alexa-avs-sample-app#545]
When I try to authenticate the Pi through amazon account, it shows error while processsing the request.

**Comment by sanjayrd** [comment]
Could you provide more details? What kind of errors are you getting?

**Comment by stefhannisse** [comment]
I have the same problem. When i log in there is a screen that says: An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to solve it shortly. When i got to the port in the webpage, there is also an error. There the error is: {"error" : "MissingParams"."message":"The following parameters were missing or empty strings: code, state"}. How can i solve this problem?

**Comment by chinmayshah99** [comment]
![image](https://cloud.githubusercontent.com/assets/10958613/23103544/8d429c2c-f6e2-11e6-8dc8-04e16705eb49.png)

**Comment by charanya13** [comment]
encountered the same problem. Is there a solution to it?

**Comment by Henkx** [comment]
Hi i have the same problem :( maybe Amazon change something with authencitation?

**Comment by shirltone** [comment]
Hi, I too am having the same problem. Any ideas?

**Comment by Alexnagel** [comment]
@chinmayshah99 It seems your certificate isn't valid. For simplicities sake, try rerunning the `automated_installer.sh`

**Comment by chinmayshah99** [comment]
@Alexnagel tried re-running` automated_install.sh`. The same problem persists

**Comment by shirltone** [comment]
I've tried running install again but it made no difference.

**Comment by shirltone** [comment]
Solved my problem by what was suggested in issue [#5](https://github.com/alexa/alexa-avs-sample-app/issues/5) about making device id and device name both equal my_device.

**Comment by chinmayshah99** [comment]
Issue #5  's solution helped me. There was problem with device id and security profile.

**Comment by TeamKalis** [comment]
This never helped me. I'll rerun automated. I'm on the verge of giving up on this project.

**Comment by amark14912** [comment]
Solved my problem using issue #5 . Thank you
