### ISSUE TITLE
At step 7 i get this issue bash: mvn: command not found

### ISSUE THREAD

**Issue by larserno** [alexa/alexa-avs-sample-app#549]
bash: mvn: command not found
on step 7 terminal 2 i get the error message that mvn cant be found, Ive reinstalled both node.js and alexa voice service with no luck. Please help!

**Comment by AR019** [comment]
Did you update and or upgrade before using the Pi?

Run these in terminal (use -f if you already updated and or upgraded to repair any broken packages.):

sudo apt-get update
sudo apt-get upgrade

If that doesn't work, you will need to install Maven manually: https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=112184

**Comment by larserno** [comment]
Thank you so much. Did just that and reinstalled and it works now!
