### ISSUE TITLE
While configuring Alexa for raspberripi, getting issues

### ISSUE THREAD

**Issue by monupurohit** [alexa/alexa-avs-sample-app#550]
Used the script:
http://www.mediafire.com/file/txcar7sj5198104/start_alexa.sh 

pi@raspberrypi:~/Desktop $ ./start_alexa.sh
Starting sample app.
When finished
Press space to continue..../start_alexa.sh: line 10: mvn: command not found

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alex                                                                                        a-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend                                                                                         them for the AVS app.

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/compani                                                                                        onService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/w                                                                                        ww`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start                                                                                         script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-compa                                                                                        nion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.18+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path                                                                                        : 'npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.1.18+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-                                                                                        debug.log
npm ERR! not ok code 0
^[[Api@raspberrypi:~/Desktop $ [A./start_alexa.sh: line 16: ./wakeWordAgent: No such file or directory                                                                sudo tar -xzvf /path/to/apach^C

**Comment by Alexnagel** [comment]
Have you installed alexa using the `automated_installer.sh`? Seems like you have some dependencies not set, such as maven.

**Comment by monupurohit** [comment]
Thanks.
Its worked ...

**Comment by max-erler** [comment]
Closing this issue since it has been resolved.
