### ISSUE TITLE
In step 7 i get this errormesage when I try starting wakeup engine

### ISSUE THREAD

**Issue by larserno** [alexa/alexa-avs-sample-app#551]
./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.4 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 May 2017 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started

What can i do?

**Comment by Alexnagel** [comment]
Could you check #533 and see if any of those steps help?

**Comment by larserno** [comment]
tried everything on that post and it doesnt seem to help. Did run the test for wakeupengine and i get this error message; ERROR:test trace
 **** Logging tests passed ok ****
ERROR (Input():snowboy-io.cc:266) Fail to open input file "../ext/resources/common.res"
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (Input():snowboy-io.cc:266) Fail to open input file "../ext/resources/common.res"

[stack trace: ]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZN7snowboy13GetStackTraceEv+0x34) [0xc0538]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZN7snowboy13SnowboyLogMsgD1Ev+0x4b8) [0xc0b78]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZN7snowboy5InputC1ERKSs+0x264) [0xb56d4]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZN7snowboy22UnpackPipelineResourceERKSsPSs+0x28) [0xad058]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZN7snowboy13SnowboyDetectC1ERKSsS2_+0x1d4) [0x9b98c]
.
.
.
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_ZSt11make_sharedIN13AlexaWakeWord27KittAiSnowboyWakeWordEngineEJP18DummyWakeWordAgentEESt10shared_ptrIT_EDpOT0_+0x44) [0x80fa0]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_Z16createTempKittAiv+0x40) [0x80c78]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(_Z10testKittAiv+0xc) [0x80cb8]
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/wakeWordAgentTest(main+0x64) [0x807ac]
/lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x114) [0x76b89294]

Aborted

**Comment by My3VM** [comment]
@larserno We too are running into this issue :(
Could you please share some hints about how did you solve this problem?

Thanks in advance!
My3

**Comment by orobsonpires** [comment]
I got the same issue. I solved it following this thread #533 specifically using the hints from @Alexnagel

**Comment by larserno** [comment]
I really dont know how I solved the issue, I just followed the steps and I tried the kitt.ai wakeengine and it didnt work, but then I tried the Sensory one and it magically worked. Thats what I did

**Comment by My3VM** [comment]
Thanks for the reference, #533 resolved all my issues.
