### ISSUE TITLE
Step 7 error

### ISSUE THREAD

**Issue by Kristiangrue** [alexa/alexa-avs-sample-app#554]
During step 7 when i open the link this comes up

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
client_id=amzn1.application-oa2-client.0ce39ceb35aa44f2aff06af1299ceefc
response_type=code
redirect_uri=https://localhost:3000/authresponse
scope=alexa%3Aall
state=799b7c9e-1147-4bee-922c-683fea7c6020
scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22EchoPi%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22123456789%22%7D%7D%7D

**Comment by Kristiangrue** [comment]
Found a fix saved the link as a Allowed Return URL before opening it

**Comment by cfentress** [comment]
What did you do to fix it?
I am getting the same error and I've gotten as far as editing my security profile, but there is no Web Services tab for me to place this URL. Did you have a similar issue, or was your Web Services tab already there?

**Comment by appendixie** [comment]
for cfentress....
My producs, manage,Security Profile,Allowed return URLs, put here :https://localhost:3000/authresponse, give a add, and save settings.   Bingo (for me)
greetings, Ad
