### ISSUE TITLE
Step 7, mvn exec:exec error

### ISSUE THREAD

**Issue by russcv** [alexa/alexa-avs-sample-app#556]
Hi. I'm having trouble with Step 7 on the second window, and I have't seen anyone post about this one yet. 
The error is:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.107s
[INFO] Finished at: Mon Feb 20 20:22:34 EST 2017
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples/javaclient $ run mvn -X exec:exec
bash: run: command not found
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples/javaclient $ run mvn -X exec:exec
bash: run: command not found
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples/javaclient $ run mvn -X exec:exec
bash: run: command not found
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples/javaclient $ cd javaclient && mvn exec:exec
bash: cd: javaclient: No such file or directory
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples/javaclient $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.303s
[INFO] Finished at: Mon Feb 20 21:18:49 EST 2017
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

- After the first time seeing this issue, I reran the _automated_install.sh_ to make sure everything was installed properly.
- _java -version_ correctly finds java 1.8.0_121
- _mvn -version_ does not work right off the bat, I have run _export M2_HOME=/usr/share/maven_ in order to relocate it.

After relocating maven, I run _cd javaclient && mvn exec:exec_ in the terminal. This is when I get the above error.

EDIT: Since I saw this in another thread. I tried running _run mvn -X exec:exec_ and I get:
**bash: run: command not found**

**Comment by cmmh** [comment]
I'm having the exact same problem. I don't get the bash: run: command not found error, though.
I'll try to pull the previous commit and see if that fixes things or not...

**Comment by Alexnagel** [comment]
@russcv if you leave out the `run` bit it should work. So what you want to run is the following:
`mvn -X exec:exec` in the directory `~/Desktop/alexa-avs-sample-app/samples/javaclient`  

Then post the output here

**Comment by cmmh** [comment]
I feel like its a clue that mvn clean fails.  

```
@pi3-ts:~/Desktop/alexa-avs-sample-app/samples/javaclient$ mvn clean
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.987 s
[INFO] Finished at: 2017-02-21T14:59:30-05:00
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): java.lang.IllegalStateException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by Alexnagel** [comment]
@cmmh you're sort of taking over this issue....  
For one you don't have your JAVA_HOME set... 

`export JAVA_HOME=<java sdk location>`
where `<java_sdk_location>` is the location of your java sdk, find it with `readlink -f $(which java)` and copy until the `/jre` part

If the error still persists: [try this](http://stackoverflow.com/questions/30522679/plugin-org-apache-maven-pluginsmaven-clean-plugin2-5-or-one-of-its-dependencie)

**Comment by cmmh** [comment]
I've traced it down to some internal error with SSL when downloading from the maven repo.  Perhaps a java problem.

`*** ECDHClientKeyExchange
ECDH Public value:  { 4, 28, 23, 159, 231, 106, 153, 221, 171, 207, 119, 156, 189, 171, 255, 245, 10, 168, 47, 156, 132, 248, 211, 71, 145, 145, 3, 141, 174, 31, 82, 188, 22
8, 90, 78, 147, 30, 235, 89, 110, 206, 220, 236, 238, 158, 162, 144, 7, 154, 11, 230, 71, 189, 157, 78, 187, 106, 125, 104, 22, 111, 88, 209, 152, 79 }
[write] MD5 and SHA1 hashes:  len = 70
0000: 10 00 00 42 41 04 1C 17   9F E7 6A 99 DD AB CF 77  ...BA.....j....w
0010: 9C BD AB FF F5 0A A8 2F   9C 84 F8 D3 47 91 91 03  ......./....G...
0020: 8D AE 1F 52 BC E4 5A 4E   93 1E EB 59 6E CE DC EC  ...R..ZN...Yn...
0030: EE 9E A2 90 07 9A 0B E6   47 BD 9D 4E BB 6A 7D 68  ........G..N.j.h
0040: 16 6F 58 D1 98 4F                                  .oX..O
main, WRITE: TLSv1.2 Handshake, length = 70
[Raw write]: length = 75
0000: 16 03 03 00 46 10 00 00   42 41 04 1C 17 9F E7 6A  ....F...BA.....j
0010: 99 DD AB CF 77 9C BD AB   FF F5 0A A8 2F 9C 84 F8  ....w......./...
0020: D3 47 91 91 03 8D AE 1F   52 BC E4 5A 4E 93 1E EB  .G......R..ZN...
0030: 59 6E CE DC EC EE 9E A2   90 07 9A 0B E6 47 BD 9D  Yn...........G..
0040: 4E BB 6A 7D 68 16 6F 58   D1 98 4F                 N.j.h.oX..O
main, handling exception: java.lang.IllegalStateException
%% Invalidated:  [Session-1, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
main, SEND TLSv1.2 ALERT:  fatal, description = internal_error
main, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 02 50                               ......P
main, called closeSocket()
`

**Comment by russcv** [comment]
Man, I got a whole bunch of terminal vomit from `mvn -X exec:exec`

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.38-v7+", arch: "arm", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/pi/.m2/settings.xml
[DEBUG] Using local repository at /home/pi/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/pi/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.apache.maven:standalone-pom:pom:1: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.5.0 from repository central (https://repo.maven.apache.org/maven2, releases)
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.apache.maven:standalone-pom:pom:1
[DEBUG] Tasks:   [exec:exec]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.5.0 from repository central (https://repo.maven.apache.org/maven2, releases)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.apache.maven:standalone-pom:1
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <async default-value="false">${exec.async}</async>
  <asyncDestroyOnShutdown default-value="true">${exec.asyncDestroyOnShutdown}</asyncDestroyOnShutdown>
  <basedir default-value="${basedir}"/>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <executable>${exec.executable}</executable>
  <longClasspath default-value="false">${exec.longClasspath}</longClasspath>
  <outputFile>${exec.outputFile}</outputFile>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${exec.skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
  <toolchain default-value="jdk">${exec.toolchain}</toolchain>
  <workingDirectory>${exec.workingdir}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.517s
[INFO] Finished at: Tue Feb 21 18:48:47 EST 2017
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/pi). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/pi). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:179)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.lifecycle.MissingProjectException: Goal requires a project to execute but there is no POM in this directory (/home/pi). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by russcv** [comment]
Closing this issue. I finally resolved my problem. I had to run through the procedure a few times before it finally worked. Just requires some patience and determination. 

I ended up deleting the entire alexa directory and redownloaded everything.
