### ISSUE TITLE
Possible to set up on Pi without X11 Display? (Only through terminal?)

### ISSUE THREAD

**Issue by smholsen** [alexa/alexa-avs-sample-app#560]
Are there any ways of running the samples/javaclient maven project without GUI?

**Comment by Alexnagel** [comment]
With this project, no.
There is #86 but that still requires X
And there's #431. Don't know what their requirements are

**Comment by smholsen** [comment]
Allright, Thanks! :)

**Comment by itayavra** [comment]
Hey, I created a small script to run it headless with one command (and without sleep so it runs as fast as possible).
Feel free to try and let me know what you think (alexa-avs-sample-app should be installed as a prerequisite for my script):
https://github.com/itayavra/alexa-headless-start
