### ISSUE TITLE
Java application error on raspbian

### ISSUE THREAD

**Issue by smholsen** [alexa/alexa-avs-sample-app#562]
Hello. so I am trying to run the sample app on my raspberry pi, but the mvn terminal shows errors allready when the chromium window pops open for the tokens. 

When I click the button in the java app to record I get a NullPointerException, (could this simply be that my microphone does not work? I have tested it by recording a short 10s wav file and played it back and that worked.. )

Any ideas on how I can fix this?

Here are the errors from the mvn terminal; http://pastebin.com/dsHRtXVR

**Comment by elstryan** [comment]
Hi, 
Are you still running into this issue? This does sound like a problem with the microphone. How is the microphone connected to your PI? Is it possible to try a different microphone (I've always tested with USB microphone)?

Here's a related issue: https://github.com/alexa/alexa-avs-sample-app/issues/364 that might be of some help.

**Comment by smholsen** [comment]
Thanks for the reply. 
The issue was indeed with the microphone not being recognized. I followed some steps to setuup the microphone and after that it went smoothly. (My microphone has bad pi support), I will try to post the name of the mic and the link to the steps to follow at a later time. 

Thanks again! :)
