### ISSUE TITLE
wakeWordAgent not working under ubuntu 16.10

### ISSUE THREAD

**Issue by lmore377** [alexa/alexa-avs-sample-app#576]
I want to use alexa on my ubuntu pc, and it builds and works fine, but when it was compiling, it couldn't compile the wakeWordAgent part of the package, so it dosen't work. When i manually tried to run make it was missing the wiringpi library. Is there anything i can do?

**Comment by scotthea-amazon** [comment]
Hello Imore377,
Currently the wakeWordAgent support is limited to the Raspberry PI platform. 
-SWH

**Comment by elstryan** [comment]
Closing the issue since their was no follow up questions and this is currently a limitation of the wake word agents.
