### ISSUE TITLE
Raspberry Pi 3 Bluetooth Speaker

### ISSUE THREAD

**Issue by Eddd97** [alexa/alexa-avs-sample-app#577]
Hi! I am trying to make Alexa output the sound through a bluetooth speaker that is connected to Raspberry Pi 3. I get all the sound from the Raspberry through the speaker, but no sound from Alexa. I've seen other similar issues, but the info provided there didn't help me. Thanks!

**Comment by bigapple10027** [comment]
Hi @Eddd97 ,

You can check a few things:

1. Check if you have received the directives correctly from Alexa. You can tell this from the log I think.

2. If you can receive the directives from the Alexa correctly, then check if Alexa is muted. Or you can try ask Alexa to set the volume to the full volume.

**Comment by Eddd97** [comment]
What do you mean by "correctly directives"? I've checked the log file and I think it looks ok. I am also sure that alexa isn't muted. Anyway, it seems I am getting an error when I try to talk to alexa for the first time after I connect the speaker: "line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2bytes/frame, little-endian not supported ". After I dismiss this error Alexa seems to work ok, except the fact that it doesn't output any sound.

**Comment by Eddd97** [comment]
Another fact that I've noticed is that the Alexa javaclient app doesn't appear in Pulse Audio Volume Control panel under the playback tab, while other "apps" appear (like aplay when playing a wav file from terminal).

**Comment by Alexnagel** [comment]
@Eddd97 That error you dismiss is the most likely reason why it doesn't work.
Try running pulse audio as daemon, see #533

**Comment by D3rpi** [comment]
@Eddd97 I have a similar set up and remember having that error too. It's been a while since I fixed it. IIRC, I had to change something in pulseaudio volume control to make it work. 
My configuration in volume control is as follow:
Bcm2835 ALSA
Profile: Analog Stereo Output

Aukey(My bluetooth speaker)
Profile: High fidelity Playback (A2DP Sink)

Hope that helps.

**Comment by Eddd97** [comment]
@Alexnagel Thank you! I've managed to make it work, following your instructions from that post.
