### ISSUE TITLE
./wakeWordAgent - No Such File or Directory

### ISSUE THREAD

**Issue by russcv** [alexa/alexa-avs-sample-app#578]
When I follow the instructions for Terminal Window 3 with the code below, the file can not be found.
```
pi@raspberrypi ~ $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi ~/Desktop/alexa-avs-sample-app/samples $ cd wakeWordAgent/src && ./wakeWordAgent -e sensory
bash: ./wakeWordAgent: No such file or directory
```
I browsed through the files and have found the WakeWordAgent.h and .cpp files in directory referenced by the code. Are these the correct files that should be called? Any reason they can not be found in the Terminal? 

Edit: I am using a Raspberry Pi 2

**Comment by bonhomie** [comment]
have u tried to run the . wakeWordAgend -e kitt_ai?

**Comment by russcv** [comment]
Yes, same problem occurs

**Comment by Alexnagel** [comment]
Probably haven't been built, did you install using `automated_installer.sh`? You could rerun that.

Other option:
`cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4`

**Comment by russcv** [comment]
Yes I used `automated_installer.sh`. 

I tried your second option, it seems it could not find a file. Interesting... maybe it is a clue why it didn't work for me. Here is the output
`pi@raspberrypi ~ $ cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src &&cmake . &&make -j4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp:6:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:374: recipe for target 'CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
I reran `automated_install.sh` this morning. I found this error during the install:
`Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
[ 33%] Building CXX object CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp:6:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:374: recipe for target 'CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
[ 15%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 25%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/SensoryWakeWordEngine.cpp.o
[ 30%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp:6:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
[ 35%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp.o
CMakeFiles/wakeWordAgentTest.dir/build.make:326: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

=============================
*****************************
========= Finished ==========
*****************************
=============================
`
I suppose we know why its not working on my Pi now. 
Any suggestions?

**Comment by Alexnagel** [comment]
Ah you're missing wiringPi, it isn't included in the dependencies.
`sudo apt-get install wiringpi` and try building again. If it doesn't compile again, check #571

**Comment by russcv** [comment]
cool, I installed it and reran `automated_installer.sh`. I'm up and running now. Thanks for the feedback. Closing the issue.

**Comment by yoyo7373** [comment]
OMG thanks a lot the same problem has been bothering me for a while.

**Comment by KriyenKP** [comment]
When I try this : 

`cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4`
 
I get this

```
~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/ && cmake . && make -j4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[  6%] Linking CXX executable wakeWordAgent
CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by meganstapley** [comment]
I am having the same problem but I have wiringPi...anyone have any other solutions?

**Comment by wzone001** [comment]
I alse got this problem, and i check th wiringpi have installed and show the newest version(2.44)....anyone can give me some advise??thanks

**Comment by petealves** [comment]
Anyone here got it to work? I'm having the same problem as @KriyenKP

**Comment by HansMees** [comment]
I am having the same problem as @KryenKP

**Comment by wzone001** [comment]
https://github.com/alexa/alexa-avs-sample-app/issues/902   see this one maybe can solve this problem @petealves @HansMees
