### ISSUE TITLE
Documentation error:  No mention of Amazon Music

### ISSUE THREAD

**Issue by szaske** [alexa/alexa-avs-sample-app#580]
I was following the step by step guide, to create a AVS device (url is [here](https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile)), and the screenshots and wording does not mention a 4th tab labeled "Amazon Music".  I assume this is a new feature added after the guide was written.  It would be nice to update the guide to include this new feature.

**Comment by scotthea-amazon** [comment]
Hi szaske,

Thank you for pointing this out!

**Comment by scotthea-amazon** [comment]
Hello again, it turns out that the option was recently removed, and the documentation is actually up to date.

**Comment by elstryan** [comment]
I verified this as well. Closing this issue.
