### ISSUE TITLE
Error on device(linux) authorization by windows or android

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#590]
Dear
I installed AVS on ubuntu, all is successful. Now I want to use windows or android to do Oauth login. But meet the error bellow: 
We're sorry! An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
what my step:
1. install AVS on ubuntu. -> successful.
2. I can login it and can talk with Alexa. that's OK!
3. I restart nodejs(npm start) , and javaclient on Ubuntu. then visit the nodejs like :"https://192.168.31.213:3000/provision/1d0f5c499512b12a7bb37451" on windows and android. It's return   Error.
4.  I restart nodejs(npm start) , and javaclient on Ubuntu. then visit the nodejs like :"https://192.168.31.213:3000/provision/1d0f5c499512b12a7bb37451" on Ubuntu. It's return   OK.

What's the problem? thanks very much!

**Comment by Alexnagel** [comment]
Please check #5 if any of those help

**Comment by howardguo** [comment]
It's not the same with #5 . 
I use the ubuntu to visit the "https://192.168.31.213:3000/provision/1d0f5c499512b12a7bb37451" ,it is OK. But use the windows or android to visit it, the error occured!

**Comment by elstryan** [comment]
Hi Howardguo, 
Can you check your redirect url as configured in developer.amazon.com? Is it set to  https://localhost:3000/authresponse? If that's the case the LWA redirect while on Windows will fail. If that's the case please update it to use the correct IP. Resolving the issue for now. If this doesn't work please feel free to re-open.
