### ISSUE TITLE
Possible to set up on OSMC / Kodi running on Raspberry Pi 3?

### ISSUE THREAD

**Issue by dr3x** [alexa/alexa-avs-sample-app#591]
I'm interested in getting Alexa to run on my OSMC; almost have it working following your steps.

There were hurdles to getting the components to compile, I can add more details on what I did if there is interest.

Stopped where it is supposed to get auth; probably because I SSH'd in:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

Is there a way to do the auth headless / from an SSH session?  

I can VNC in to the box and get to the OSMC UI.

My goal is to run AVS and OSMC on the same device to reduce clutter; not necessarily to have AVS control Kodi but that would be a bonus if doable.

**Comment by scotthea-amazon** [comment]
Hello dr3x,

Unfortunately, there is no completely headless solution because at some point the user has to authorize AVS operations on her behalf.  Probably the closes you can get is to have a companion app that handles the required user interaction.  Here is a link to a fuller description: 

    https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-product-from-an-android-or-ios-mobile-app

**Comment by elstryan** [comment]
We are tracking this internally as a feature request on the project. Closing the issue at this point.

**Comment by dr3x** [comment]
Ok, just to confirm:
You can do the auth for a headless device with an app on a separate device but it expires in an hour and you have to reauth.

So does this mean you have to keep reauthing with the separate device?
What approach would you use to do an auth without the X11 dependency?

**Comment by keleric** [comment]
There are 2 methods to authorize with LWA - implicit grant and authorization code. Implicit grant expires after an hour and cannot be refreshed. Authorization code style comes with a refresh token that you can use to get a new access token without reauthentication. Both the companion app flow and companion service flow use authorization code grant. The difference is the companion service always has to be running, whereas with companion app flow once you log in, you don't have to touch it again. Does that help?
