### ISSUE TITLE
"Oops! it was not possible to show this website" Step 7: Terminal window 2

### ISSUE THREAD

**Issue by Czechnate14** [alexa/alexa-avs-sample-app#598]
Does anybody know how to get around this error on Epiphany

**Comment by elstryan** [comment]
Hi Czechnate14, 

Can you verify a few things: 

1) Can you check that your node service is running? I.e. that in Terminal Window 2 you can see 'Listening on Port 300' 
2) Can you connect to other websites in your Epiphany browser?

**Comment by Czechnate14** [comment]
elstryan, 

Yes, the Listening on Port 3000 does pop up. and yes i can connect to other websites. I believe it is blocking just the https websites and was wondering if there is anyway to allow the website through.

Thanks!

**Comment by elstryan** [comment]
Hi, 
I haven't faced this specific issue with Epiphany before - but after searching around I think this might be a possible solution: 
Can you give this command go: sudo apt-get install --reinstall ca-certificate ca-certificates-java
Let me know if that works or not.

**Comment by elstryan** [comment]
I think that should address your issue. Closing for now. Please re-open if you still run into issues.
