### ISSUE TITLE
How to enable amazon music?

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#599]
How to Enable Amazon Music to my device? what's the step? Any document or pictures to indicate?

**Comment by elstryan** [comment]
“Hi howardguo, we apologize for the lack of clarity on Amazon Music approvals. Amazon Music is currently limited to Alexa-enabled devices that are approved for commercial distribution and use.    If you are developing a commercial device, please let us know.  We’d love to help.  Thanks for being an AVS developer.

**Comment by IntusFacultas** [comment]
Is there any news on whether Amazon Music will be approved for personally developed Alexa-enabled devices?
