### ISSUE TITLE
Suggestions on improvements for this post !

### ISSUE THREAD

**Issue by rprocha** [alexa/alexa-avs-sample-app#60]
I had Alexa running on my Raspberry Pi for about 2 months now and I had to find out a lot of this by myself. Here are a few suggestions to the team so the GitHub code is more useful for the DIYers:
1) Include code to make the tokens persist on the server side. Without that, every time you re-start the server you need to re-authorize the device at Amazon. As a hobby at home I used Excel NPM libraries to save the tokens and reload them back at runtime, when I start the server portion.
2) You could refine the client code and include a thin voice recognition library to enable use of a trigger word (e.g. "Alexa"). In my project I used Sphinx and Voce Java libraries with a very very small dictionary to recognize words like ("Alexa") and trigger the listening to send the audio stream to the Alexa service. It is quite straightforward to use them and I do not need the Java button anymore.
3) If you have a voice recognition function looking for the trigger word "Alexa", I would also recommend the use of USB array mics to increase the fidelity of the "listening". I have ordered these at Amazon and they work very well: Andrea C1-1021450-100 PureAudio USB-SA External Digital USB Sound Card with Superbeam Array2S Microphone Bundle

**Comment by jacksonrdlc** [comment]
@rprocha Would be really interested for you to go further into how you wrote the trigger word code.

**Comment by bill-orange** [comment]
Ditto.  I know writing an FAQ would be a lot of work but it sure would help the rest of us.

**Comment by shankararunachalam** [comment]
Ditto. This would be very usefull overall. @rprocha, if you get a chance, it would be wonderful if you could create a repo or write up an FAQ on this.

**Comment by gregwa1953** [comment]
@rprocha , THANK YOU in advance!!!!!!!!!!!!!!
Could you also go into more details on the persistent token storage?

**Comment by ITJamie** [comment]
@rprocha Cant wait for you to share number 2! this will be a great addition.

**Comment by illperipherals** [comment]
I ended up using PocketSphinx with PulseAudio, and it works quite well. It was a bit of a pain to get PA set up correctly using a USB mic/output and splitting I/O so I was using on-board output and the USB just for the mic.

**Comment by ITJamie** [comment]
@illperipherals any chance you could share your code?

**Comment by illperipherals** [comment]
Of course. I broke a few things this weekend trying out some changes, but I
will get it cleaned up.

In the meantime, this article has some good information in it. (not mine)

**Comment by illperipherals** [comment]
You might need this...
https://wolfpaulus.com/journal/embedded/raspberrypi2-sr/

**Comment by dly9014** [comment]
@rprocha +1 for interest in your approach to saving tokens to avoid manual re-Auth. Please share!

**Comment by keleric** [comment]
1. I think it's a great idea! Feel free to fork our repository and share the results. I'm sure a lot of people here would appreciate it.
2. In case you missed it, we did implement your suggestion! The current sample app experience includes a wake word agent that comes with the "Alexa" keyword preloaded.
