### ISSUE TITLE
nmp ERR! Exit status 8

### ISSUE THREAD

**Issue by cooper2450** [alexa/alexa-avs-sample-app#601]
Hi,
I tried to install Amazon Alexa at my Raspberry Pi 3. I used this instruction: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi. But when I want to run the web service for authorization by writing "cd ~/alexa-avs-sample-app/samples/companionService && npm start", I got following error message:

„[…]
npm ERR! alexa-voice.service-sample-companion.service@1.0.0 start: ’node ./bin/www‘
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/www
npm ERR! You can get their info via:
npm ERR! npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command „/usr/bin/nodejs“ „/usr/bin/npm“ „start“
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary „node“
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
“

Can someone help me with this problem?

**Comment by IRLionel** [comment]
Hi. Being a newbie, I cannot offer much in the way of assistance, but I wanted to confirm that I am getting almost the same as you except I don't seem to get the "legacy binary" line near the end of yours.    I followed the instructions to the letter ( twice ).  Did you get errors on the certificate creation step  ( 5 ) ?

**Comment by cooper2450** [comment]
There was no error before this.
But I was able to fix it
