### ISSUE TITLE
Timeout exception

### ISSUE THREAD

**Issue by alexeybb** [alexa/alexa-avs-sample-app#602]
I keep getting a 11:18:38.278 [RequestThread] ERROR com.avslib.AVSApp - An error occured creating speech request
com.avslib.http.AVSClient$RequestException: java.util.concurrent.TimeoutException

in the AVS code. I checked the other threads on this issue and they point to being outside of the United States, but in my case I'm in US, I'm not using a proxy or anything that would show my IP as outside US.

**Comment by elstryan** [comment]
Hi @alexeybb, 
Can you try reproducing this again? We had an update to the service before you opened this issue which might address this.

**Comment by pratikdatta91** [comment]
Hi,

i am also facing the same issue, this primarily happens after i say alexa but do not follow it up with a statement.

**Comment by yugoren** [comment]
Hi @pratikdatta91,

Could you verify that you're also in a similar setup like @alexeybb? Also, does the interaction work if you follow 'Alexa' by some utterance?

**Comment by shaolinkhoa** [comment]
I'm not in US but I have the same error #213 
would you mind helping me

**Comment by jordan-heier** [comment]
Hi,

It sounds like there are a few people experiencing this issue. Is this intermittent or does it consistently happen with every request? If there are any requests that are getting through could you provide me with the Request ID so I can try to look up what the issue is with some of these TimeoutExceptions?

**Comment by shaolinkhoa** [comment]
Hi @jordan-heier ,
I think the problem was my internet connection of that day.
The next day, I ran the old sample and everything worked normal just like nothing happened.

**Comment by gopal-amlekar** [comment]
Hi, I am getting the exception continuously again. All the setup had worked perfectly a few days ago. I haven't used the app for last week or so. When I tried it yesterday, it started showing the java.util.concurrent.timeoutexception. I haven't changed anything in configuration or anywhere else.
Log file is here. 
[log.txt](https://github.com/alexa/alexa-avs-sample-app/files/892772/log.txt)


I am in India and using Raspberry Pi 3 with a fresh raspbian install, all updated. The microphone is a USB webcam mic and speakers are analog (headphone). All the setup was same when it had worked earlier.
The tokens authentication etc. everything works perfectly fine, internet connection is working fine. Audio recording using arec works correctly and even the headphones work. I can hear the Alexa beep when I click on the 'Listen' button. But after some time, it just shows the exception.
Restarting the app or Raspberry Pi - nothing is helping..

**Comment by keleric** [comment]
I see you're getting timeout exceptions in the log, but it looks like it's intermittent. As a side note, AVS is not currently supported in India. That could be why you're getting more frequent timeout exceptions. You can try increasing the timeout. See: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/http/AVSClient.java#L69

**Comment by gopal-amlekar** [comment]
Ok thanks @keleric. It is intermittent really. I will keep trying.
Meanwhile, if it is not supported in India, it shouldn't work at all then..?

**Comment by namanmittal-namanm** [comment]
Hi @gopal-amlekar we do not explicitly block the request coming from the non-supported countries, we just don't have the servers and other resources installed explicitly to support the non-supported countries.

**Comment by gopal-amlekar** [comment]
Ok @namanmittal-namanm thanks for explanation. I hope it gets supported soon to have a more reliable experience.

**Comment by tweaty100** [comment]
@gopal-amlekar i am also in india and i am also facing the timeout issue .willyou please tell me is it work for you now ?
I am in India . The microphone is a headphones(which come along phone) will they work  as a mic as they also have microphone in them ? 
 the headphones are notn working . I can't hear the Alexa beep when I click on the 'Listen' i am not able to hear anything please help
@namanmittal-namanm please help i am not getting any reply back from alexa whatever i am saying i think it is being processed and i am getting error sometimes it hangs even  ?
@alexeybb how to use proxyserver as i am India i.e outside U.S ?

thanks all
