### ISSUE TITLE
Wakeword Fails on license expiration

### ISSUE THREAD

**Issue by bill-orange** [alexa/alexa-avs-sample-app#603]
I have seen similar issues, but they seemed to apply to the situation where the license is expiring, not expired.  the fix in frequently asked questions does not work.  Here's the error message.

cd wakeWordAgent/src && ./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.1 | model file: ../ext/resources/spot-alexa-rpi.snsr
ERROR:SensoryWakeWordEngine: Initialization error:Could not allocation a new Sensory session: snsrNew(): License expired on 28 Jan 2017 00:00:00 GMT.
ERROR:WakeWordAgent: exception in constructor: Could not allocation a new Sensory session: snsrNew(): License expired on 28 Jan 2017 00:00:00 GMT.
ERROR:main: Exception happened: Could not allocation a new Sensory session: snsrNew(): License expired on 28 Jan 2017 00:00:00 GMT.
INFO:Shutting down Wake Word Agent

Any suggestions?

**Comment by elstryan** [comment]
Hi, 
Did you try these steps here: https://github.com/Sensory/alexa-rpi#license 
Specifically have you have the latest libsnsr.a?

**Comment by bill-orange** [comment]
I ran the script to do the license update. How can I tell if I have the latest lobsnsr.a?

**Comment by elstryan** [comment]
You can execute a 'git log' and make sure that you have the latest commit: 'License key for 5.0.0-avs.4 expires 2017-06-27.' 

After that can you try re-running the automated install script?

**Comment by bill-orange** [comment]
Rather than only rerunning the install script, I flashed a fresh uSD and and reinstalled Alexa with the new install script.  Wow, That's way simpler now.  I am sure newcomers to Linux will have a much easier time now.
I am back up and running for another 6 months, I suppose.

**Comment by frakman1** [comment]
* In `samples/wakeWordAgent/sensory/alexa-rpi/` issue these commands:

```
git reset --hard
git pull
./bin/license.sh; # accept license agreement
cp ./lib/libsnsr.a ../../ext/lib/
cp ./include/snsr.h ../../ext/include/
cp ./models/*.snsr ../../ext/resources/
cp ./models/spot-alexa-rpi-31000.snsr ../../ext/resources/spot-alexa-rpi.snsr
cd ../../src
make
./wakeWordAgent -e sensory

```

**Comment by jabulonboaz** [comment]
@frakman1 my sensory wakeord licence has expired and when I follow the above commands I can find ext/. What am I missing, in which directory is the ext that I need?
