### ISSUE TITLE
Wake Word Not Working Error

### ISSUE THREAD

**Issue by kenyboy9** [alexa/alexa-avs-sample-app#604]
Hey guys i have followed the guide on the raspberry pi 3 and then i do the wake word command using:

wakeWordAgent/src && ./wakeWordAgent -e sensory

ERROR: An Error happened in the mainLoop of sensorywakeword snsrRun(): task: Input channel audio-pcm: ALSA eror: no such file in or directory

Then it connects to the AVS client.

Any ideas? Thanks

**Comment by kenyboy9** [comment]
For all those who are having this issue  :)

sudo nano ~/.asoundrc

change your ~/.asoundrc file to:
pcm.!default { type asym playback.pcm { type plug slave.pcm "hw:0" } capture.pcm { type plug slave.pcm "hw:1" } }
sudo nano ~/.asoundrc

and work with Sensory
cd ~/Desktop/alexa-avs-sample-app/samples cd wakeWordAgent/src && ./wakeWordAgent -e sensor

**Comment by M4rc0P1** [comment]
cool

**Comment by yugoren** [comment]
Hi @kenyboy9,

Thanks for finding the fix for the problem! Since this resolved the issue completely, I'll go ahead and close this. Please feel free to open it again if the problem still persists.

**Comment by MrTrainCow** [comment]
That isnt working for me. Still get the error.

**Comment by architek1** [comment]
Yeah, I'm having the same error still as well @MrTrainCow. All demos and apps are working except this Alexa app :( Did you get it working?
