### ISSUE TITLE
Not able to RUN AlexaPi on Boot!

### ISSUE THREAD

**Issue by adaboolean** [alexa/alexa-avs-sample-app#606]
Kindly suggest any method to start AlexaPi on boot of my RaspberryPi.

**Comment by thjansen72** [comment]
3 scripts in~/..config/autostart to start the 3 services. Then wait for java-box,  use xautomatation (xte) (4.th script) to send "space" - opens default browser - wait a while, simulate mouseclick for amazon login, wait, minimize browser-window, send "space2 for 2o.K. when ready) and hope...

**Comment by yugoren** [comment]
Hi @adaboolean,

Re-iterating on @thjansen72's post; If you're using the companion service through `node` server, you should start that in the background, either by modifying `~/.config/autostart` like the suggestion, or by creating an init level script for just that service. After this, you can also add to `~/.config/autostart` a script to start the Java sample app, which will redirect you to the browser. Is this the start on boot behavior you wanted?

**Comment by thjansen72** [comment]
I've been starting the services in exact this way (via scripts in  ~/.config/autostart) until PM2 does that job by exident - I totaly forgott the behavior of the programm when installing it.
Here a little example of the  "autologin" with all possible "remeber me" options in the brower, so the script just have to click "continue" and mimimize the browser for register at Amazon. It is starting at the point, when all 3 services starting up - running, and a little window appears: "click ok to open default browser ..."
Still didn't manage to filter the java-applet apperance with PGREP (to many java in the list) - I'm working on it.
The sleep timings are  eperimentel for a "samfe start" in about 2 minutes. At the end mm2 will be executed - my Pi is also a MagicMirror...
Youll need to play withe the coordinates - in the script are mine (1920x1080 monitor)

autologin.sh:
#!/bin/bash
sleep 30s                        # waiting for the java window and scripts startup - working on pgrep
xte "key Return" -x:0      #Open Default-Browser
sleep 30s
xte "mpusemove 450 480" -x:0  # Mouse over Continue-button
xte "mouseclick 1" -x:0
sleep 15s
xte "mousemove 1030 50" -x:0 # mouse over minimize 
xte "mouseclick 1"-x:0
xte "key Return" -x:0                 # "press ok when ready"
sleep 10
/home/pi/mm2.sh &                # Magic Mirror starten

**Comment by thjansen72** [comment]
The interesting question would be: how it works on a Amazon Echo/Dot...

**Comment by univers3** [comment]
@thjansen72 thanks for your solution, very appreciated.

Maybe will be far better to use one of the forks done by users that workaround that thing?
like: https://github.com/jzarca01/alexa-avs-sample-app
or: https://github.com/SamuelBrucksch/alexa-avs-sample-app
In theory they have Startup and Credential storing, to do an automatic auth.

Maybe the Alexa-pi will be ok too:
https://github.com/alexa-pi/AlexaPi

**Comment by keleric** [comment]
The sample app wasn't designed to be used as an Echo/Echo dot replacement, but we do recognize that many of our users would like to use it in that way. Auto start is a highly requested feature, and it has been added to our backlog. I recommend following our repository to make sure you're notified when we update the sample app! In the meantime, do check out some of the forks of the sample app that add that feature.
