### ISSUE TITLE
Fresh install - npm fails, mvn fails.  Now what?

### ISSUE THREAD

**Issue by steelblue48310** [alexa/alexa-avs-sample-app#608]
Followed the instructions to the letter, using the NOOBS method.

Step 7 (npm start) fails with this:

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8

<<<<    snip  >>>>

I've tried to re-run the automated installer script...  that didn't fix it.

Tried to start the next step (just out of curiosity), and I get this: 

**-bash: mvn: command not found**

Looks to me that mvn didn't install correctly either.

Any other ideas that I can try?

**Comment by yugoren** [comment]
Hi @steelblue48310,

The first part of the problem looks related to `npm` rather than `mvn`. To fix `mvn` issue, could you try installing maven using
```
sudo apt-get install -y maven
```
and checking if it works using `mvn -version`?

Also, were there any errors/warnings after step 6 (or after the re-run of the script) on your terminal? Looking to the order of installations in `automated_install.sh`, there might have been some problems after or during the installation of VLC.

**Comment by steelblue48310** [comment]
Thanks for the reply...  It seems that dpkg and several other things didn't go so well.  When I tried the command you mentioned, it said that 'dpkg was interrupted' and I need to run this:
**sudo dpkg --configure -a** to fix it.

mvn -version looked ok, but the dpkg error keeps showing up.    I'm re-installing everything.

:)

**Comment by jordan-heier** [comment]
Hi @steelblue48310 ,

Did the re-install fix the dpkg issues you were running into or are you still having issues?

**Comment by steelblue48310** [comment]
Yes...  it did.  Sorry for not updating this thread.   The only thing I did
differently was to use a 16Gb SD card instead of a 8Gb card.  So, either
the card is defective, or 8Gb isn't enough to do the install.

I am still working through a small issue with the USB sound device, but if
I can't figure it out, I will start a new thread.

Thanks for following up.
