### ISSUE TITLE
Broken link on wiki/get started  

### ISSUE THREAD

**Issue by shaolinkhoa** [alexa/alexa-avs-sample-app#609]
Hi,
Those links on [Get started](https://github.com/alexa/alexa-avs-sample-app/wiki#get-started) have been broken.
```
-     Raspberry Pi, or
-     Linux, or
-     Mac, or
-     Windows
-     New! Raspberry Pi + Conexant 2-Mic Development Kit for Amazon AVS
```

**Comment by yugoren** [comment]
Hi @shaolinkhoa,

Thanks a lot for the detailed report! I changed the links, they should point to the correct pages now.

**Comment by shaolinkhoa** [comment]
Hi,
All links are still wrong.

I think you miss the word "wiki" in links.

Ex: It's should `https://github.com/alexa/alexa-avs-sample-app/wiki/Linux` 
instead of `https://github.com/alexa/alexa-avs-sample-app/Linux`
