### ISSUE TITLE
missing resource file for building wake word agents

### ISSUE THREAD

**Issue by Turboman99** [alexa/alexa-avs-sample-app#611]
Hello. 
I have followed the instructions for the Raspberry Pi and I get a directory not found error when I open the third terminal window and attempt to start a wake word agent. On closer examination of the wakeWordAgent/src directory, I see that the subfolder wakeWordAgent has not actually been built by the auto install script.

I tried running make to build the directory and these errors were returned:

[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o
/home/jrdev/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp:6:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:374: recipe for target 'CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/GPIOWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have cloned the git repository twice and each time I come up with this same behavior/ error. Was wiringPi.h removed from the project? If so, there are still modules that are calling for it and that needs to be fixed. Any advice or assistance will be greatly appreciated.

**Comment by yugoren** [comment]
Hi @Turboman99,

This came up earlier in #416. You can solve it by installing `wiringpi`:
```
sudo apt-get install wiringpi
```

**Comment by Turboman99** [comment]
Thanks, this solution worked for me as well.
