### ISSUE TITLE
how to append my voice before the request stream?

### ISSUE THREAD

**Issue by wsywsya119** [alexa/alexa-avs-sample-app#612]
As the title, I use the Alexa skill kit that I need "_ask something_".
I want to abbreviate this command. So I try the sentEvent function in /http/AVSClient.java 
But it seem not work, Dose anyone have idea of it?

**Comment by yugoren** [comment]
Hi @wsywsya119,

Could you clarify what do you mean by "ask something"? If you mean sending voice data to Alexa, the Java sample app is already doing that when you push the microphone button, so [this function](https://github.com/alexa/alexa-avs-sample-app/blob/411d848a9f0147cc40c35e440c362292d5874d73/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L260) might be a good point to start. Also, for further reference on how to construct multi-part messages for AVS API, you can check its documentation starting [here](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/avs-api-overview).
