### ISSUE TITLE
Build Failure with maven Illegal State Exception

### ISSUE THREAD

**Issue by julienlegault** [alexa/alexa-avs-sample-app#616]
When using the automated installer on Ubuntu I get an error saying:
```
Build Failure
Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): java.lang.IllegalStateException -> [Help 1]
```
OS: Ubuntu 16.04.2 LTS
Java: 1.8.0_121
maven: 3.3.9

If you need any other information or more from the error logs just ask and I can probably get that to you.

**Comment by xaos11** [comment]
The automated installer probably won't work without issue on OS other than Raspbian, you'd have to run with the linux guide even if you're on RPI (or at least check the guide for hints). Try running the maven build with -X, and verify the java version in your POM file matches per the linux guide.

**Comment by julienlegault** [comment]
That makes so much sense. I'm probably going to install Raspbian then.
Issue closed, my incompetence the main problem.
