### ISSUE TITLE
Continue Beep on Set timer

### ISSUE THREAD

**Issue by harpreet9629** [alexa/alexa-avs-sample-app#618]
When i ask to Alexa "Alexa Set a time for 5 seconds" She continue play beep sound and don't stop it. Then i stopped here forcefully. Its a issue in Alexa?

**Comment by D3rpi** [comment]
You have to tell it to stop the timer

**Comment by yugoren** [comment]
@harpreet9629: @D3rpi is right, Alexa doesn't stop until you tell her to stop the timer. I'll go ahead and close the issue now but feel free to reopen it if the issue still persists.
