### ISSUE TITLE
6b - Android Companion App - Chain Validation Failed

### ISSUE THREAD

**Issue by SaniHEM** [alexa/alexa-avs-sample-app#620]
Dear all,

I know there was a similar topic here #464, however I have set  targetSdkVersion 22 in my gradle and I still get the following error:
<img width="298" alt="chain error" src="https://cloud.githubusercontent.com/assets/7461212/24273539/32887dc4-1023-11e7-9c7c-ce0aa361cc45.png">

The stack trace is:
`03-23 23:23:25.170 20708-20738/com.amazon.alexa.avs.companion D/NetworkSecurityConfig: No Network Security Config specified, using platform default
03-23 23:23:25.291 20708-20708/com.amazon.alexa.avs.companion W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
03-23 23:23:25.291 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
03-23 23:23:25.291 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
03-23 23:23:25.291 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.doRequest(ProvisioningClient.java:124)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.doRequest(ProvisioningClient.java:98)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.getDeviceProvisioningInfo(ProvisioningClient.java:50)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.LoginWithAmazonActivity$1$1.doInBackground(LoginWithAmazonActivity.java:117)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.LoginWithAmazonActivity$1$1.doInBackground(LoginWithAmazonActivity.java:104)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-23 23:23:25.292 20708-20708/com.amazon.alexa.avs.companion W/System.err:     at java.lang.Thread.run(Thread.java:761)`

I did now a couple of times the following:
- Removing keystore.jks file
- Generating new keystore.jks file (keytool -genkey -v -keystore keystore.jks -alias androiddebugkey -keyalg RSA -sigalg SHA1withRSA -keysize 2048 -validity 10000)
- Took the MD5 finderprint and copied it to Amazon --> Apps and Services --> Security profiles --> "My security profile" --> Tab "Android/Kindle Settings" --> Add an API Key
- The generated API Key I copied into ../samples/androidCompanionApp/app/src/main/assets/api_key.txt

Still I get this error and I really don't know what else I can change to have this running.

**Comment by yugoren** [comment]
Hi @SaniHEM,

After the second step in the last four steps you listed, have you verified that you have matching CA certificates between the Java sample app and the Android?

**Comment by SaniHEM** [comment]
Hey @yugoren,

not explicitly. I would assume I need to update one of these files to do so?
- samples/javaclient/config.js
- samples/companionService/config.js

Could you let me know if these are the right files for doing the matching of the CA certificates and if yes, which attributes specifically?

Many thanks

**Comment by yugoren** [comment]
Hi @SaniHEM,

Since you're using the Android companion app, `samples/companionService/config.js` is not being used in this case. Following [Step 4](https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#4---generating-self-signed-certificates) (I'm referencing Linux here but your version should have a similar step), a CA certificate is created in `samples/javaclient/certs/ca/ca.crt`. You'll need to make sure that the Android emulator has that certificate in `samples/androidCompanionApp/app/src/main/res/raw/`. Also, could you make sure to run the Java client before you run the companion app?

**Comment by SaniHEM** [comment]
Thanks, somehow it worked by just executing step 4 (creating the CA certificate) again. I didn't manually copy and paste the ca.crt file to my androidCompanionApp folder.

**Comment by p3420a1** [comment]
I did all the steps mentioned. But still getting the same error. This didn't come when I use Api 22. But with API 22, my emulator browser doesn't work at all. It has all the internet permissions in the manifest file.
