### ISSUE TITLE
Smart home devices discovery 

### ISSUE THREAD

**Issue by Kinjalk** [alexa/alexa-avs-sample-app#621]
Hello,
I have followed amazon's documentation on creating Alexa smart home devices and i am successfully able to add devices in my Alexa app using **Echosim.io** or directly scanning in Alexa app. Also i am able to control devices using Echosim but unable to discover devices using Alexa on raspberry pi. Alexa always says "Could not find any smart home devices" even though all the devices are already in my Alexa app.

Is there any way to control devices using Alexa on raspberry pi ? I know i can use Alexa Skill and AWSIot but then i would have to use invocation. Can i use it without invocation ?

**Comment by Kinjalk** [comment]
I have all my smart home devices listed in my Alexa App as you can see in screenshot 
![screenshot_2017-03-24-06-48-50-814](https://cloud.githubusercontent.com/assets/5174221/24276681/6140140c-105e-11e7-87b6-e082342b8339.jpeg)

**Comment by yugoren** [comment]
Hi @Kinjalk,

The local device discovery is not supported in AVS. Are these devices cloud-based?
That being said, you should still be able to control the ones listed in the picture; does that functionality work?

**Comment by Kinjalk** [comment]
Hello @yugoren,
No. I am unable to control them. On asking AlexaPi to turn off/on any listed device she always reply with 'could not find any smart home device'. But i am able to control they using **Echosim**.
Is it mandatory to have genuine Echo device on the network to control smart home devices using Alexa on raspberry pi ??

**Comment by Kinjalk** [comment]
@yugoren  
I reinstalled the project and now its working :)

**Comment by pecirep** [comment]
How exactly did you reinstall @Kinjalk ? I'm not even able to add the devices at all, neither using the voice command nor the app.

**Comment by Kinjalk** [comment]
@pecirep I had to install Raspbian again. Which devices are you trying to connect to and did you write your own smart home skill ?

**Comment by pecirep** [comment]
@Kinjalk I also did a fresh install of Raspbian (Pixel). I am trying to connect to a raspberry Pi that is pretending to be a WeMo Device as shown [here](https://www.instructables.com/id/Hacking-the-Amazon-Echo/?ALLSTEPS). No I do not have my own smart home skill, but shouldn't I be able to at least connect the devices without one? Maybe you can share how you are connecting to your rpi, I am trying to do something very similar to what you are doing.

Also I live in Austria and my Amazon location is set there. Could that somehow be an issue?

**Comment by Kinjalk** [comment]
@pecirep The tutorial you are following will work only if you have an Echo device. **Alexa on Raspberry pi can't see devices on the network**. So no, you can't connect to any device on your network without actually having an Echo device.  
If you want to control GPIOs on raspberry pi ,one way is to write your own  **Smart home skill** and use **AWSIot things**. Alexa on raspberry pi will be able to see your AWSIot things, you could leverage it to send MQTT messages to raspberry pi and control whatever you want. You will be able you use utterances like "**Alexa turn on <your device name>**".
Location of device does't matter at all. My device location is set to INDIA and it still works like a charm. 

**Follow these steps (Sorry if this post seems toooo long )** 

**Create Smart Home Skill** 
- Login to [Amazon developer Account](https://developer.amazon.com) and create new skill. 
- Select **Smart Home Skill API** and give it a name . **Save** -> **Next** -> **Next**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24427279/0993e594-1428-11e7-8130-78ab81a6e952.png)

- In Configuration, you can select any of two **Service Endpoint Type**. But be sure if you choose **North America** your **Lambda** and **AWSIot things** must be in **US East (N. Virginia)** and if you choose **Europe** they must be in **EU (Ireland)**. Here I am choosing **Europe**.

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428204/3a243ac6-142b-11e7-8895-5d4d9bb942f6.png)

 Now before proceeding further. Open [AWS Console](https://eu-west-1.console.aws.amazon.com/lambda/). Make sure **Ireland** is selected.

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428143/02dc1bba-142b-11e7-8f05-437587bfdc8c.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428306/a057e126-142b-11e7-8eec-71c0c4e1cc83.png)

Don't change any thing in **Advanced Settings**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428390/f6b8f49c-142b-11e7-8573-a73af1da87ec.png)

You will be redirected to new webpage. Select **Create a New IAM role** -> **Give it a name** -> **Allow**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428536/75275350-142c-11e7-9936-9b81c6c29fb1.png)

Click on **Create function**. You will get something like below . Don't worry we will write our code soon. 
Copy **ARN**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428805/2e47c6c6-142d-11e7-9198-7b46db419d2d.png)

Now we can proceed with our skill. Paste **ARN**  you just copied in **Service end point**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24428881/7c5d9d86-142d-11e7-9af7-09152a4e8576.png)

Now for **Account Linking** you need to go to **[LWA](http://login.amazon.com/)**. Create an account if you don't have one. Then go to **App Console** and **Register new application**.

Copy **Client ID** , **Client Secret** 

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429313/2659c228-142f-11e7-9118-02759c0110d8.png)

Paste **Client ID** , **Client Secret**  in their respective places. 
**Authorization URL**-https://www.amazon.com/ap/oa
**Scope**- profile
**Authorization Grant Type**- Auth Code Grant
**Access Token UR**I- https://api.amazon.com/auth/o2/token
**Client Authentication Scheme**- Credentials in request body
**Privacy Policy URL**- Same as you added in LWA while creating new application.

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429613/74c61906-1430-11e7-88a8-455ff143b58e.png)

Copy **Redirect URLs** and paste them in **Allowed Return URLs**  LWA.


![untitled](https://cloud.githubusercontent.com/assets/5174221/24429699/ccea6f06-1430-11e7-871a-1b89f1e4d6c9.png)

Click **Next** in your Skill. Copy **ID**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429812/53a50f88-1431-11e7-993f-b1d32cc03151.png)

Now in **Lambda function** we just created click **Triggers**  -> **Add trigger**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429877/9679bd04-1431-11e7-8f91-9f03696d48f9.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429924/cfa9a8be-1431-11e7-97e3-7d918403929a.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24429932/d9c28ed8-1431-11e7-8459-eea765fd64e6.png)

Now we are done with **Smart home Skill**.  But our Lambda won't do much as we have not added any code to it. 

Go to [IAM](https://console.aws.amazon.com/iam/home?region=eu-west-1#/home) and Click on **Roles** then on the Role you made for your lambda. 

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430170/f8d4c3d0-1432-11e7-8457-ebaa230d4cb5.png)

In **permissions** click **Attach Policy** 

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430258/59212e40-1433-11e7-83da-3523cc62ce3b.png)

Select policies as in below image and click **Attach Policy**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430334/b0044602-1433-11e7-9708-208e3d5971c0.png)

Click **Edit Policy** in **Inline Policies** and  replace all the content with 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": "iot:UpdateThingShadow",
            "Resource": "*"
        }
    ]
}`

Now Go to **Dashboard** and Select **Create individual IAM users** -> **Manage Users**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430433/43a78ff4-1434-11e7-873c-f4a140c3f4e6.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430468/5eabcd2e-1434-11e7-8c49-c91f301d0379.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430506/8c629f22-1434-11e7-9a0a-ed3003cfd5c9.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430524/9d3f7b6c-1434-11e7-87d4-736b20f9909a.png)

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430562/ccc7180e-1434-11e7-8e4f-68581fd2e969.png)

Attach All three policies as in below image.

![untitled](https://cloud.githubusercontent.com/assets/5174221/24430581/d8704950-1434-11e7-9934-dc2888653dfd.png)

Click **Create User**


Save **Access key ID** and **Secret access key**. Make Sure you at least save **Secret access key** because you wont be able to retrieve it again. 

Install awscli and AWSIot
`$ pip install awscli`
`$ pip install AWSIoTPythonSDK`
`$ sudo aws configure`

Add **Access key ID**, **Secret access key**. **default region** to **eu-west-1** and **default output** to **text**.
Now you can add things to your **AWSIot** using **CLI**

`$ sudo aws iot create-thing --thing-name <YOUR-DEVICE_NAME>`

Add as many things as you want.

Verify if things are added 

`$ sudo aws iot list-things`

Paste this [Code](https://github.com/alexa/alexa-avs-sample-app/files/877299/Lambda.code.txt) in code section of your lambda. Edit the code to your needs. **applianceId** in code must be same as name of the thing you created above. 

Go to your Alexa App and Enable the skill we just created. You might have noticed we didn't publish our skill. Don't worry as long as you login in Alexa app with same Email which is linked with your Amazon developer account you are good to go. 
All done now your Alexa on raspberry pi will be able to see AWSIot Things . 

Now in order to control GPIOs you need to write a python code. Similar to this 
[Controll RPi GPIO using MQTT](https://github.com/alexa/alexa-avs-sample-app/files/877324/MQTT.txt)

In the attached [Controll RPi GPIO using MQTT](https://github.com/alexa/alexa-avs-sample-app/files/877324/MQTT.txt) Edit the following in Bold.

`def createIoT():
	iot = AWSIoTMQTTShadowClient('**<ANY_NAME_YOU_WANT_TO_USE>**', useWebsocket=True)
	iot.configureEndpoint('**<END-POINT>.iot.eu-west-1.amazonaws.com**', 443)
	iot.configureCredentials(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem'))
	iot.configureConnectDisconnectTimeout(10)  # 10 sec
	iot.configureMQTTOperationTimeout(5)  # 5 sec
	iot.connect()
	return iot`

**ANY_NAME_YOU_WANT_TO_USE**- Client name as you desire
**END-POINT**- End point which you can get as follows 

- Log in to AWSIot Dashboard 
  **Registry**->**Things**
- Click on any **Thing**

Copy the **Rest API Endpoint** and paste it in END-POINT of [Controll RPi GPIO using MQTT's](https://github.com/alexa/alexa-avs-sample-app/files/877324/MQTT.txt) **createIoT()**

![untitled](https://cloud.githubusercontent.com/assets/5174221/24431615/8df78fd6-143a-11e7-9378-d044719e25ef.png)


Now we download the required certificate file that AWS IoT requires.
Got to the directory you saved [Controll RPi GPIO using MQTT](https://github.com/alexa/alexa-avs-sample-app/files/877324/MQTT.txt) and 

`$ wget https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem`

That't It. Now you can control your GPIOs and much more using Alexa .

**Cheers !!! 👍 **

**Let me know if you want any help.**

**Comment by Kinjalk** [comment]
@pecirep Hope this helps !

**Comment by pecirep** [comment]
Dude you are insane. Thank you for this, I really appreciate it. I assume I have to delete the abundant appliances in the lambda code? I'm not done yet, finishing it early tomorrow though, I'll let you know how it went

**Comment by pecirep** [comment]
I think I am doing something wrong in the last part. When I say Turn on Computer (thing 1) she responds with ok, I can see the thing in the alexa app. But nothing happens on the pi. Do I have to have the script running? When I run the Controll script it gives me an error

`sudo python mqtt.py
Traceback (most recent call last):
  File "mqtt.py", line 56, in <module>
    iot = createIoT()
  File "mqtt.py", line 51, in createIoT
    iot.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line                                              808, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line                                              403, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqt                                             tCore.py", line 290, in connect
    self._pahoClient.connect(self._host, self._port, keepAliveInterval)  # Throw                                              exception...
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/pah                                             o/client.py", line 655, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/pah                                             o/client.py", line 777, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(se                                             lf._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
`

**Comment by Kinjalk** [comment]
@pecirep 
Yes, script must always be running.
This error is thrown when AWSIoTMQTTShadowClient is unable to connect to your End point. Verify whether you have correct end point in `iot.configureEndpoint('<END-POINT>', 443)` . If the end point is already correct , verify if you have correct **Access key ID, Secret access key and default region**. Use both
`sudo aws configure` and `aws configure`. Add Values if they are not present in any case.

**Comment by pecirep** [comment]
This worked directly on the Pi that Alexa is installed on. On my Zero i get

`Traceback (most recent call last):
  File "MQTT.py", line 5, in <module>
    from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTShadowClient
ImportError: No module named AWSIoTPythonSDK.MQTTLib
`

**Comment by Kinjalk** [comment]
Did you Install AWSIoTPythonSDK on your Pi Zero ?

**Comment by pecirep** [comment]
I uninstalled libyaml and reinstalled it again. It works now. Thanks man! This is fing awesome!

**Comment by Kinjalk** [comment]
👍

**Comment by wiatrM** [comment]
That should be added to wiki!

**Comment by keleric** [comment]
@Kinjalk You're my hero. Seriously dude, fantastic tutorial! Thanks for making the Alexa ecosystem awesome!

**Comment by Kinjalk** [comment]
@keleric hahah... thanks !

**Comment by erikhopf-amzn** [comment]
@Kinjalk would you be interested in turning your guide into a Gist that we can link to?

**Comment by Kinjalk** [comment]
@erikhopf-amzn 
Sure i will. Should I add everything as it is or do you have any suggestions ? Let me know.

**Comment by mohaggag** [comment]
Is there a tutorial on how to use it with nodemcu , or mqtt

**Comment by xaos11** [comment]
@mohaggag There is a firmware called ESPurna (that runs on the nodemcu), that has the fauxmo wemo emulator library that allows Alexa to discover the devices (which also gives mqtt control and http control). I have an echo dot though, which I'm pretty sure is what my Alexa prototype uses to control the devices. I'm not entirely sure if it will work with just the prototype. However, you can also use Node-RED to set up a flow with the node-red-contrib-alexa-home-skill, to control MQTT devices.

**Comment by erikhopf-amzn** [comment]
@Kinjalk Go ahead and set it up as is. Then we can collaborate on edits :). Thanks again for making this community GREAT!

**Comment by Pukington** [comment]
@Kinjalk This is an amazing writeup mate, top job!  Sorry though, i seem to be struggling and returning an error when pasting the lambda code in, when I save it I get an error: `The Code tab failed to save. Reason: Unexpected token < in JSON at position 2`

Even if i paste the code unedited from your lambda.txt in and save I get this error.  I've retraced my steps and pretty sure i've covered everything along the way, finding it rather infuriating!  I'd appreciate any input at all!

**Comment by Pukington** [comment]
@Kinjalk Great writeup mate! Is it possible to interface Alexa with my Home-Assistant install by using this method?  I've currently got Alexa running IFTTT commands using the HASS restapi which works wonderfully, but it would be lovely to remove the "Alexa trigger" command and the resulting "sending that to IFTTT".

I've used your writeup to make two devices in ASloT which appear in my Alexa app, and Alexa knows they are there.  But how do i make Alexa either talk to HASS or send the RESTAPI commands to turn on/off the devices? Am i missing something?

**Comment by Kinjalk** [comment]
@Pukington What kind of devices are you using with Home Assistant ? Are you using ESP8266 ?

**Comment by Kinjalk** [comment]
You can turn on/off device using RESTAPI. I am attaching modified [Lambda.](https://github.com/alexa/alexa-avs-sample-app/files/997111/Lambda.code.py.txt)

**Change the following in Lambda code as required:**
applianceId,
friendlyName,
friendlyDescription,
manufacturerName,
YOUR-HOME-ASSISTANT-URL,
YOUR-HOME-ASSISTANT-PASSWORD

Let me know if this works for you.

**Comment by Pukington** [comment]
Many thanks for your input @Kinjalk, I really appreciate your time.  Unfortunately when i replace the lambda with the new one, my Alexa won't find any devices, with or without the editing of your requested tags.  If i replace the lambda with your original one (which i edited) it finds my two devices again so unfortunately I guess there's something not right with my new lambda.


I currently have two devices that i call via RESTAPI.  My HA is accessible from the web via https address and works fine currently with IFTTT.  An example of the API I use:

`URL: https://MY-HOME-ASSISTANT-ADDRESS/api/services/light/turn_off?api_password=MY-HOME-ASSISTANT-PASSWORD`
Method is Post, content Application/Json
`Body: { "entity_id": "light.lamp" }`

I'm sorry, I'm really no programmer but love tinkering with things like this. I would be happy if the lambda you wrote had an area for each device that i could enter the restapi url/body etc, if that makes sense.

**Comment by Kinjalk** [comment]
@Pukington hmmmm... That lambda is working fine for me . I have deleted all devices from old lambda and added new one called "lamp". Give it a try if it works you can add more devices. you just need to add your home assistant URL and password .
Also delete all devices from Alexa app before rediscovering.  
[Lambda](https://github.com/alexa/alexa-avs-sample-app/files/999355/lambda.py.txt)

**Comment by Pukington** [comment]
@Kinjalk Mate, that's awesome, works a treat!  Thanks so much for helping me, really appreciate it!

**Comment by Kinjalk** [comment]
@Pukington I am glad I could help. Cheers !!! 
Also you can go ahead and delete your AWSIot things, if not required , as in your case you don't really need them .

**Comment by AnuPauly** [comment]
Hi 
I am new to AWS Services.You told to install awscli and awsiOT. where to install this? In system or somewhere else?

**Comment by huhwang** [comment]
@Kinjalk this is so cool! Yet this article shouldn't be hidden here in this issue page. Make it a wiki or an stand-alone article so that more people can read and learn from it. Anyhow thanks for your post!

**Comment by krrrishh** [comment]
Awesome info dude. Now is there a way to make it generic like how the alexa searches for Wemo devices in the udp broadcast channel? Can we make alexa search for our devices also like that?

**Comment by speatzle** [comment]
@Kinjalk is saw your post: https://github.com/alexa/alexa-avs-sample-app/issues/621#issuecomment-289936814 you said: So no, you can't connect to any device on your network without actually having an Echo device. I hava an real amazon echo and an raspberry alexa avs. Now the question is if i can use my local smarthome stuff that my genuine alexa can see and use over my avs version (they are on the same network) and if yes then how?
