### ISSUE TITLE
Automatic install script not working fully

### ISSUE THREAD

**Issue by PeterGMat** [alexa/alexa-avs-sample-app#624]
Hi
I am trying to get Alexa working on a new Raspberry Pi 3
The first two terminal sessions work perfectly and I get Alexa working when I click on the listen button - but the third just bombs out saying no such file or directory. ( screen dump below)

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && sudo ./wakeWordAgent -e sensory
sudo: ./wakeWordAgent: command not found
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ dir
CMakeCache.txt			 SensoryWakeWordEngine.h
CMakeFiles			 WakeWordAgent.cpp
cmake_install.cmake		 WakeWordAgent.h
CMakeLists.txt			 WakeWordDetectedInterface.h
GPIOWakeWordEngine.cpp		 WakeWordEngine.cpp
GPIOWakeWordEngine.h		 WakeWordEngineFactory.cpp
IPCInterface.cpp		 WakeWordEngineFactory.h
IPCInterface.h			 WakeWordEngine.h
KittAiSnowboyWakeWordEngine.cpp  WakeWordException.cpp
KittAiSnowboyWakeWordEngine.h	 WakeWordException.h
Logger.cpp			 WakeWordIPC.cpp
Logger.h			 WakeWordIPCFactory.cpp
main.cpp			 WakeWordIPCFactory.h
Makefile			 WakeWordIPC.h
PortAudioWrapper.cpp		 WakeWordIPCSocket.cpp
PortAudioWrapper.h		 WakeWordIPCSocket.h
SensoryWakeWordEngine.cpp	 WakeWordUtils.h
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ cd ..
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent $ cd sensorypi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/sensory $ dir
alexa-rpi

I noticed that there are a couple of errors reported when the auto install script is run so perhaps some of the files have not been created ?

My knowledge of Linux is limited ( but growing) so I dont yet have the skills to analyse what is gong wrong - Please can you help so that I can wake Alexa with my voice not a click ? 

Thanks
Peter

**Comment by xaos11** [comment]
What build of Raspbian are you using? Did you try to re-run the installer script? Or you could try to manually build the wake word agent and provide the results:
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst && cmake . && make -j4

**Comment by xaos11** [comment]
For more details I think you can append `VERBOSE=1` to the make command.

**Comment by PeterGMat** [comment]
I installed the latest version of Raspian yesterday  with sudo apt update and then sudo apt upgrade. 
I tried both re running the three consoles and when that didnt work  I went right back to the Git hub clone .
I will try your suggestions tomorrow and post the results - thanks

**Comment by PeterGMat** [comment]
Just tried and it failed 
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordIPC.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/IPCInterface.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordIPCSocket.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
[ 33%] Building CXX object CMakeFiles/wakeWordAgent.dir/Logger.cpp.o
CMakeFiles/wakeWordAgent.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordException.cpp.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Looks like the script didn't fully get all the files in the first place.
I will try again - can you tell me which directories to delete so that I have a clean install.

**Comment by PeterGMat** [comment]
Tried again and same issue during install script - looks like this is the key part.

compilation terminated.
[ 25%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
CMakeFiles/wakeWordAgentTest.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

=============================
*****************************
========= Finished ==========
*****************************
=============================

**Comment by xaos11** [comment]
Try the patch in issue #329?

**Comment by PeterGMat** [comment]
Please can you tell me how to use the patch - do I run it in a terminal( doesn't work) append it onto the end of the install script or something else ?

**Comment by PeterGMat** [comment]
Thanks for all the suggestions - it turned out that WiringPi.h was missing and having downloaded it the whole build works fine - now to develop some skills
