### ISSUE TITLE
Step 5 cannot start wake word engine installation

### ISSUE THREAD

**Issue by MisterMiJarvis** [alexa/alexa-avs-sample-app#625]
Hello,

I have almost completed the installation on a Raspberry PI 3. However I am having an issue on the last installation step and pretty sure I am missing something:

Following instructions from step 5:

Type in cd ~/Desktop/alexa-avs-sample-app/samples and press Enter.
Type in cd wakeWordAgent/src && ./wakeWordAgent -e kitt_ai

I have the following return:
pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd wakeWordAgent/src && ./wakeWordAgent -e kitt_ai
-bash: ./wakeWordAgent: No such file or directory
pi@raspberrypi:~/alexa-avs-sample-app/samples/wakeWordAgent/src $

Am I missing something? I have the following files in the src folder:

pi@raspberrypi:~/alexa-avs-sample-app/samples/wakeWordAgent/src $ ls
CMakeCache.txt                   SensoryWakeWordEngine.h
CMakeFiles                       WakeWordAgent.cpp
cmake_install.cmake              WakeWordAgent.h
CMakeLists.txt                   WakeWordDetectedInterface.h
GPIOWakeWordEngine.cpp           WakeWordEngine.cpp
GPIOWakeWordEngine.h             WakeWordEngineFactory.cpp
IPCInterface.cpp                 WakeWordEngineFactory.h
IPCInterface.h                   WakeWordEngine.h
KittAiSnowboyWakeWordEngine.cpp  WakeWordException.cpp
KittAiSnowboyWakeWordEngine.h    WakeWordException.h
Logger.cpp                       WakeWordIPC.cpp
Logger.h                         WakeWordIPCFactory.cpp
main.cpp                         WakeWordIPCFactory.h
Makefile                         WakeWordIPC.h
PortAudioWrapper.cpp             WakeWordIPCSocket.cpp
PortAudioWrapper.h               WakeWordIPCSocket.h
SensoryWakeWordEngine.cpp        WakeWordUtils.h

Thanks in advance!

Stéphane

**Comment by xaos11** [comment]
Re-run the automated installer script, or run these commands:
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4 VERBOSE=1
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst && cmake . && make -j4 VERBOSE=1

I usually just take the 3 snippets from the end of output of the script and paste them into shell scripts on the desktop for easy launching.

**Comment by alepanzetta** [comment]
xaos11 this is the output of the **cmake . && make -j4 VERBOSE=1** command in src:

_-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
/usr/bin/cmake -H/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src -B/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/CMakeFiles /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
make -f CMakeFiles/wakeWordAgent.dir/build.make CMakeFiles/wakeWordAgent.dir/depend
make[2]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/CMakeFiles/wakeWordAgent.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
make -f CMakeFiles/wakeWordAgent.dir/build.make CMakeFiles/wakeWordAgent.dir/build
make[2]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp:14:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:326: recipe for target 'CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
CMakeFiles/wakeWordAgent.dir/build.make:302: recipe for target 'CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
make[1]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2_

**Comment by alepanzetta** [comment]
and this  is the output of the cmake . && make -j4 VERBOSE=1 command in tst:

_-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst
/usr/bin/cmake -H/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst -B/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/CMakeFiles /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
make -f CMakeFiles/wakeWordAgentTest.dir/build.make CMakeFiles/wakeWordAgentTest.dir/depend
make[2]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/CMakeFiles/wakeWordAgentTest.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
make -f CMakeFiles/wakeWordAgentTest.dir/build.make CMakeFiles/wakeWordAgentTest.dir/build
make[2]: Entering directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/testKittAi.cpp
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp
[ 15%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
/usr/bin/c++    -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src -I/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../ext/include  -std=c++11 -o CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o -c /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp:14:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgentTest.dir/build.make:278: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/testKittAi.cpp:15:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgentTest.dir/build.make:230: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/wakeWordAgentTest.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
make[1]: Leaving directory '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
_

**Comment by yugoren** [comment]
@MisterMiJarvis: As @xaos11 pointed out, your `automated_install.sh` must have failed to compile. 
@alepanzetta (and possibly @MisterMiJarvis): You seem to be missing `pa_ringbuffer.h` that must have been pulled in during `automated_install.sh`. Could you check if `samples/wakeWordAgents/ext/include/include/pa_ringbuffer.h` exists in your path?

**Comment by alepanzetta** [comment]
@yugoren only this three are in the include dir:
portaudio.h  
snowboy-detect.h  
snsr.h

**Comment by yugoren** [comment]
@alepanzetta: That's interesting. Looking at the following section for [Line 559](https://github.com/alexa/alexa-avs-sample-app/blob/master/automated_install.sh#L559) to Line 566 in `automated_install.sh`
```
cp $Kitt_Ai_Loc/snowboy/include/snowboy-detect.h $External_Loc/include/snowboy-detect.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/portaudio.h $External_Loc/include/portaudio.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h $External_Loc/include/pa_ringbuffer.h
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/include/pa_util.h $External_Loc/include/pa_util.h
cp $Kitt_Ai_Loc/snowboy/lib/$OS/libsnowboy-detect.a $External_Loc/lib/libsnowboy-detect.a
cp $Kitt_Ai_Loc/snowboy/examples/C++/portaudio/install/lib/libportaudio.a $External_Loc/lib/libportaudio.a
cp $Kitt_Ai_Loc/snowboy/resources/common.res $External_Loc/resources/common.res
cp $Kitt_Ai_Loc/snowboy/resources/alexa.umdl $External_Loc/resources/alexa.umdl
```
I notice that you're not missing all of the includes. Could you check the contents of `samples/wakeWordAgents/kitt_ai/snowboy/examples/C++/portaudio/install/include` to make sure that the download of the source was successfull? If `pa_ringbuffer.h` is not there, I would go ahead and make a fresh install. This time it will go much faster since system requirements are already installed.

**Comment by alepanzetta** [comment]
@yugoren I did try reinstalling it and I even tried starting fresh on another SD I have. On the new SD I flashed the last Jessie, I did sudo apt-get update and upgrade, then I installed cmake and even tried downloading and compiling portaudio.... no luck, same issue

**Comment by MisterMiJarvis** [comment]
Thanks @yugoren  and @xaos11 . It's late here but will try again in the morning and report back my findings.

**Comment by Simco75** [comment]
Same exact problem

**Comment by PeterGMat** [comment]
Same as me - has the install script been changed recently or corrupted?

**Comment by xaos11** [comment]
Try the patch in issue #329?

**Comment by alepanzetta** [comment]
I think the patch worked! I cannot test it atm but it looks like it went through all of the process, hooray!

**Comment by alepanzetta** [comment]
I can confirm that the patch works and I can now use the wakewordagent!

**Comment by Simco75** [comment]
The patch works! Thank you

**Comment by keleric** [comment]
Excellent! I'm glad you've figured it out.
