### ISSUE TITLE
in step 6: there is a question

### ISSUE THREAD

**Issue by jtlkm** [alexa/alexa-avs-sample-app#637]
Hi
I execute the npm start command in the   companionService  directory，The results are shown below：

> alexa-voice-service-sample-companion-service@1.0.0 start /home/lkm/samba_share/Alexa/alexa-avs-sample-app-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Then it did not show anything else。Is this right?

I execute the mvn exec command in the   javaclient  directory，The results are shown below：
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ sample-java-client ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.784s
[INFO] Finished at: Tue Mar 28 17:25:20 CST 2017
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project sample-java-client: Unable to parse configuration of mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:java: Cannot assign configuration values to array of type java.lang.String: [-Xbootclasspath/p:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, -Dlog4j.configurationFile=file:////home/lkm/samba_share/Alexa/alexa-avs-sample-app-master/samples/javaclient/log4j2.xml, -classpath, Classpath {}, -Djna.library.path=${env.VLC_PATH}, com.amazon.alexa.avs.AVSApp] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
Why is this problem? 
Looking forward to everyone's reply，Thank you!

**Comment by jtlkm** [comment]
My platform is Linux
mvn -version
Warning: JAVA_HOME environment variable is not set.
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-68-generic", arch: "i386", family: "unix"

java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)

**Comment by xaos11** [comment]
Sounds like an error in the pom.xml file. Make sure you didn't use quotes around the "alpn-boot.version" entry in the pom.xml file. If this is not the case, you could provide a copy of the pom.xml file for troubleshooting. If mvn verify and mvn install run with build errors, provide the output with the -X flag. If those run fine provide the output of mvn -X exec:exec.

**Comment by jordan-heier** [comment]
Hi @jtlkm ,

The output from your companion service looks correct. Can you run mvn -X exec:exec for debug information and post the output?

**Comment by jtlkm** [comment]
Hi @xaos11  @jordan-heier 
I have solved this problem，Thank you for your reply！
The input command  "mvn -e -X exec:exec" can run successfully。Before I entered the command is  "mvn exec:exec" ,
Forgive me not familiar with mvn order.

**Comment by jordan-heier** [comment]
Closing issue. If you run into issues around this again, then please reopen it.
