### ISSUE TITLE
Alexa voice stops, after a skill with sound starts

### ISSUE THREAD

**Issue by buluba89** [alexa/alexa-avs-sample-app#639]
Hello
I installed alexa on my bananapi and it works unexpectedly good.
But have a problem, i installed some skills that play sounds, for example "Sleep Sounds: Babbling Brook", and when i open it, starts to play sound as expected. 
But afterwards alexa voice is not audible, it activates when i say "alexa", starts and stop the skills when i say, but the voice and the activation sound is not audible anymore.
No errors in the java client logs.

Anyone experienced anything similar?

**Comment by xaos11** [comment]
Check alsamixer to make sure it is not muted. Also run raspi-config to force audio out of the 3.5mm output.  There is a pull request #557 with a fix to force volume to 100, but I am not sure if it fixes this.

**Comment by jordan-heier** [comment]
Hi @buluba89 ,

When you restart the application it works fine and then once you invoke a skill the application gets into a bad state? Does this happen with all skills or only certain ones? Does the sound of the skill continue to work even after the Alexa voice and bells stop coming through? If you play music does this happen as well or only for skills?

**Comment by buluba89** [comment]
thanks for your answer i managed to fix this (randomly) by messing around with alsa settings. I think because i had a usb sound card, something was going wrong

@jordan-heier Yes when i was launching it, it worked fine until i was starting a skill. Afterwars the sound of the skill was playing correctly, but i couldnt hear alexa. I tried some skills like: news feed, Babbling Brook, an ocean sounds skill, whatever was streaming sound produced this problem.
