### ISSUE TITLE
Run Javaclient headless

### ISSUE THREAD

**Issue by Kinjalk** [alexa/alexa-avs-sample-app#641]
Hello !
I have tweaked some of the codes in **javaclient** and have managed to remove the need to log in again and again. Also I **no longer need to run** **companionService** and am running **wakeWordAgent** as a service on boot. Basically I just need to run one command **mvn exec:exec** (Without having to login again in a browser ) to get Alexa running. 

Everything is running very smoothly. But i am unable to run **mvn exec:exec** in headless mode. I have tried to export display using **export DISPLAY=:1** but its not good enough.
**Is there any way to run javaclient headless ?** As it does not require user interaction to log in, it will be possible to run Alexa on boot .

I am getting this error when i try to run it in headless mode 
**No X11 DISPLAY variable was set, but this program performed an operation which requires it**

**Comment by jordan-heier** [comment]
Hi @Kinjalk ,

We don't currently support running the Java client in headless mode. The closest support for this that we have right now is using [SSH & VNC](https://github.com/alexa/alexa-avs-sample-app/wiki/Setup-SSH-&-VNC). Please let us know if you are able to get this working successfully.

**Comment by psycomatis** [comment]
Did you manged to work cause i have the same issue

**Comment by Kinjalk** [comment]
@psycomatis  No not yet.

**Comment by Kinjalk** [comment]
@psycomatis @jordan-heier @pecirep Done !!  Just now !!!
- Converted GUI app to Console app
- One time login
- Alexa starts on boot and is working great.

**Comment by keleric** [comment]
Hi guys - I appreciate your input! We know that headless mode is a requested feature for the sample app, and it is in our backlog. As a general note, we track our feature requests for AVS at the following link: https://forums.developer.amazon.com/spaces/185/index.html, rather than through Github issues, so I'm closing this. Thanks!

**Comment by Kinjalk** [comment]
@psycomatis Did you solve your issue ? If not check [#203](https://github.com/alexa-pi/AlexaPi/issues/203#issuecomment-294254644)
