### ISSUE TITLE
Viewing verbose output from client?

### ISSUE THREAD

**Issue by mph070770** [alexa/alexa-avs-sample-app#645]
Hi.
Is it possible to view all of the API messages from my client (Mac) to Alexa? I'm trying to debug what is probably a malformed message that I'm sending to Alexa and it would be good to view the JSON format of working messages between Alexa and my device.

**Comment by namanmittal-namanm** [comment]
Hi @mph070770 You can see all the request made to alexa in the application.log file. The file is located inside samples/javaclient/logs
