### ISSUE TITLE
How long is the refreshToken expires_in time?

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#655]
Dear .
As I know ,the accessToken expires_in is 3600s, the refreshToken expires_in should be longer than accessToken. How long is the refreshToken expires_in time?

**Comment by namanmittal-namanm** [comment]
Hi @howardguo , the refresh tokens are valid indefinitely and doesn't expire unless the user has removed the website or mobile app from the list of allowed apps for their account.
https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/refresh_token.html

**Comment by keleric** [comment]
Did @namanmittal-namanm answer your question?

**Comment by howardguo** [comment]
@keleric @namanmittal-namanm Yes, thank you very much!:)
