### ISSUE TITLE
Throw new Error can not find module 'express'

### ISSUE THREAD

**Issue by praveen-science** [alexa/alexa-avs-sample-app#656]
**I am getting following error in installation, Any help?** 

`Error: Cannot find module 'express'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! `sh "-c" "node ./bin/www"` failed with 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 4.0.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! message `sh "-c" "node ./bin/www"` failed with 1
npm ERR! errno {}
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
npm WARN /usr/share/doc/nodejs/README.Debian
npm WARN
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm not ok
`

**Comment by keleric** [comment]
Can you try running npm install before running npm start? Also, if you ran the automated install script, you shouldn't be seeing this. Maybe there was an error while running it? I'd recommend starting from scratch and doing the automated_install.sh script again, paying attention to see if it failed at any point.

**Comment by praveen-science** [comment]
This is the issue with old raspberian OS, to solve this we need to re-install raspberian. Solved by this method.
