### ISSUE TITLE
What does mean of LWAException

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#663]
{"error":"LWA_ERROR","message":"{\"error_description\":\"Not authorized for requested operation\",\"error\":\"unauthorized_client\"}"}

I met an LWAException like this. Login in Amazon is successful, but the error occured while post to javaClient to refreshToken.

**Comment by keleric** [comment]
Are you running an unmodified version of the sample app and companion service? Are the steps duplicable? How frequently can you reproduce this?

**Comment by jacky-ge** [comment]
hi @keleric I have solved this，Thanks very much
