### ISSUE TITLE
Issue to send request with nghttp2

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#672]
Hi
**When I use the nghttp2 send the request to establish downchannel as bellow:**

[INFO] SSL/TLS handshake completed
sizeof(nva) is 320 sizeof(nva[0]) is 40
[INFO] Stream ID = 1
[INFO] C <---------------------------- S (START SETTINGS)
[INFO] C ----------------------------> S (HEADERS)
:method: GET
:version: HTTP/1.1
:path: /v20160207/directives
:scheme: https
:authority: avs-alexa-na.amazon.com
accept: */*
authorization: Bearer Atza|IwEBIH0lcta5ZhjXuD0I3YuwPV-xFKnGQYSyGlhMAiPyYvCEXFsHNNmkQgdmUQmVoRh09zS5OEZptCampzdSLayGqzhZ47zoPBrA9UkhsbodZSuJXnagP2jTz9g84xCMPTNF69-2ln9ZXuXa89hklJfA-R3zUBbrxpromLnOSe9Y3sQDco3Glc1M4NO75X_RjCA7q80YaEXhQ94Mq5qcA14oXaR1Dbn29q8pGi419knqDKd-wlhxSalFy2UKmbm2ZFXDhko-EaADFTEaSAWL7zyZsTJv7YxQTo6El7L_P_-Tn8O0-EEQGMkUlHaU9fXWnDFszFWE_R2UCIAa3mYHNr06wbXqg4KisgvumYDTgYcAX1iM8M2LFuuXcsvOpT1H2K9mp8JUFj8NCzVRxEpKbW9JfZvUoQ38l1yL4BPOUnFbFa8hpKchQkj4hfg64XOWQS1nZfSlag-EGd3p1YZLfomF1wzmPbgp-ujBB9yp9Svx4KzI-vOQByGIzwt8QERVVwud_ezX049fMiKCDIQNmiAbm6KdyAzOBW_VHmp4tsh9lfkikS73UChQyDpnTta1Z3AGAIs
content-type: multipart/form-data; boundary=__this_is_a_boundary__

--__this_is_a_boundary__
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{
  "event" : {
    "header" : {
      "namespace" : "Settings",
      "name" : "SettingsUpdated",
      "messageId" : "c5d2d1f6-ad7f-4feb-a132-c4fc773962f7"
    },
    "payload" : {
      "settings" : [ {
        "key" : "locale",
        "value" : "en-US"
      } ]
    }
  }
}

--__this_is_a_boundary__--

[INFO] C <---------------------------- S (START SETTINGS)
[INFO] C <---------------------------- S (HEADERS)

The problem is:
I can not get the header data. How to get header data? ex: no status(200).

**Comment by roshanDD** [comment]
@howardguo , I am actually on the same boat, 3 month after you closed this post. Did you find any udpate on this matter?
