### ISSUE TITLE
Change account can not take effect immediately

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#676]
While I log on to a new account, wake up device and say 'what's profile?',  it's stii the old account, but after restart it, the account has been changed

**Comment by scotthea-amazon** [comment]
Hello jacky-ge,
Would you please be a bit more specific.  What exactly do you mean by "log on to a new account"?  Have you tried uttering "Alexa, switch to <some other account name>"? 
Thanks,
-SWH
