### ISSUE TITLE
mvn exec:exec BUILD Failure while testing alexa sample app on Linux platform

### ISSUE THREAD

**Issue by satishc4u** [alexa/alexa-avs-sample-app#677]
alexa-avs-sample-app/samples/javaclient$   mvn exec:exec

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Can't obtain updateLastError method for class com.sun.jna.Native".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:244)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:140)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:140)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:113)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.402s
[INFO] Finished at: Wed Apr 12 16:17:51 IST 2017
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by fosterfoster** [comment]
Here is a great guide for building the Alexa. https://www.google.com/amp/lifehacker.com/how-to-build-your-own-amazon-echo-with-a-raspberry-pi-1787726931/amp

**Comment by dskidmor** [comment]
Hey @satishc4u, can you confirm that you have VLC installed and working?

**Comment by satishc4u** [comment]
Than you for the reply.
Issue is resolved after adding the following line in AVSApp.java main function.
System.setProperty("jna.nosys", "true");

Please clarity the following questions,

1). Can we integrate Alexa in Real Time Operating system(RTOS) like FreeRTOS devices which has low footprint (memory and speed wise)?
2). As per my understanding we can show Alexa directives on screen/display instead of playback to speaker, is it correct ?
3). Does it make sense to convert alexa-sample-app (Java) code  to C++ code as my device has low processing speed ?

**Comment by scotthea-amazon** [comment]
Hello satishc4u,
Good questions!
1) Yes, it is possible.  Some developers have done this.
2) You could somehow render the directives to a display of some kind - but the currently available API is really focused around a voice based interface.
3) There are a lot of trade-offs in that decision - things like the constraints of target device, development effort, available expertise and timeline etc.  There really is no one-size fits all answer.
-SWH

**Comment by satishc4u** [comment]
Hi Scotthea,

Thanks for the explanation. Sorry for the late reply.

1).Does it good idea to integrate AVS sample app in RTOS customized devices  ?
2).Could you help me what are best market areas to integrate Alexa Voice service to integrate ?

**Comment by keleric** [comment]
Hi @satishc4u,

1. That's really a product decision. As you'll be the one building this product, you have to be the one to make the decision as to what OS / processing power / CPU makes the most sense for your device. There's nothing technical preventing AVS from working, but you'll want to make sure that whatever media playing library you use can support a wide variety of formats. GStreamer is often used for this. That said, the Sample app is NOT production-code. It exists to show how interacting with the API should look.
2. Sorry, I can't help you here. Just build what makes sense to you, and hopefully consumers will respond to that!

**Comment by satishc4u** [comment]
Hi Keleric,

Thank you very much.
