### ISSUE TITLE
Invalid Audio Format

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#678]
dear. when I send the audio data to AVS bellow：

--__this_is_a_boundary__
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "29de4c3a-8916-461f-a40e-b4e992b13a8d",
      "dialogRequestId" : "0b66d617-4d7f-4dc8-a394-a7145e3f85b0"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 0,
      "muted" : false
    }
  } ]
}

--__this_is_a_boundary__
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{{binary audio attachment}}
--__this_is_a_boundary__--

# I got a response bellow.But received no binary audio data(no directive: SpeechSynthesizer). why? 
BTW: On amazon AVS interface website have no this interface: "header" : {"namespace" : "SpeechSynthesizer","name" : "SpeechState"} .
what's the SpeechState mean?
The AVS response bellow:
--------abcde123
Content-Type: application/json

{"directive":{"header":{"namespace":"SpeechRecognizer","name":"StopCapture","messageId":"62712c76-9557-4ed3-859f-666210c47c65"},"payload":{}}}

--------abcde123

[audio.tar.gz](https://github.com/alexa/alexa-avs-sample-app/files/918624/audio.tar.gz)

**Comment by howardguo** [comment]
any one can follow this issue?

**Comment by scotthea-amazon** [comment]
Hello howardguo,
I do not see any obvious errors in the JSON of the SpeechRecognizer.Recognize event you are sending, and the directive you are receiving is just telling you to stop streaming more audio for that event.  See:
     https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speechrecognizer#stopcapture
-SWH
