### ISSUE TITLE
Problem with setting up

### ISSUE THREAD

**Issue by ire4ever1190** [alexa/alexa-avs-sample-app#681]
When I run the first setup command

 cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start
 
I get this error 

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

anybody know how to fix it

Im running rasbian on a rasp pi

**Comment by fosterfoster** [comment]
Add a space before companionService...?

**Comment by fosterfoster** [comment]
Here is an awesome guide for what you are doing: https://www.google.com/amp/lifehacker.com/how-to-build-your-own-amazon-echo-with-a-raspberry-pi-1787726931/amp

**Comment by ire4ever1190** [comment]
nope still get the same error

**Comment by ire4ever1190** [comment]
It says the problem is most likely with this and not npm

**Comment by ire4ever1190** [comment]
reintalled and it worked.
wiered =/
