### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#682]
When I use this request , I got a error. what the problem?thanks. error bellow:
{"header":{"namespace":"System","name":"Exception","messageId":"187581c8-491c-4550-8c94-d4598b06f214"},"payload":{"code":"INVALID_REQUEST_EXCEPTION","description":"Bad Request"}}

Request:

--__this_is_a_boundary__
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{
    "context": [
        {
            "header": {
                "namespace": "AudioPlayer",
                "name": "PlaybackState"
            },
            "payload": {
                "token": "abcd1234",
                "offsetInMilliseconds": 7000,
                "playerActivity": "PLAYING"
            }
        },
        {
            "header": {
                "namespace": "Alerts",
                "name": "AlertsState"
            },
            "payload": {
                "allAlerts": [
                    {
                        "token": "foo-bar",
                        "type": "ALARM",
                        "scheduledTime": "2017-04-30T22:34:51+00:00"
                    }
                ],
                "activeAlerts": [
                ]
            }
        },
        {
            "header": {
                "namespace": "Speaker",
                "name": "VolumeState"
            },
            "payload": {
                "volume": 25,
                "muted": false
            }
        },
        {
            "header": {
                "namespace": "SpeechSynthesizer",
                "name": "SpeechState"
            },
            "payload": {
                "token" : "",
                "offsetInMilliseconds": 0,
                "playerActivity": "FINISHED"
            }
        }
    ],
    "event": {
        "header": {
            "namespace": "SpeechRecognizer",
            "name": "Recognize",
            "messageId": "messageId-123",
            "dialogRequestId": "dialogRequestId-321"
        },
        "payload": {
            "profile": "NEAR_FIELD",
            "format": "AUDIO_L16_RATE_16000_CHANNELS_1"
        }
    }
}

--__this_is_a_boundary__
Content-Disposition: form-data; name="audio"
Content-Type: application/octet-stream

{{binary audio attachment}}
--this-is-a-boundary--

**Comment by dskidmor** [comment]
Hey @howardguo, do you have any requestId's you could share to help us look up what went wrong? Also, are you sure your audio is in the correct format?

**Comment by howardguo** [comment]
@dskidmor thank you for your reply. It maybe the boundary issue. I can send it successfully and got the StopCapture reply.
Btw, another question: https://github.com/alexa/alexa-avs-sample-app/issues/678 
could you help me to see this one? Thank you! :)

**Comment by yugoren** [comment]
@howardguo: Referenced issue #678 was closed. I'll go ahead and close this one too, but feel free to open it.
