### ISSUE TITLE
raspberry pi zero w KittAiSnowboyWakeWordEngine start failed

### ISSUE THREAD

**Issue by 123anvar** [alexa/alexa-avs-sample-app#687]
I am using raspberry pi zero W and an external usb sound card (http://www.amazon.in/Storite-Adapter-Virtual-5-1-Channel/dp/B01KQ1378Y?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=739dbd02-9062-4ef8-bf51-c139a3863d2d)

Alexa is working fine with the Java UI button click . But I got below error while triying to use the wakeword agent 'snowboy' (as sensory is not working and heard that it dnt have support on raspberry zero):

cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e kitt_ai

INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
ERROR:Failed to open PortAudio stream.Device unavailable
ERROR:KittAiSnowboyWakeWordEngine: Initialization error:Failed to open PortAudio stream.
ERROR:WakeWordAgent: exception in constructor: Failed to open PortAudio stream.
ERROR:main: Exception happened: Failed to open PortAudio stream.
INFO:Shutting down Wake Word Agent

Also I tried snowboy manually by downloading from https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.2.0.tar.bz2

Which works on running
python demo.py resources/snowboy.umdl

Its been a long time having this issue , somebody please help out.

**Comment by 123anvar** [comment]
I have disabled the default audio device by commenting out 
#dtparam=audio=on
in /boot/config.txt

Below is the content of /home/pi/.asoundrc and /etc/asound.conf files which I have configured for using the USB sound card.
pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "hw:1,0"
}
capture.pcm {
type plug
slave.pcm "hw:1,0"
}

Below is the output of aplay -l and arecord -l commands :

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by sginsbe** [comment]
I'm having this same issue on a Raspberry Pi 3 with a USB mic. Sensory works fine but Kitt.ai continually fails to open the PortAudio stream and says the device is unavailable.

**Comment by 123anvar** [comment]
Worked after :
1. disabling the default audio device by commenting out
**#dtparam=audio=on**
in /boot/config.txt
2.Changing content of /home/pi/.asoundrc  to below :
**pcm.!default { type plug slave { pcm "plughw:1,0" } } ctl.!default { type hw card 1 }**

3.Then installed alexa once more with this settings after a reboot after changing above settings.

Now I have KittiAi snowboy for wakeword detection !!

My configuration was RapberryPiZeroW & external USB sound card as mentioned in this post's start.

If it ddnt work for you , try ALSA instead of OSS for snowboy,
so in /examples/C++ and run
**./configure --without-jack --without-oss --with-alsa
make && make install**

**Comment by beda000** [comment]
I just wanted to share my experiences:
I use USB soundcard on RaspPI Zero W.
Finally this helped:

apt-get install pulseaudio
alsactl init
and 123anvar's .asoundrc

**Comment by cjbeames** [comment]
> I just wanted to share my experiences:
I use USB soundcard on RaspPI Zero W.
Finally this helped:

apt-get install pulseaudio
alsactl init
and 123anvar's .asoundrc


can you explain how to do this for an amateur?
