### ISSUE TITLE
Node.js debugging ENOENT 34

### ISSUE THREAD

**Issue by Petr2** [alexa/alexa-avs-sample-app#697]
error code: ENOENT
error number: 34

There is no more information. Anyone have any ideas? 
P

**Comment by scotthea-amazon** [comment]
Hello Petr2,
We need more context (preferably steps to reproduce the problem) to be able to help you with this.
-SWH
ithout some context or steps to reproduce this error there

**Comment by Petr2** [comment]
I am not having much joy here.  Previous comment re no wiringpi.h - I hand edited the script as the pull request suggested then re run it.  That seemed to be ok.  Other than that, it was a new install of jessie-lite on a pi zero, I had set up a usb mic and speaker as default (chose 3.5 mm jack as there is no usb option thinking I could fix it later)  I had installed orace-java-8 (which was uninstalled and then reinstalled?)
Otherwise I was quite explicitly following the instructions and really not sure what other context there might be...

![talkmldevgui 1](https://cloud.githubusercontent.com/assets/27725225/25142248/2ce2fbca-245e-11e7-930d-75655e1ae3f5.png)

**Comment by scotthea-amazon** [comment]
Hello Petr2,
The screen shot helps a lot!  ENOENT means a file or directory was not found. "npm start" is looking for package.json in the current directory ( alexa-avs-sample-app ), where it does not normally exist.
I expect you are running the steps found here:

    https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

And that you are revisiting step 7.  Note that in that step you need to cd to alexa-avs-sample-app/samples/companionService before "npm start" is executed.

Hope that helps,
-SWH

**Comment by Petr2** [comment]
And I thought I was being very careful!  cd to the right directory was the solution for EOENT 34 message.
