### ISSUE TITLE
Android App to adding Alexa Voice Service to your mobile 

### ISSUE THREAD

**Issue by javaand** [alexa/alexa-avs-sample-app#699]
Hi Guys,

I have just test your alexa sample app using both android and nodejs authentication method. I would like if there is an android app that is responsible to login with amazon and interact with alexa in the same time (without companion app).

Thanks in advance.

**Comment by scotthea-amazon** [comment]
Hello javaand,
Unfortunately at this time Amazon does not have an Android example client for AVS.
It has been filed a couple of times in the [feature request forum]( https://forums.developer.amazon.com/spaces/185/index.html.) with some follow on discussion that you might find interesting
-SWH

**Comment by elstryan** [comment]
We don't have a sample but we have these code snippets: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-mobile-app. That page shows you how to perform an login with amazon authorization request to get an access token for your android device.  

I'll close this issue for now - but if you need more information feel free to re-open.

**Comment by ParikshitSinghTomar** [comment]
Can anyone tell me about application android application "Reverb". This application have Alexa Assistant in  android. I tried it and its works prefect.
