### ISSUE TITLE
Headless?

### ISSUE THREAD

**Issue by Petr2** [alexa/alexa-avs-sample-app#701]
I was hoping to run this headless on a pi zero  (jessie lite) but now have the message:
No X11 DISPLAY variable was set.  This seems to be built in to the java avs code.  Does this mean my hopes have been dashed?   It seems I should be able to do that in a browser on a different machine and then, without the windowing environment, confirm I've done it.
If this is not possible at the moment, could we make it a feature request.

P

**Comment by Kinjalk** [comment]
@Petr2 Hi. I have made some changes to javaclient and its working headless now. Starts on boot as well. Tested for 20 days and its working great.
[#203](https://github.com/alexa-pi/AlexaPi/issues/203#issuecomment-294254644)
Let me know if this works for you.

**Comment by Petr2** [comment]
Thanks for the pointer but it seems the code is moved on.  No more
AVSApp.java in the Amazon source ...
I will take another look in a month or so and perhaps the dust will have
settled.

P

**Comment by scotthea-amazon** [comment]
Hello  Petr2,
If you're interested having this added to the sample app, you can also create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html.
Thanks!
-SWH

**Comment by tr1plus** [comment]
Latest version allows for a complete headless usage. You only need to start it once via VNC and the other thing you need to do is create a few scripts. I made a small blog post on it. All you need is to install tmux and create a script to launch on boot:
http://www.triplustutorials.be/2017/04/24/provide-usb-sound-output-for-alexa-voice-services-useful-for-the-raspberry-pi-zero/

**Comment by Kinjalk** [comment]
@Petr2 Check [#203](https://github.com/alexa-pi/AlexaPi/issues/203#issuecomment-294254644) again. I have added steps for new repo.

**Comment by Colin1964** [comment]
@tr1plus  Your startup script is just what I am after. At work ATM but plan to try this out asap. If I use your script do I still need to have completed the logging off instructions below? 

> Quit the AVS java sample app (CTRL + C).
> Open /samples/javaclient/config.json and clear your sessionId. It should look like this:
> "sessionId": ""
> Delete the refresh_tokens file in samples/companionService.
> The next time you log in you will be prompted to authenticate.

If so, could these be incorporated into a "Log Off" script?

**Comment by tr1plus** [comment]
@Colin1964 I haven't used those. However it has been a while since I used alexa on my Pi

**Comment by elstryan** [comment]
@Colin1964 the log off instructions were added due to a recent update to the project that would persist tokens between starting and stopping a running Node service which will be very helpful for a headless mode. 
You don't need to follow the logout steps unless you intend to log a user out of the application.
Thanks to the community for helping out on this thread. I'll close this out for now but feel free to re-open if there is anything else we can help with.

**Comment by itayavra** [comment]
Hey, I created a small script to run it headless with one command (and without sleep so it runs as fast as possible). 
Feel free to try and let me know what you think (alexa-avs-sample-app should be installed as a prerequisite for my script):
https://github.com/itayavra/alexa-headless-start
