### ISSUE TITLE
javaclient runnig into a exeption after login in amazon 

### ISSUE THREAD

**Issue by JamesZEMOURI** [alexa/alexa-avs-sample-app#702]
running mvn exec:exec

![image](https://cloud.githubusercontent.com/assets/18288140/25201809/62b6bc14-2553-11e7-97eb-6c2b52865896.png)

running sudo mvn exec:exec
![image](https://cloud.githubusercontent.com/assets/18288140/25201967/e4295270-2553-11e7-9eac-df00e7a1b069.png)

**Comment by scotthea-amazon** [comment]
Hello JamesZEMOURI,

In our first screen grab I see the error "The required file config.json could not be updated".   You might want to check that the file is there and that the permissions are open enough to allow the application to write to it.  This file should be under:
~~~~
{REFERENCE_IMPLEMENTATION}samples/companionService
~~~~

In the second screen grab I see errors from sun.awt.x11graphicsenvironment.initdisplay.  With some googling I came to [this article](http://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t), which looks like it may be helpful.
Hope this helps!
-SWH

**Comment by JamesZEMOURI** [comment]
Thx :D
