### ISSUE TITLE
skills in german dont work for me

### ISSUE THREAD

**Issue by mowoe** [alexa/alexa-avs-sample-app#706]
i switched the locale to de, but the skills dont work. Alexa says that the languauges aren't the same. In the app i see the german skill store(i know the app is broken for the pi), in the web interface i see the us skill store( the web site is on german but the skills are english), any way to fix that?
![ss](https://cloud.githubusercontent.com/assets/12197109/25314501/78cf2bcc-2845-11e7-8e9c-edfb7b4952fa.png)

**Comment by stevbenn** [comment]
@mowoe:  Can you include information on where you modified the locale so I can attempt to reproduce this?

**Comment by dogboy21** [comment]
I'm also experiencing this issue. I changed the locale setting in the java client's [config.json](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/config.json#L6) to `de_DE`

**Comment by yugoren** [comment]
@mowoe, @dogboy21: You'll need to set your internalization settings for your account (that you used in LWA page) in Amazon MArketplace. If you follow [this link](https://www.amazon.com/mn/dcw/myx.html/ref=nav_youraccount_myk#/home/settings/payment), you'll see Country Settings. Could you set that to an address in your locale (in this case, Germany) and try again?

**Comment by dogboy21** [comment]
Yep, that works, thank you :)
