### ISSUE TITLE
Windows installation, step six failure

### ISSUE THREAD

**Issue by tomesdw** [alexa/alexa-avs-sample-app#707]
I have run through the steps found here - https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app

And all went well until I got to step 6 and ran the mvn install, and got some compilation errors and a build failure.  I am not sure what I did wrong or even how to troubleshoot this.  I verified each step as I went and was meticulous.  This is my first real venture with GitHub stuff, and am looking for some guidance.  I apologize in advance for general noobness, but hoping to get up the learning curve as fast as I can with some help.

Thanks

![screenshot 2017-04-23 23 49 12](https://cloud.githubusercontent.com/assets/27940637/25321988/b38fb7dc-2880-11e7-90ef-3113b8713b40.png)

**Comment by yugoren** [comment]
Hi @tomesdw,

It seems like your system is missing a Java compiler (2nd red error line in the image). Could you double-check if you have it?

**Comment by tomesdw** [comment]
yes, after a windows update, something got messed up (and a system restore
failed) so I am going to start from scratch as I had to reinstall
Windows...  -=sigh=-  More to follow after I dig out from under this one...

**Comment by yugoren** [comment]
@tomesdw: Good luck with that! I'll close the issue for the moment, but please feel free to open it again if the problem persists after re-install.
