### ISSUE TITLE
Java client not starting 

### ISSUE THREAD

**Issue by koolkarni** [alexa/alexa-avs-sample-app#716]
~/Desktop/alexa-avs-sample-app/samples/javaclient$ echo $LD_LIBRARY_PATH
/usr/lib/vlc

~/Desktop/alexa-avs-sample-app/samples/javaclient$ echo $VLC_PLUGIN_PATH
/usr/lib/vlc/plugins**

Still I am getting

Desktop/alexa-avs-sample-app/samples/javaclient$ mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path ([file:/home/nik/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/nik/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar, file:/home/nik/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/nik/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/nik/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/nik/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/nik/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/nik/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/nik/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/nik/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/nik/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/home/nik/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/nik/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/nik/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/nik/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/nik/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:

    Include NativeLibrary.addSearchPath("vlc", ""); at the start of your application code.
    Include System.setProperty("jna.library.path", ""); at the start of your application code.
    Specify -Djna.library.path= on the command-line when starting your application.
    Add to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:248)
at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:141)
at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:171)
at com.amazon.alexa.avs.App.<init>(App.java:65)
at com.amazon.alexa.avs.App.<init>(App.java:53)
at com.amazon.alexa.avs.App.main(App.java:48)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.670 s
[INFO] Finished at: 2017-04-27T00:37:34Z
[INFO] Final Memory: 11M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by stevbenn** [comment]
@koolkarni: Let's confirm first that libvlc.so is in your path with the following commands:
``` bash
ls -l $LD_LIBRARY_PATH
ls -l $VLC_PLUGIN_PATH
```
Can you share the output?

**Comment by koolkarni** [comment]
**## nik@COROS_TX2_1:~$ ls -l $LD_LIBRARY_PATH**
total 40
-rw-r--r--  1 root root  1980 Feb 22 15:14 libcompat.a
lrwxrwxrwx  1 root root    21 Feb 22 15:14 libvlc_vdpau.so -> libvlc_vdpau.so.0.0.0
lrwxrwxrwx  1 root root    21 Feb 22 15:14 libvlc_vdpau.so.0 -> libvlc_vdpau.so.0.0.0
-rw-r--r--  1 root root 14304 Feb 22 15:14 libvlc_vdpau.so.0.0.0
drwxr-xr-x  8 root root  4096 Apr 25 21:54 lua
drwxr-xr-x 27 root root  4096 Apr 27 00:24 plugins
-rwxr-xr-x  1 root root 10320 Feb 22 15:14 vlc-cache-gen


## **nik@COROS_TX2_1:~$ ls -l $VLC_PLUGIN_PATH**
total 380
drwxr-xr-x 2 root root   4096 Apr 27 00:23 access
drwxr-xr-x 2 root root   4096 Apr 25 21:54 access_output
drwxr-xr-x 2 root root   4096 Apr 25 21:54 audio_filter
drwxr-xr-x 2 root root   4096 Apr 25 21:54 audio_mixer
drwxr-xr-x 2 root root   4096 Apr 27 00:23 audio_output
drwxr-xr-x 2 root root   4096 Apr 27 00:23 codec
drwxr-xr-x 2 root root   4096 Apr 27 00:23 control
drwxr-xr-x 2 root root   4096 Apr 25 21:54 demux
drwxr-xr-x 2 root root   4096 Apr 27 00:23 gui
drwxr-xr-x 2 root root   4096 Apr 25 21:54 lua
drwxr-xr-x 2 root root   4096 Apr 25 21:54 meta_engine
drwxr-xr-x 2 root root   4096 Apr 27 00:23 misc
drwxr-xr-x 2 root root   4096 Apr 25 21:54 mux
drwxr-xr-x 2 root root   4096 Apr 27 00:23 notify
drwxr-xr-x 2 root root   4096 Apr 25 21:54 packetizer
-rw-r--r-- 1 root root 283739 Apr 27 00:24 plugins.dat
drwxr-xr-x 2 root root   4096 Apr 27 00:23 services_discovery
drwxr-xr-x 2 root root   4096 Apr 25 21:54 stream_filter
drwxr-xr-x 2 root root   4096 Apr 25 21:54 stream_out
drwxr-xr-x 2 root root   4096 Apr 27 00:23 text_renderer
drwxr-xr-x 2 root root   4096 Apr 27 00:23 vdpau
drwxr-xr-x 2 root root   4096 Apr 25 21:54 video_chroma
drwxr-xr-x 2 root root   4096 Apr 25 21:54 video_filter
drwxr-xr-x 2 root root   4096 Apr 27 00:23 video_output
drwxr-xr-x 2 root root   4096 Apr 27 00:23 video_splitter
drwxr-xr-x 2 root root   4096 Apr 27 00:23 visualization

**Comment by stevbenn** [comment]
@koolkarni:  
I don't see either of the files suggested by the error message:
```
The required native libraries are named "libvlc.so" and "libvlccore.so".
```

Are you sure VLC is installed correctly?

**Comment by koolkarni** [comment]
### Now i have all the required files still it says the same thing 

**nik@OOS_TX2_1:~/Desktop/alexa-avs-sample-app/samples/javaclient$** ls -l $LD_LIBRARY_PATH 
total 1048
-rw-r--r--  1 root root   1980 Feb 22 15:14 libcompat.a
lrwxrwxrwx  1 root root     19 Feb 22 15:14 libvlccore.so -> libvlccore.so.8.0.0
lrwxrwxrwx  1 root root     19 Feb 22 15:14 libvlccore.so.8 -> libvlccore.so.8.0.0
-rw-r--r--  1 root root 909456 Feb 22 15:14 libvlccore.so.8.0.0
lrwxrwxrwx  1 root root     15 Feb 22 15:14 libvlc.so -> libvlc.so.5.5.0
lrwxrwxrwx  1 root root     15 Feb 22 15:14 libvlc.so.5 -> libvlc.so.5.5.0
-rw-r--r--  1 root root 117688 Feb 22 15:14 libvlc.so.5.5.0
lrwxrwxrwx  1 root root     21 Feb 22 15:14 libvlc_vdpau.so -> libvlc_vdpau.so.0.0.0
lrwxrwxrwx  1 root root     21 Feb 22 15:14 libvlc_vdpau.so.0 -> libvlc_vdpau.so.0.0.0
-rw-r--r--  1 root root  14304 Feb 22 15:14 libvlc_vdpau.so.0.0.0
drwxr-xr-x  8 root root   4096 Apr 25 21:54 lua
drwxr-xr-x 27 root root   4096 Apr 27 00:24 plugins
-rwxr-xr-x  1 root root  10320 Feb 22 15:14 vlc-cache-gen

**Comment by koolkarni** [comment]
Issue is resolved after adding the following line in /AVS/App.java main function.
System.setProperty("jna.nosys", "true");

referred already opened issue
