### ISSUE TITLE
step2  找不到或无法加载主类 com.amazon.alexa.avs.App 

### ISSUE THREAD

**Issue by lvan-jone** [alexa/alexa-avs-sample-app#717]
Thank everyone for reading and answering.

After downloading alexa-avs-sample-app, execute the command "D: \ Lvan \ eworkspaces \ avssamplef" mvn exec: exec -Dalpn-boot.version = 8.1.7 as described in "javaclient / readme.txt". V20160121 "after the error, the following is a screenshot（The following is an error description in "cmd"）:

**********************************************
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>d:

D:\>cd D:\Lvan\workspaces\avssamplef>
命令语法不正确。

D:\>cd D:\Lvan\workspaces\avssamplef

D:\Lvan\eworkspaces\avssamplef>mvn exec:exec -Dalpn-boot.version=8.1.7.v20160121

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.logging.log4j:log4j-core:jar:2.3 is invalid, tr
ansitive dependencies (if any) will not be available, enable debug logging for m
ore details
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
错误: 找不到或无法加载主类 com.amazon.alexa.avs.App
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.377 s
[INFO] Finished at: 2017-04-27T11:57:40+08:00
[INFO] Final Memory: 10M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (d
efault-cli) on project sample-java-client: Command execution failed. Process exi
ted with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

D:\Lvan\workspaces\avssamplef>

**********************************************

Operating environment is: win7 64-bit, JDK8, in a WEB project

Thanks again for your reading and answering.

**Comment by stevbenn** [comment]
@lvan-jone:
Are you following the tutorial instructions here?
[https://github.com/alexa/alexa-avs-sample-app/wiki/Windows](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows)

**Comment by lvan-jone** [comment]
@stevbenn Yes, I follow, but copy the project in the directory, Java classes are being given, no JAR package, so want to deal with the next.
And then out of this error

**Comment by stevbenn** [comment]
@lvan-jone: Have the other items from [Step 6](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app) been successful?  e.g.
```bash
mvn validate
mvn install
```

Also, which directory are you running this from?

**Comment by lvan-jone** [comment]
@stevbenn I have not yet come to step 6，
(I was in the javaclent directory before the copy, and later being given,)
Now a new web project, put all the catalogs into the project.


![dir](https://cloud.githubusercontent.com/assets/26494609/25551350/14985212-2cb6-11e7-92f1-082db1c7d4a0.PNG)

**Comment by yugoren** [comment]
Hi @lvan-jone,

I don't understand what you mean by ' have not yet come to step 6' since the command `mvn exec:exec` is not executed until [Step 6.8](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app). Have you completed all the previous steps in that link?

Also, why are you passing `-Dalpn-boot.version=8.1.7.v20160121` to `mvn`? That's not listed in the instruction steps. Did you have a previous problem with Maven not finding `alpn`?

To understand completely your setup, which authorization method are you using?

**Comment by lvan-jone** [comment]
@yugoren The original second step do not have to deal with sample, has passed, still thank you and thank @stevbenn
