### ISSUE TITLE
step4-4.8 ssl.cnf unable to find 'distinguished_name' in config problems making Certificate Request

### ISSUE THREAD

**Issue by lvan-jone** [alexa/alexa-avs-sample-app#723]
Thank everyone for reading and answering.

![generate_error](https://cloud.githubusercontent.com/assets/26494609/25603098/aee9cacc-2f2b-11e7-8857-d0c859f15ee3.png)
![sslcnfpric](https://cloud.githubusercontent.com/assets/26494609/25603097/aee3780c-2f2b-11e7-900c-5cf172ff9cb9.png)

When I execute to 4.8, the error occurred, as shown, "req: Error on line 1 of config file" ./ssl.cnf "
Unable to find 'distinguished_name' in config ', i need to put "distinguished_name" on the first line or how to handle it?
There can not find the file "certs \ client \ client.crt" "certs \ client \ client.csr" and so on, which is in which the directory generated?

Thanks again for your reading and answering.

**Comment by lvan-jone** [comment]
In addition, some directories are found, for example, "openssl.cfg" in "set OPENSSL_CONF = {OpenSSL installation location} \ bin \ openssl.cfg" is not found;
There are prompts that can not find the directory of those files.

**Comment by namanmittal-namanm** [comment]
Hi @lvan-jone, it looks like the ssl path didn't got set-up correctly and also it looks like you are trying to set up Alexa on Windows, so can you please try setting ssl path again as described in steps [here](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#4---generating-self-signed-certificates)

**Comment by lvan-jone** [comment]
My "ssl configuration" was shown to be successful
In addition, I saw the same question in the forum, changed to this, or not
`[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                 # C=
stateOrProvinceName     = WA            # ST=
localityName            = Seattle                         # L=
organizationName        = Amazon                 # O=
organizationalUnitName  = Alexa          # OU=`

`Product ID: amzn1.application.6f4d5046ea64b188c95a8d3a0567741
Serial Number: 123456
Password for Keystores:
Generating RSA private key, 4096 bit long modulus
................................................................................
....................................................................++
..................................++
e is 65537 (0x010001)
req: Error on line 1 of config file "./ssl.cnf"
unable to find 'distinguished_name' in config
problems making Certificate Request
9772:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or envi
ronment variable:crypto\conf\conf_lib.c:272:
Generating RSA private key, 2048 bit long modulus
........................+++
....................+++
e is 65537 (0x010001)
req: Error on line 1 of config file "ssl.cnf"
unable to find 'distinguished_name' in config
problems making Certificate Request
9836:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or envi
ronment variable:crypto\conf\conf_lib.c:272:
x509: Cannot open input file certs\client\client.csr, No such file or directory
x509: Use -help for summary.
pkcs12: Cannot open input file certs\client\client.crt, No such file or director
y
pkcs12: Use -help for summary.
Generating RSA private key, 2048 bit long modulus
..+++
..+++
e is 65537 (0x010001)
req: Error on line 1 of config file "ssl.cnf"
unable to find 'distinguished_name' in config
problems making Certificate Request
8172:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or envi
ronment variable:crypto\conf\conf_lib.c:272:
x509: Cannot open input file certs\server\node.csr, No such file or directory
x509: Use -help for summary.
Generating RSA private key, 2048 bit long modulus
......+++
.........+++
e is 65537 (0x010001)
req: Error on line 1 of config file "ssl.cnf"
unable to find 'distinguished_name' in config
problems making Certificate Request
9892:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or envi
ronment variable:crypto\conf\conf_lib.c:272:
x509: Cannot open input file certs\server\jetty.csr, No such file or directory
x509: Use -help for summary.
pkcs12: Cannot open input file certs\server\jetty.crt, No such file or directory

pkcs12: Use -help for summary.
找不到文件 - ca.crt
复制了 0 个文件
x509: Cannot open input file certs\ca\ca.crt, No such file or directory
x509: Use -help for summary.
找不到文件 - ca.der
复制了 0 个文件
`

@namanmittal-namanm @ajot @jpeddicord @jpalat @hyandell  Can you help me?thanks

**Comment by lvan-jone** [comment]
@namanmittal-namanm  this is my openssl option:
OpenSSL 1.1.0c 10 Nov 2016
Built on: reproducible build, date unspecified
Platform:
Compiler: cl "" VC-WIN64A
OPENSSLDIR: "C: \ Program Files \ Common Files \ SSL"
ENGINESDIR: "C: \ Program Files \ OpenSSL \ lib \ engines-1_1"

**Comment by namanmittal-namanm** [comment]
Hi @lvan-jone Sometime the editor messes the file with non-visual characters which creates problems while parsing, what I recommend doing once is to again download the ssl.conf file and try editing it in a different editor.

**Comment by lvan-jone** [comment]
@namanmittal-namanm  I used the editor of the UE,What kind of the editor would be better?

**Comment by keleric** [comment]
@lvan-jone Try getting a fresh copy of ssl.cnf, then modifying it with notepad.exe.

**Comment by lvan-jone** [comment]
@keleric  When I used notepad, then the following error occurred:

> D:\Lvan\eworkspaces\alexa-avs-sample-app\samples\companionService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start D:\Lvan\eworkspaces\alexa-avs-sample-app\
samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS ap
p.

_tls_common.js:65
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:65:17)
    at Server (_tls_wrap.js:733:25)
    at new Server (https.js:17:14)
    at Object.exports.createServer (https.js:37:10)
    at Object.<anonymous> (D:\Lvan\eworkspaces\alexa-avs-sample-app\samples\companionService\bin\www
:31:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by lvan-jone** [comment]
Because the 4.8 problem has been resolved, thanks to every answer, I finally version of the win can be changed to the Mac version, it is estimated that there are problems before the openssl configuration.
Now the problem is happening in 5.10, so I put this question off, 5.10 the link is here:
https://github.com/alexa/alexa-avs-sample-app/issues/729

**Comment by zefeng2016** [comment]
hi,我也遇到了这个问题，能否请教下你是怎么解决的

**Comment by lvan-jone** [comment]
I finally version of the win can be changed to the Mac version, it is estimated that there are problems before the openssl configuration.

**Comment by zefeng2016** [comment]
Yes, I tried yesterday for a whole day, and finally did not complete, and finally encountered the page was intercepted by the browser, showing unsafe.

发自我的 iPhone
