### ISSUE TITLE
Raspberry Pi: MVN fails to run correctly on autostart 

### ISSUE THREAD

**Issue by reesul** [alexa/alexa-avs-sample-app#726]
I am trying to get the sample app running automatically upon each boot.  NPM and WakeWord are not an issue; they haven't given me any sort of problems.  I cannot seem to get Maven to build the java app correctly though.  Each method for starting this at boot has the app start recording audio, but it does not stop recording or give a response like the working app does.  I can run the mvn exec:exec command manually, and it will work exactly as it should, so I am not sure why the app fails to build correctly just because it starts running based off of some autostart method.  

I have tried quite a few approaches, including making crontab entries, adding commands to /etc/rc.local, setting up desktop entries in a ~/.config/autostart folder, adding commands to the autostart folder for lxsession to open separate terminals for each command, and making a separate python script (to run the same .sh) for startup with no success. The most recent attempt places the script containing the mvn command on the desktop, the boot script moves the mouse there, and starts "psuedo-manually" starts the base file with scripted mouse/keyboard commands (using xdotool), but the issue persists.

Sometimes I will get an error message from the application: java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException

I have also included a .txt file that logged the output of the script containing the mvn command when run manually.  When the app works correctly, the log only has about 20 lines max, all of which seem like reasonable outputs as shown in the file.

[mvnlog_successful.txt](https://github.com/alexa/alexa-avs-sample-app/files/971085/mvnlog_successful.txt)

Below is a log built the same way, but for when the application is started automatically.  I notice that it seems to try to run the mvn script twice, but I cannot seem to figure out where this second call is coming from (assuming this isn't supposed to happen).  At best, the client runs for one command, then stops working.  
[mvnlog_fail.txt](https://github.com/alexa/alexa-avs-sample-app/files/971460/mvnlog_fail.txt)

I am not sure whether the issue is with maven, the app itself, or something that I have done/not done, but could someone provide some insight here?  Thank you.

Edit:  Here is the log file made by the actual client, as opposed to whatever output mvn had: 
[application-2017-05-02-7.txt](https://github.com/alexa/alexa-avs-sample-app/files/972078/application-2017-05-02-7.txt)

**Comment by namanmittal-namanm** [comment]
Hi @reesul, I looks like there might be a problem with the cron entry, I think what you may try is before starting the job you can try to kill the running process and then start the application.

**Comment by gerenb** [comment]
I'm having the exact same problem. Has a solution been found?

**Comment by reesul** [comment]
@gerenb I found the problem to be a duplicate version of the same script running at startup when I tried to autostart the script using a desktop entry.  I did not use any sort of cron entry for this.  

My solution had a script for starting each of the services and another script above that to start it.  The way I fixed the duplicate was a sort of dirty solution, where I had the lower level script writing its PPID (echo "$$") to a log file, which was reset by /etc/rc.local at boot.  I noticed that if I tried to read a line past what the actual last line of the log was, it would just give me the last line.  So I had a part of the upper level script reading two of the lines, and if they were equal, then it must be the case that only one of the scripts has written its PPID so far.  This is the script I decided to keep open.  If they were not equal, I used that second PPID from the log to kill the second instance of the script.  

You have may to play with the sleep command to get the timing right for this, but it ended up working out for me.  If this is unclear, let me know.

**Comment by gerenb** [comment]
@reesul It would be really helpful if you could provide the scripts, locations and modified config. files to resolve this problem. It has been giving me grief for a long time and I'm sure it would help many others. Thx

**Comment by reesul** [comment]
I attached the 3 scripts I used zipped together, along with a desktop entry for autostarting control.sh (the top level script).  I kept the scripts on the Desktop, along with another folder called "Alexa" on the Desktop, containing a folder called "logs" for which all of the log files go.  For the Desktop entry, place it in /home/pi/.config/autostart, and you may have to create the autostart folder yourself.  

I reset each log at boot by adding a line to /etc/rc.local containing something like echo "boot" < /home/pi/Alexa/logs/[YourLogNameHere]


Hopefully the timing is not an issue on your machine, but the control script should do what I outlined in the comment before.  There are surely quite a few ways that these could be more efficient, so feel free to play with them.  I can try to help troubleshoot some too I guess.


[AlexaAutostart.zip](https://github.com/alexa/alexa-avs-sample-app/files/1002050/AlexaAutostart.zip)

**Comment by gerenb** [comment]
I've implemented your scripts but I still can't get the java app to reliably run. I'll try again over the next few days. In any case, thanks for your assistance.

**Comment by gerenb** [comment]
I fixed the problem by using a brute force approach. I run a script from the desktop using xautomation xte to do a mouse click, followed by a return, return (xdotool seg faults with tightvnc). Works every time 8-)
