### ISSUE TITLE
Must I keep the RPi's hostname as the default (raspberrypi) for the automated_install.sh to work correctly?

### ISSUE THREAD

**Issue by joel0063** [alexa/alexa-avs-sample-app#727]

**Comment by namanmittal-namanm** [comment]
Hi @joel0063 I believe you can change the RPi hostname, are you facing problems during installation? If so can you please paste the error's you are getting.

**Comment by ssfdre38** [comment]
you can have different host names for the raspberry pi, it doesnt require it to be raspberrypi

**Comment by elstryan** [comment]
I'll close this issue for now in light of the answers above. Feel free to re-open or let us know if you need anything else.
