### ISSUE TITLE
npm  start error -"products" error

### ISSUE THREAD

**Issue by lvan-jone** [alexa/alexa-avs-sample-app#729]
Thank everyone for reading and answering.

When I execute "npm start" the following error occurs,
`LvandeMacBook-Pro:companionService lvan$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/config.js:27
        "amzn1.application.6f4d5046ad64b188c95a8d3a0567741": [“123456”], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
                                                               ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/npm-debug.log
`

Then I saw someone else's example, changed to the following, or there is an error

`LvandeMacBook-Pro:companionService lvan$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/config.js:27
        "ProductID": [“DeviceSerialNumber”], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
                      ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/npm-debug.log
`
and

`LvandeMacBook-Pro:companionService lvan$ npm list
alexa-voice-service-sample-companion-service@1.0.0 /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService
├─┬ body-parser@1.12.4
│ ├── bytes@1.0.0
│ ├── content-type@1.0.2
│ ├── depd@1.0.1
│ ├── iconv-lite@0.4.8
│ ├─┬ on-finished@2.2.1
│ │ └── ee-first@1.1.0
│ ├── qs@2.4.2
│ ├─┬ raw-body@2.0.2
│ │ └── bytes@2.1.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.15
│     └── mime-db@1.27.0
├─┬ debug@2.2.0
│ └── ms@0.7.1
├─┬ express@4.12.4
│ ├─┬ accepts@1.2.13
│ │ └── negotiator@0.5.3
│ ├── content-disposition@0.5.0
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.6
│ ├── escape-html@1.0.1
│ ├─┬ etag@1.6.0
│ │ └── crc@3.2.1
│ ├── finalhandler@0.3.6
│ ├── fresh@0.2.4
│ ├── merge-descriptors@1.0.0
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.3
│ ├─┬ proxy-addr@1.0.10
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.0.5
│ ├── range-parser@1.0.3
│ ├─┬ send@0.12.3
│ │ ├── destroy@1.0.3
│ │ └── mime@1.3.4
│ ├── serve-static@1.9.3
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ node-storage@0.0.7
│ ├── async@0.9.2
│ └─┬ mkdirp@0.5.1
│   └── minimist@0.0.8
└── node-uuid@1.4.1

`
Thanks again for your reading and answering.

**Comment by namanmittal-namanm** [comment]
Hi @lvan-jone It looks like "testdevice1": ["DSN1234", "DSN5678"] (In your 2nd try this looks like unknown token "DSN5678"] ) is not getting commented out and is being treated as unknown key value pair can you please delete the part you were commenting and try gain with correct values of ProductID and DSN.

**Comment by lvan-jone** [comment]
@namanmittal-namanm  When I delete the note, or so prompted, so I think it should be other issues

**Comment by namanmittal-namanm** [comment]
Hi @lvan-jone Can you please paste your config.js file here. Also please remove clientID and secret before pasting.

**Comment by lvan-jone** [comment]
/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.**********b4afa5fb004d8701',
    clientSecret: 'f830cd15*******d71e89b22436efe2695eaec26e897a59ab6',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\server\\node.key',
    sslCert: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\server\\node.crt',
    sslCaCert: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\ca\\ca.crt',
    products: {
        "amzn1.application.6f4d5046ead4***88c95a8d3a0567741": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;


thanks for your reminder

**Comment by lvan-jone** [comment]
@namanmittal-namanm

**Comment by lvan-jone** [comment]
@namanmittal-namanm `/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.*********##b4afa5fb004d8701',
    clientSecret: 'f830cd15*******d71e89b22436efe2695eaec26e897a59ab6',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\server\\node.key',
    sslCert: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\server\\node.crt',
    sslCaCert: 'D:\Lvan\eworkspaces\alexa-avs-sample-app\\samples\\javaclient\\certs\\ca\\ca.crt',
    products: {
        "amzn1.application.6f4d5046ead4***88c95a8d3a0567741": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;
`

**Comment by namanmittal-namanm** [comment]
Hi @lvan-jone it seems you are missing a comma after ["123456"] in products.
It should be
`amzn1.application.6f4d5046ead4***88c95a8d3a0567741": ["123456"],` 
Also I think you are using security profile ID instead of deviceID (ProductId).

**Comment by lvan-jone** [comment]
@namanmittal-namanm 
LvandeMacBook-Pro:companionService lvan$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/config.js:27
        “amzn1.application-oa2-client.d2***###4d8701”: [“1234”] ,// Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]},
        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/companionService/npm-debug.log

**Comment by lvan-jone** [comment]
Api document tips:

`8.In your favorite text editor, open {REFERENCE_IMPLEMENTATION}/samples/companionService/config.js and edit the following values:
clientId: Paste in your client ID as a string.
clientSecret: Paste in your client secret as a string.
products: The products object consists of a key that should be the same as the product ID (also referred to as Device Type ID) that you set up in the developer portal and an array of unique product identifiers. For this project, the array should be a single value, and match the serial number you entered while generating certificates.`

**Comment by keleric** [comment]
Can you paste your entire config.js file here? Please do so within a code block, and remove delete your client secret. There's clearly some issue with it that hopefully I can solve by looking at it.

**Comment by lvan-jone** [comment]
@keleric 
config.js
`/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.d2#####afa5fb004d8701',
    clientSecret: 'f830ccf171b61d1#####8d71e89b22436efe2695eaec26e897a59ab6',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/javaclient/certs/server/node.key',
    sslCert: '/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt',
    sslCaCert: '/Users/lvan/Documents/amazon/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt',
    products: {
        “amzn1.application.6f4d50#####95a8d3a0567741”: [“123456”],
   },
};

module.exports = config;
`

**Comment by keleric** [comment]
Hi @lvan-jone,

As @namanmittal-namanm said, you have an incorrect product id. It should be the field in the following box:

![product id](https://cloud.githubusercontent.com/assets/18313017/25753062/1037f3a4-316f-11e7-9fc1-301fb89c5397.png)

Also, please delete the commas after ["123456"] and the following }. I believe those commas are making it invalid. You'll also want to make sure that you're using the correct " characters. You can try changing them to single quotes. If you do, make sure they're ' quotes and not ` quotes.

Let me know if that fixed the problem.

**Comment by lvan-jone** [comment]
@keleric @namanmittal-namanm 
I used single quotation marks and double quotes, but also removed the comma, the result is the token is being given. As follows:

`LvandeMacBook-Pro:companionService lvan$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/config.js:27
        "SmartDevice": [‘123456’]    },
                        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/npm-debug.log
LvandeMacBook-Pro:companionService lvan$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/config.js:27
        "SmartDevice": [“123456”]    },
                        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/npm-debug.log
LvandeMacBook-Pro:companionService lvan$ `

**Comment by lvan-jone** [comment]
@keleric  In addition, I also used the ID you said

**Comment by lvan-jone** [comment]
@keleric 
this is my config.js:
`/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.c480####88c51131b15579d6',
    clientSecret: '002b0d82802ec82f0e831#####08273d478138269dfc799e97acc5e',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/server/node.key',
    sslCert: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt',
    sslCaCert: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt',
    products: {
        "SmartDevice": [“123456”]   
 },
};

module.exports = config;
`

**Comment by lvan-jone** [comment]
This is a solution today, is the symbol of the problem, thank you to answer.
