### ISSUE TITLE
Can I run the Alexa Voice Service on android or iOS ?

### ISSUE THREAD

**Issue by Arroon** [alexa/alexa-avs-sample-app#732]
Can I run the Alexa Voice Service on android or iOS ?
Because our hardware is just bluetooth earphone, Not Raspberry Pi, nor Linux, or Mac, or Windows。Thanks!

**Comment by keleric** [comment]
Of course! Many people do so. Here are some links to get you started:
https://forums.developer.amazon.com/articles/10110/creating-an-android-avs-app-vs-creating-an-android.html
https://forums.developer.amazon.com/articles/10111/ensuring-your-ios-app-records-in-the-correct-forma.html
https://forums.developer.amazon.com/articles/40652/troubleshooting-the-okhttp-client-library.html
https://forums.developer.amazon.com/articles/38623/okhttp-issues-with-alexa-voice-service-avs.html
