### ISSUE TITLE
[Solution]: snowboy not getting  installed on aarch64 systems (Nvidia TX2)

### ISSUE THREAD

**Issue by koolkarni** [alexa/alexa-avs-sample-app#734]
when we try to run "/snowboy/example/c++/install_portaudio.sh"

It gives problem with config.guess and config.sub

by replacing the below attached files in portaudio.tar.gz file you will be able to install it

NOTE: remove .txt from both files once copied
[config.sub.txt](https://github.com/alexa/alexa-avs-sample-app/files/980287/config.sub.txt)
[config.guess.txt](https://github.com/alexa/alexa-avs-sample-app/files/980288/config.guess.txt)

**Comment by elstryan** [comment]
Hi @koolkarni, 

Thanks very much for posting this fix for other users. 

This bug really belongs in the snowboy project - but it looks like you've already added it here: https://github.com/Kitt-AI/snowboy/issues/182. Right now we're only officially supporting the wake word engines on RaspberryPi and not aarch64. I'll close this issue and if Snowboy accepts your patch then any users that run the automated install will pickup your change for free.
