### ISSUE TITLE
I'm actually done with building and using alexa but like would like to change the voice of alexa

### ISSUE THREAD

**Issue by pi3123** [alexa/alexa-avs-sample-app#741]
Can someone help me??

**Comment by elstryan** [comment]
HI pi3123, 
Right now we don't support changing the voice of Alexa. This probably isn't exactly what you're looking for but you can try experimenting with changing the language of Alexa by setting a locale in the config: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/config.json 

I.e. you can try setting it to en-GB and Alexa will have a different accent. 

I'm closing this issue for now - please feel free to re-open if there is anything else that you need.
