### ISSUE TITLE
Tokens expiring much quicker than usual

### ISSUE THREAD

**Issue by kevinkey619b** [alexa/alexa-avs-sample-app#742]
Hi,

Has anyone else noticed that the tokens are expiring MUCH quicker than usual lately? Is there any workaround for this?

Thanks,

Kevin

**Comment by elstryan** [comment]
Hi @kevinkey619b , 

I tried to reproduce this on my device and I'm not able to see this. Can we check a few things: 

What scopes are you authorizing for? Is it just alexa:all or are you also requesting additional scopes? 

Can you try adding a log statement here: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/auth/OAuth2AccessToken.java#L38 

with the expiresIn value so that we can verify that the tokens are expiring more quickly? Alternatively can you elaborate on what problem the tokens expiring is causing for your client?

**Comment by kevinkey619b** [comment]
Thanks @elstryan . I've added a log statement and will let you know when the error occurs again. Where do I find the log file when that happens?

**Comment by elstryan** [comment]
In your local repository their should be the following directory: samples/javaclient/logs 

Under the logs directory their is an application.log file

**Comment by kevinkey619b** [comment]
@elstryan  Thanks again. I just got the authentication error again. Nothing got logged, however. Did I do the line of code for the logging properly? 

I wanted to post a screenshot, but it looks like attachments aren't allowed here. The popup error reads:

"Unable to authenticate the request. Please provide a valid authorization token."

Here's my code:

`    public OAuth2AccessToken(String accessToken, int expiresIn) {
        if (StringUtils.isBlank(accessToken)) {
            throw new IllegalArgumentException("Missing " + AuthConstants.OAuth2.ACCESS_TOKEN + " parameter");
        }

	log.info("KK Debug expiresIn = " +expiresIn);

        if (expiresIn < 0) {
            throw new IllegalArgumentException("Invalid " + AuthConstants.OAuth2.EXPIRES_IN
                    + " value. Must be a positive number.");
        }`

Here are the recent (and hopefully relevant) log entries otherwise created:

15:40:08.706 [Thread-160] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
15:40:08.706 [Thread-160] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output
15:40:09.155 [HttpClient@1738274-15] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
15:40:09.247 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 403
15:40:09.247 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0a782bfffe44251d-0000353a-0002f8a4-47a153be2b8606e5-26704c41-1
access-control-allow-headers: authorization,x-amz-access-token
content-type: application/json; charset=UTF-8


15:40:09.250 [RequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "header" : {
    "namespace" : "System",
    "name" : "Exception",
    "messageId" : "79f71ca8-86d1-4952-9f94-e7f01c8c5e80"
  },
  "payload" : {
    "code" : "UNAUTHORIZED_REQUEST_EXCEPTION",
    "description" : "Unable to authenticate the request. Please provide a valid authorization token."
  }
}
15:40:09.252 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.exception.AlexaSystemException: Unable to authenticate the request. Please provide a valid authorization token.
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:572) [classes/:?]
15:40:09.253 [RequestThread] ERROR com.amazon.alexa.avs.ui.ListenView - An error occured creating speech request
com.amazon.alexa.avs.exception.AlexaSystemException: Unable to authenticate the request. Please provide a valid authorization token.
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:572) [classes/:?]
15:40:11.550 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
15:40:11.567 [RequestThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
15:

**Comment by kevinkey619b** [comment]
I also tried logger.info, but have had no luck. Do I need to wipe everything and reinstall?

**Comment by elstryan** [comment]
One quick question: Did you do a mvn install after adding that line? 

Also you'll need to add a couple of import statements and declare a Logger at the top of the class. There's a sample here: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/auth/AuthSetup.java 

Alternatively you can do a System.out.println with the information 

Can we get a couple of more log statements? Specifically a speech requests or something that works immediately before you run into this error would be really helpful so we could see the activity around that time. 

I'll also try and reproduce it on my side. In the meantime do you possibly have more info on steps to recreate the error? Does it occur approximately every hour? Or more regularly than that? Are you use the companion node service for authorization?

**Comment by kevinkey619b** [comment]
@elstryan  I ended up deleting everything and attempted to start over. Now it seems that I may be banned by Amazon. The Amazon site now give an Error 400 every time I try to acquire a key. Not sure what I'm doing wrong.

**Comment by elstryan** [comment]
Can you clarifying when you say the Amazon site. 

Is this when you enter your user credentials on the Login With Amazon Page or is it when you make requests to api.amazon.com?

**Comment by kevinkey619b** [comment]
@elstryan  https://developer.amazon.com/avs/home.html#/  I had to create an entire new device - then everything worked flawlessly.  :)

**Comment by elstryan** [comment]
I'll close this issue for now in that case. If it does occur occur again please re-open this issue.

**Comment by kevinkey619b** [comment]
All good for now. Definitely a problem on Amazon's end last night.
