### ISSUE TITLE
How to make Executable .jar for Javaclient ?

### ISSUE THREAD

**Issue by Kinjalk** [alexa/alexa-avs-sample-app#743]
How to make Executable .jar for Javaclient ?

**Comment by elstryan** [comment]
We don't yet have a target for this. You can look at the maven-assembly-plugin and add a target for generating an executable jar: https://maven.apache.org/plugins/maven-assembly-plugin/usage.html 

If you do a search on that page for "Creating an Executable JAR" you'll find steps.

**Comment by Kinjalk** [comment]
@elstryan  This is the error i am getting on executing .jar

`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.amazon.alexa.avs.AVSApp.<clinit>(AVSApp.java:22)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
`

**Comment by elstryan** [comment]
Can you try the steps here: http://stackoverflow.com/questions/16222748/building-a-fat-jar-using-maven 

It looks like there is a few more configurations that you need to add on-top of what's in the maven docs

**Comment by Kinjalk** [comment]
@elstryan i made changes in pom.xml but still i get same error !

**Comment by elstryan** [comment]
Can you share how you are attempting to execute the jar file? Are you using cp or jar?

**Comment by Kinjalk** [comment]
@elstryan I am using ` java -jar filename.jar`

**Comment by elstryan** [comment]
Can you share your modification to the POM file? Specifically I want to verify that you've added the configuration to add dependencies: 

<configuration>
    <descriptorRefs>
        <descriptorRef>jar-with-dependencies</descriptorRef>
    </descriptorRefs>
</configuration>

(Also apologies on the back and forth here - as I mentioned this isn't an officially supported part so we don't have sample code that does exactly this at the present)

**Comment by Kinjalk** [comment]
@elstryan This is modified [pom.xml](https://github.com/alexa/alexa-avs-sample-app/files/988340/pom.xml.txt)

**Comment by elstryan** [comment]
Hmm. Those both look correct. I'll leave this tagged as a feature request. Stepping back can you expand on your use case (this would help with prioritizing the request). Is there a reason you don't want to execute via mvn? There's many dependencies in the project and mvn makes this simple.

**Comment by Kinjalk** [comment]
@elstryan Yeah mvn is simple but it takes a lot of time to build and start Alexa.

**Comment by elstryan** [comment]
If you only want to interact with Alexa you can try https://echosim.io which is a browser based Alexa client.
