### ISSUE TITLE
No Recording Device

### ISSUE THREAD

**Issue by lshoell** [alexa/alexa-avs-sample-app#754]
I've followed the guide to set up the Conexant AudioSmart 4-Mic Development Kit for Amazon AVS. There were no obvious errors while doing the steps. After the setup was complete, the LEDs, AVS service and AVS client seem to be working. However, the recordingAgent is not working. It continually shows the following error:

Cannot open audio device. No such file or directory (No such file or directory)
ALSA lib pcm-direct.c:1539;(_snd_pcm_direct_get_slave_ipc_offset) Invalid value

When looking at the audio device setting, I do not see a recording device, which I'm assuming is causing the problem. (Playback to the conexant board does work as I can "aplay test.wav" and hear it play through the speaker attached to the conexant board.)

Any ideas as to what the problem could be is appreciated.

**Comment by max-erler** [comment]
Hello,

That error does seem to indicate the audio device as the issue. Could you try running through the Conexant setup again and see if the issue persists?

**Comment by lshoell** [comment]
Are you suggesting I do the setup again over the top of the current setup, or are you suggesting I start with a fresh install of Raspbian?

 

Leonard

**Comment by lshoell** [comment]
At the beginning of the rpi-linux/readme.md it shows 8 driver patches. It is not clear to me if I'm supposed to do something with these patches. Are these already in the files so when the kernel it built, it gets these patches? Or, am I supposed to apply these patches? If so, can you point me to instructions for how to apply the patches?

**Comment by lshoell** [comment]
I've done the Conexant setup multiple times and still get the same errors that indicate a problem with the audio device.

What should I look at to debug this problem?

FYI, if you don't reboot in between after running automated_install.sh and loading the new kernel, there are a lot of problems including no keyboard, mouse or wifi.

**Comment by yugoren** [comment]
Hi @lshoell,

Could you try listing your capture devices by executing `arecord -l`? If the list shows Conexant board's capture device, could you try actually capturing by `arecord -d 2` (`2` for 2 seconds of audio here) and check if it records properly?

**Comment by annovotny** [comment]
I'm having the same issue mentioned above - i ran through the Conexant setup multiple times, but still don't have a recording device listed when I query for them.

`$ arecord -l
**** List of CAPTURE Hardware Devices ****
`

Should I see the Conexant device listed in the list of CAPTURE Hardware Devices?  I am successfully able to use the device for audio playback (tested with aplay), and I confirmed that the drivers are added into the kernel successfully...

**Comment by annovotny** [comment]
I ended up figuring out my problem.

For anyone else struggling with this issue:
The Conexant 4-mic development kit has 2 different USB connectors.  You need to plug the usb cable into the port **farthest** from the power port - not the one right next to it.  If you do this, the recording device comes up as expected.
