### ISSUE TITLE
HOWTO: Headless Alexa in RPi3 Jessie with autostart

### ISSUE THREAD

**Issue by rainman-xx** [alexa/alexa-avs-sample-app#763]
(Can't add in the wiki, so just created this doc through bug report)
These steps is to automate the execution of the programs when the RPI bootsup (automatically to the GUI)

1. Create the file  /home/pi/alexa_startup.sh
`$nano /home/pi/alexa_startup.sh`

with the content:
```
#!/bin/bash
lxterminal -t "NPM"  --geometry=40x2 --working-directory="/home/pi/Desktop/alexa-avs-sample-app/samples/companionService" -e "npm start " &
sleep 15
lxterminal -t "JVM"  --geometry=40x2 --working-directory="/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient" -e "sudo mvn exec:exec" &
sleep 30
lxterminal -t "WAKE" --geometry=40x2 --working-directory="/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src" -e "./wakeWordAgent -e kitt_ai" &
```

2. Set the permission to be executable
`$chmod 755 /home/pi/alexa_startup.sh`

3. Edit /home/pi/.config/lxsession/LXDE-pi/autostart 
-commented out @xscreensaver -no-splash with a # 
-added @/home/pi/alexa_startup.sh

`$nano /home/pi/.config/lxsession/LXDE-pi/autostart
`
New content:
````
@lxpanel --profile LXDE-pi
@pcmanfm --desktop --profile LXDE-pi
**#@xscreensaver -no-splash**
@point-rpi
**@/home/pi/alexa_startup.sh**
```

4. Finally reboot and wait for about a minute to fully reboot RPi and the three programs to run in the background
`$sudo reboot`

**Comment by jimwarb** [comment]
Thanks! I've been trying to get this working for a few weeks :)

**Comment by pi3123** [comment]
You have to add 's' after "sleep 5" and "sleep 10" in the shell script. Or else it won't work.

**Comment by yugoren** [comment]
Hi @rainman-xx,

Thanks for your contribution! I'll tag this post appropriately and close the issue.

**Comment by gbCambridge** [comment]
The script alexa_startup.sh works perfectly. But I have had ZERO luck in getting an autostart of this script by the method shown. It just seems to be ignored.  Anyone had a problem with this?. I am running on an rpi 2

**Comment by gbCambridge** [comment]
Also, I wanted to run truly "headless" but the Alex startup does not complete when no screen is connected. So, with the problems I mentioned above, I bring the system to life manually and when it is running I disconnect the screen and the rest. Not a very smooth operation for my rpi-Alexa.

**Comment by itayavra** [comment]
Hey, if you're still interested, I created a small script to run it with one command and without using sleep.
You can call this script from the startup sh file.
Feel free to try and let me know what you think (alexa-avs-sample-app should be installed as a prerequisite for my script):
https://github.com/itayavra/alexa-headless-start

**Comment by gbCambridge** [comment]
Hi,
thanks for the offer, but I have the system running in headless mode with the latest Amazon Alexa app files. It turns out that if I use other versions then Alexa does not talk to the HAB bridge...so I cannot then get  Alexa to control lights/power etc.
I have added a DAC Hat to the system and it is now able to play FLAC files through a pair of attached powered speakers via the DAC output, whilst Alexa's voice comes from the onboard 3.5 mm jack (via a 3-watt built-in amp). This gives me separate control of Alexa voice and music playback levels, with better quality gear being used for music Alexa would be overpowering through that system.
The next step is to get Alexa to select and play music via the DAC.  I guess what I have built is a 21st-century radiogram.
All the best

George

**Comment by nerdtoob** [comment]
Hey all! Running this on a rpi3. Got Alexa AVS to run on startup no problem but seems to be running in a sort of loop. Every 30 seconds or so alexa says "hello" as if she was rebooted not sure why this is happening? Alexa app says my device is online but she just keeps saying hello. Any advice?

**Comment by mikejrh** [comment]
the three terminal windows appear on the desktop but there is no text.  Please help.  
screenshot of desktop below
![snip20180228_1](https://user-images.githubusercontent.com/18380977/36805238-e73b524a-1c8a-11e8-973e-8b08d768ae00.png)

**Comment by mikejrh** [comment]
three terminals load in desktop with no text.  please advise

![snip20180228_1](https://user-images.githubusercontent.com/18380977/36806982-bd8d7630-1c8f-11e8-9607-efe8681b3369.png)

**Comment by gbCambridge** [comment]
Hi,

I have never had this problem. I suggest you check the logs to see what has happened. It is surprising to see all three windows empty ..which means it is probably something simple….perhaps you need administrator (sudo) permissions in your system

 

George

**Comment by mikejrh** [comment]
I just found that this was also described in  #1072 Autostart. Just 3 empty terminals

**Comment by leavmealonepy** [comment]
```
!/bin/bash
lxterminal -t "NPM"  --geometry=40x2 --working-directory=/home/pi/alexa-avs-sample-app/samples/companionService --command="npm start" &
sleep 15
lxterminal -t "JVM"  --geometry=40x2 --working-directory=/home/pi/alexa-avs-sample-app/samples/javaclient --command="sudo mvn exec:exec" &
sleep 30
lxterminal -t "WAKE" --geometry=40x2 --working-directory=/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src --command="./wakeWordAgent -e sensory" &
```
Fixed script
