### ISSUE TITLE
How to setup response LED

### ISSUE THREAD

**Issue by Zacki84** [alexa/alexa-avs-sample-app#772]
Hi
My AlexaPi is working well, also the wake word engine is working but I want to setup 2 additional LEDs. One simular to wake word response "ping"-sound and a second while listening.
Does sombody know how to setup? What and where I have to change something in the code?

Thanks a lot!!!

**Comment by dhpp** [comment]
Hi Zacki84,

Nice idea!  For the hardware side, you should refer to resources such as this:

https://thepihut.com/blogs/raspberry-pi-tutorials/27968772-turning-on-an-led-with-your-raspberry-pis-gpio-pins

For the software side, you should look at the following code for triggering the LEDs / sounds:

https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java

When Alexa is going to speak, then the function handleSpeechSynthesizerDirective is invoked.

When the WakeWord is detected by the Java Sample App (it is notified of this by the C++ WakeWordAgent instance), the function onWakeWordDetected is invoked.

Hope that helps!

**Comment by Zacki84** [comment]
Hi
thanks a lot
can you help me with the code in java?
How can I open a python script in the AVSController.java?

thanks

**Comment by yugoren** [comment]
Hi @Zacki84,

Why do you want to run a Python script through AVSController? If you want to integrate GPIO controls to your sample app, I think it's better to stick with Java libraries, e.g. [Pi4J](http://pi4j.com/).

**Comment by Zacki84** [comment]
Yes, you are right if you say its better to stick with Java libraries,
but I really don´t know in which file I have to add which code.
I simply want a Led flashing for 1 sec while wakeword was detected and for the time while alexa is speaking and a second one while alexa is listening?

**Comment by yugoren** [comment]
@Zacki84: [This tutorial](http://pi4j.com/example/control.html) gives an example on how to use Pi4J for GPIO controls. As @dhpp pointed out start with [onWakeWordDetected](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSController.java#L692) function and modify the code to blink an LED.

**Comment by a2ron** [comment]
+1
