### ISSUE TITLE
Import Alexa Skill

### ISSUE THREAD

**Issue by vunhatminh241191** [alexa/alexa-avs-sample-app#780]
Hi Guys, 

I just created a custom skills in AWS Lambda. Does anyone know how to import that Alexa Skill Kit into this project? Thanks

**Comment by wsywsya119** [comment]
Use the same account which you create the Skill to login this project.

**Comment by vunhatminh241191** [comment]
Thanks for you replying. However, could you please tell me more specific details how could I do that? Should I do that in the Companion Service or in the JavaClient service?

Moreover, I would like to integrate some Alexa Skill example, do you know how should I do that? I am a beginner of Alexa and Raspberry Pi, so there are a lot of problems, which I do not know how to start it.

I am very appreciated you guys time to help me out of these problems. Thanks

**Comment by yugoren** [comment]
Hi @vunhatminh241191,

At the very first step of the guides, you'll need to login to Developer Portal to create a device type for your Raspberry Pi. When you do that, you should use the account that you created the skill in. The client ID and client secret that goes into the Companion Service uses that device type's security profile. Also, when you get redirected to LWA page, use your developer password again to make sure that you have access to the skill. The Java Client uses the Companion Service as the authentication point for LWA and LWA only needs to know which account the device owner belongs to. You should then be able to add the skill to your account, either using the web client, or using voice depending on how you designed your skill.

**Comment by vunhatminh241191** [comment]
Hi Yogoren,

Thanks for answering my question, however, could you please tell me some more details about LWA page? I could not get what is that.

**Comment by yugoren** [comment]
@vunhatminh241191: LWA (Login With Amazon) is the page you land on, where you enter your Amazon credentials, after you click `Yes` on the dialog Java client opens up when it starts. We show the dialog and the LWA page in the instructions under [Step 7](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#step-7-run-your-web-service-sample-app-and-wake-word-engine) (if you look at items 1-6 you'll see the screenshots).

**Comment by vunhatminh241191** [comment]
@yugoren: Thanks for helping me out this problem. You are absolutely right about LWA. After login into Amazon account, my Alexa is auto connecting with my skill. I just use my awake word to talk with my skill set without any additional set up. Anyway, thanks for your help me to understand this problem. I am very appreciated that.
