### ISSUE TITLE
Raspberry Echo Amazon Music /alexa-avs-sample-app/

### ISSUE THREAD

**Issue by icemanmax95** [alexa/alexa-avs-sample-app#782]
Hey I have got the full thing downloaded but amazon music is still not working. How may i get amazon's permission to allow it to happen

**Comment by yugoren** [comment]
Hi @icemanmax95,

Unfortunately, Amazon Music is currently limited to Alexa-enabled devices that are approved for commercial distribution and use. Requests for access to Amazon Music on AVS will remain in a pending state if you are not actively working with Amazon to develop a commercial device.  If you are developing a commercial device, please let us know; we’d love to help!
