### ISSUE TITLE
run shell when Wake Word detected and "Start_Sound" is playing

### ISSUE THREAD

**Issue by Zacki84** [alexa/alexa-avs-sample-app#784]
Hi

Pls help me
I want to run a Shell script when Wake Word is detected and "Start_Sound" is playing

for this I add " Runtime.getRuntime().exec("/home/pi/Desktop/LED.sh");"  in AVSController.java ....

....
 // audio state callback for when recording has started
    @Override
    public void recordingStarted() {
        player.playMp3FromResource(START_SOUND);
        Runtime.getRuntime().exec("/home/pi/Desktop/LED.sh");
     }
.....

but this is not working! Can sombody help me?

**Comment by yugoren** [comment]
Hi @Zacki84,

Have you tested if your script runs in the command line? If it does, could you try
```java
Runtime.getRuntime().exec("bash /home/pi/Desktop/LED.sh");
```
where I added `bash` to specify the shell it's running?

**Comment by Zacki84** [comment]
if I run 
/home/pi/Desktop/LED.sh 
in the Terminal it runs

I changed and add"bash" but still nothing

**Comment by yugoren** [comment]
@Zacki84: After some searching, I realized that you're not waiting for the process to finish. Could you look at `executeCommand` method in [this example class](https://www.mkyong.com/java/how-to-execute-shell-command-from-java/) and implement yours accordingly?

**Comment by Zacki84** [comment]
holy shit! Thanks a lot but I think I´m to much noob to get this implemented :-( Shit

**Comment by yugoren** [comment]
@Zacki84: Here's a quick hack; just add `executeCommand` function in `AVSController` class, right above `recordingStarted` and call it. First add the required libraries at the top:
```
import java.io.BufferedReader;
import java.io.InputStreamReader;
```
and modify the code:
```
...
private String executeCommand(String command) {

    StringBuffer output = new StringBuffer();

    Process p;
    try {
        p = Runtime.getRuntime().exec(command);
        p.waitFor();
        BufferedReader reader =
                        new BufferedReader(new InputStreamReader(p.getInputStream()));

                    String line = "";
        while ((line = reader.readLine())!= null) {
            output.append(line + "\n");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    return output.toString();

}
// audio state callback for when recording has started
@override
public void recordingStarted() {
    player.playMp3FromResource(START_SOUND);
    System.out.println(executeCommand("bash /home/pi/Desktop/LED.sh"));
}
...
```
I'll go ahead and close the issue for the moment. Good luck!

**Comment by Zacki84** [comment]
thanks

**Comment by D3rpi** [comment]
Would the same method apply for a python script as well?
