### ISSUE TITLE
No response from Alexa

### ISSUE THREAD

**Issue by mhaisekar** [alexa/alexa-avs-sample-app#785]
The installation went well. No errors. However when I start the exec:exec the Java be window opens up. There is no pop up window to authenticate from Amazon website after a couple of restarts. The the Bearer Token is populated automatically. There is a beep at the start and one after I am done speaking, but after that there is no response at all. The audio is output to 3.5mm jack. I play music on youtube and it works fine. Also, when I go to the alexa.amazon.com website, there are no cards populated.

Any help is appreciated.

**Comment by D3rpi** [comment]
Is your microphone set up properly? Looks like Alexa can't hear  you. 
Try playing something from tunein on alexa.amazon.com to see if you can get an audio output.

**Comment by mhaisekar** [comment]
Yeah, you might be correct. While the microphone seems to be set up properly programatically, there seems to be some kind of issue with it. When I to go to alexa.amazon.com, look at the history underneath the settings and play the audio, it is all white noise there. It does not seem to hear me properly. I will check with some other microphone later today and check if it is working.

Thank you.

**Comment by D3rpi** [comment]
Also try playing around with the microphone volume.

**Comment by mhaisekar** [comment]
this is silly, the mic had a small plastic wrap on it. I removed it and alexa started responding using the tap to speak button. 

However when I start the wakeWordAgent using the sensory, there is no response. There is no error in the window but for some reason it does not seem to be working.

**Comment by mhaisekar** [comment]
Following is the content of .asoundrc

pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

**Comment by dskidmor** [comment]
@mhaisekar, it sounds like there may be some contention between the Java sample app and the wake word engine. Could you attach some logs from both?

**Comment by mhaisekar** [comment]
I reinstalled the whole thing, changed the .asoundrc file(see below) and the wake word engine is working now. It is a bit temperamental, i.e. it picks up when I say alexa sometimes but many a times it does not.  Not sure if it does the same thing at your end.





pcm.!default
{
  type asym
  playback.pcm {
    type hw
    card 0
    device 0
  }
  capture.pcm {
    type plug
    slave {
      pcm {
        type hw
        card 1
        device 0
      }
    }
  }
}

**Comment by dskidmor** [comment]
Different wake word engines have different levels of accuracy, so false-positives and true-negatives are to be expected. Good to hear you got it fixed!

**Comment by mhaisekar** [comment]
I used another microphone and it is working fine and as expected. In my situation, hardware issues were bigger problems than software ones.

**Comment by mhaisekar** [comment]
Thank you all for your support.
