### ISSUE TITLE
How can I use javaclient by openJDK？

### ISSUE THREAD

**Issue by RogerZheng** [alexa/alexa-avs-sample-app#789]
Hi all，
   Could exec javaclient by openJDK?How to do?

**Comment by dskidmor** [comment]
Hey @RogerZheng, by default the automated install script uses Oracle JDK, which we have thoroughly tested and works with a specific version of our [ALPN implementation](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html). You can definitely uninstall this version of Java and instead use `openjdk-8-jdk`, but you may need to make additional changes to your project to get everything working.

You should install OpenJDK if you have not already, then tell your system to use the new version of Java, and verify it is being used. The second batch of commands below can also be used to switch back to Oracle JDK if you need to.

    # update apt and get OpenJDK
    sudo apt update
    sudo apt install openjdk-8-jdk
    
    # tell your system to use OpenJDK instead of Oracle JDK
    update-java-alternatives -l
    sudo update-java-alternatives -s java-1.8.0-openjdk-armhf
    
    # verify you are now using OpenJDK
    java -version

**Comment by RogerZheng** [comment]
you have tested Oracle JDK，but does it have license？If we use it，do we have to pay for it？

**Comment by dskidmor** [comment]
Hey @RogerZheng, please refer to the [Binary Code License Agreement](http://www.oracle.com/technetwork/java/javase/terms/license/index.html) if you have any questions regarding licensing of the Oracle JDK.

**Comment by RogerZheng** [comment]
ok ,thanks
