### ISSUE TITLE
why AVS send GOAWAY to my client

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#790]
dear all
My client connect to AVS, and send ping comand every 5min. But after 1hour, AVS send GOAWAY to client.
dose the AVS only support 1 hour long connection?

**Comment by dskidmor** [comment]
That is correct @howardguo, you need to establish a fresh connection after one hour. This should align with the lifetime of the access token, which also lasts for one hour. Let us know if this helps!

**Comment by howardguo** [comment]
@dskidmor Got it! Thank you very much...
