### ISSUE TITLE
how to play the content sent by directive?

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#810]
when I say "BBC radio 1", AVS return bellow message:
{
   "directive" : {
      "header" : {
         "dialogRequestId" : "0b66d617-4d7f-4dc8-a394-a7145e3f85be",
         "messageId" : "3a5a51f4-34a3-46f0-8747-8622e0dc1b8f",
         "name" : "Speak",
         "namespace" : "SpeechSynthesizer"
      },
      "payload" : {
         "format" : "AUDIO_MPEG",
         "token" : "amzn1.as-ct.v1.Domain:Application:Knowledge#ACRI#GlobalDomain_ActionableAbandon_8ecac26e-65c7-48a8-88ea-da8a304440b0",
         "url" : "cid:GlobalDomain_ActionableAbandon_8ecac26e-65c7-48a8-88ea-da8a304440b0_1580517651"
      }
   }
}

How I use the payload content(url) to get/play the audio?

**Comment by theMooseChen** [comment]
Hi,

Each Speak directive will have a corresponding binary audio attachment as one part of the multipart message. CID stands for Content-ID, this ID can point to the corresponding binary attachment. You can find the attachment in the Http2 response.
Check this documentation for details.  [Link](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speechsynthesizer#speak)

This [Link](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/avs-http2-requests#responses) might be helpful as well. Thanks.

**Comment by howardguo** [comment]
@theMooseChen thanks a lot
