### ISSUE TITLE
Response start cut off

### ISSUE THREAD

**Issue by FrancisALR** [alexa/alexa-avs-sample-app#812]
Hi,

I'm attempting to set up the sample app on a raspberry pi model 3, all is working, except when a question is asked the beginning of the response is cut off so for example the time it should say is 14.13pm but all that is audible is '13 pm'. 

Is this a known issue or is there a way of editing some of the code to increase a timer to fix this?

Thanks for your help

**Comment by theMooseChen** [comment]
Hi 
I did not experience this before and did not see any related post in the issue area. Could you reproduce this bug every time? Does it cut off response every time you ask Alexa something? Can you check the log if there is anything unusual and attach it here? Thanks.
