### ISSUE TITLE
How to stop a audio stream that is on playing?

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#813]
Hi
When I got a url from AVS(like->http://xxxx.mp3), I use the ffplay to play it. The question is how I stop the it by AVS? How I can get the "stop" command from AVS? 
when I say "stop xxx", the AVS response "I'm not sure " or nothing and so on.

**Comment by theMooseChen** [comment]
Hi, 
Do you mean you use the url generated by avs and play the url directly with ffplay? Then "Stop" will not work because you are on ffplay. I ran the avs sample app and played some music, if I say "Stop", it will stop playing, and I say "Continue", it will continue playing. Could you provide more information for your problem?
Thanks!

**Comment by howardguo** [comment]
Do you mean you use the url generated by avs and play the url directly with ffplay? -> yes
If I want to use ffplay but not avs app, how to do ? Is there some event can be useful?

**Comment by theMooseChen** [comment]
Hi
I am sorry, I still did not quite get your problem. Client has to communicate with AVS to get voice control. You cannot simply say "Stop" to stop the music only by using ffplay.

**Comment by howardguo** [comment]
Yes. The step is bellow:
1, send event with record data to AVS, and get the http URL successfully.
2, just use the ffplay(sample app use vlc? I think it is no difference. right?) to play the URL.
3, send the "Stop" speech record to AVS, and got nothing. As my understanding, after I sent the "Stop" record to AVS, AVS should return a stop directive command to my client. right?

**Comment by theMooseChen** [comment]
Got it. The [PlaybackStarted](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/audioplayer#playbackstarted) event must be sent to AVS after your client processes a Play directive and begins playback of the associated audio stream. Also, you need to make sure the [Context](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/context#context) should be PLAYING for the [AudioPlayer.PlaybackState](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/context#playbackstate).

**Comment by howardguo** [comment]
Ok, thanks .

**Comment by howhot2008** [comment]
Hi, theMooseChen and howardguo, 
I have the same problems. I can't receive Stop or Pause directive when I play a radio.
The diffirence is that I have sent the Context and PlaybackStarted event to AVS when I process a Play directive. After that, I received a status=200 response. But I didn't receive a Stop directive when I say "Stop" to AVS. 
I have a question about Context: should I send all status(including AudioPlayer, Speaker, SpeechSynthesizer and so on) in context every time? or I can only send one AudioPlayer status in Context when I send PlaybackStarted event to AVS?
Can you help me? Thank you very much!   @theMooseChen @howardguo

**Comment by howhot2008** [comment]
The follow is my message sent to AVS:
--this-is-my-boundary
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{
    "event": {
        "header": {
            "namespace": "AudioPlayer", 
            "name": "PlaybackStarted", 
            "messageId": "njc_message_id-1503395662-5"
        }, 
        "payload": {
            "token": "amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#dfffa7f9-4b2e-4ce4-9607-0abc2da72532:1", 
            "offsetInMilliseconds": 0
        }
    }, 
    "context": [
        {
            "header": {
                "namespace": "Speaker", 
                "name": "VolumeState"
            }, 
            "payload": {
                "volume": 100, 
                "muted": false
            }
        }, 
        {
            "header": {
                "namespace": "Alerts", 
                "name": "AlertsState"
            }, 
            "payload": {
                "allAlerts": [], 
                "activeAlerts": []
            }
        }, 
        {
            "header": {
                "namespace": "AudioPlayer", 
                "name": "PlaybackState"
            }, 
            "payload": {
                "token": "amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#dfffa7f9-4b2e-4ce4-9607-0abc2da72532:1", 
                "playerActivity": "PLAYING", 
                "offsetInMilliseconds": 10
            }
        }
    ]
}
--this-is-my-boundary--this-is-my-boundary--

**Comment by howhot2008** [comment]
@theMooseChen I have resolved it. It is OK when I send recognize event with my context to AVS . Thank you!

**Comment by anu-mathur** [comment]
Hi @howardguo 
I am doing a user study on the alexa-avs-sample-app and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tinyurl.com/AVSContactForm
) and I will get in touch with you.
Thanks
