### ISSUE TITLE
iam using windows os ....got stuck with npm install

### ISSUE THREAD

**Issue by ANANDSKRISHNAN** [alexa/alexa-avs-sample-app#817]
C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app>cd samples

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples>cd companionService

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm intall
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Rakesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

openssl config failed: error:02001003:system library:fopen:No such process
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install -g openssl
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
C:\Users\Rakesh\AppData\Roaming\npm
`-- openssl@1.1.0
  +-- mout@0.11.1
  `-- nyks@2.31.3
    +-- async@2.4.1
    | `-- lodash@4.17.4
    `-- mout@1.0.0

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

openssl config failed: error:02001003:system library:fopen:No such process
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install --save latest-version
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
alexa-voice-service-sample-companion-service@1.0.0 C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
`-- latest-version@3.1.0
  `-- package-json@4.0.1
    +-- got@6.7.1
    | +-- create-error-class@3.0.2
    | | `-- capture-stack-trace@1.0.0
    | +-- duplexer3@0.1.4
    | +-- get-stream@3.0.0
    | +-- is-redirect@1.0.0
    | +-- is-retry-allowed@1.1.0
    | +-- is-stream@1.1.0
    | +-- lowercase-keys@1.0.0
    | +-- safe-buffer@5.1.1
    | +-- timed-out@4.0.1
    | +-- unzip-response@2.0.1
    | `-- url-parse-lax@1.0.0
    |   `-- prepend-http@1.0.4
    +-- registry-auth-token@3.3.1
    | `-- rc@1.2.1
    |   +-- deep-extend@0.4.2
    |   +-- ini@1.3.4
    |   +-- minimist@1.2.0
    |   `-- strip-json-comments@2.0.1
    +-- registry-url@3.1.0
    `-- semver@5.3.0

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

openssl config failed: error:02001003:system library:fopen:No such process
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

openssl config failed: error:02001003:system library:fopen:No such process
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>

**Comment by theMooseChen** [comment]
Hi
Did you [download and install the nodejs](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#3---install-dependencies)?
[How to Install Node.js® and NPM on Windows](http://blog.teamtreehouse.com/install-node-js-npm-windows) . This link might also be useful to you.
Thanks.

**Comment by ANANDSKRISHNAN** [comment]
hi,
i have install node js but when i test npm this error have been poped up, i am very new to this  plz help me.

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Rakesh>node -v
v6.11.0

C:\Users\Rakesh>npm -v
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
3.10.10

C:\Users\Rakesh>

**Comment by ANANDSKRISHNAN** [comment]
at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm clean

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Rakesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'r' at 16:4
npm ERR!   "repository": {
npm ERR!    ^
npm ERR! File: C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'r' at 16:4
npm ERR!   "repository": {
npm ERR!    ^
npm ERR! File: C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '}' at 18:1
npm ERR! }
npm ERR! ^
npm ERR! File: C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm clean

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Rakesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm -v
3.10.10

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm update

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm bugs
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '}' at 18:1
npm ERR! }
npm ERR! ^
npm ERR! File: C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm clean

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Rakesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\{REFERENCE_IMPLEMENTATION}\samples\javaclient\certs\server\node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\bin\www:21:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService\npm-debug.log

C:\{REFERENCE_IMPLEMENTION}\alexa-avs-sample-app\samples\companionService>

**Comment by theMooseChen** [comment]
Hi

Looks like your npm is not installed correctly. Could you try uninstall it and re-install it?
Here is a [link](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) to follow to uninstall nodejs and npm completely.

Thanks.

**Comment by theMooseChen** [comment]
Sorry that link is for Mac OS, for windows, there is an uninstall section in this [link](http://blog.teamtreehouse.com/install-node-js-npm-windows)

**Comment by ANANDSKRISHNAN** [comment]
thnku my error rectified
