### ISSUE TITLE
FAILED TO EXECUTE mvn exec:exec while running sample app of amazon alexa voice

### ISSUE THREAD

**Issue by venkateshsubbiah** [alexa/alexa-avs-sample-app#823]
F:\ComputerScience\Development\freelancing\Alexa\alexa-avs-sample-app-master\alexa-avs-sample-app-master\samples\javaclient>mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 67 at (line no=9, column no=27, offset=221)
        at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
        at org.glassfish.json.JsonTokenizer.unescape(JsonTokenizer.java:231)
        at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:184)
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
        at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:261)
        at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:184)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:64)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
        at com.amazon.alexa.avs.App.<init>(App.java:53)
        at com.amazon.alexa.avs.App.main(App.java:48)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.002 s
[INFO] Finished at: 2017-06-25T10:42:52+05:30
[INFO] Final Memory: 11M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lijessi** [comment]
It seems the bug is caused by the confused characters with QUOTATION MARK. So you actually need to replace all the confusing character with QUATATION MARK. Here is a link for that, hope it works for you.

http://unicode.org/cldr/utility/confusables.jsp?a=%22&r=None

**Comment by ANANDSKRISHNAN** [comment]
can u please suggest the files which i want to look upon i am new to this that's why...

**Comment by lijessi** [comment]
config.json  Thanks.

**Comment by ANANDSKRISHNAN** [comment]
We have to remove all the characters with quotation mark right ???

**Comment by ANANDSKRISHNAN** [comment]
Sorry not remove replace

**Comment by ANANDSKRISHNAN** [comment]
Like this "product_id " have to change into "product_1d" in this way ??

**Comment by lijessi** [comment]
Is it a typo with "i" and "1"? After you change the config file, could you please paste it here so that I can double check that for you.

**Comment by ANANDSKRISHNAN** [comment]
Ok i will paste it ...ya "i" and "1" is a typo..that is shown in when i checked that link

**Comment by ANANDSKRISHNAN** [comment]
For example when we write samples after removing confusable characters it becomes samp1es right??

**Comment by ANANDSKRISHNAN** [comment]
Samples after removing confusable characters it becomes samp1es this is what I understand sorry if its wrong

**Comment by ANANDSKRISHNAN** [comment]
Is it right??

**Comment by lijessi** [comment]
You should not change the character in the words. Just change the quotation mark please. Thanks.

**Comment by ANANDSKRISHNAN** [comment]
So we have to remove all the quotations mark right?

**Comment by ANANDSKRISHNAN** [comment]
i am generally asking doubt because i am confused with your sentence that :=
It seems the bug is caused by the confused characters with QUOTATION MARK. So you actually need to replace all the confusing character with QUATATION MARK?/
plz explain it once more

**Comment by ANANDSKRISHNAN** [comment]
my config.json file

'productId':'my_device',
    'dsn':'123456789',
    'provisioningMethod':'companionApp',
    'wakeWordAgentEnabled':true,
    'locale':'en-US',
    'companionApp':{
        'localPort':8443,
        'sslKeyStore':'C:\project\anand\samples\javaclient\certs\server\jetty.pkcs12',
        'sslKeyStorePassphrase':'',
        'lwaUrl':'https://api.amazon.com'
    },
    'companionService':{
        'serviceUrl':'https://localhost:3000'
        'sslClientKeyStore':'C:\project\anand\samples\javaclient\certs\client\client.pkcs12',
        'sslClientKeyStorePassphrase':'',
        'sslCaCert':'C:\project\anand\samples\javaclient\certs\ca\ca.crt'
    }
}

**Comment by vaibhavbhanawat01** [comment]
hi ANANDSKRISHNAN, did find the solution for above issue???

**Comment by vaibhavbhanawat01** [comment]
![img_20170721_173605](https://user-images.githubusercontent.com/12860795/28463576-b7b5b272-6e3e-11e7-819a-80605691e612.jpg)

**Comment by namanmittal-namanm** [comment]
Hi @ANANDSKRISHNAN It seems like you are trying to run avs sample app on Windows. In windows the file path being provided by you should have 2 slashes for eg: sslCaCert path will be C:\\project\\anand\\samples\\javaclient\\certs\\ca\\ca.crt Please modify this for all the path in config.json file. Also you have missed a comma after supplying serviceUrl value. I have corrected your file and pasted down below.

You can use this json file: 
{
	"productId": "my_device",
	"dsn": "123456789",
	"provisioningMethod": "companionApp",
	"wakeWordAgentEnabled": true,
	"locale": "en-US",
	"companionApp": {
		"localPort": 8443,
		"sslKeyStore": "C:\\project\\anand\\samples\\javaclient\\certs\\server\\jetty.pkcs12",
		"sslKeyStorePassphrase": "",
		"lwaUrl": "https://api.amazon.com"
	},
	"companionService": {
		"serviceUrl": "https://localhost:3000",
		"sslClientKeyStore": "C:\\project\\anand\\samples\\javaclient\\certs\\client\\client.pkcs12",
		"sslClientKeyStorePassphrase": "",
		"sslCaCert": "C:\\project\\anand\\samples\\javaclient\\certs\\ca\\ca.crt"
	}
}

Also make sure your productID (aka Device Type Id) you have supplied here is matching that of on developer portal

**Comment by ANANDSKRISHNAN** [comment]
Thanku so much 😊

**Comment by ANANDSKRISHNAN** [comment]
I got it 😊
