### ISSUE TITLE
Did the alexa must use java?

### ISSUE THREAD

**Issue by Shaco-Ma** [alexa/alexa-avs-sample-app#826]
Hi man:
           When I use alexa in Arm7 machine use the os of Linux,but I don't want transplant the jdk to the arm machine,So, can U publish a sdk just use c,c++?

**Comment by lijessi** [comment]
Alexa sample app only use java now. Unfortunately, there isn't any c, c++ sdk now.

**Comment by Shaco-Ma** [comment]
@lijessi So,what time will have c,c++ sdk?because many arm7 core linux os use jave work not very well.

**Comment by lijessi** [comment]
Great suggestion. We will consider it. Thanks.
