### ISSUE TITLE
Alexa doesn't answer anything

### ISSUE THREAD

**Issue by lucastanure** [alexa/alexa-avs-sample-app#832]
Alexa can hear me because I can see in history http://alexa.amazon.com/spa/index.html#settings
But she doesn't answer anything over the speaker. 
I'm using debian and followed the instructions.

There is no issues on dmesg, journalct, or output from mvn exec:exec

**Comment by lijessi** [comment]
Hi, it seems that you have the same problem as https://github.com/alexa/alexa-avs-sample-app/issues/76 . Could you please try the solution there? Thanks.

**Comment by lucastanure** [comment]
My embedded system doesnt have hdmi. I'm ruining a vnc server just because the alexa app is gui. 
I installed pavucontrol, but didn't fix the issue.

**Comment by lucastanure** [comment]
no solutions found

**Comment by seanzhuu** [comment]
What hardware and os are you running avs on?
Sounds like a soundcard issue to me

**Comment by mradulan** [comment]
are you able to see the response from Alexa in the Settings->History? http://alexa.amazon.com/spa/index.html#settings/dialogs

**Comment by lucastanure** [comment]
Yes, I can see the response on the web site. 
No, it's not a soundcard issue, because arecord and aplay works fine.

**Comment by mradulan** [comment]
so you can play music over your sound card but cannot hear the response from Alexa?

**Comment by mradulan** [comment]
are you trying to run the app as root?

**Comment by lucastanure** [comment]
I was using stable debian (stretch) with openjdk. 
I got working with old stable Jessie and oracle jdk.

**Comment by mradulan** [comment]
so is this resolved now?

**Comment by lucastanure** [comment]
yes

**Comment by NicoSoftware** [comment]
Hey, I'm having the exact same Problem on Raspbian stretch, any ideas?
