### ISSUE TITLE
VLC plugin issue

### ISSUE THREAD

**Issue by ANANDSKRISHNAN** [alexa/alexa-avs-sample-app#833]
i have already set vlc envoirnment variable but it shows this error

Exception in thread "main" java.lang.RuntimeException: Failed to initialise libvlc.

This is most often caused either by an invalid vlc option begin passed when creating a MediaPlayerFactory or by libvlc being unable to locate the required plugins.

If libvlc is unable to locate the required plugins the instructions below may help:

In the text below <libvlc-path> represents the name of the directory containing "libvlc.dll" and "libvlccore.dll" and <plugins-path> represents the name of the directory containing the vlc plugins...

For libvlc to function correctly the vlc plugins must be available, there are a number of different ways to achieve this:
 1. Make sure the plugins are installed in the "<libvlc-path>/plugins" directory, this should be the case with a normal vlc installation.
 2. Set the VLC_PLUGIN_PATH operating system environment variable to point to "<plugins-path>".

plz reply

**Comment by lijessi** [comment]
Do you check the architecture(32 or 64-bit) of the VLC matching the architecture of the Java Development Kit(JDK) you have installed?

**Comment by ANANDSKRISHNAN** [comment]
Error corrected i jst got the bearer token value

**Comment by lijessi** [comment]
Nice!
