### ISSUE TITLE
npm failed start

### ISSUE THREAD

**Issue by kimtheis** [alexa/alexa-avs-sample-app#835]
the log says:

[npm-debug.log.zip](https://github.com/alexa/alexa-avs-sample-app/files/1112226/npm-debug.log.zip)

**Comment by lijessi** [comment]
Hi, are you able to pasted the error log in command prompt after you run npm start? Thank you very much.

**Comment by barlowcaz** [comment]
I'm having a similar issue with the npm 

 Command-------     cd companionService && npm start

Response---------     -bash: npm: command not found

**Comment by kimtheis** [comment]
sh: 1: node: not found

npm ERR! Linux 4.8.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/smarthome-controle/alexa-avs-sample-app/samples/companionService/npm-debug.log

**Comment by barlowcaz** [comment]
I sussed out mine was due to me typing the device id incorrect 😔

**Comment by barlowcaz** [comment]
Also just to add ensure you leave all terminal windows open during the process.....something else I learned the hard way 😔😁

**Comment by kimtheis** [comment]
the hard way????

**Comment by kimtheis** [comment]
and device id in what file

**Comment by kimtheis** [comment]
sry for bad english i'm from denmark

**Comment by barlowcaz** [comment]
The device id was incorrect in the automated_install.sh (I had used a capital letter instead of lowercase)

As for the terminal windows if you close them as you work through them I found the token for Amazon companion would not generate

**Comment by kimtheis** [comment]
in ubuntu?

**Comment by barlowcaz** [comment]
I don't know what Ubuntu is 😔

I made my mistake creating an alexa pie.......using raspberry pie 

I encountered an npm issue due to a typo when entering the credentials

**Comment by kimtheis** [comment]
ubuntu is linux

**Comment by kimtheis** [comment]
:)

**Comment by barlowcaz** [comment]
Haha yeh I was using Linux 😁

**Comment by kimtheis** [comment]
lijessi what is the fail

**Comment by mradulan** [comment]
@kimtheis is the issue resolved?

**Comment by kimtheis** [comment]
Yes

Den 7. jul. 2017 4.28 PM skrev "Mradula Nayak" <notifications@github.com>:

**Comment by EvilDuky** [comment]
Hi I have the same problem with the npm start command
Console Error:

> _This node service needs to be running to store token information memory and vend
>  them for the AVS app.
> 
> fs.js:641
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\502640888\Documents\Too
> ls\Alexa\alexa-avs-sample-app-master\samples\companionService\Users(2640888Docum
> entsToolsAlexaalexa-avs-sample-app-mastersamplesjavaclientcertsserver
> ode.key'_

I have updated automated_install.sh file by filling ProductID, ClientID and ClientSecret

Is there some batch to relaunch after that?

Thanks

**Comment by jordan-heier** [comment]
Hi @EvilDuky , based on the path in your error it looks like you are setting up the application on Windows. Please follow this [guide for setting up the application on Windows](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows). For the Windows setup, the automated_install.sh file does not need to be updated. Please confirm if you have followed the guide I have linked and we will look more into the issue.

**Comment by EvilDuky** [comment]
Yes I followed this link (for windows) but I can't start npm

**Comment by dhpp** [comment]
EvilDuky, the line you posted here:

Error: ENOENT: no such file or directory, open 'C:\Users\502640888\Documents\Too
ls\Alexa\alexa-avs-sample-app-master\samples\companionService\Users(2640888Docum
entsToolsAlexaalexa-avs-sample-app-mastersamplesjavaclientcertsserver
ode.key'_

looks like something is misconfigured.  I'm guessing the file it's trying to open does not actually exist on your device.  My advice would be to start the process again in a fresh directory, carefully repeating each step in the install guide.

**Comment by EvilDuky** [comment]
I forgot the double "\" in the path of of config file, now it works!
