### ISSUE TITLE
companion service erroe

### ISSUE THREAD

**Issue by ANANDSKRISHNAN** [alexa/alexa-avs-sample-app#844]
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

**Comment by ANANDSKRISHNAN** [comment]
C:\abysis\alexa\samples\companionService>npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\abysis\alexa\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000

**Comment by ANANDSKRISHNAN** [comment]
plz help

**Comment by mradulan** [comment]
can you print the data in your config.js file?

**Comment by ANANDSKRISHNAN** [comment]
CONFIG.JSON
{
    "productId":"alexa",
    "dsn":"123456789",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"C:\\abysis\\alexa\\samples\\javaclient\\certs\\client\\client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"C:\\abysis\\anand\\samples\\javaclient\\certs\\ca\\ca.crt"
    }
}

**Comment by ANANDSKRISHNAN** [comment]
CONFIG .JS
redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.key",
    sslCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.crt",
    sslCaCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\ca\\ca.crt",
    products: {
        "alexa": ["123456789"],
    },
};

module.exports = config;

**Comment by ANANDSKRISHNAN** [comment]
new error 
15:44:55.175 [Thread-17] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: BadRequest: The provided product and dsn do not match valid values
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:76) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:68) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:91) [classes/:?]

**Comment by mradulan** [comment]
I do not see clientId, clientSecret and products field being entered in config.js.

One clarification, are you using Windows or Linux as your platform?

**Comment by ANANDSKRISHNAN** [comment]
windows os

**Comment by ANANDSKRISHNAN** [comment]
var config = {
    clientId: "amzn1.application-oa2-client.aad78093e58d4360afedd4acbc0b11f3",
    clientSecret: "d501561a41f3f3773909ba7c9cdf803f121acd339b90ed75ab2a74324135e790",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.key",
    sslCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.crt",
    sslCaCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\ca\\ca.crt",
    products: {
        "alexa": ["123456789"],
    },
};

module.exports = config;

**Comment by mradulan** [comment]
with the above config.js, can you run npm start?

**Comment by ANANDSKRISHNAN** [comment]
YES

**Comment by ANANDSKRISHNAN** [comment]
i changed the file to
/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: "amzn1.application-oa2-client.aad78093e58d4360afedd4acbc0b11f3",
    clientSecret: "d501561a41f3f3773909ba7c9cdf803f121acd339b90ed75ab2a74324135e790",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.key",
    sslCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\node.crt",
    sslCaCert:"C:\\abysis\\alexa\\samples\\javaclient\\certs\\ca\\ca.crt",
    products: {
        "alexa": ["alexa"],
    },
};

module.exports = config;

config.js

**Comment by ANANDSKRISHNAN** [comment]
config .json
{
    "productId":"alexa",
    "dsn":"alexa",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"C:\\abysis\\alexa\\samples\\javaclient\\certs\\server\\jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"C:\\abysis\\alexa\\samples\\javaclient\\certs\\client\\client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"C:\\abysis\\alexa\\samples\\javaclient\\certs\\ca\\ca.crt"
    }
}

**Comment by ANANDSKRISHNAN** [comment]
then i got that error rectified

**Comment by mradulan** [comment]
are you using config.js or config.json?

**Comment by ANANDSKRISHNAN** [comment]
both files have been installed i am new to this i follow jst the instruction

**Comment by mradulan** [comment]
ok so from the instructions, are you able to complete "5a" step?

**Comment by ANANDSKRISHNAN** [comment]
no error have been poped up so...

**Comment by ANANDSKRISHNAN** [comment]
after npm start it is listening to port 3000

**Comment by mradulan** [comment]
that is fine, are you able to complete Step 6, till man exec:exec

**Comment by mradulan** [comment]
mvn exec:exec

**Comment by ANANDSKRISHNAN** [comment]
nope

**Comment by ANANDSKRISHNAN** [comment]
sorry i got it i am confused with both json and js file i have to edit only the js file right??

**Comment by mradulan** [comment]
config.js is edited in step 5a, and config.json is edited in step 6

**Comment by ANANDSKRISHNAN** [comment]
yes

**Comment by ANANDSKRISHNAN** [comment]
i have edited both the file

**Comment by ANANDSKRISHNAN** [comment]
plz tell how to make it

**Comment by mradulan** [comment]
What is your "Device Type ID" in https://developer.amazon.com/avs/home.html#/

**Comment by ANANDSKRISHNAN** [comment]
alexa

**Comment by mradulan** [comment]
in config.js, can you edit last line as:

products{
"alexa" : ["DSN123456"]
},
};
save it and run "npm start". 

If that is successful, in config.json, edit 1st two lines as:
{
"productId":"alexa",
"dsn":"DSN123456",

**Comment by ANANDSKRISHNAN** [comment]
Ok

**Comment by ANANDSKRISHNAN** [comment]
It works 😍😍 thankuu

**Comment by ANANDSKRISHNAN** [comment]
I am using it as a companion service can i add alexa skill to it??

**Comment by manchinagarjuna** [comment]
yes, you can add skills to Alexa companion service. You can do that either by navigating to "https://www.alexa.amazon.com" or from the Alexa app on your mobile.
