### ISSUE TITLE
Alexa Sound and Voice is scratching

### ISSUE THREAD

**Issue by Bjoern3003** [alexa/alexa-avs-sample-app#846]
Hello,
All my last Problems, I have fixed with the Issues here. Very nice.

Now my last Problem is, that very often, Alexa is Scratching. Also the "Bing" and answers.

If I play a mp3 with vlc on the Raspberry, everthing is fine.

Specs:
rpi 3
USB Soundcard with connected Microphone and Loudspeakers.

**Comment by mradulan** [comment]
By scratching, do you mean the response is broken? Do you get the response here http://alexa.amazon.com/spa/index.html#settings/dialogs ?

**Comment by Bjoern3003** [comment]
I can only hear my question and can read the answer from alexa. There is no possibility to hear the answer.

**Comment by mradulan** [comment]
can you give the command "Alexa, volume level 8".

**Comment by Bjoern3003** [comment]
Yes i can,  and i see it in my alexa app, but nothing changed.

**Comment by mradulan** [comment]
Can you check your configuration according to https://www.raspberrypi.org/documentation/configuration/audio-config.md

Also Check https://github.com/alexa/alexa-avs-sample-app/issues/76

**Comment by Bjoern3003** [comment]
This could not be my solution, because sound and microphone are connected to usb soundcard. Music from vlc for example is working fine.

**Comment by mradulan** [comment]
What is the output on your terminal?

**Comment by Bjoern3003** [comment]
Which output did you mean?

I have 3 Terminals. Without any issue in it.

**Comment by mradulan** [comment]
do you have a 3.5mm cable connected your Loudspeakers?

**Comment by Bjoern3003** [comment]
Yes, but over an USB Soundcard, not in the 3.5mm Jack from rpi.

**Comment by mradulan** [comment]
https://github.com/alexa/alexa-avs-sample-app/issues/533 can you check this

**Comment by Bjoern3003** [comment]
Hi, this is, what I have done before.

**Comment by SzDavidHUN** [comment]
Now I'm testing, the default alsa settings are 8bit 8000Hz Mono, scratchy as hell!
```
pi@pi1:~ $ arecord -D default | aplay -D default 
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
Playing WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
```
Set format as cd or dat, the scratchiness is gone!
```
arecord -D default -f dat | aplay -D default -f dat
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
```
If I raise the rate it won't help, but with rate and depth it sound great. Okay, this is a $1 USB soundcard, but clear, and even okay for listening some music.
Maybe the software uses too low quality?

**Comment by mradulan** [comment]
@Bjoern3003 can you try setting the format to cd or dat?

**Comment by Bjoern3003** [comment]
I do not understand, what @SzDavidHUN posted.

This is what I get, if i paste the code in my terminal:

`arecord -D default | aplay -D default 
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
Playing WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
underrun!!! (at least 122.445 ms long)`

`arecord -D default -f dat | aplay -D default -f dat
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
underrun!!! (at least 123.476 ms long)`

**Comment by dhpp** [comment]
Hi Bjoern, is this still an issue for you?  Please let us know if we can help further, thanks.

**Comment by Bjoern3003** [comment]
Hi, I have deleted alexa vom rpi at the moment, because of this issues. I will try it in a few weeks again.

**Comment by bandkenamazoncom** [comment]
Closing for now, please reopen if issues persist.
