### ISSUE TITLE
Non GUI version of Alexa

### ISSUE THREAD

**Issue by lucastanure** [alexa/alexa-avs-sample-app#851]
There is a version of the avs sample app that is for the command line?

**Comment by namanmittal-namanm** [comment]
Hi @lucastanure Can you please explain your requirement in detail.
Do you want to know if we have a sample app that can be run, handles user authentication, and do everything via command line? If this is your question, no we dont have any sample app that is for the command line.

**Comment by namanmittal-namanm** [comment]
Hi @lucastanure I am Sorry I provided wrong information. Yes you can run the sample app from command line just by setting "headless":true in config file in javaclient.

**Comment by lucastanure** [comment]
wont solve. 
https://github.com/alexa/alexa-avs-sample-app/issues/868
