### ISSUE TITLE
Adding dummy devices in Raspberry Pi3

### ISSUE THREAD

**Issue by Nishad009** [alexa/alexa-avs-sample-app#854]
Hi,
I have setup alexa on Raspberry Pi using the steps mentioned in https://github.com/alexa/alexa-avs-sample-app/wiki/Setting-up-the-Raspberry-Pi and able to execute basic alexa skills like "what is the weather".

Now I am trying to add basic home skills to Raspberry-Pi like "turn on kitchen light".
I have tried to run fauxmo.py  (https://github.com/makermusings/fauxmo) in same Raspberry-Pi. But the dummy devices are not listed while searching devices through "Discover device" option (tried with both web interface & alexa Android app).

Is it possible to setup dummy devices in same Pi3 along with alexa support?

**Comment by namanmittal-namanm** [comment]
Hi @Nishad009 no we dont have a way to setup devices using Alexa on raspberry pi, but you can check out this issue: https://github.com/alexa/alexa-avs-sample-app/issues/621#issuecomment-289936814 where the user is describing about controlling devices by creating a skill.

**Comment by Nishad009** [comment]
Hi @namanmittal-namanm ,
Thank you for your comments.
I have found a workaround to test dummy devices.
1. Enable Samsung smart things skill
2. Once Samsung account linked with amazon developer account, we can add simulated  devices (bedroom light, thermostat etc) from Samsung Smart Things skill website and test the home skills.
