### ISSUE TITLE
Issue with detecting voice command

### ISSUE THREAD

**Issue by chinmayshah99** [alexa/alexa-avs-sample-app#863]
Terminal output in wakewordAgent using kitt_ai
```
wake word detected 
state set to wake_word_detected(3) 
sent_wake_word_detected(4)
```

When I say Alexa, this is displayed in terminal. No further process is done. The same cycle is repeated every-time you say 'alexa'.

**Comment by namanmittal-namanm** [comment]
Hi @chinmayshah99, can you please provide us with the platform you are running it on. Also have you tried with Sensory wakeword engine? does it give the same issue?

**Comment by chinmayshah99** [comment]
I'm using raspberry pi model b. I tried using sensory but that wasn't getting installed properly.
