### ISSUE TITLE
Wake Word won't start 

### ISSUE THREAD

**Issue by ambelbasha** [alexa/alexa-avs-sample-app#865]
Alexa works fine with the javaclient button but seems unable to work with wake word.
The output of : cd /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e sensory

#         Output           #

INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-beta.10.2 | model file: ../ext/resources/spot-alex$
WARNING:Library expires on: License expires on 28 Oct 2017 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:Not connected! Make sure AVS client is running
INFO:WakeWordAgent: thread started
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:Not connected! Make sure AVS client is running
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:SensoryWakeWordEngine: handling pause
INFO: *** THREAD JOINING: Sensory ***
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:SensoryWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended

Any help with this ?

**Comment by tweaty100** [comment]
@ambelbasha 
does your problem solve let me know as i am also facing similar issue ?

**Comment by namanmittal-namanm** [comment]
Hi @ambelbasha Can you please try the steps as described in this issue: https://github.com/alexa/alexa-avs-sample-app/issues/604

**Comment by lutalent** [comment]
Solved by this :
sudo nano ~/.asoundrc

change your ~/.asoundrc file to:
pcm.!default { type asym playback.pcm { type plug slave.pcm "hw:0" } capture.pcm { type plug slave.pcm "hw:1" } }
sudo nano ~/.asoundrc

**you must delete other text in ¬/.asoundrc and keep only the above text in the file**

**Comment by ambelbasha** [comment]
Just edited the above ~/.asoundrc as lutalent suggested while to be honest i kind of experimented with a few more things and had it running in perfect shape . Most of those solutions are located in github or the raspberry forums. Didn't know to tell exactly what fixed the issue but  ... it worked.

**Comment by ambelbasha** [comment]
Closing this issue.
