### ISSUE TITLE
WakeWordAgent not compiling - No rule to make target '../ext/lib/libblas.so.3'

### ISSUE THREAD

**Issue by katjabregenzer** [alexa/alexa-avs-sample-app#867]
Hi, 
I´m trying to install the sample app on a raspberry pi 3 but the installation script fails when compiling the wakeWordAgent: 
`Scanning dependencies of target wakeWordAgentTest
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
[ 25%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/SensoryWakeWordEngine.cpp.o
make[2]: *** No rule to make target '../ext/lib/libblas.so.3', needed by 'wakeWordAgentTest'.  Schluss.
make[2]: *** Warte auf noch nicht beendete Prozesse...
[ 30%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

I saw issues with simular descriptions, where the suggestion came up to re-run the script. So I did that, but it doesn´t change anything. 

Thanks in advance for your help.

**Comment by namanmittal-namanm** [comment]
Hi @katjabregenzer it looks like it is unable to find libblas.so.3, I will suggest you to re run the automated_installer.sh so that it can the fetch the dependencies or what you can also try is running this command: sudo apt-get install libblas-dev liblapack-dev which has the file libblas.so.3 and then copy the required file in that location as specified in error.

**Comment by katjabregenzer** [comment]
Hi, 

thanks, I copied the file manually in the required location and the wakeWordAgent compiled. In case this should happen to someone else, you find the file in /usr/lib/libblas
