### ISSUE TITLE
Please check below the screenshot and let me know how to resolve this issue

### ISSUE THREAD

**Issue by vaibhavbhanawat01** [alexa/alexa-avs-sample-app#869]
![img_20170721_173605](https://user-images.githubusercontent.com/12860795/28463003-af7ff610-6e3b-11e7-9f58-40ba09bc9bb7.jpg)

**Comment by namanmittal-namanm** [comment]
Hi @vaibhavbhanawat01 can you please try the steps as stated here: https://github.com/alexa/alexa-avs-sample-app/wiki/Troubleshooting#unable-to-find-avsappclass

**Comment by vaibhavbhanawat01** [comment]
issue is resolved, hence close this issue
