### ISSUE TITLE
getting an error while installing campanionService in alexa installation ???????? 

### ISSUE THREAD

**Issue by vaibhavbhanawat01** [alexa/alexa-avs-sample-app#870]
![img_20170721_181947](https://user-images.githubusercontent.com/12860795/28464139-7aefdcc0-6e41-11e7-88e3-988dc335088f.jpg)

**Comment by namanmittal-namanm** [comment]
Hi @vaibhavbhanawat01, can you please provide us with the details on what steps are you following to install companionService. Also have to tried installing it using automated_install.sh?

**Comment by vaibhavbhanawat01** [comment]
while installing the app using automated_install.sh file. i am getting this error. I am able to install the java client but while installing the companion service i am getting this error.

**Comment by jordan-heier** [comment]
Hi @vaibhavbhanawat01 , It looks like someone else had this issue with npm (https://github.com/npm/npm/issues/4510). In their case it ended up being a corporate proxy issue. Are you on a corporate proxy? Can you check your [npmrc](https://docs.npmjs.com/files/npmrc) files to make sure there are no proxies configured?

**Comment by vaibhavbhanawat01** [comment]
Hi @jordan-heier  this issue has resolved. This issue was related to proxy. Thanks

**Comment by yoyo7373** [comment]
@vaibhavbhanawat1 where did you find the npmrc file

**Comment by vaibhavbhanawat01** [comment]
hi @yoyo7373  if you are using the raspbian then you will find this file inside the npm folder or nodejs
