### ISSUE TITLE
error getting token

### ISSUE THREAD

**Issue by fatpanda98** [alexa/alexa-avs-sample-app#872]
hey guys. im new into this project and when i try to get the token it says "device tokens ready"..in terminal i get this:                                                                           pi@raspberrypi:~/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for Alexis / 123456789
Successfully retrieved registration code for Alexis / 123456789

/home/pi/alexa-avs-sample-app/samples/companionService/node_modules/node-storage/index.js:24
        throw err;
              ^
Error: EACCES, open './refresh_tokens~'

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by vaibhavbhanawat01** [comment]
Did you found the solution for this issue ???

**Comment by fatpanda98** [comment]
No, do you have any solution?

**Comment by vaibhavbhanawat01** [comment]
noo

**Comment by namanmittal-namanm** [comment]
Hi @fatpanda98 @vaibhavbhanawat01 It looks like the problem are with the file permissions. Have you guys installed the avs-sample-app using sudo by any chance? Also did you guys used automated_installer.sh to install the app?

**Comment by vaibhavbhanawat01** [comment]
yes i have used automated_installer.sh to install the app

**Comment by fatpanda98** [comment]
yeah i used sudo and automated_install.sh to install

**Comment by vaibhavbhanawat01** [comment]
![img_20170725_160815](https://user-images.githubusercontent.com/12860795/28568494-9ba241aa-7153-11e7-94f3-df37d9960cf1.jpg)

Hi @fatpanda98 and @namanmittal-namanm  this the latest error i am getting while starting companionService

**Comment by namanmittal-namanm** [comment]
Hi @fatpanda98 @vaibhavbhanawat01 can you guys please do a clean installation by running automated_installer without sudo.

**Comment by vaibhavbhanawat01** [comment]
hi @namanmittal-namanm  still i am getting this error after clean installation by automated_install.sh


pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ sudo npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by namanmittal-namanm** [comment]
Hi @vaibhavbhanawat01 Can you please try running npm install before running npm start. Also when you ran automated_installer.sh did you saw any errors?

**Comment by vaibhavbhanawat01** [comment]
hi, i am getting this error while running automated_installler.sh

After this operation, 173 MB disk space will be freed.
(Reading database ... 108337 files and directories currently installed.)
Removing oracle-java8-jdk (8u65) ...
update-alternatives: using /opt/jdk1.8.0_141/bin/javac to provide /usr/bin/javac (javac) in auto mode
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys EEA14886
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.v1pV0VzKeg --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver pgp.mit.edu --recv-keys EEA14886
gpg: requesting key EEA14886 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.BTvWARiJAw --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys EEA14886
gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
ERROR: FAILED TO FETCH GPG KEY. UNABLE TO UPDATE JAVA

**Comment by namanmittal-namanm** [comment]
Hi @vaibhavbhanawat01 Seems like you have really old version of java installed, can you force remove the old version and install the latest one. or You can also try running this command : sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 and then run the automated_installer.sh

**Comment by vaibhavbhanawat01** [comment]
thanks, i will try this

**Comment by vaibhavbhanawat01** [comment]
hi @namanmittal-namanm  after running that command follow is the update 

gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
^Z
[4]+  Stopped                 sudo gpg --keyserver hkp://keyserver.ubuntu.com:8080 --recv-keys EEA14886
pi@raspberrypi:~ $ sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: key EEA14886: "Launchpad VLC" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by vaibhavbhanawat01** [comment]
hi @namanmittal-namanm  after running that following is the update 

gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: key EEA14886: "Launchpad VLC" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by namanmittal-namanm** [comment]
Can you try these steps:
1. remove old Java
sudo apt-get purge openjdk*
sudo apt-get purge java7*
sudo apt-get autoremove
2. sudo apt-key adv –recv-key –keyserver keyserver.ubuntu.com EEA14886
3. sudo vim /etc/apt/sources.list
      #Add following lines
deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main

4. Install Java8

sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo apt-get install oracle-java8-set-default
5. check success

java -version

if it shows Java 8 then continue with automated_installer script.

**Comment by vaibhavbhanawat01** [comment]
Hi @namanmittal-namanm i have tried all the step but still there is some error i am getting. Please check it and let me know if i am making any mistake 


========== Installing Companion Service ==========
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:185:19)
    at Object.urlParse [as parse] (url.js:101:5)
    at Object.validateUrl [as validate] (/usr/lib/nodejs/nopt.js:164:13)
    at validate (/usr/lib/nodejs/nopt.js:212:24)
    at validate (/usr/lib/nodejs/nopt.js:179:11)
    at /usr/lib/nodejs/nopt.js:101:12
    at Array.map (native)
    at /usr/lib/nodejs/nopt.js:67:15
    at Array.forEach (native)


/usr/share/npm/lib/npm.js:32
    throw new Error('npm.load() required')
          ^
Error: npm.load() required
    at Object.npm.config.get (/usr/share/npm/lib/npm.js:32:11)
    at exit (/usr/share/npm/lib/utils/error-handler.js:49:40)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:324:3)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
========== Preparing External dependencies for Wake Word Agent ==========
mkdir: cannot create directory ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/include’: File exists
mkdir: cannot create directory ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/lib’: File exists
mkdir: cannot create directory ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources’: File exists
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/portaudio.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/pa_ringbuffer.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/include/pa_util.h’: No such file or directory
cp: cannot stat ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/install/lib/libportaudio.a’: No such file or directory
ln: failed to create symbolic link ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/lib/libblas.so.3’: File exists
mkdir: cannot create directory ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/ext’: File exists
========== Compiling Wake Word Agent ==========
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp:14:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:326: recipe for target 'CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:302: recipe for target 'CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/wakeWordAgent.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
[ 15%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp:14:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
CMakeFiles/wakeWordAgentTest.dir/build.make:278: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/testKittAi.cpp:15:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst/../src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:19:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.h:17:27: fatal error: pa_ringbuffer.h: No such file or directory
 #include "pa_ringbuffer.h"
                           ^
compilation terminated.
compilation terminated.
CMakeFiles/wakeWordAgentTest.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o] Error 1
CMakeFiles/wakeWordAgentTest.dir/build.make:230: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
chown: changing ownership of ‘/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log’: Operation not permitted
chown: changing ownership of ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/lib/libblas.so.3’: Operation not permitted

=============================
*****************************
========= Finished ==========
*****************************
=============================

To run the demo, do the following in 3 seperate terminals:
Run the companion service: cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start
Run the AVS Java Client: cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
Run the wake word agent: 
  Sensory: cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e sensory
  KITT_AI: cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e kitt_ai
  GPIO: PLEASE NOTE -- If using this option, run the wake word agent as sudo:
  cd /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && sudo ./wakeWordAgent -e gpio

**Comment by namanmittal-namanm** [comment]
Hi @vaibhavbhanawat01 this issue seems to come when sitting behind a proxy. If you are sitting behind a proxy can you please try again outside of proxy.

**Comment by vaibhavbhanawat01** [comment]
sure @namanmittal-namanm  i will try without network

**Comment by vaibhavbhanawat01** [comment]
Hi @namanmittal-namanm  I am able to connect with ALexa voice service, issue was related to proxy. Thanks

**Comment by jordan-heier** [comment]
Closing this issue as the problem looks to be resolved. Please reopen if more assistance is needed with the issue.
