### ISSUE TITLE
I've try to connect to avs sample server 10.0.2.2:8443 but it doesn't respond.

### ISSUE THREAD

**Issue by duckky93** [alexa/alexa-avs-sample-app#877]
java.net.ConnectException: failed to connect to /10.0.2.2 (port 8443): connect failed: ECONNREFUSED (Connection refused)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:124)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.net.Socket.connect(Socket.java:884)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:143)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
07-26 17:43:32.342 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.doRequest(ProvisioningClient.java:124)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.doRequest(ProvisioningClient.java:98)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.ProvisioningClient.getDeviceProvisioningInfo(ProvisioningClient.java:50)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.LoginWithAmazonActivity$1$1.doInBackground(LoginWithAmazonActivity.java:117)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at com.amazon.alexa.avs.companion.LoginWithAmazonActivity$1$1.doInBackground(LoginWithAmazonActivity.java:104)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at libcore.io.Posix.connect(Native Method)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
07-26 17:43:32.343 3455-3455/com.amazon.alexa.avs.companion W/System.err: 	... 28 more

**Comment by namanmittal-namanm** [comment]
Hi @duckky93, Usually you get this exception when nothing is listening on that port or the firewall is blocking it, can you please check you have completed Step 5b of the platform you are on, and the server is listening on port 8843.
