### ISSUE TITLE
no echo signal to cx20921,cx20709 need configuration?

### ISSUE THREAD

**Issue by laojiang1614** [alexa/alexa-avs-sample-app#882]
​I operate according the official document  to set up the Conexant AudioSmart 2-Mic Development Kit for Amazon AVS.When  I ask it to play the news,the rpi3 can play.But  when I send the signal  to the  board,the CX20709 chip only receive the signal and not to send the signal as echo to CX20921.I don't know if I have to make the configuration of cx2709.Do anyone tell me how to do it？

**Comment by jordan-heier** [comment]
Hi @laojiang1614 , Just letting you know we have received this and we are working on looking into this issue. We will provide more of an update once we know more about the issue.

**Comment by laojiang1614** [comment]
CX20709  receive the analog signal via 3.5mm audio jack,but not convert it into the digital signal to CX20921

**Comment by laojiang1614** [comment]
I have find the problem,the firmware is not right.Update the firmware of the CX20709,everything is ok.

**Comment by gdpeter8075** [comment]
How do you update the firmware. I search it online but I can't find the firmware for CX20709
