### ISSUE TITLE
What do javaclient have to do with companionService

### ISSUE THREAD

**Issue by StupidYe** [alexa/alexa-avs-sample-app#883]
hi, i do not know what's the relationship between the project javaclient and companionService.As far as i considers,the app act as client,and the javaclient run in the product as server,it is right?Please tell me the answer,thanks!

**Comment by jordan-heier** [comment]
Hi @StupidYe , a companion service is one method to authenticate an AVS application (like the javaclient). See [this page](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/avs-api-overview#authorization) for more information about authorizing an AVS app and other methods of authorization that are available. Resolving this, please reopen if you have further questions.
