### ISSUE TITLE
Alexa Internal flow ??

### ISSUE THREAD

**Issue by vaibhavbhanawat01** [alexa/alexa-avs-sample-app#885]
Hi, 
Can anyone tell me how the Alexa voice service internally works. I am able to connect my raspberry pi to the AVS, But i am very curious to know the internal working of the Alexa. How it converts the speech into text than how it analyze the text than return the correct response of any query. How again it converts the text to the speech??? 
Whether it uses some google expertise system or something  else?????
Please share any links or information related to this.

**Comment by jordan-heier** [comment]
Hi @vaibhavbhanawat01 , we have not made the internal logic of Alexa public. You may want to check out [this video](https://www.youtube.com/watch?v=t58fUp15YB4&t=564s) for a high level overview of Alexa, but we are unable to share more information at this time. Please reopen if you have more questions.

**Comment by vaibhavbhanawat01** [comment]
Thanks @jordan-heier
