### ISSUE TITLE
I am not getting JSON logs in my app

### ISSUE THREAD

**Issue by LisySamuel92** [alexa/alexa-avs-sample-app#886]
I am getting only voice response from alexa and not getting JSON logs. Please help me with this i am confused with this

![screenshot from 2017-08-07 15-16-49](https://user-images.githubusercontent.com/28390513/29021546-7d2d226e-7b83-11e7-887c-071c90736794.png)

**Comment by AlphaDrakonix999** [comment]
Hello LisySamuel92,

Thank you for reaching out to us with your inquiry.

JSON logs are stored in the javaclient/logs folder.  

Could you please confirm that such directory exists in your workspace?

Best,

**Comment by LisySamuel92** [comment]
Hello AlphaDrakonix999,
Thank you for your help. 
JSON logs directories are exists in my workspace directory.
![screenshot from 2017-08-08 10-25-36](https://user-images.githubusercontent.com/28390513/29058142-64045fa6-7c2c-11e7-89f2-5643c8cd8c5e.png)
Do i need do something to display this logs in my app?

**Comment by AlphaDrakonix999** [comment]
You could open the log and read it in memory and associate the content as a text field in a ui element.
Regards,

**Comment by LisySamuel92** [comment]
Thank you so much for your help AlphaDrakonix999

**Comment by LisySamuel92** [comment]
Thank you so much for your help AlphaDrakonix999
