### ISSUE TITLE
Alexa Client stopped working without reason

### ISSUE THREAD

**Issue by lauderdice** [alexa/alexa-avs-sample-app#887]
Hi,

up to now i have had no issues with Alexa AVS sample app, not even when i tried it this morning.

Then i left it for some time and did some stuff on PC and wanted to run it again so i did npm start and when i wanted to mvn exec:exec, it showed this error. Dont understand how this could happen..

mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.JsonException: Cannot auto-detect encoding, not enough chars
	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:131)
	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:76)
	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:76)
	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:68)
	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:131)
	at javax.json.Json.createReader(Json.java:220)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:63)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:36)
	at com.amazon.alexa.avs.App.main(App.java:31)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.351 s
[INFO] Finished at: 2017-08-07T15:28:38+02:00
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by AlphaDrakonix999** [comment]
Hello Lauderdice,

Thank you for reaching out to use with your inquiry.

We have been unable to reproduce your issue.  At this point we suggest that you log-out from your account session, log-in back, and try to reproduce the issue.

Could you please let use know if this resolved your issue?

Thank you advance,

**Comment by lauderdice** [comment]
I ran the auto install again and noticed that the script deletes some parts of gnome-terminal. during the period when Alexa stopped working I actually installed gnome-terminal but then uninstalled it again , reinstalling solved the issue.

**Comment by AlphaDrakonix999** [comment]
Hello Lauderdice,

Thank you for providing us with the additional information.  We are glad that your issue has been resolved.

Have an Amazing day! 😃
