### ISSUE TITLE
NoReplyFromAlexa

### ISSUE THREAD

**Issue by Uraforclain** [alexa/alexa-avs-sample-app#888]
I followed the guide from http://lifehacker.com/the-simplest-way-to-build-a-raspberry-pi-powered-amazon-1794218212 which i think is the latest version to run echo on the PI3.

I am using a PI-3
USB microphone MI-305
Speaker output via 3.5mm jack

After i followed the guide,
1. I opened up sudo raspi-config -> advance options -> audio -> and i chose 3.5mm jack 

**Problem**
When i say Alexa, up till now it has only replied me a "YES?" like once in 100 times. But even after that one time and i repeat "Alexa" again, no reply comes out.
When i reboot the pi, it says Hello. But after that when i call alexa again simply no reply.

**Here is what i get when i check the status of the AlexaPi Service**

```
pi@RP3:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Wed 2017-08-09 11:04:37 +08; 4min 30s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 583 (python)
   CGroup: /system.slice/AlexaPi.service
           └─583 /usr/bin/python /opt/AlexaPi/src/main.py --daemon

Aug 09 11:07:39 RP3 python[583]: Traceback (most recent call last):
Aug 09 11:07:39 RP3 python[583]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Aug 09 11:07:39 RP3 python[583]: self.run()
Aug 09 11:07:39 RP3 python[583]: File "/usr/lib/python2.7/threading.py", line 763, in run
Aug 09 11:07:39 RP3 python[583]: self.__target(*self.__args, **self.__kwargs)
Aug 09 11:07:39 RP3 python[583]: File "/opt/AlexaPi/src/main.py", line 541, in trigger_process
Aug 09 11:07:39 RP3 python[583]: audio_stream = capture.silence_listener(force_record=force_record)
Aug 09 11:07:39 RP3 python[583]: File "/opt/AlexaPi/src/alexapi/capture.py", line 53, in silence_listener
Aug 09 11:07:39 RP3 python[583]: inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, self._config['sound']['input_device'])
Aug 09 11:07:39 RP3 python[583]: ALSAAudioError: Device or resource busy [plughw:CARD=Device,DEV=0]
pi@RP3:~ $ 
```

**This is what i have in the starting few lines of my config.yaml file**
```
  sound:

  # Name of your ALSA microphone/soundcard in arecord -L
  input_device: "plughw:CARD=Device,DEV=0"
  # This is here if none of the listed device: "raspberrypi"
  # This is an override that is normally not needed and is a last resort.
  allow_unlisted_input_device: false

  playback_handler: "vlc"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "alsa"
  # output device: "raspberrypi"
  # currently supports ALSA only
  output_device: "default"

  # if left empty, won't be passed to the underlying library / command if it supports it
  # if it doesn't 100% will be used
  default_volume: 80
```

**What i have tried from Audio setup & debugging Git page**
Checking if your system audio works

**TRIED IT WORKS** To test playback, run aplay /usr/share/sounds/alsa/Front_Center.wav

To test recording, run
**TRIED IT WORKS** arecord -f S16_LE -r 16000 -D your_input_device test.wav - exit with CTRL+C and
**TRIED IT WORKS** aplay -f S16_LE -r 16000 test.wav to play

**Comment by AlphaDrakonix999** [comment]
Hello Uraforclain,

We are sorry to hear you are facing difficulties with third party tutorials posted in a third-party weblog.  We suggest you to contact the author of the weblog post to communicate him the difficulties you are facing while following his tutorial.

Regards,
