### ISSUE TITLE
Display cards in AVS sample?

### ISSUE THREAD

**Issue by apatti** [alexa/alexa-avs-sample-app#890]
Hi,

According to https://developer.amazon.com/alexa-voice-service/gui we should be able to test the Display card functionality with AVS sample code on raspberry pi, can someone let me know if AVS sample code is updated with the display card functionality?

**Comment by AlphaDrakonix999** [comment]
Hello Apatti,
Thank you for reaching out to us with your inquiry.  As of June 21, 2017 the sample app now support Display Cards.
Source: https://github.com/alexa/alexa-avs-sample-app
Regards,

**Comment by apatti** [comment]
Hi,

Cool, thanks for the update. How do we enable the display cards then? currently when i run the sample code using mvn exec:exec i only get the regular UI and voice.

**Comment by smare** [comment]
Same here - no cards are displayed.  I've enabled them in for my device in the developer console - is there some additional configuration needed?
