### ISSUE TITLE
Do i have to have a usb mini microphone since my speaker already has one?

### ISSUE THREAD

**Issue by abdelrahmanhmed** [alexa/alexa-avs-sample-app#892]
Do i have to have a usb mini microphone since my speaker already has one?

**Comment by AlphaDrakonix999** [comment]
Hello Abdelrahmanhmed,
Thank you for reaching out to us with your inquiry.  No, you do not need to have an independent microphone if your speakers already have one.  What is important is that your app can recognize and read audio data from your audio device independently of its hardware implementation.
Have an Amazing experience your development! :-),
