### ISSUE TITLE
How to enable display cards in alexa sample code

### ISSUE THREAD

**Issue by apatti** [alexa/alexa-avs-sample-app#894]
Hi,

From the information i have received, the AVS sample code is updated to include display card functionality but I am not sure how to enable it.
Currently if issue mvn exec:exec i get regualr UI.

**Comment by apatti** [comment]
Sorry, i found how to do it.

**Comment by juan-gutierrez-nxp** [comment]
Hi @apatti

Can you comment how to enable the cards?
