### ISSUE TITLE
Conexant Microphone "Dancing Lights" Error

### ISSUE THREAD

**Issue by AsherRoland** [alexa/alexa-avs-sample-app#897]
I have a working internet connection, and a perfectly good loading process of alexa, but when I start it up and say "Alexa" then ask for the time, it thinks for a little bit then stops the moving lights from thinking and fades them out, that's why i called them dancing lights. Voice and Button do not make it work. Any ideas?

**Comment by AsherRoland** [comment]
It says that it cannot create an audio device when I load it up.

**Comment by dhpp** [comment]
Hi AsherRoland,

It sounds like you are on the right path - what you describe sounds like you create a valid connection to AVS, send a Recognize Event (user speech), then when AVS sends back a Speak Directive, the Java runtime has problems with the audio playback.

What platform are you running this on?  Are your audio drivers, and Java, up to date?  This does seem like a platform issue, than an AVS issue.  If you'd like us to verify the client / server interaction further to confirm, please provide an x-amzn-requestid from one of the AVS responses, which will allow us to inspect server logs.

**Comment by AsherRoland** [comment]
This is currently what the Raspberry Pi 2 says my audio device is(the conexant Amazon 4 mic system). I am thinking this looks corrupt. Have any ideas?


![2017-08-15-084519_1024x768_scrot](https://user-images.githubusercontent.com/31007279/29316499-442835da-8196-11e7-880e-807cfd969d08.png)

**Comment by bandkenamazoncom** [comment]
This is quite old.  Please re-open if the steps provided by @dhpp don't help.
