### ISSUE TITLE
Error with the exec:exec terminal

### ISSUE THREAD

**Issue by xTheCodingChicken** [alexa/alexa-avs-sample-app#902]
hey,
I moved my Alexa (previously working) from Raspbian Lite to normal Raspbian (both installations done without NOOBS/ I installed Alexa completely new on my new operating system.). But now I get this error in the second terminal (the exec:exec one): https://pastebin.com/V9Gi9Kkc . Terminal one is fine if that is important to you. So far I tried reinstalling vlc (it says that 0 files have been updated or downloaded so I guess that vlc is fine.) and I tried to install Java 8 32bit but I can just download the 64bit version(which automatically got installed and is up to date.). Can someone here help me please? 

## EDIT: 
 If it is possible i don't want to change back to Raspbian lite because then I would have to keep my Pc with the terminals running for it to work, right?

**Comment by ofuangka** [comment]
I think Raspbian was recently updated to Stretch, and the alexa-avs-sample-app has not yet been updated to support Stretch.

https://www.raspberrypi.org/blog/raspbian-stretch/

See https://github.com/alexa/alexa-avs-sample-app/issues/900

**Comment by ofuangka** [comment]
I was able to get it working under Stretch with a few workarounds. The VLC library issue can be resolved by installing libvlc-dev. There's an issue with compiling wakeWordAgent. That can be resolved by modifying CMakeLists.txt

    add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

There's an issue with the install-java8.sh script, which you can workaround by adding the following:

    elif [ "$VERSION" == "stretch" ]; then
        UBUNTU_VERSION="yakkety"

**Comment by xTheCodingChicken** [comment]
@ofuangka Where can I find this CMakeLists.txt?

**Comment by ofuangka** [comment]
https://github.com/alexa/alexa-avs-sample-app/blob/5261ef3f9cb0a4f4c2911bb50b418a10dc6e063c/samples/javaclient/install-java8.sh#L17

I think I also had to add --allow-unauthenticated to the apt-get install java8 packages at the bottom. Obviously do this at your own risk.

https://github.com/alexa/alexa-avs-sample-app/blob/5261ef3f9cb0a4f4c2911bb50b418a10dc6e063c/samples/wakeWordAgent/src/CMakeLists.txt#L31

You might be better off waiting for the script to be updated.

**Comment by jeroen1970** [comment]
I have the same problem, but I'm also new to programing and stuff so I don't understand anything and so I can't complete these steps.
Is it possible for one of you smart guys to make a simple video about it?

**Comment by XneddyX** [comment]
@ofuangka thx your workaround is good.....

**Comment by setau06** [comment]
@ofuangka thank you so much <3 
You saved my projekt till the script get updated.

**Comment by kencecka** [comment]
Hi all,

We have filed a ticket to look at supporting raspbian stretch in a future release of the Java sample application.

Ken

**Comment by eziohzy** [comment]
I am curious how to run alexa with rapbian-lite?  As far as I know ,rabian-lite don't have destop-GUI then how can U run javaclient on it

**Comment by mradulan** [comment]
Hi @eziohzy , you can manually install an external GUI like LXDE GUI on the Pi.

**Comment by mandalae** [comment]
@ofuangka Thanks so much for this fix. You should probably just raise a PR with those changes, as it seems to fix the install problems on Stretch.

**Comment by BennyAvramson** [comment]
Raspbian Stretch is supported on the last release.
