### ISSUE TITLE
App Support Unavailable shown for all music services

### ISSUE THREAD

**Issue by HappySock** [alexa/alexa-avs-sample-app#906]
at alexa.amazon.com all I see in the music category (my music library, spotify, tunein, etc...) is App Support Unavailable shown for all music services. every one.

what gives? I can still say "alexa tell tunein to play 89.1" and it works just fine.

I've rebooted and reloaded to no avail.
I can sign out but signing in takes me to "**null**/spa/index.html"
backing up signs me in again which is stupid, I sign out and all it would take for someone else to use my account would be to hit the back button?

ok this little rant needs to take a detour.
I replaced the null with "https://alexa.amazon.com" and it takes me into the alexa page and now music services are working. so this appears to be related to some type of error in the login page directing you to a bad address.

Would one of you please try signing out and then back in. let me know what you get.

**Comment by jietaatamazon** [comment]
Hi @HappySock 
What browser did you use when you hit the back button? Did you use the Alexa java sample app? Besides, could you share the screenshot for the issue? 
Thanks.

**Comment by HappySock** [comment]
using chrome. but they have since fixed the misdirected address.
