### ISSUE TITLE
[Thread-25] ERROR com.amazon.alexa.avs.auth.companionservice.Compan ionServiceAuthManager - There was a problem connecting to the Companion Service.

### ISSUE THREAD

**Issue by EvilDuky** [alexa/alexa-avs-sample-app#908]
Hi,

I have the following message when I did "mvn exec:exec" (windows)

_"15:34:13.052 [Thread-25] ERROR com.amazon.alexa.avs.auth.companionservice.Compan
ionServiceAuthManager - There was a problem connecting to the Companion Service.
 Trying again in 2 seconds. Please make sure it is up and running."_

Can you help me?

Thanks

**Comment by EvilDuky** [comment]
I forgot tu so "npm start", now I have another error when I click to Login:

**## Into nmp start windows:**
__"Listening on port 3000
Error retrieving registration code: BadRequest, The provided product and dsn do
not match valid values"_

## **into mvn exec:exec windows:**
"15:47:04.002 [Thread-25] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to
tart companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteService
xception: BadRequest: The provided product and dsn do not match valid values
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.ca
lService(CompanionServiceClient.java:238) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.ge
RegistrationCode(CompanionServiceClient.java:156) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.requestRegistrationCode(CompanionServiceAuthManager.java:74) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.startNewProvisioningRequest(CompanionServiceAuthManager.java:66) ~[classes/:?

        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$3
AuthSetup.java:86) [classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$$Lambda$35/1804379080.run(Unknow
 Source) [classes/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
15:47:08.543 [Thread-27] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to
tart companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteService
xception: BadRequest: The provided product and dsn do not match valid values
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.ca
lService(CompanionServiceClient.java:238) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.ge
RegistrationCode(CompanionServiceClient.java:156) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.requestRegistrationCode(CompanionServiceAuthManager.java:74) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.startNewProvisioningRequest(CompanionServiceAuthManager.java:66) ~[classes/:?

        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManag
r.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$3
AuthSetup.java:86) [classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$$Lambda$35/1804379080.run(Unknow
 Source) [classes/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]"_

**Comment by anjali58** [comment]
I am also getting the same problem.
