### ISSUE TITLE
-- Configuring incomplete, errors occured! chown: cannot access `/home/root/asoundrc': No such file or directory

### ISSUE THREAD

**Issue by yoyo7373** [alexa/alexa-avs-sample-app#909]
when I type in sudo bash automated_install in my terminal the file does not finish configuration and once I run the three separate terminals, the npm gives me errors, the javaclient does not open a window and doesn't finish building, and wakeWordAgent says thatd there is no file or directory with ./wakeWordAgent.

**Comment by yoyo7373** [comment]
I discovered that right before automated_install.sh finished running it said:
-- Configuring incomplete, errors occured!
chown: cannot access `/home/root/asoundrc': No such file or directory

can someone please help me with this problem???

**Comment by sgript** [comment]
Having the same issue.

**Comment by kencecka** [comment]
Hi @yoyo7373 and @sgript,

It sounds like you are trying to run automated_install.sh as root (or using sudo).  The script does not explicitly check for running as root, but was written to be run as a regular user.  In particular, it tries to set up an alsa configuration file in /home/$User/.asoundrc.  While this is the correct location for a regular user, the home directory for root is in /root/.asoundrc.  As such, the automated_install.sh does not work when run as root.

Is it critical that you install as root, or can you install as a regular user?

Ken

**Comment by yoyo7373** [comment]
Hi @kencecka thanks for your feedback but i already tried running it without root but it keeps on saying that it needs permission to remove specific files and/or programs, so i typed y and pressed enter but it said permission denied.

**Comment by kencecka** [comment]
Hi @yoyo7373,

It may be that previous attempts to run the script as root have created root-owned files that you now do not have permission to delete.  I just tried running the autoated_install.sh as described in the directions on a fresh install of rasbian stretch as a regular user, and did not encounter any permissions issues.

If possible, you might want to try a clean install.  If that is impractical, we can try to work through the specific files you are seeing permissions errors on and clean them up manually.

Ken

**Comment by yoyo7373** [comment]
@kencecka, so I reinstalled the alexa-avs file without root and ran everything without root, but then while automated_install.sh was running an error happened with wakeWordAgent saying: changing ownership of '/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/ext/lib/libblas.so.3': Operation not permitted

**Comment by yoyo7373** [comment]
everything was going smooth until that error occurred.

**Comment by yoyo7373** [comment]
I fixed that problem, but there are another 3 errors that are saying: recipe for target 'filename' failed

**Comment by yoyo7373** [comment]
@kencecka could you please send me the steps you took to download alexa-avs-sample-app and the steps you took to run it so I can double check myself.

**Comment by mradulan** [comment]
Hi @yoyo7373 , is the issue resolved?

**Comment by anu-mathur** [comment]
Hi @yoyo7373 @sgript 
I am doing a user study on the alexa-avs-sample-app and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tinyurl.com/AVSContactForm
) and I will get in touch with you.
Thanks

**Comment by yoyo7373** [comment]
I'm closing this issue I used another Alexa program on github that worked much better (search it up on youtube).
