### ISSUE TITLE
Keyboard input to wake up Alexa

### ISSUE THREAD

**Issue by 1387625003** [alexa/alexa-avs-sample-app#910]
Hi, I would like to wake up alexa using a keyboard input (i.e. press any key on keyboard) in SampleApp. This is for Windows 10 PC. I am not too familar with Java, so any help will be appreciated.

Does anyone know which code I need to change in the library to achieve this?

Thanks

**Comment by kencecka** [comment]
Hi @1387625003,

There was another question recently about this topic - see #904.  In general, you will need to write some code which listens for keypresses, and then make calls to ListenViewController.listenButtonPressed().  You should be able to find examples of how to listen for keypresses by searching the web for "windows java keyboard input".

Ken

**Comment by 1387625003** [comment]
Hi Ken

Thanks for input, I have managed to insert a keyboard listener.

PAS
