### ISSUE TITLE
mvn exec:exec error  (BANANA PI M64)

### ISSUE THREAD

**Issue by JimmyChangJY** [alexa/alexa-avs-sample-app#912]
I did my homework. I spent one week to google every web page to seek the solution. 
There are so many people ask the same question. 
BUT I saw the only solution is they upgrade their entire system., For example from Debian 7 upgrade to Debian 8. The problem is gone. But my problem is I can't upgrade my system. 

> My hardware is Banana Pi M64. 
> OS:  Ubuntu 16.04 
> Thanks https://github.com/avafinger/bpi-m64-firmware
> 
> Uname -a 
> Linux Jimmy-M64 3.10.105 
> #1 SMP PREEMPT Sun Mar 26 17:44:41 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux

Step 1. 
I git alexa-avs-sample-app
And run automated_install.sh 
I skip the some step that I register on Amazon web page and get the ID number blah blah...

Step 2. 
I install Java 8 
I add 

> deb http://ppa.launchpad.net/webupd8team/java/ubuntu
> deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu
> into /etc/apt/source 

then 
```
sudo apt-get update
sudo apt-get  install oracle-java8-installer
sudo apt-get  install oracle-java8-set-default
```

then I check the environment 
```

sudo update-alternatives --config javac
/usr/lib/jvm/java-8-oracle/bin/javac

sudo update-alternatives --config java
/usr/lib/jvm/java-8-oracle/bin/java
```

```
ldconfig -p | grep vlc
	libvlccore.so.8 (libc6,AArch64) => /usr/lib/libvlccore.so.8
	libvlc_vdpau.so.0 (libc6,AArch64) => /usr/lib/vlc/libvlc_vdpau.so.0
	libvlc_vdpau.so (libc6,AArch64) => /usr/lib/vlc/libvlc_vdpau.so
	libvlc.so.5 (libc6,AArch64) => /usr/lib/libvlc.so.5
	libvlc.so (libc6,AArch64) => /usr/lib/libvlc.so
```

Step 3.
mvn install 
Success no error 

Then !!!!!!! 
mvn exec:exec error which I post below 

Any idea???

```

===================error message=========================


root@Jimmy-M64:/home/ubuntu/alexa/alexa-avs-sample-app/samples/javaclient# sudo mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path ([file:/home/ubuntu/alexa/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/root/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/root/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/root/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/root/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/root/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/root/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/root/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/root/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/root/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/root/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:183)
	at com.amazon.alexa.avs.App.<init>(App.java:47)
	at com.amazon.alexa.avs.App.<init>(App.java:36)
	at com.amazon.alexa.avs.App.main(App.java:31)

```

**Comment by kencecka** [comment]
Hi @JimmyChangJY,

I see that you're using 64-bit libraries; is your java installation all 64-bit as well?

Also, have you read through this thread yet?
https://github.com/alexa/alexa-avs-sample-app/issues/172

There is some discussion there about editing the pom file to download the JNA JAR.

Ken

**Comment by JimmyChangJY** [comment]
Thanks Kencecka 
I read #172 already 
And I also modify below  

<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>4.1.0</version>
  <scope>compile</scope>
</dependency>

**Comment by balaraju1278** [comment]
Hello JimmyChangJy,

your plugin should be look like this in pom.xml check once.

<plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>1.2</version>
          <configuration>
            <executable>java</executable>
            <arguments>
              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
              <argument>-Dlog4j.configurationFile=file:///${basedir}/log4j2.xml</argument>
              <argument>-classpath</argument>
              <classpath/>
              <argument>-Djna.library.path=${env.VLC_PATH}</argument>
              <argument>com.amazon.alexa.avs.App</argument>
            </arguments>
          </configuration>
        </plugin>

**Comment by balaraju1278** [comment]
hi JimmyChangJY,

your plugin should be look like this in pom.xml check once.




`<plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>1.2</version>
          <configuration>
            <executable>java</executable>
            <arguments>
              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
              <argument>-Dlog4j.configurationFile=file:///${basedir}/log4j2.xml</argument>
              <argument>-classpath</argument>
              <classpath/>
              <argument>-Djna.library.path=${env.VLC_PATH}</argument>
              <argument>com.amazon.alexa.avs.App</argument>
            </arguments>
          </configuration>
        </plugin>`

**Comment by balaraju1278** [comment]
Did you add env variable for vlc. 
EXPORT VLC. PATH="your vlc path"

Then run again if it won't work try to pass env variable through terminal while executing

**Comment by torumodos** [comment]
I was facing similar issue 
The thread as below helped me in my case (RPi3).

https://github.com/alexa/alexa-avs-sample-app/issues/907

cd /usr/lib/arm-linux-gnueabihf
sudo ln -s libvlc.so.5 libvlc.so
sudo ldconfig

**Comment by mradulan** [comment]
Hi @JimmyChangJY , is the issue resolved for you?

**Comment by JimmyChangJY** [comment]
Sorry, I choose 
https://github.com/alexa-pi/AlexaPi to replace.
So I didn't try those solution.

**Comment by mradulan** [comment]
Closing the issue for now. Please reopen if the problem persists.
