### ISSUE TITLE
npm start fails. How to debug?

### ISSUE THREAD

**Issue by RonaldOlsthoorn** [alexa/alexa-avs-sample-app#914]
I am trying to get the linux app to work on ubuntu 16.04. When I execute npm start, the following appears:

>lexa-voice-service-sample-companion-service@1.0.0 start /home/ronald/Workspace/alexa-avs-sample->app/samples/companionService
> node ./bin/www

> sh: 1: node: not found

> npm ERR! Linux 4.10.0-32-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs alexa-voice-service-sample-companion-service
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
> npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ronald/Workspace/alexa-avs-sample-app/samples/companionService/npm-debug.log

[npm-debug.log.zip](https://github.com/alexa/alexa-avs-sample-app/files/1265099/npm-debug.log.zip)

Before I could run the nodeJS server I had to install a shitton of software and configure a shitton of text files. Could very well be my mistake, but I have no Idea how to debug this, since I am a nodeJS noob. Any ideas on how to debug this?

**Comment by kencecka** [comment]
Hi @RonaldOlsthoorn,

This looks like the same issue:
https://github.com/alexa/alexa-avs-sample-app/issues/190

Can you verify that you actually have node installed?

Ken

**Comment by RonaldOlsthoorn** [comment]
Is node something different than nodeJS? nodeJS v4.2.6 installed and working

**Comment by RonaldOlsthoorn** [comment]
Ah, check. It actually is. Server is running now, we can close this one. Thank you very much kencecka!
