### ISSUE TITLE
Authorization page error

### ISSUE THREAD

**Issue by fsteff** [alexa/alexa-avs-sample-app#918]
Logging in in the sample app fails for me - the amazon oauth page shows only
"We´re sorry! An error occured when we tried to process your Request. ..."

Exact link: (credentials removed at ###)
https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.###&response_type=code&redirect_uri=https://localhost:3000/authresponse&scope=alexa%3Aall&state=b092f3ec-1b4e-4bcd-97a6-7838f112ad13&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22###%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22###%22%7D%7D%7D

**Comment by ryter--** [comment]
Have you added localhost to the allowed origins and return URLs in your security profile?

**Comment by fsteff** [comment]
Oh, thank you - I had a typo in the in the allowed origins URL.
