### ISSUE TITLE
wakeWordAgent no such file or directory - TRIED TO CMAKE - NOT WIRINGPI

### ISSUE THREAD

**Issue by KriyenKP** [alexa/alexa-avs-sample-app#925]
When I try this : 

`cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src && cmake . && make -j4`
 
I get this

```
~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ cd ~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/ && cmake . && make -j4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[  6%] Linking CXX executable wakeWordAgent
CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by sanjayrd** [comment]
Hi @KriyenKP,

What environment are you running this on?

Thanks,
Sanjay

**Comment by soaringsoul** [comment]
I ran into the same error, you need to just manually clone and compile Wiring Pi. 
Follow the instructions found [here](http://wiringpi.com/download-and-install/), and build wiring pi, then rerun the auto install script (or cmake command).

**Comment by wzone001** [comment]
I also got the same error message, i used Pi3 board and running NOOBS

CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by initcole** [comment]
Install this package ```sudo apt-get install wiringpi``` make sure your mic and speaker are connected and re run the automated install script again.

**Comment by arodr10** [comment]
This works for me:

1. Go to alexa-avs-sample-app/samples/wakeWordAgent/src folder and edit the CMakeLists.txt file, add the following line at the final:

add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

2. Run the following command in "alexa-avs-sample-app/samples/wakeWordAgent/src" path:

cmake . && make -j4

**Comment by initcole** [comment]
@arodr10 Thanks a lot. Works for me now.

**Comment by kjkh** [comment]
Problem has been resolved. @KriyenKP, if addition assistance is needed, please feel free to re-open the ticket.

**Comment by Dr-Greg** [comment]
Hi everybody, i got this error when i run cmake . && make -j4 (i have already modified the CMakeList)

########################

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ cmake . && make -j4
-- HAL found => /usr/lib/libmatrix_creator_hal.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp: In member function ‘void AlexaWakeWord::WakeWordAgent::mainLoop()’:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp:74:27: error: return-statement with a value, in function returning 'void' [-fpermissive]
   if (!bus.Init()) return false;
                           ^~~~~
CMakeFiles/wakeWordAgent.dir/build.make:86: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ 

########################
