### ISSUE TITLE
wake Word Agent build error - undefined reference to 'snowboy::SnowboyDetect...'

### ISSUE THREAD

**Issue by HoK-matic** [alexa/alexa-avs-sample-app#926]
I'm using a new Raspberry Pi 3 with a new SD-Card and a fresh _stretch_ installation.  I'm using the _automated_install.sh_ script, but compiling the wakeWordAgent always fails with an 'undefined reference' error. It looks like there's a header file or something else missing, but I'm not able to figure it out. I used the search function in this repository and found some issues related to the wakeWordAgent, but nothing really helped me solving this issue. 

cat /proc/version
Linux version 4.9.47-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1033 SMP Mon Sep 4 21:48:16 BST 2017

...
========== Compiling Wake Word Agent ==========
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
[ 33%] Linking CXX executable wakeWordAgent
CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_uni                                                                  que<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>                                                                  , std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<                                                                  char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_de                                                                  leteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c                                                                  ): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basi                                                                  c_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: die Regel für Ziel „wakeWordAgent“ scheiterte
make[2]: *** [wakeWordAgent] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/wakeWordAgent.dir/all“ scheiterte
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
****

**Comment by thoralmighty** [comment]
I have the same problem on a Raspberry Pi 3 (Raspbian 9 Stretch), tried using `CC=gcc4.9 make` and others but to no avail, wakeWordAgentTest also fails to compile with the same output. Since @HoK-matic 's output is in German, here is the last part in English:
```
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I've been looking around on the snowboy github pages, but so far this seems to be unknown.

**Comment by ac2wire** [comment]
Editing Cmakelists und running cmake again solved it for me.
See #902

**Comment by HoK-matic** [comment]
I did the modifications as described in [#902](https://github.com/alexa/alexa-avs-sample-app/issues/902). The 'undefined reference' error is gone and there's now a wakeWordAgent executable, which seems to work. I haven't had much time to test ist, right now. However, building wakeWordAgent/tst still fails. Maybe it's better to wait for a script updated for 'Stretch'.

**Comment by kjkh** [comment]
Hi,

As mentioned above, we do not officially support Stretch, but plan to in a future release. If you would like to pursue the issue further, please post the failure logs and reopen the issue.
