### ISSUE TITLE
Issue on wakewordageng on raspbian stretch

### ISSUE THREAD

**Issue by juliusdethan** [alexa/alexa-avs-sample-app#930]
Hi,

I have issues when compiling the wakewordagent on raspbian stretch. Here is the following error on ./automated_install.sh : 

========== Compiling Wake Word Agent ==========
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
[ 33%] Linking CXX executable wakeWordAgent
CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:436: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 10%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
[ 15%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testSensory.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 25%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/SensoryWakeWordEngine.cpp.o
[ 30%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp.o
[ 35%] Linking CXX executable wakeWordAgentTest
CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o: In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KittAiSnowboyWakeWordEngine.cpp:(.text._Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_[_Z11make_uniqueIN7snowboy13SnowboyDetectEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EESt10unique_ptrIT_St14default_deleteISB_EEDpOT0_]+0x4c): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgentTest.dir/build.make:566: recipe for target 'wakeWordAgentTest' failed
make[2]: *** [wakeWordAgentTest] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
chown: cannot access '/home/root/.asoundrc': No such file or directory

=============================
*****************************
========= Finished ==========
*****************************
=============================

**Comment by arodr10** [comment]
Go to:

alexa-avs-sample-app/samples/wakeWordAgent/src

Try adding the following line at final of CMakeLists.txt:

add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

And run the following command in "alexa-avs-sample-app/samples/wakeWordAgent/src" path:

cmake . && make -j4

**Comment by kjkh** [comment]
Hi. This is a known issue that we are tracking internally, and will update in a future release. The above suggestion mentioned by arodr10 should work. Closing, but feel free to re-open if problem persists.
