### ISSUE TITLE
Avoid mixed audio output (hdmi, amp card) and only use amp

### ISSUE THREAD

**Issue by ifs-net** [alexa/alexa-avs-sample-app#931]
Hi,

I just set up the sample app on a raspi 3. Seems to work quite fine except one thing: I use a hifiberry amp+ amplifier as audio output.
But the javaclient uses the hdmi output and so the output alexa says actually only can be heared via the speakers included in the hdmi screen. (but this screen will not be available later for my raspi, it will get a smaller touchscreen).
If I ask alexa to play a radio station the station is played via my amplifier (that is configured as default sound output at my raspi). 

So the audio output actually is mixed...

Is there a way to get the sample app to use the default audio output, too?

Thanks in advance!
Florian

**Comment by kjkh** [comment]
Hi,
We're having troubles reproducing the issue. Which version of the RaspberryPi OS have you installed? You also mentioned you have configured the default audio output. How did you configure that, and what did you configure it to?

The client itself actually does use two separate players for rendering SpeechSynthesizer Directives and AudioPlayer directives.

With speaks (such as Alexa replies), it's done through javazoom jl player, and with audio, VLC is used instead. This sounds like the default audio output is not being picked up by the javazoom jl player.

**Comment by ifs-net** [comment]
Thank you for your reply. I could solve it yesterday.
Asound config was wrong. It was correct at /etc/asound.conf but my raspi created a wrong .asoundrc at reboot for user pi. I have overwritten the asoundrc file with the content of the .conf File ans now the sound works fine.
