### ISSUE TITLE
Error retrieving access token: InvalidSessionId, No refresh tokens stored for this session id

### ISSUE THREAD

**Issue by iamchury** [alexa/alexa-avs-sample-app#936]
Hello. 

I'm trying to run Alexa in RPI3 with stretch version. (I got "raspbian stretch with desktop", release date: 2017-09-07). 

I installed alexa-avs following the guide below: 
https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi 

and I'm in "Step 8: Talk to Alexa", 
when I spoke out "Alexa" then I could hear the beep. 
And I spoke a query like "what's the time" then there's no response. 

I posted   

**In wakeWordAgent terminal, there's no progress after sending "wake_word". and it got stuck.** 

_INFO:WakeWordAgent: State set to IDLE(2)
INFO:KittAiSnowboyWakeWordEngine: Wake Word Detected
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:KittAiSnowboyWakeWordEngine: handling pause
INFO:KittAiSnowboyWakeWordEngine: releasing portAudio
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)_ 

**In companionService terminal:**
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for chury_pi3 / 123456789
Error retrieving access token: InvalidSessionId, No refresh tokens stored for this session id: fd551eca-f110-4bc6-afa1-caf1354edfd

Please share how to fix this issue if someone met this issue..

**Comment by Borduni** [comment]
Stretch isn't supported yet, but you can try to play with scripts (#902) to make it work but I would recommend you to wait or downgrading to jessie.

**Comment by Borduni** [comment]
Stretch isn't supported yet, but you can try to play with scripts (#902) to make it work but I would recommend you to wait or downgrading to jessie.

**Comment by kjkh** [comment]
Closing issue. Feel free to re-open if there are any additional questions.

**Comment by nekhil** [comment]
Hello..
I installed alexa-avs following the guide below:
https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

For the first time,i have got the tokens.....
and I'm in "Step 8: Talk to Alexa",
when I spoke out "Alexa" then I could hear the beep.
And I spoke a query like "what's the time" then there's no response
so i closed that session and started a new one,the "device tokens are ready" is shown in the webpage but some sort of error in retrieving token,the error is shown below

**"Listening on port 3000
Error retrieving access token: InvalidSessionId, The provided sessionId was invalid.
Successfully retrieved registration code for raspi_3 / 123456789
Error retrieving access token: InvalidSessionId, No refresh tokens stored for this session id: 32de897d-6bf6-4064-b6f6-06db"**
please help...

**Comment by adrihack** [comment]
Hello, did someone have find how to patch this error ?
I have the same message and i don't know how continue....
Thank's for helping !
