### ISSUE TITLE
./wakeWordAgent : No such file or directory 

### ISSUE THREAD

**Issue by ambelbasha** [alexa/alexa-avs-sample-app#937]
I have a Raspberry Pi 3 with AVS and i have installed wiringPi and re-run the automated_install.sh but getting the same error. Any ideas or help ?

**Comment by eziohzy** [comment]
same peroblem ?have you run cd to javaclient and  $ mvn exec:exec yet? do have any problems on this step?

**Comment by Juli15Boy** [comment]
I've been fighting with another error and when finally seems fixed I'm getting this one... TT Some advances in the resolution? :(

**Comment by arodr10** [comment]
For mvn exec:exec I do the following steps:

1. Run sudo apt-get install libvlc-dev
2. Go to alexa-avs-sample-app/samples/javaclient folder and edit the pom.xml file, I just change the value in tag  alpn-boot.version for this value: 8.1.6.v20151105

For wakeWordAgent

1. Go to alexa-avs-sample-app/samples/wakeWordAgent/src folder and edit the CMakeLists.txt file, add the following line at the final:

add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

2. Run the following command in "alexa-avs-sample-app/samples/wakeWordAgent/src" path:

cmake . && make -j4

**Comment by ambelbasha** [comment]
Thank you for your reply first of all arod10 ! 
The make part finally worked but now i'm getting a new error:
pi:~ $ cd /home/pi/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.pom
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.pom (3 KB at 0.2$
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-project/8.1.6.v20151105/alpn-project-8.1.6.v20151105.pom
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-project/8.1.6.v20151105/alpn-project-8.1.6.v20151105.pom (8 KB $
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar (54 KB at 21$
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale is blank in your config file. Supported$
        at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:134)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
        at com.amazon.alexa.avs.App.<init>(App.java:36)
        at com.amazon.alexa.avs.App.main(App.java:31)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:16 min
[INFO] Finished at: 2017-09-17T00:02:20+00:00
[INFO] Final Memory: 9M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution$
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ambelbasha** [comment]
Thank you for replying arodr10 !
Im now getting a new error : 
pi:~ $ cd /home/pi/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.pom
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.pom (3 KB at 0.2$
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-project/8.1.6.v20151105/alpn-project-8.1.6.v20151105.pom
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-project/8.1.6.v20151105/alpn-project-8.1.6.v20151105.pom (8 KB $
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar
Downloaded: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar (54 KB at 21$
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale is blank in your config file. Supported$
        at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:134)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
        at com.amazon.alexa.avs.App.<init>(App.java:36)
        at com.amazon.alexa.avs.App.main(App.java:31)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:16 min
[INFO] Finished at: 2017-09-17T00:02:20+00:00
[INFO] Final Memory: 9M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution$
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by arodr10** [comment]
@ambelbasha may be a different java versión, please run:

java -versión

and there are some equivalences for the pom.xml file:

1.8.0_05 = 8.1.0.v20141016
1.8.0_11 = 8.1.0.v20141016
1.8.0_20 = 8.1.0.v20141016
1.8.0_25 = 8.1.2.v20141202
1.8.0_31 = 8.1.3.v20150130
1.8.0_40 = 8.1.3.v20150130
1.8.0_45 = 8.1.3.v20150130
1.8.0_51 = 8.1.4.v20150727
1.8.0_60 = 8.1.5.v20150921
1.8.0_65 = 8.1.6.v20151105
1.8.0_66 = 8.1.6.v20151105
1.8.0_71 = 8.1.7.v20160121
1.8.0_72 = 8.1.7.v20160121
1.8.0_73 = 8.1.7.v20160121
1.8.0_74 = 8.1.7.v20160121
1.8.0_77 = 8.1.7.v20160121
1.8.0_91 = 8.1.7.v20160121
1.8.0_92 = 8.1.8.v20160420
1.8.0_101 = 8.1.8.v20160420
1.8.0_102 = 8.1.9.v20160720
1.8.0_111 = 8.1.9.v20160720
1.8.0_112 = 8.1.9.v20160720
1.8.0_121 = 8.1.11.v20170118
1.8.0_131 = 8.1.11.v20170118
1.8.0_141 = 8.1.11.v20170118
1.8.0_144 = 8.1.11.v20170118

**Comment by ambelbasha** [comment]
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK Zero VM (build 25.141-b15, interpreted mode)

**Comment by kjkh** [comment]
Hi. I see the following line in your output:

[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale is blank in your config file. Supported$

In your config.json file, can you check that the "locale" key has been appropriately set to either:
- "en-US"
- "en-GB"
- "de-DE"

**Comment by ambelbasha** [comment]
Solved with a clean automated_install.sh from beginging and updated the java version to 8.

**Comment by Juli15Boy** [comment]
@arodr10 Guy, reaally reaally thank you, you almost made me cry when I've seen Alexa answering me, really thank you again, you made my day :1st_place_medal:

**Comment by Dr-Greg** [comment]
Hi everybody, i got this error when i run cmake . && make -j4 (i have already modified the CMakeList)

########################

pi@raspberrypi:/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $ cmake . && make -j4
-- HAL found => /usr/lib/libmatrix_creator_hal.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src
[ 6%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp: In member function ‘void AlexaWakeWord::WakeWordAgent::mainLoop()’:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp:74:27: error: return-statement with a value, in function returning 'void' [-fpermissive]
if (!bus.Init()) return false;
^
CMakeFiles/wakeWordAgent.dir/build.make:86: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src $

########################
