### ISSUE TITLE
Port 3000 how to change?

### ISSUE THREAD

**Issue by tocan** [alexa/alexa-avs-sample-app#939]
In a lot of cases is port 3000 used by other important program and i could not find any description where or how to change this port.

**Comment by balaraju1278** [comment]
In companion service folder you can find bin ,in that bin there is www file you can configure your port

**Comment by ANANDSKRISHNAN** [comment]
How can I run my compnion app in my mobile device currently I am running in emulator plz help

**Comment by tocan** [comment]
thanks for the answer. I use a jessie based platform for my boat with raspberry and all should be on raspberry there but i changed the port now but did not keep it to run.

http://www.sailoog.com/en/openplotter


down is the downlod on this page... maybee a more experienced is able to help to run it with this software at raspberry... the main server on this plattform is the marine signal k server that needs port 3000 in generall all works but the register popup does not appear.. i will open another isue for this...

**Comment by balaraju1278** [comment]
for running app on mobile device you have to add your ip or dns on ssl.cnf file and it should be like this

subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1 
IP.2                     = 10.0.2.2
IP.3			= "your ip here"

after adding you have to generate your signed certs again

**Comment by ANANDSKRISHNAN** [comment]
Can we release the  app to play store.

**Comment by balaraju1278** [comment]
In companion service node-express default port is 3000 ,so that works on that port only but if your express version is 4.13.1 or above you can change your port that works

var port = normalizePort(process.env.PORT || '3000');  here change your port number otherwise you can set an environment variable for that like this

export PORT=8080
and then restart your pi

**Comment by ANANDSKRISHNAN** [comment]
After running in my mobile can I add this app to play store for that what should I do?

**Comment by balaraju1278** [comment]
No that won't work for that you have to follow another way to ssl certificates and you have your own dns server than only it will work

**Comment by ANANDSKRISHNAN** [comment]
Thanku, if you don't mind can u plz help me to achieve that

**Comment by ANANDSKRISHNAN** [comment]
Jst steps to get into that

**Comment by balaraju1278** [comment]
Before going to playstore did you run on device not on emulator

**Comment by ANANDSKRISHNAN** [comment]
Nope i jst run on emulator

**Comment by ANANDSKRISHNAN** [comment]
I jst one to know that I have my own dns and ssl certificate.

After running it in my physical device can I run own on my own server.

**Comment by mradulan** [comment]
Closing the issue of change of port 3000. For other issues, please open a new ticket.

**Comment by ANANDSKRISHNAN** [comment]
I had add my up address and I had generated certificate again but when I open the app it says waiting for debugger...plz help
