### ISSUE TITLE
java app build requires settings-security.xml

### ISSUE THREAD

**Issue by archana76** [alexa/alexa-avs-sample-app#942]
I am trying to do mvn install Step 6 and getting following exception.

[DEBUG] Failed to decrypt password for server deploy-repo: org.sonatype.plexus.c
omponents.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException:
C:\Users\adix15\.m2\settings-security.xml (The system cannot find the file speci
fied)

What am I missing?

Thanks

**Comment by balaraju1278** [comment]
did you install maven in your system and which version it is

**Comment by everledger** [comment]
Yeah.. version  Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:0
6+01:00)

**Comment by balaraju1278** [comment]
can you paste your pom.xml file which will be useful to find out problem

**Comment by everledger** [comment]
I have fixed it.. many thanks

**Comment by mradulan** [comment]
Hi @archana76 , if the issue is resolved, can you close the ticket. Thanks,
