### ISSUE TITLE
Official support for Raspbian Stretch?

### ISSUE THREAD

**Issue by Borduni** [alexa/alexa-avs-sample-app#949]
Is someone working on it? I don't want to apply experimental changes to make it work on stretch.

**Comment by Kieranwest** [comment]
I'd like to know this too. I cannot for the life of me get this working on Stretch. Just get to the stage of building the wakeword engine and it just flops.

**Comment by hschraep** [comment]
I'm also very intrested because it looks like strech can handle pluetooth speeker with HFP profile by default in case it use pulseaudio version 10. So it could be a good for a pi zero W.

**Comment by mradulan** [comment]
Hi All, currently we do not support it on Stretch. But the future release will have the support for Stretch.
