### ISSUE TITLE
Cannot play stream music, tunein or iheartradio

### ISSUE THREAD

**Issue by yannicklin** [alexa/alexa-avs-sample-app#950]
Hi, I'm setting up this sample on my small notebook,
ACER AspireOne, 
ATOM N270 CPU, 2G RAM, Lubuntu 16.04.3 LTS

The sample JAVA application could work, for voice commands like "what's the weather"...
But once I tried the command: "Play DC101 on iHeartRadio", then it crashed.

I saw plenty of threads mentioned the missing of "libvlc.so",
so I created the systematic link from "libvlc.so.5.5.0" also.

The errors shown in terminal are:

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0xb768b194, pid=8584, tid=0x6bafcb40

JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
Java VM: Java HotSpot(TM) Server VM (25.144-b01 mixed mode linux-x86 )
Problematic frame:
C  [libc.so.6+0x121194]  _IO_file_underflow+0x64

Core dump written. Default location: /home/yannick/alexa-avs-sample/samples/javaclient/core or core.8584
An error report file with more information is saved as:
 /home/yannick/alexa-avs-sample/samples/javaclient/hs_err_pid8584.log

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.374 s
[INFO] Finished at: 2017-09-24T20:41:37+10:00
[INFO] Final Memory: 11M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 134 (Exit value: 134) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Here is the log file:
[hs_err_pid8584.log](https://github.com/alexa/alexa-avs-sample-app/files/1327214/hs_err_pid8584.log)

**Comment by mradulan** [comment]
Hi @yannicklin, did the crash happen only after playing iHeartRadio? Was the sample app working before?

**Comment by mradulan** [comment]
Hi @yannicklin , do you have 32bit or 64bit version of Linux? This problem looks like #390.

**Comment by yannicklin** [comment]
I have the 32bit version of Linux and Java VM.
After surveying, the remove of LUA really works.

rm /usr/lib/vlc/lua/ -r

Thanks, @mradulan
