### ISSUE TITLE
WakeWordEnginge crashes when i turn off my speaker

### ISSUE THREAD

**Issue by adrianknorr** [alexa/alexa-avs-sample-app#951]
I have got the following Setup:
- Raspberry Pi 3
- 3,5 Audio Output
- USB Microphone Input

Now, if i turn of my speaker (by turning off the power strip it's connected to) my WakeWordEngine crashes. Alexa still recognises me when i push the button manually, but saying Alexa won't work anymore. Here is the ouput of my WakeWordEnginge -e sensory (src):

> WordAgent -e sensory
> INFO:main: Starting Wake Word Agent
> INFO:WakeWordAgent: State set to IDLE(2)
> INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-beta.10.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
> WARNING:Library expires on: License expires on 28 Dec 2017 00:00:00 GMT
> INFO:SensoryWakeWordEngine: mainLoop thread started
> INFO:WakeWordIPCSocket::mainLoop thread started
> INFO:WakeWordIPCSocket: init socket on port:5123
> INFO:===> Connected to AVS client <===
> INFO:WakeWordAgent: thread started

(Everything is working fine. Now i turn off my speaker)

> ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input stream for channel "audio-pcm": ALSA read error: Input/output error
> INFO:SensoryWakeWordEngine: mainLoop thread ended

Kitt_ai is doing the same thing. 

So, how can i turn off my speaker without crashing the WakeWordEngine?

Many thanks to everyone! And sorry if my English isn't the best, i am only a german student :P

**Comment by mradulan** [comment]
Please check "config.json" file in "samples/javaclient" and make sure that "wakeWordAgentEnabled" is set to true.

**Comment by adrianknorr** [comment]
Hey,
yes it is set to true. It's working, until i turn off my speaker.

**Comment by adrianknorr** [comment]
I just fixed it by turning on the headless mode! It was in the file mradulan mentioned.
