### ISSUE TITLE
How to enable Display Cards?

### ISSUE THREAD

**Issue by juan-gutierrez-nxp** [alexa/alexa-avs-sample-app#952]
Hi 

How can I enable Display Cards. I am able to see the java app, but where are supposed to be render the Display Cards: within the java app, as another window, on vlc?

Do I need to enable something on the json files, to enable it, or pass a parameter somehow?

Can you explain, please?

Thanks
juan gutierrez

**Comment by juan-gutierrez-nxp** [comment]
Does the render for the Display cards needs to be implemented or does the app already render the cards?

**Comment by mradulan** [comment]
As of now the rendering is not implemented. In future releases, some templates will be rendered.

**Comment by anu-mathur** [comment]
@juan-gutierrez-nxp 
Hi
I am doing a user study on the alexa-avs-sample-app and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tinyurl.com/AVSContactForm) and I will get in touch with you! 
Thanks
