### ISSUE TITLE
Debian “stretch” Release

### ISSUE THREAD

**Issue by vidanov** [alexa/alexa-avs-sample-app#954]
I tried to install Alexa-Avs-Sample-App on the Raspberry PI with Debian "stretch" Release.
It is stable since July and it is as one possible download now on Raspbianpi.org.
But the Alexa-Avs-Sample-App does not work on it.
Will you make it working on "stretch" too?

**Comment by mradulan** [comment]
yes we will have an update of Java sample app on Stretch.

**Comment by amanarora10** [comment]
Hi, is there a planned date for release with support for "stretch"?

**Comment by mradulan** [comment]
@amanarora10 , we are in progress, do not have a specific date.

**Comment by vidanov** [comment]
You know, it is good to mention in your actual installation guide! 
And please put the information about the last noobs here, where your code works.
I spent some hours before I found out, that the actual noobs does not work with the code.
