### ISSUE TITLE
Can't Stop Playback Once Begins

### ISSUE THREAD

**Issue by participationaward** [alexa/alexa-avs-sample-app#958]
As the title says, I have a fully functioning setup of the avs sample app on an rasperry pi running jesse build from july, I can ask it questions and do all the regular stuff and it responds and works quite well, the only issue I have run into is say I ask it to play a radio station from tune in, or give me a flash briefing, or an alarm or timer is going off, it does not recognize my requests to STOP, or SHUT UP, I must simply wait for it to end , or pull the power, or go to the website to physically delete the alarm or stop the music playback.

Any solutions would help alot thank you for all your hard work!

**Comment by kclchan** [comment]
Can you let us know if you use "Tap to Speak" or Wakeword to Stop?

**Comment by lenina101** [comment]
I have the same problem using wakeword. There is no noise to say the wakeword has been acknowledged

**Comment by lenina101** [comment]
It also seems to be hit and miss as to whether she'll respond if there is a notification sound. I'm running raspbian jessie version 8

**Comment by participationaward** [comment]
hey there, not sure what happened but I started from scratch and she seems to be able to hear me now when she is playing audio (btw I am using wakeword), one thing I noticed is that if I try to wake her to stop during playback it helps if I say alexa during a short pause between speech say or notes or commercials ect ect, I suspect this may be a microphone issue I think its picking up the audio and not able to hear the wake word at times

**Comment by kclchan** [comment]
Hi @participationaward and @lenina101 , I think the issue is due to the lack of Acoustic Echo Cancellation (AEC) on the Raspberry pi and the music playback is interfering with the wakeword detection.   Thanks!

**Comment by participationaward** [comment]
@kclchan this is precisely it, thanks for elaborating it so eloquently!
