### ISSUE TITLE
can't build alexa companion for android 

### ISSUE THREAD

**Issue by gezn** [alexa/alexa-avs-sample-app#961]
I'm trying to build the alexa companion app,
I followed https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#5b---build-and-run-an-android-companion-app-authentication
but an error appears that says 
Error:(19, 1) Execution failed for task ':app:checkForRequiredFiles'.
> The Certificate Authority public certificate file does not exist. Please make sure ./src/main/res/raw/ca.crt exists and contains the public certificate created during setup.

according to the gradle build script is verifying the existence of a ca.crt, but the guides doens't say anything about how to get this ca.crt

**Comment by kclchan** [comment]
Hi @gezn, please take a look at https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#4---generating-self-signed-certificates on how to generate a ca.crt certificate.  Thanks!

**Comment by gezn** [comment]
thanks, I didn't noticed that to run the android companion we have to build all the others, now everything is working.
