### ISSUE TITLE
My device not support reminder and timer

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#963]
Dear all
Our device has already certificated by amazon, and already support some function like "Amazon music". 

1. But not support the reminder . 
On the web site it displayed: Reminders are not supported on this device.  

2. When I said "set a timer after two minutes", it returned and said "two minutes, starting now", but I can see any timer on website (ex: https://alexa.amazon.com/spa/index.html#timersAndAlarms/timers), and after two minutes, there is nothing sent back to my device from AVS server.

Could you help to indicate us what's the problems? Thank you very much!

**Comment by dhpp** [comment]
Hi howardguo,

Thanks for your questions.

1. Reminders require enablement via the Developer Portal, under the 'Capabilities' section for your device.  Once you have enabled this, Reminders will work for your device.

2. Timers always take effect from the time of the user request.  So, in your case, Alexa is still interpreting the question as asking for a timer 2 minutes from now.  Which means the timer will go off 2 minutes after asking.  In terms of Directives, I believe the SetAlert Directive is sent to the device once your device sends the SpeechFinished Event.  Then, the device should store the Alert and render it at the appropriate time in the future (specified in ISO-8601 time within the Directive).  Please see here for further guidance:
[https://developer.amazon.com/docs/alexa-voice-service/alerts.html](https://developer.amazon.com/docs/alexa-voice-service/alerts.html)
and
[https://developer.amazon.com/docs/alexa-voice-service/alerts-overview.html](https://developer.amazon.com/docs/alexa-voice-service/alerts-overview.html)

Please let us know if the above does not answer your questions.

-David

**Comment by howardguo** [comment]
The time is still not displayed on the web site. And have no any Directive from AVS server.
could you give me a example? For ex: I want to set a timer after 2 minutes from current time.

**Comment by howardguo** [comment]
The time already displayed on web site ,thank you！

**Comment by RV999** [comment]
I have "Named Timers and Reminders" checked under capabilities but I do not receive an alarm or timer response message.
nothing is listed on https://alexa.amazon.com/spa/index.html#timersAndAlarms/timers page.
"You do not currently have any alarms set. Please use your device to set a new alarm."
"You do not currently have any timers set. Please use your device to set a new timer."
