### ISSUE TITLE
How can I get next song use my device

### ISSUE THREAD

**Issue by howardguo** [alexa/alexa-avs-sample-app#966]
Dear all
Our device has already certificated by amazon, and already support some function like "Amazon music".
When I say "play some music", it response to me a URL that can be play. But when this song play finished, and I sent the "PlaybackFinished" event to AVS server. But can not get the next song. 
what's the problem?

**Comment by dhpp** [comment]
Hi howardguo,

Could you please provide us with an x-amzn-requestid token, which AVS sends with each response?  This will allow us to look up the server logs and see if things look good there.

Please also check you are sending the correct Events per the guidance here:

[https://developer.amazon.com/docs/alexa-voice-service/audioplayer.html](https://developer.amazon.com/docs/alexa-voice-service/audioplayer.html)

Thanks.

-David

**Comment by howardguo** [comment]
This is the event I sent: 
{
   "event" : {
       "header" : {
          "messageId" : "a04ed2e6-cc6a-416a-d4ee-591fd8c2fd26",
          "name" : "PlaybackFinished",
         "namespace" : "AudioPlayer"
       },
       "payload" : {
          "offsetInMilliseconds" : 212000,
          "token" : "amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#bda51d04-a78b-44c2-b5b0-ee9f16388f1c:1"
       }
    }
}

**Comment by howardguo** [comment]
I got the next stream use PlaybackNearlyFinished but not PlaybackFinished . This issue can be closed.
