### ISSUE TITLE
Doubt in Alexa AVS when consuming this sample app

### ISSUE THREAD

**Issue by SenthilKumartd** [alexa/alexa-avs-sample-app#969]
Hi, I am trying to integrate Alexa Voice Service into my android mobile app, to use Alexa in my mobile sample app. I googled regarding this, I got your link. So that, tried to execute the sample Alexa Companion app and the JavaClient, to ensure whether it will fulfill my need.  After 15 days of effort in doing lot of googling and reading certificate problem, finally I executed two programs successfully. Well. Its working fine. But I am having still basic doubt that, can we integrate alexa voice service into my android mobile app and utilize the alexa feature. Clarification 1): Is the path I am going is the right one? Can you please ensure? Because, android companion app only provisioning devices, in your case a PC (Javaclient is running in that device). Clarification 2): is my expectation is right or wrong?  Clarification 3). Can we integrate, i mean , what I would like to say is, Can we execute or consume alexa voice service with out physical echo device, instead we can use Mobile Phone? is it possible? Please clarify.

**Comment by dhpp** [comment]
Hi SenthilKumartd.  Thanks for these questions - it's great to hear you have your mobile app working with AVS and Alexa!  To your questions.

1) An AVS client can run on any platform.  All that is required is that it correctly interacts with the AVS HTTP/2 endpoint over the internet, and provides the expected user experience per our guidance on our documentation pages.  For example, [here](https://developer.amazon.com/docs/alexa-voice-service/interaction-model.html).  So, you don't need to be concerned about your underlying OS being Android.
2) I'm not sure exactly what you mean by your expectation in this question, but the mobile app you have described sounds fine.
3) Yes, Alexa via AVS can work on any device which has a microphone, speaker, and internet connection.

Hope this helps.  Do let us know if you have any follow-up questions.

**Comment by SenthilKumartd** [comment]
Thanks so much for your valuable answer.
