### ISSUE TITLE
what is segmentation fault on Linux?

### ISSUE THREAD

**Issue by sungjinp11** [alexa/alexa-avs-sample-app#978]
pi@raspberrypi:~ $ pip install flask-ask
Collecting flask-ask
  Using cached Flask_Ask-0.9.7-py2.py3-none-any.whl
Collecting pyOpenSSL==17.0.0 (from flask-ask)
  Using cached pyOpenSSL-17.0.0-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from flask-ask)
Collecting six==1.10.0 (from flask-ask)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.12.1 (from flask-ask)
  Using cached Flask-0.12.1-py2.py3-none-any.whl
Collecting aniso8601==1.2.0 (from flask-ask)
Collecting cryptography>=1.7 (from pyOpenSSL==17.0.0->flask-ask)
Collecting itsdangerous>=0.21 (from Flask==0.12.1->flask-ask)
Collecting click>=2.0 (from Flask==0.12.1->flask-ask)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from Flask==0.12.1->flask-ask)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from Flask==0.12.1->flask-ask)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting python-dateutil (from aniso8601==1.2.0->flask-ask)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
Collecting enum34; python_version < "3" (from cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask==0.12.1->flask-ask)
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.7->pyOpenSSL==17.0.0->flask-ask)
  Using cached https://www.piwheels.hostedpi.com/simple/pycparser/pycparser-2.18-py2.py3-none-any.whl
Installing collected packages: pycparser, cffi, enum34, asn1crypto, idna, six, ipaddress, cryptography, pyOpenSSL, PyYAML, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, Flask, python-dateutil, aniso8601, flask-ask
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 Werkzeug-0.12.2 aniso8601-1.2.0 asn1crypto-0.23.0 cffi-1.11.2 click-6.7 cryptography-2.1.1 enum34-1.1.6 flask-ask-0.9.7 idna-2.6 ipaddress-1.0.18 itsdangerous-0.24 pyOpenSSL-17.0.0 pycparser-2.18 python-dateutil-2.6.1 six-1.10.0
Segmentation fault

**Comment by BennyAvramson** [comment]
Hi @sungjinp11,

I don't think Flask-Ask is related to the Sample App. I suggest you'll post the question on Flask-Ask forum.

Thanks,
Benny
