### ISSUE TITLE
Terms and conditions for modification and redistribution

### ISSUE THREAD

**Issue by shivasiddharth** [alexa/alexa-avs-sample-app#979]
Hi,
While going through the Installer_Licenses file, i came across so many individual guidelines for modification and redistribution. In short, am I allowed or not allowed to fork and modify the forked git?
Regards

**Comment by jairajiv** [comment]
@shivasiddharth, your legal team will be the best resource access and answer your questions around what, if anything, you need to modify and redistribute this repository.  

Please fill out this [Contact Form](https://tinyurl.com/AVSContactForm) if you want to follow-up.

**Comment by shivasiddharth** [comment]
@jairajiv , Just curious. I would understand if it was for someone who is developing a commercial product. But for DIY hobbyist and enthusiasts, why is there a constraint for making changes for even non-commercial purposes?

**Comment by shivasiddharth** [comment]
No one got back ! Closing this !!
