### ISSUE TITLE
error is "HTTP 405 : METHOD NOT ALLOWED"

### ISSUE THREAD

**Issue by sungjinp11** [alexa/alexa-avs-sample-app#982]
when i was making skills of Alex, using HTTP method not lambda, an error occured.
i had 2 terminal windows on the Raspberry pi.
at first terminal, i wrote this command "sudo python hello.py".
at the second terminal, i wrote this command "sudo ./Desktop/ngrok http 5000".
and then i made a alexa-skills on amazon.
during test, i wrote Utterance at the service simulator, the message says " there was an error calling the remote endpoint,  which returned HTTP 405 : METHOD NOT ALLOWED"
i'm stuck here... 
plz help me...
thank  you

**Comment by stevbenn** [comment]
Hi @sungjinp11 
I'd recommend sharing this on the Alexa Skills forums [here](https://forums.developer.amazon.com/spaces/23/index.html), where you'll get more specific Alexa Skills related help.
