### ISSUE TITLE
How can i trigger another application/script when wakeWordAgent detects hotword?

### ISSUE THREAD

**Issue by gpavankv** [alexa/alexa-avs-sample-app#983]
Hi all,

I've successfully installed the alexa avs sample app on my raspberry pi 3. I was able to make all of them start while booting the device. But i want to know if there's a way to trigger an application or a python script whenever we say "alexa" i.e., whenever the wakeWordAgent detects the hotword.

**Comment by BennyAvramson** [comment]
Hi @gpavankv,

To use the sample app with Alexa wake word on Pi, please follow the [Pi instructions](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi). You can use either Sensory or KITT.AI for wake word engine.

Thanks,
Benny

**Comment by shivasiddharth** [comment]
@gpavankv , You need to add the scripts to the KittAiSnowboyWakeWordEngine.cpp before running the automated installer.

**Comment by D3rpi** [comment]
I'm only familiar with python. What would I need to add to trigger a python script when the wakeworld is detected?

**Comment by bandkenamazoncom** [comment]
You would need to trigger a script from within the WakeWordEngineCode.  I suggest looking into the  system command:

http://www.cplusplus.com/reference/cstdlib/system/

**Comment by gpavankv** [comment]
so insert the code to call a system command in sensory or kitt_ai. I shall look into it! 👍

**Comment by gpavankv** [comment]
but there are number of cpp files in wakeWordEngine folder which in particular? If someone can help me out!

**Comment by bandkenamazoncom** [comment]
I see where you are going with this.  This is unsupported behavior, but you might be able to get something working.  Check out the AudioInputProcessor::recognize(...) function.

It's in CapabilityAgents/AIP/src/AudioInputProcessor.cpp.

**Comment by gpavankv** [comment]
was able to modify the wakeWordAgent.cpp file and execute a python script! 👍  Thank you very Much!!!
