### ISSUE TITLE
Headless autostart

### ISSUE THREAD

**Issue by shivasiddharth** [alexa/alexa-avs-sample-app#985]
For the benefit of those running this version of alexa, i have prepared scripts to autostart the alexa on boot on pi with a startup tone. Here is the link to the git.
https://github.com/shivasiddharth/headless-alexa-avs-sample-app
And for reference..https://youtu.be/zaMIz-oLrsQ

**Comment by bandkenamazoncom** [comment]
Thanks for helping out the community!  Users like you are what makes this project great!
