### ISSUE TITLE
maybe, tutorial wiki page has miss type and link.

### ISSUE THREAD

**Issue by ionis111** [alexa/alexa-avs-sample-app#986]
Maybe, this wiki page has miss type and link.
　https://github.com/alexa/alexa-avs-sample-app/wiki/Linux

It's blow 5a (Build and Run a Node.js Server Authentication) section.
> The server is running. You are now ready to run the sample app. Skip to - "5 - Run the sample app".

correct is not 5 but 6 .

And its link is
  `https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#5---run-the-sample-app`
But correct is
  `https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#6---run-the-sample-app`

---

5b and 5c section have same miss type too.
* 5b
> You are now ready to run the sample app. Skip to - "5 - Run the sample app".
* 5c
> You are now ready to run the sample app. Skip to - "5 - Run the sample app".

**Comment by bandkenamazoncom** [comment]
Thanks!  It's in the process of being fixed.

**Comment by BennyAvramson** [comment]
The doc has been fixed. Thanks!
