### ISSUE TITLE
Not authorized for requested operation. Error:unauthorized_client

### ISSUE THREAD

**Issue by Davidxiaoshuo** [alexa/alexa-avs-sample-app#987]
hello:
 I want to use Authorize a headless device from Companion App. When the headless device request access token occur a error. 
{"error_description":"Not authorized for requested operation","error":"unauthorized_client"}
below is my request params:
endpoint---> https://api.amazon.com/auth/o2/token

bodys--->{client_id=amzn1.application-oa2-client.38b9222693674c979a0c73f09e51dba0, redirect_uri=amzn://ai.ling.device.x.alexa, code_verifier=qAzsu4Hvu0zYVwuDpe_Qm1YWsrsH9lXj6sYf0QrucwY, code=ANJLLtyeFyIDpRFFzXxD, grant_type=authorization_code}

codeChallenge--->cjzOTMjvXbQfPuZQu25EL3TuI5LODH4t1mxF_T3BgRg=

below is my code:

        private String mCodeVerifier;
        CodeChallengeWorkflow.getInstance().generateProofKeyParameters();
        String codeChallenge = CodeChallengeWorkflow.getInstance().getCodeChallenge();
        String codeChallegeMethod = 
        CodeChallengeWorkflow.getInstance().getCodeChallengeMethod();
        mCodeVerifier = CodeChallengeWorkflow.getInstance().getCodeVerifier();

        final JSONObject scopeData = new JSONObject();
        final JSONObject productInstanceAttributes = new JSONObject();

        try {
            productInstanceAttributes.put(DEVICE_SERIAL_NUMBER, PRODUCT_DSN);
            scopeData.put(PRODUCT_INSTANCE_ATTRIBUTES, productInstanceAttributes);
            scopeData.put(PRODUCT_ID, PRODUCT_ID_VALUE);

            AuthorizationManager.authorize(new AuthorizeRequest.Builder(mRequestContext)
                    .addScope(ScopeFactory.scopeNamed(ALEXA_ALL_SCOPE, scopeData))
                    .forGrantType(AuthorizeRequest.GrantType.AUTHORIZATION_CODE)
                    .withProofKeyParameters(codeChallenge, CODE_CHALLENGE_METHOD)
                    .build());

      private class AuthorizeListenerImpl extends AuthorizeListener {

        @Override
        public void onSuccess(final AuthorizeResult authorizeResult) {
            final String authorizationCode = authorizeResult.getAuthorizationCode();
            final String redirectUri = authorizeResult.getRedirectURI();
            final String clientId = authorizeResult.getClientId();
            LogPrinter.info("authorizationCode---> " + authorizationCode);
            LogPrinter.info("redirectUri---> " + redirectUri);
            LogPrinter.info("clientId---> " + clientId);
            LogPrinter.info("token--->" + authorizeResult.getAccessToken());
            AlexaLoginSendRequest request = new AlexaLoginSendRequest(new ResponsedCallback() 
       {
                @Override
                public void onResponse(@Nullable BaseEntity entity, @Nullable Exception error) {

                }
            });
            request.startRequest(authorizationCode, redirectUri, clientId, mCodeVerifier);
        }

**Comment by bandkenamazoncom** [comment]
This looks to be a similar problem facing these users:

https://forums.developer.amazon.com/questions/35655/error-descriptionnot-authorized-for-requested-oper.html
https://forums.developer.amazon.com/questions/77868/error-descriptionnot-authorized-for-requested-oper-1.html

Is the code that you are generating meetings the standards mentioned in these issues?

**Comment by Davidxiaoshuo** [comment]
thank you for answer me! The above two links have looked, but there is no solution.
below is my code verifier , does it have a problem?
 public static String getCodeChallengeMethod() {
        return CODE_CHALLENGE_METHOD; //"S256"
    }

    /**
     * Create a String hash based on the code verifier, this is used to verify the Token exchanges
     *
     * @return
     */
    public static String getCodeChallenge() {
        String verifier = getCodeVerifier();
        return base64UrlEncode(getHash(verifier));
    }

    /**
     * Return our stored code verifier, which needs to be consistent, if this doesn't exist, we create a new one and store the new result
     *
     * @return the String code verifier
     */
    public static String getCodeVerifier() {
        String codeVerifier = AlexaAccountInfoManager.getInstance().getCodeVerifier();
        if (codeVerifier.isEmpty()) {
            //no verifier found, make and store the new one
            codeVerifier = createCodeVerifier();
            AlexaAccountInfoManager.getInstance().saveCodeVerifier(codeVerifier);
        }
        return codeVerifier;
    }

    /**
     * Create a new code verifier for our token exchanges
     *
     * @return the new code verifier
     */
    public static String createCodeVerifier() {
        return createCodeVerifier(128);
    }

    /**
     * Create a new code verifier for our token exchanges
     *
     * @return the new code verifier
     */
    public static String createCodeVerifier(int count) {
        char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-_.~".toCharArray();
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < count; i++) {
            char c = chars[random.nextInt(chars.length)];
            sb.append(c);
        }
        return sb.toString();
    }


    /**
     * Encode a byte array into a string, while trimming off the last characters, as required by the Amazon token server
     * <p>
     * See: http://brockallen.com/2014/10/17/base64url-encoding/
     *
     * @param arg our hashed string
     * @return a new Base64 encoded string based on the hashed string
     */
    private static String base64UrlEncode(byte[] arg) {
//        String s = Base64.encodeToString(arg, 0); // Regular base64 encoder
//        String s = new String(com.google.api.client.util.Base64.encode(arg));
        String s = new String(Base64.encode(arg, Base64.URL_SAFE|Base64.NO_PADDING|Base64.NO_WRAP));
        s = s.split("=")[0]; // Remove any trailing '='s
        s = s.replace('+', '-'); // 62nd char of encoding
        s = s.replace('/', '_'); // 63rd char of encoding
        return s;
    }

    /**
     * Hash a string based on the SHA-256 message digest
     *
     * @param password
     * @return
     */
    private static byte[] getHash(String password) {
        MessageDigest digest = null;
        try {
            digest = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e1) {
            e1.printStackTrace();
        }
        digest.reset();
        return digest.digest(password.getBytes());
    }

**Comment by theMooseChen** [comment]
Hi
A code verifier should be hashed(SHA256) before handing off to your companion app. According to your code `getCodeVerifier()`, you seems not hash it and you only hash it while creating Code Challenge?

Correct me if I am wrong. Thanks!

**Comment by qinicy** [comment]
Hi,this code is work:
` 
-------------
String codeVerifier = generateCodeVerifier();
String codeChallenge = generateCodeChallenge(codeVerifier, "S256");
-------------
private String generateCodeVerifier() {
        String randomOctetSequence = generateRandomOctetSequence(100);
        randomOctetSequence = "qinijiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        String codeVerifier = base64UrlEncode(randomOctetSequence.getBytes());
        return codeVerifier;
    }

    /**
     * Create a new code verifier for our token exchanges
     *
     * @return the new code verifier
     */
    private String generateRandomOctetSequence(int count) {
        char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-_.~".toCharArray();
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < count; i++) {
            char c = chars[random.nextInt(chars.length)];
            sb.append(c);
        }
        return sb.toString();
    }

    private String generateCodeChallenge(String codeVerifier, String codeChallengeMethod) {
        String codeChallenge = "";
        if ("S256".equalsIgnoreCase(codeChallengeMethod)) {
            try {
                byte[] digest = MessageDigest.getInstance("SHA-256").digest(
                        codeVerifier.getBytes());
                codeChallenge = base64UrlEncode(
                        digest);
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
        } else {
            // Fall back to code_challenge_method = "plain" codeChallenge = codeVerifier;
        }
        return codeChallenge;
    }

    private String base64UrlEncode(byte[] arg) {
        String s = new String(Base64.encode(arg, Base64.URL_SAFE | Base64.NO_PADDING | Base64.NO_WRAP));
        s = s.split("=")[0]; // Remove any trailing '='s
        s = s.replace('+', '-'); // 62nd char of encoding
        s = s.replace('/', '_'); // 63rd char of encoding
        return s;
    }`

**Comment by qinicy** [comment]
Hi,this code works:
`String codeVerifier = generateCodeVerifier();
 String codeChallenge = generateCodeChallenge(codeVerifier, "S256");`
`private String generateCodeVerifier() {
        String randomOctetSequence = generateRandomOctetSequence(100);
        randomOctetSequence = "qinijiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        String codeVerifier = base64UrlEncode(randomOctetSequence.getBytes());
        return codeVerifier;
    }

    /**
     * Create a new code verifier for our token exchanges
     *
     * @return the new code verifier
     */
    private String generateRandomOctetSequence(int count) {
        char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-_.~".toCharArray();
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < count; i++) {
            char c = chars[random.nextInt(chars.length)];
            sb.append(c);
        }
        return sb.toString();
    }

    private String generateCodeChallenge(String codeVerifier, String codeChallengeMethod) {
        String codeChallenge = "";
        if ("S256".equalsIgnoreCase(codeChallengeMethod)) {
            try {
                byte[] digest = MessageDigest.getInstance("SHA-256").digest(
                        codeVerifier.getBytes());
                codeChallenge = base64UrlEncode(
                        digest);
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
        } else {
            // Fall back to code_challenge_method = "plain" codeChallenge = codeVerifier;
        }
        return codeChallenge;
    }

    private String base64UrlEncode(byte[] arg) {
        String s = new String(Base64.encode(arg, Base64.URL_SAFE | Base64.NO_PADDING | Base64.NO_WRAP));
        s = s.split("=")[0]; // Remove any trailing '='s
        s = s.replace('+', '-'); // 62nd char of encoding
        s = s.replace('/', '_'); // 63rd char of encoding
        return s;
    }`

**Comment by Davidxiaoshuo** [comment]
thx, I had resolved this issue. It was my program that called out the error. thank you very match！
