### ISSUE TITLE
'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing.

### ISSUE THREAD

**Issue by jcwang84** [alexa/alexa-avs-sample-app#988]
Hi guys, i have little knowledge on this issue. 
i did some research over internet. i have tried manually enter the alpn verision . but i dont think it worked. 

im running raspbian jessie, and java version :1.7.0_151

ERROR:
========== Installing Java Client ==========
java version: 1.7.0_151 
major version: 1.7.0 minor version: 151
Unsupported or unknown java version (1.7.0_151), defaulting to latest known ALPN.
bash: Echo: command not found
Hit ENTER or wait ten seconds[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.amazon.alexa.avs:sample-java-client:20160207.6 (/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing. @ line 59, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

Thanks!

**Comment by jcwang84** [comment]
here is the debpi@raspberry:~/Desktop/alexa-avs-sample-app $  mvn exec:exec -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /usr/lib/jvm/oracle-java8-jdk-i386/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-686-pae", arch: "i386", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/pi/.m2/settings.xml
[DEBUG] Using local repository at /home/pi/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/pi/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.apache.maven:standalone-pom:pom:1: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 KB at 17.2 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/apache/maven/plugins/resolver-status.properties
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 26.3 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/resolver-status.properties
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (741 B at 9.5 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/exec-maven-plugin/resolver-status.properties
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom (13 KB at 145.7 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom.lastUpdated
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/exec-maven-plugin/1.6.0/_maven.repositories
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom (33 KB at 271.3 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom.lastUpdated
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/mojo-parent/40/_maven.repositories
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar (57 KB at 458.7 KB/sec)
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar.lastUpdated
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/codehaus/mojo/exec-maven-plugin/1.6.0/_maven.repositories
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.6.0 from repository central (https://repo.maven.apache.org/maven2, releases)
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.apache.maven:standalone-pom:pom:1
[DEBUG] Tasks:   [exec:exec]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins/maven-metadata.xml, already updated during this session.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo/maven-metadata.xml, already updated during this session.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/pi/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, already updated during this session.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.6.0 from repository central (https://repo.maven.apache.org/maven2, releases)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.apache.maven:standalone-pom:1
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <addOutputToClasspath default-value="true">${addOutputToClasspath}</addOutputToClasspath>
  <addResourcesToClasspath default-value="false">${addResourcesToClasspath}</addResourcesToClasspath>
  <async default-value="false">${exec.async}</async>
  <asyncDestroyOnShutdown default-value="true">${exec.asyncDestroyOnShutdown}</asyncDestroyOnShutdown>
  <basedir default-value="${basedir}"/>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <executable>${exec.executable}</executable>
  <localRepository default-value="${localRepository}"/>
  <longClasspath default-value="false">${exec.longClasspath}</longClasspath>
  <longModulepath default-value="true">${exec.longModulepath}</longModulepath>
  <outputFile>${exec.outputFile}</outputFile>
  <pluginDependencies default-value="${plugin.artifacts}"/>
  <project default-value="${project}"/>
  <remoteRepositories default-value="${project.remoteArtifactRepositories}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${exec.skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
  <toolchain default-value="jdk">${exec.toolchain}</toolchain>
  <workingDirectory>${exec.workingdir}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.420s
[INFO] Finished at: Wed Oct 25 19:40:39 BST 2017
[INFO] Final Memory: 11M/106M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/pi/Desktop/alexa-avs-sample-app). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/pi/Desktop/alexa-avs-sample-app). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:179)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.lifecycle.MissingProjectException: Goal requires a project to execute but there is no POM in this directory (/home/pi/Desktop/alexa-avs-sample-app). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
ug sheet

**Comment by bandkenamazoncom** [comment]
"Please verify you invoked Maven from the correct directory."

Run Maven from <SAMPLE_APP_DIR>/samples/javaclient

**Comment by jcwang84** [comment]
hey thanks for help @bandkenamazoncom 
i found out somehow  when i do the auto install . it install 1.7 java jdk for me install of 1.8 so ALPN wont install unless java is 1.8 per sripts. 

so i  point the path to 1.8
