### ISSUE TITLE
Companion cannot work in my side

### ISSUE THREAD

**Issue by mmm2006** [alexa/alexa-avs-sample-app#989]
I just configure and buid a android apk. In first page, it ask me to enter a address.  I had tried default value: https://10.0.2.2:8443, https://192.168.125.212(real address), But it always report error. First address report connection timed out, second report Connection refuesed error. Can you tell how to set for this step? Thanks.

**Comment by bandkenamazoncom** [comment]
Can you be more specific?  I'm don't understand what portion you are asking about.

**Comment by mmm2006** [comment]
app just used to get information from product firstly. https://10.0.2.2:8443 is proudct ip.
