### ISSUE TITLE
How make Alexa Run during Boot up process

### ISSUE THREAD

**Issue by gaurion** [alexa/alexa-avs-sample-app#992]
There are 2 things that I want to achieve :

1)Initiate Alexa service on system bootup
2)Activate Alexa Voice Service whenever "ALEXA" is prompted by the user.

Also is there a way that I can make alexa play music for me?
OS : Ubuntu 16.04

**Comment by bandkenamazoncom** [comment]
What have you tried so far?  The SDK is capable of both of those requests.  I'd recommend the C++ SDK, look for the Linux Quick Start guide: https://github.com/alexa/avs-device-sdk

**Comment by gaurion** [comment]
Its working fine on my Raspberry Pi 3. It starts everytime the system boots.
The problem with the deployment of the Alexa Service on my laptop. I am using Ubuntu 16.04 OS on my laptop. 
![screenshot from 2017-10-30 23-02-07](https://user-images.githubusercontent.com/18081563/32185860-694d3876-bdc6-11e7-88b4-457be0c0b797.png)

There are 2 things that I want to achieve :
 1)Initiate Alexa service on system bootup
2)Activate Alexa Voice Service whenever "ALEXA" is prompted by the user.

**Comment by frozenberg** [comment]
Hi @gaurion, have you followed this guide? https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

The end of step 7 explains how to activate a wakeword engine which sounds like it could address your second concern.

As to your first concern, you can run scripts on boot in various ways. One way is by editing /etc/rc.local

You can find some docs on that here: https://www.raspberrypi.org/documentation/linux/usage/rc-local.md

What you might be able to do is stick the commands you find in step 7 of the guide into here. Make sure to include an & after the command so you fork the process.

**Comment by mradulan** [comment]
closing the issue as no further response from user.
