### ISSUE TITLE
Alexa not responding

### ISSUE THREAD

**Issue by theboss1956** [alexa/alexa-avs-sample-app#993]
I have tried over and over again to try and find the issue for the error. It reads:

IOError: [Errno -9997] Invalid sample lines 1-18/18 (END)

Any idea what's happening? The service says it's running.

**Comment by frozenberg** [comment]
Hi @theboss1956, what steps have you taken to reproduce this issue?

**Comment by mradulan** [comment]
closing the issue as no further response from user.
