### ISSUE TITLE
Amazon Alexa app

### ISSUE THREAD

**Issue by Alexnagel** [alexa/alexa-avs-sample-app#995]
Hello,

I updated the Amazon Alexa app on my phone, which is Android. Now I can't seem to find my Alexa device listed in it. 
All I see is: "Please setup an Alexa device to use this page". If I indeed try to setup an Alexa device it wants to connect to the Alexa device WiFi, which my sample app doesn't have. 

I noticed that in the app it says that my host is alexa.amazon.co.uk. I set the device locale to EN_GB, but on the avs dashboard I don't see any locale information for my product. 
Could it be that there is a mismatch between those two? (Device being US and my app looking for UK)

Is it still possible to manage my device through the Alexa App?
If not, is there a different way to turn on/off my development skills?

Thank you

Alexa App info
Client Version: 1.24.2967.0
Bridge Version: 2.2.191.12

Alexa AVS sample is up to date with master

**Comment by frozenberg** [comment]
Hi @Alexnagel, 

What platform are you running Alexa on?

**Comment by Alexnagel** [comment]
Ah sorry forgot to mention that, It's on the Raspberry Pi

**Comment by frozenberg** [comment]
If you log in to alexa.amazon.com and click "Settings" on the left, does your device appear?

**Comment by Alexnagel** [comment]
Hmm no it doesn't. I can't even go to settings as it doesn't recognize a device has been set up. Altering the url to show settings (suffixing with "#settings") shows no devices too.

On this web interface I am able to go to my skills by suffixing with "#skills", but that is a bit 'hacky'.

**Comment by Alexnagel** [comment]
Okay it got a bit more interesting, it says there is no device set up but when I go to the home page I see all the requests I just did on my Alexa

**Comment by frozenberg** [comment]
Ok so let's try two things.

1. When you boot up the SampleApp and you go to localhost for your refresh token, does the email you use when signing in match the one you are using to log into alexa.amazon.com?

2. On alexa.amazon.com can you add something to your shopping list, then ask Alexa for your shopping list on your pi and see if they match up?

**Comment by Alexnagel** [comment]
1. Yes, I've only got one amazon account
2. Yes, they match up. The other way round it works too

**Comment by frozenberg** [comment]
Hmm ok. On amazon.com if you mouse over the "Account and Lists" tab and click Your Content and Devices, then click the Devices tab, does it show up there?

**Comment by Alexnagel** [comment]
No, it does not. When I go to that page I get redirected to books and it says my account is linked to the Dutch Kindle store, so I guess I know what the problem is. 
I'm based in the Netherlands and my account somehow knows this, although I've never bought anything. With that my Alexa device is in some limbo, being registered but as my account is based in a country that isn't supported it can't show the device. Could that be right?

**Comment by frozenberg** [comment]
Yep, I believe AVS is only available in US, UK, and Germany as of right now.

**Comment by Alexnagel** [comment]
Okay, I'll have to keep using the 'hacky' way then.

Thanks for the quick responses and the help! 😄
